Zilliqa/Zilliqa

docs/State Diagrams.md

The image references pointed to another repository. I also changed them to be relative, instead of absolute.

Fixed image references in State Diagrams.md

---

tests/Persistence/Test_DSPersistence.cpp
tests/Persistence/Test_TxPersistence.cpp

This fixes an unintentional declaration of a local variable as non-constant, which works for some compilers but fails for the Microsoft C++ compiler.
:link: Related to #19

Ensure arrays are initialized with constants

---

src/libUtils/Scheduler.h

- adds #include functional to Scheduler.h
- fixes #46 
- also solves original problem of #21

fixes a compiler error on fedora/ some version of gcc

---

src/depends/Sha3/Sha3.c

Add explicit casts where intended to avoid compiler warnings

---

.travis.yml

This PR implements the repository side of #48. A maintainer of this repository will still need to enable Travis CI before builds occur.

Add build configuration for travis-ci

---

local_run/README.md
src/common/Messages.h
src/libDirectoryService/DSBlockPreProcessing.cpp
src/libDirectoryService/DirectoryService.cpp
src/libDirectoryService/DirectoryService.h
src/libDirectoryService/PoW1Processing.cpp
src/libDirectoryService/ShardingPreProcessing.cpp
src/libNode/ShardingInfoProcessing.cpp
tests/Zilliqa/CMakeLists.txt

Not all DS members may receive POW submission from every single node. When a node didn't receive POW submission from nodes, it may not be able validate dsblock or sharding structure. This update will let the DS members requests the information from DS leader (rather than halting itself by raising an exception). 
A future improvement will be needed. The DS member should request the information from 20 DS rather than 1 DS.

Inconsistent view of m_hasAllPoWconns recovery

---

README.md

References:
http://leveldb.org/
https://cmake.org/
https://github.com/open-source-parsers/jsoncpp

Respect the capitalization of the dependency names

---

src/libDirectoryService/DirectoryService.h
src/libUtils/TimeUtils.cpp
src/libUtils/TimeUtils.h
tests/Crypto/Test_Schnorr.cpp

This change simplifies the code using new C++ standard library features, and addresses a future issue where `clock_gettime` is not defined on Windows platforms.
:link: Related to #19

Use std::chrono instead of clock_gettime for portability

---

CMakeLists.txt
build.sh
src/libCrypto/CMakeLists.txt

- removed hardcoded version in boost path
- removed trailing `/openssl` in linker flags
- this allows us to remove the workaround in `src/libCrypto`
- needed because: e.g. `#include <openssl/ec.h>` in
`src/libCrypto/*.h` would wind up looking in path
`.../openssl/openssl/ec.h` instead of `.../openssl/ec.h`
- auto-detect openssl include and lib paths

 fix : osx build issues for openssl and boost

---

CMakeLists.txt

- Remove the wrong placement of flag `-DIS_LOOKUP_NODE`, `-DSTAT_TEST`
- Correct the project name
- Enforce lowercase cmake command convention

Fix cmake issue regarding compiling flags and formating

---

.travis.yml
README.md

Travis CI doesn't support Ubuntu 16.04 natively, so the docker image `ubuntu:16.04` is used. This releases us from maintaining another set of dependencies for old OS versions.
`README.md` is also updated to indicate the change. We now only need to maintain the development instructions on Ubuntu 16.04 for Linux platform. The support for other OSes and platforms will be improved after we have a major progress in the codebase.

Enforce ubuntu 16.04 travis build for linux platform

---

tests/Zilliqa/main.cpp

Remove stack trace and related function from main.cpp  as it is no longer used.

remove unused function (stack trace) from main.cpp

---

.travis.yml
tests/Data/Test_Account.cpp
tests/Data/Test_AccountStore.cpp
tests/Data/Test_Transaction.cpp
tests/Lookup/Test_LookupNodeForDSBlock.cpp
tests/Lookup/Test_LookupNodeForTxBlock.cpp
tests/Persistence/ReadBlock.cpp
tests/Persistence/Test_DSPersistence.cpp
tests/Persistence/Test_TxBody.cpp
tests/Persistence/Test_TxPersistence.cpp
tests/depends/libDatabase/Test_LevelDB.cpp

The ctest is having errors on osx platform.
```
The following tests FAILED:
3 - Test_Account (Failed)
4 - Test_AccountStore (Failed)
6 - Test_Transaction (Failed)
7 - Test_LevelDB (Failed)
8 - Test_LookupNodeForDSBlock (Failed)
9 - Test_LookupNodeForTxBlock (Failed)
11 - Test_DSPersistence (Failed)
12 - Test_TxPersistence (Failed)
13 - Test_TxBody (Failed)
14 - ReadBlock (Failed)
```
found errors both on local Mac machines and travis build

Fix testing errors on Mac

---

docker/Dockerfile
docker/README.md

Added a Dockerfile that allows building a Docker image of Zilliqa. From this image, you can spawn Docker containers (running Ubuntu 16.04) which contain the entire Zilliqa source tree and it's built binaries.
Currently by spawning a container from this image, you can enter an interactive shell. This image can however be used to flexibly define several Docker services running a specific Zilliqa node. For example:
- one Docker service for running a Zilliqa _testnet_ node listening on _localhost_ on port _20_
- one Docker service for running a Zilliqa _mainnet_ node listening on _another IP_ on port _40_
- ...
These services would all use the same (prebuilt) Docker image to spawn their own container instance.
Let me know what you think or if you have any questions.

Docker image for Zilliqa

---

CMakeLists.txt

It will generate a file `compile_commands.json` in the root directory. It will be needed by development tools like [YouCompleteMe](https://github.com/Valloric/YouCompleteMe).

Enable CMAKE_EXPORT_COMPILE_COMMANDS for development use

---

.travis.yml
CMakeLists.txt

This pr enables `ccache` in `cmake` in a failsafe way - nothing changed for the system without `ccache`. `ccache` will speed up the building process without worrying about clean up the temporary files, such as `make clean` or `git clean -dfx`.
It also accelerates the travis build on both linux and osx platforms. It's [now](https://travis-ci.org/Zilliqa/Zilliqa/builds/355508477) around 5 minutes, 2x speedup.
Currently, the installing of `ccache` is not documented in `README.md`.

Enable ccache speedup

---

src/libNetwork/P2PComm.cpp
src/libNetwork/P2PComm.h

This pr moves the ThreadPool instances from the function local variables to data members of P2PComm, saving the time spent on constructing/destructing the ThreadPool instances at every function call.
It also fixes the following issues:
1. wildcard captured exceptions without logging the exception messages
2. duplicated message sending logic in multiple `Send*` functions
3. extra trailing white spaces at some places.

Improve time efficiency in P2PComm

---

src/depends/CMakeLists.txt

It's broken in certain test cases. And we no longer need it (based on the successful build results on Travis)
The benchmark for JSON library is [here](https://github.com/miloyip/nativejson-benchmark) and jsoncpp seems fine but no better than [RapidJSON](https://github.com/Tencent/rapidjson).

Remove json_spirit from depends

---

.travis.yml

It (1) fixes the problem that caching the Homebrew directory takes too long to tar and upload the cache; (2) stops updating homebrew everytime since [doc](https://docs.travis-ci.com/user/reference/osx/#Homebrew) says it will be updated by travis.

Fix several issues with Travis

---

src/libServer/Server.cpp

Issue : getTxBlockRate was accessing DS blockchain, instead should access the Tx.

fixed time in getTxBlockRate

---

.travis.yml

- Stop auto-updating brew when `brew install`, which saves some time as per travis [doc](https://docs.travis-ci.com/user/reference/osx/#Homebrew)
- Fix the dep instruction for linux

Improvement and fixup for travis

---

src/libServer/Server.cpp

Now GetNumPeers() returns the sum of normal nodes + DS nodes

Fixed number of peers to include DS peers

---

src/depends/libDatabase/LevelDB.cpp
src/libData/AccountData/AccountStore.cpp
src/libData/AccountData/AccountStore.h
src/libDirectoryService/DirectoryService.cpp
src/libLookup/Lookup.cpp
src/libNode/DSBlockProcessing.cpp
src/libNode/Node.cpp
src/libNode/Node.h
src/libNode/ShardingInfoProcessing.cpp
src/libPersistence/Retriever.cpp
src/libZilliqa/Zilliqa.cpp

It's found that after persistence recovery, for new node joining it always failed the state root check before initializing mining. After carefully investigation, the reason is after retrieving the state trie from db, when updating the state afterward, the state root will be different from the state trie obtained from init. This is because the order of insertion counts when populating the trie.

New Node Joining After Persistence Recovery; Root Check Failure Rejoining

---

.travis.yml
CMakeLists.txt
README.md
build.sh
build_lookup.sh
cmake/FindLevelDB.cmake
scripts/ci_build.sh
scripts/ci_install_deps.sh
src/depends/libDatabase/CMakeLists.txt
src/libUtils/CMakeLists.txt
tests/CMakeLists.txt
tests/Zilliqa/CMakeLists.txt

The most important change is enabling out-of-tree build, see `build.sh` and `build_lookup.sh` for details. 
Now developers can stay in one source tree directory and have two independent build folder (`build` and `build_lookup`). The impact to the local run testing is only the running directory change - previously `./tests/Node/test_node_simple.sh` is run in root directory, but now it's in individual build directories, for example:
- running normal nodes: `cd build && ./tests/Node/test_node_simple.sh`
- running lookup nodes: `cd build_lookup && ./tests/Node/test_node_lookup.sh`
Other changes
- Refactor top-level `CMakeLists.txt`
- remove the libraries linking commands to sub-directories
- use `find_package` and `pkg_search_modules` for dependency check
- use  `brew --prefix openssl` to set …

Refactor cmake and travis

---

build.sh
build_lookup.sh

Allow `build.sh` and `build_lookup.sh` to be run repeatedly after `build` and `build_lookup` is created the first time.

Fix build.sh & build_lookup.sh

---

src/libNode/FinalBlockProcessing.cpp
src/libNode/MicroBlockProcessing.cpp
src/libNode/Node.h

When announce message arrive when the shard backup transit it's state to microblock consensus, it will sleep for 0.5s. This 0.5s turn out to be very costly. It caused the shard backup to miss the entire microblock consensus process and also a missed a microblock. To add on, it will also hold onto the mutex for consensus protocol. This will only be released when the shard backup become a shard leader, which will then discard the announcement message from multiple epochs ago. 
This fix removed the sleep and busy wait and replace it with two conditional variable

Fix bug where announce message for microblock consensus was not processed in time

---

src/libNetwork/P2PComm.cpp

When the node needs to be restarted right away, for example after a crash or a config change, socket binding may fail due to the previous bound TCP connection still being in TIME_WAIT state, preventing the node from starting. This issue can be avoided by setting the SO_REUSEADDR option on the socket.
Note that only this corner case is covered by the fix: an active TCP connection would still gracefully prevent the binding.

Use option SO_REUSEADDR to avoid socket binding failures

---

src/libValidator/Validator.cpp
src/libValidator/Validator.h

It's very weird to log and continue on a null pointer. 2 lines later, on dereference, a seg fault will happen.
```
if (m_mediator == nullptr)
{
LOG_GENERAL(WARNING, "Error: pointer to Mediator is nullptr.");
}
```
The easiest way to fix this is to get rid of the pointer altogether, I think.

Removes the option of null pointer in validator

---

src/libNetwork/P2PComm.h
src/libNetwork/PeerStore.cpp
src/libNetwork/PeerStore.h

Summary:
- Fixed race condition in `PeerStore`
- Deleted copy ctor and assignment operator for `P2PComm` singleton

libNetwork: Various fixes

---

CMakeLists.txt
src/libDirectoryService/DSBlockPostProcessing.cpp
src/libDirectoryService/DirectoryService.cpp
src/libDirectoryService/DirectoryService.h
src/libDirectoryService/FinalBlockPostProcessing.cpp
src/libDirectoryService/FinalBlockPreProcessing.cpp
src/libDirectoryService/MicroBlockProcessing.cpp
src/libDirectoryService/PoW1Processing.cpp
src/libDirectoryService/PoW2Processing.cpp
src/libDirectoryService/ShardingPostProcessing.cpp
src/libNetwork/P2PComm.cpp
src/libNetwork/P2PComm.h
src/libNode/DSBlockProcessing.cpp
src/libZilliqa/Zilliqa.cpp

After taking a closer look, I'm thinking about removing `STAT_TEST` completely. I understand why we have it at first - clearly identifying the code segments that later can be disabled for less verbose logs.   However, the current use of `STAT_TEST` is not cautious becuase the other code path (without `STAT_TEST`) actually has compile errors (about the use of `m_selfPeer`).
So why don't we just remove it completely. Later, if we want any of those parts disabled, we can just find it from the commit history.

remove the rest of STAT_TEST completely

---

src/depends/libethash/ethash.h
src/depends/libethash/internal.c
src/libPOW/pow.cpp
src/libPOW/pow.h

Reuses memory when the size of nodes remains the same. Doesn't hit `malloc` from multiple threads (apart from 1:30k POWs when the size changes). Treats issue #310, kudos to @ansnunez @ckyang @jiayaoqijia @bb111189 @digiront and everybody else for the excellent investigation!

no re-alloc on POW - issue #310

---

src/libNetwork/P2PComm.cpp
src/libNetwork/P2PComm.h

Add fix to clear broadcast hashes for lookup nodes

---

src/libNode/DSBlockProcessing.cpp
src/libNode/FinalBlockProcessing.cpp
src/libNode/Node.cpp
src/libNode/Node.h

1. To fix the bug that the shard without microblock in finalblock will be waiting for m_tempStateDeltaCommitted becomes true until forever if there are any microblock from other shard.
2. Also add a clean up for m_createdTransactions if a shard node becomes a DS Leader.

Don't wait for CommitTemp if my shard microblock not in finalblock

---

constants.xml
constants_local.xml
src/common/Constants.cpp
src/common/Constants.h
src/libNetwork/PeerManager.cpp
src/libNetwork/PeerManager.h

User can switch log level by specifying log level inside constant_local.xml & constant.xml.
<DEBUG_LEVEL>3</DEBUG_LEVEL>
-> Default, show INFO/WARNING/FATAL log
<DEBUG_LEVEL>2</DEBUG_LEVEL>
-> Show WARNING/FATAL log
<DEBUG_LEVEL>1</DEBUG_LEVEL>
-> Show FATAL log

Add log level switch in constant file

---

src/libPOW/pow.cpp

For the case `block_number < currentBlockNum`, the warning message would have never appeared because `currentBlockNum` would have already been set to `block_number` in the earlier code block for `block_number != currentBlockNum`.

Reordered block number checking in EthashConfigureLightClient

---

README.md

The color (#077a8f) is the darkest color from Zilliqa logo.
links:
- https://shields.io/

Improve the gitter badge quality

---

src/libDirectoryService/DSBlockPostProcessing.cpp
src/libDirectoryService/DirectoryService.h
src/libDirectoryService/FinalBlockPostProcessing.cpp
src/libDirectoryService/ShardingPostProcessing.cpp
src/libDirectoryService/ViewChangePostProcessing.cpp

This is a follow PR to PR #419. Recall that in PR #419 , we removed the hotfix (of sleeping after consensus commit) and implemented ordering of consensus message. In that particular PR, we implemented it only for microblock consensus. This PR follows up on the outstanding issue from PR #419  
Reviewer should refer back to PR #419  and #423 if he/she need context of this PR. 
Ready for review

Consensus message ordering for ds block, sharding structure, final block and view change block

---

.travis.yml
docker/Dockerfile
scripts/ci_make_image.sh
scripts/make_image.sh

The goal of this PR is to directly create and push the image to private docker registry without waiting for Travis. The main change is in `scripts/make_image.sh` and other modifications are to support it.
The intended usage of this script is
```
./scripts/make_image.sh
./scripts/make_image.sh COMMIT
``` 
The docker image it creates has the same tag as the travis-built one, so the image being pushed will eventually be overwritten by the Travis. This is safe as `scripts/make_image.sh` is actually calling `scripts/ci_make_image.sh` (which is used on travis) to make the same image.
Other minor changes include
- moving `awscli` installation from `scripts/ci_make_image.sh` to `.travis.yaml`
- removing the dockerfile ARG `BRANCH` to reduce the complexity with the price of having to clone the …

Add scripts/make_image.sh for local image build and push

---

src/libConsensus/ConsensusCommon.h
src/libDirectoryService/DSBlockPostProcessing.cpp
src/libDirectoryService/DSBlockPreProcessing.cpp
src/libDirectoryService/DirectoryService.cpp
src/libDirectoryService/FinalBlockPostProcessing.cpp
src/libDirectoryService/FinalBlockPreProcessing.cpp
src/libDirectoryService/ShardingPostProcessing.cpp
src/libDirectoryService/ShardingPreProcessing.cpp
src/libDirectoryService/ViewChangePostProcessing.cpp
src/libDirectoryService/ViewChangePreProcessing.cpp
src/libNode/MicroBlockProcessing.cpp
src/libNode/Node.cpp

In PR #419 and #428, `m_consensusObject->CanProcessMessage(message, offset)` was added before each consensus message to check whether the ordering of the consensus message is correct or wrong. However, race condition (when using `m_consensusObject`) may occurs. 
One example will be for `libNode`. When the conditional variable `cv_processConsensusMessage` timeout, depending on the situation, a node may rejoin as a new node. During this period of time, `m_consensusObject` will be reset. However, there may be more threads (in the threadpool) that will use `m_consensusObject` in the near future. There is currently no such issue for `libDirectoryService`.
This PR fixes the race condition by introducing a mutex to protect `m_consensusObject`. In addtion, for `libNode`, an additional check was …

Fix race condition when using m_consensusObject->CanProcessMessage(message, offset) and add atomic to m_state in consensusCommon

---

src/libDirectoryService/DSBlockPostProcessing.cpp
src/libDirectoryService/FinalBlockPostProcessing.cpp
src/libDirectoryService/ShardingPostProcessing.cpp
src/libDirectoryService/ViewChangePostProcessing.cpp
src/libNode/MicroBlockProcessing.cpp

Recall in PR #433, a check for `m_consensusObject == nullptr` was added to the check function before m_consensusObject->canProcessMessage. If it is `nullptr`, the lambda function will return false and it will not enter canProcessMessage. 
However, a corner case may arise when the first announcement came and `m_consensusObject` is not initialized. This will enter the lambda function and return false, resulting in a blocking state enforced by the conditional variable. In normal out of order consensus message, the message will be processed in order and the previous correct ordered message will notify the conditional variable to signal the next ordered message to process.
However, since this is the first message (announcement), there is no notify to unblock the conditional variable, result it …

Fix cornercase when prechecking consensus message

---

src/libDirectoryService/DSBlockPostProcessing.cpp
src/libDirectoryService/DSBlockPreProcessing.cpp
src/libDirectoryService/FinalBlockPostProcessing.cpp
src/libDirectoryService/ShardingPreProcessing.cpp

Upon creation of consensus object, the corresponding conditional variable should be notify. However, there may be corner cases in the case for ds block consensus where notify is not called. For instance, view change or rejoining calling `RunConsensusOnDSBlock` will not trigger the notify. 
This PR moved the `notify_all` to immediately after creation of consensus object and state transition to avoid any corner case. 
Concretely, in ds block consensus, notify will happen in `RunConsensusOnDSBlock` after `    SetState(DSBLOCK_CONSENSUS)`
In sharding consensus, notify will happen in `RunConsensusOnSharding` after `    SetState(SHARDING_CONSENSUS);`
There is no issue with microblock and view change consensus. 
Testing

Fix consensus object not created in certain cases

---

src/libDirectoryService/ViewChangePreProcessing.cpp

`m_viewChangeCounter` in view change is not being used. This should be used to ensure the candidate leader will be different in the event a view change failed. 
A concretely example will be 
epoch n: leader become faulty
epoch n-x: candidate leader become faulty
At epoch n, leader become faulty. DS committee elect candidate leader (whom failed at epoch n-x) as the new leader. Candidate leader failed to transit the `announcement` as it is faulty. DS committee elect a new candidate leader but this is the same candidate leader. 
Solution: Use `m_viewChangeCounter` to sequentially elect the leader. 
Long time solution: Elect a random candidate leader using a secure random source
Need more testing

Fix View change cornercase where candidate leader is faulty before vc consensus

---

src/common/Messages.h
src/libDirectoryService/DirectoryService.cpp
src/libDirectoryService/DirectoryService.h

In earlier development for RedPrawn (see https://github.com/Zilliqa/Zilliqa/commit/2f76d41e88a1b81b6959a5fb39bb2a965e1d41c7) we added these two messages for use in ProcessPoW2Submission, but have since stopped using them. Removing them now in preparation for PoW merging work. Also removing related variables BUFFER_TIME_BEFORE_DS_BLOCK_REQUEST and m_requesting_last_ds_block.

Remove unused LASTDSBLOCKREQUEST and LASTDSBLOCKRESPONSE

---

src/libUtils/Logger.h

Recently we have more and more function with long name.
In our log, we only log the name with size=20 and truncate the reminder.
It's easy to confuse because we have many function with same prefix.
Ex.
ProcessFinalBlockConsensus
ProcessFinalBlockConsensusWhenDone
Both above 2 function will be truncated to "ProcessFinalBlockCon" and make confuse.
In this PR, we enlarge the function name size to 30.

Enlarge log function name to avoid confusion

---

src/libDirectoryService/DSBlockMessage.h
src/libDirectoryService/DirectoryService.h
src/libDirectoryService/ShardingPostProcessing.cpp
src/libDirectoryService/ShardingPreProcessing.cpp

Another small update to prepare for PoW merging.  This time, I have moved the sharding structure serialization code into one new file called DSBlockMessage.h.
Before this change, we used sharding structure serialization in two places:
- DirectoryService::SendEntireShardingStructureToLookupNodes
- DirectoryService::SerializeShardingStructure
The only difference between the two is that the first one has the IP info for all nodes, while the second one does not.
I have now made just one function now called ShardingStructure::Serialize that has the IP info.  The part of the code that does not need the IP info (DirectoryService::ShardingValidator) can just skip over it for now, to maintain the current behavior.
Regarding the file name DSBlockMessage.h:
When PoW merging is completed, the DS …

Move sharding serialization code into one place

---

src/libDirectoryService/FinalBlockPostProcessing.cpp

Fix issue:
https://github.com/Zilliqa/Issues/issues/126
Simply let the DS call `SetState(POW_SUBMISSION)` only when a new DS epoch is about to begin.

Move SetState for POW_SUBMISSION to new epoch

---

src/libDirectoryService/DSBlockPreProcessing.cpp

The final plan is to move sharding structure into the DSBLOCK message. The structure will include all the IP info of the nodes, thereby removing the need for REQUESTALLPOWCONN.
But that will come later. Meanwhile, another place where REQUESTALLPOWCONN is used is in DSBLOCK consensus if the DS backup doesn't know the winner's IP.  So, why not just add the winner's IP to the DSBLOCK consensus message?  This PR addresses that.

[PoW Merge] Add winner IP to DSBlock to avoid REQUESTALLPOWCONN

---

src/libDirectoryService/ShardingPreProcessing.cpp

In #464 the SHARDING announcement message was updated to contain the IP info, but the IP info was ignored by the DS backup validator to maintain the current behavior.
This PR will change the DS backup validator behavior to start using the IP info. This means we don't need to call REQUESTALLPOWCONN anymore.
After this PR, REQUESTALLPOWCONN will be completely unused in the code base. I will submit another PR to finally remove the code related to REQUESTALLPOWCONN.
The change is quite similar to #465 so you can review the same way.

[PoW Merge] Use the IPs in the SHARDING consensus announcement

---

src/libDirectoryService/DSBlockMessage.h
src/libDirectoryService/DirectoryService.h
src/libDirectoryService/ShardingPreProcessing.cpp

This is a similar effort to #464 where sharding info serialization was moved to DSBlockMessage.h.
This time, serialization of txn sharing assignments has been moved to that same file.
What I basically did was split `AppendSharingSetupToShardingStructure()` into two functions:
- `DirectoryService::ComputeTxnSharingAssignments()` handles the computation part
- `TxnSharingAssignments::Serialize()` handles the serialization part
The assignment algorithm remains the same, except now we have to store the result of the computation part so that we can pass it to the serialization part.  Hence, 3 new member variables `m_DSReceivers`, `m_shardReceivers`, and `m_shardSenders`.

[PoW Merge] Move txn sharing assignments serialization code

---

src/libDirectoryService/DSBlockMessage.h
src/libDirectoryService/ShardingPreProcessing.cpp
src/libNode/ShardingInfoProcessing.cpp

Finally, after #464, #474, and #476, txn sharing info deserialization is now moved to DSBlockMessage.h.
The deserialization code is straightforward.  There are two places where it is now called:
1. The DS backup during sharding announcement (`SaveTxnBodySharingAssignment`)
2. The Node during sharding message processing (`LoadTxnSharingInfo`)

[PoW Merge] Move txn sharing assignments deserialization code

---

.travis.yml
CMakeLists.txt
scripts/ci_build.sh
scripts/ci_report_coverage.sh

The main contribution of this PR is to fix Zilliqa/Issues#124. The previous way of doing code coverage has several issues:
- The target `Zilliqa_coverage` already includes the `lcov` commands listed in `scripts/ci_report_coverage.sh`, 
https://github.com/Zilliqa/Zilliqa/blob/14be39234c99d772affff9bd6c71ff931a8c5053/cmake/CodeCoverage.cmake#L157-L160. So the duplicated command in `scripts/ci_report_coverage.sh` is removed.
- The code coverage prefer `Debug` build to have more accurate coverage report. There was some [discussion](https://github.com/Zilliqa/Zilliqa/pull/58#issuecomment-393599408) about this already. This may increase the `ctest` time a bit but in it's not a majority of the Travis build time.
- In `scripts/ci_build.sh`, we are running `ctest` twice, one via explicitly …

Travis build speed-up and improvement

---

src/libDirectoryService/DirectoryService.h
src/libDirectoryService/ShardingPostProcessing.cpp
src/libNode/Node.h
src/libNode/ShardingInfoProcessing.cpp

Now we can use the sharding structure serialization (#464) and deserialization (#476) functions in the part where the DS nodes send the SHARDING message to the shard nodes after PoW2 consensus.
To do this, we have to change the SHARDING message a bit.  Currently, it contains only the portion of the sharding structure that is relevant to the shard nodes.  Now, to be able to reuse the serialization/deserialization functions, the message will contain the entire sharding structure.

[PoW Merge] Update SHARDING message sent to Node

---

src/libData/AccountData/AccountStoreSC.tpp

Previously in order to handle output from interpreter of for Json arrayValue or objectValue, we converted the output with `JSON::Utils::convertJsonToStr`. But for plain string type, this will add extra `\"` around the value. This PR is to solve this issue.

Fix parseOutput for value with string type

---

src/libNode/FinalBlockProcessing.cpp

There will be situations when RunConsensusOnMicroblock happens earlier than CallActOnFinalblock, especially in vacuous epoch. In that case, the states delta will be calculated based on last epoch before initializing. This PR will reverse the order of CallActOnFinalblock force it being called before running consensus.

Move CallActOnFinalblock before BeginNextRound

---

src/libConsensus/ConsensusBackup.cpp

When a shard backup received microblock announcement, a shard backup may not have all the transactions proposed in the announcement. In this case, a shard backup will request it from the shard leader. The backup will also set it `m_state` to `initial` and return true from the consensusbackup.  
However, the previous implementation in #426, the backup will only reprocess announcement if `state == ConsensusCommon::State::ERROR`, which is not true in this case. 
In this PR, `m_state` is set to `ERROR` if there is missing txn. 
To test out in local test and medium-scale cloud test.

Set consensus state to error if there backup has missing txns (at microblock announcement)

---

src/libServer/Server.cpp

Server::TxBlockListing is returning the wrong TX Block count due to reading DS instead of TX Blockchain.

[fix] TxBlockListing read currBlockNum from m_txBlockChain not m_dsBlockChain

---

src/libNode/ShardingInfoProcessing.cpp

This is the fix for https://github.com/Zilliqa/Issues/issues/136
`m_numShards` should be set after deserializing the sharding structure.

Set m_numShards after deserializing the sharding structure

---

src/libNode/Node.cpp
src/libZilliqa/Zilliqa.cpp

This PR fixes the null pointer deference issue when zilliqa is running with recovery option enabled (`<1 if recovery, 0 otherwise>`). This fix won't have any side-effect when recovery option is disabled.
Related discussions:
- fix Zilliqa/Issues#141
- fix Zilliqa/Issues#142
Read the analysis in Zilliqa/Issues#142

Change the calling order of Node::Install() to avoid null pointer dereference issue under recovery mode

---

README.md
src/common/Messages.h
src/libDirectoryService/FinalBlockPostProcessing.cpp
src/libLookup/Lookup.cpp
src/libLookup/Lookup.h
src/libPOW/pow.cpp

This was the old way:
1. New node sends `GETDSBLOCKFROMSEED` and `GETTXBLOCKFROMSEED` periodically to Lookup
2. New node receives `SETDSBLOCKFROMSEED`
If next epoch number will be for PoW -> New node sends `GETDSINFOFROMSEED` to Lookup
3. New node receives `SETTXBLOCKFROMSEED`
If next epoch number will be for PoW -> New node sends `GETSTATEFROMSEED` to Lookup
4. New node receives `SETDSINFOFROMSEED` and `SETSTATEFROMSEED`
5. If New node received `SETDSINFOFROMSEED` within `POW_WINDOW_IN_SECONDS` -> `InitMining()`
This is the new way:
1. New node sends `GETDSBLOCKFROMSEED` and `GETTXBLOCKFROMSEED` periodically to Lookup
2. New node receives `SETDSBLOCKFROMSEED`
3. New node receives `SETTXBLOCKFROMSEED`
If next epoch number will be for PoW -> New node sends `GETSTATEFROMSEED` to Lookup
4. …

Updated new node joining after removal of PoW2 phase

---

src/libNetwork/P2PComm.cpp
src/libNetwork/P2PComm.h

Since P2PComm implementation is based on libevent, some standard procedure should be followed, in order to improve maintenance and readability.
1. Re-factor reading, apply event_base & evconnlistener to handle socket bind()/listen()/accept()
2. For writing part, it's unnecessary to re-factor to libevent-style because there is no obviously performance gain however will cause SIGPIPE problem for socket closing
3. Wrap socket read() & write() function to be more modularize
4. For EAGAIN error raised in non-blocking read(), allow to retry
5. Make Dispatcher and Broadcast_list_func as P2PComm member variables
Follow-up PR: provide blacklist API in P2PComm

Use standard libevent procedure

---

src/libUtils/Logger.cpp
src/libUtils/Logger.h
src/libUtils/TimeUtils.cpp
src/libUtils/TimeUtils.h

Currently, our logging time-stamp only has second precision. However, there are often lots of messages coming in the same time, from different nodes/threads. It's not easy to distinguish them according to identical time-stamp. Thus we make the logging time-stamp precision as millisecond, trying to let debugging more easily.

Support logging time-stamp on millisecond precision

---

src/libData/AccountData/Account.cpp
src/libData/AccountData/AccountStoreBase.tpp
src/libData/AccountData/AccountStoreSC.tpp
src/libUtils/SafeMath.h
tests/Utils/CMakeLists.txt
tests/Utils/Test_SafeMath.cpp

As https://github.com/Zilliqa/Issues/issues/152 described, SafeMath should be a type-independent class. Hence we make it as template, and at the same time, add some unit test cases for it.
Known issue: (fixed)
Overflow-checking of add() only works on uint8_t and uint16_t, not work on bigger data size.

Make SafeMath as template

---

src/libUtils/SafeMath.h

This PR fixes the following in `SafeMath`
- Removal of obsolete comments
- Log warning to distinguish between integer overflow and underflow. 
There is no breaking change in this PR. 
Review may wish to refer to recent PR #523 for recent changes to SafeMath

Safe math log warning enhancement and comments fix

---

tests/Node/test_node_simple.sh
tests/Node/watch_node_simple.sh

Fix wrong port number in tests:
50$port --> $((5000 + $port)) since 50$port returns 501, 502... instead of 5001, 5002...

Fix wrong port number in tests

---

src/libData/AccountData/Account.cpp
src/libData/AccountData/Account.h
src/libData/AccountData/AccountStore.cpp
src/libData/AccountData/AccountStoreTemp.cpp

Previously the every delta of a contract account will include its code, init data and so on, which is actually a waste of bandwidth. Those information is only needed in the creation of the account.
This pr removed the serialization of contract code, init data and so on after the account creation was done in the earlier epoch. And only the changed contract states will be included in the serialized delta message.
https://github.com/Zilliqa/Issues/issues/155
https://github.com/Zilliqa/Issues/issues/156

Improvement on State Delta for Contract

---

CMakeLists.txt
VERSION
release.sh
src/cmd/CMakeLists.txt
src/cmd/sign.cpp
src/cmd/signmultisig.cpp

Following upgrading protocol utilities (https://github.com/Zilliqa/Zilliqa/pull/534), the release helper should provide following features:
Usage:
source ./release.sh privateKeyFileName publicKeyFileName
Release helper is an off-line independent script that will only be executed when a release needed to be generated. No impact to current code flow, so the review focus should be identifying the correctness of generated package (.deb) and relative version information (VERSION).

Release helper for upgrading protocol

---

src/libDirectoryService/DirectoryService.cpp

Fix difficulty adjustment bug, the current algorithm continually increase difficulty after 1 year epoch is reached.
Change the difficulty adjust algorithm, only increase difficulty at 1 year epoch.
Issue 192 [https://github.com/Zilliqa/Issues/issues/192]
Check the CalculateNewDifficulty function, compare it with old one.
Change the one year epoch to a smaller value, simulate the scenario of 1 year epoch reached, difficulty will increase by 1 on local machine.

Fix difficulty adjust continually after 1 year epoch problem

---

src/libNode/DSBlockProcessing.cpp

`lastBlockHash` was not set correctly inside `Node::ProcessDSBlock`.
Could not be easily detected during testing, but the side effect was there could be two leaders at one time.

Fixed lastblockhash setting in Node::ProcessDSBlock

---

src/depends/libethash-cl/CLMiner.cpp
src/depends/libethash-cl/CLMiner.h
src/depends/libethash-cuda/CUDAMiner.cpp
src/depends/libethash-cuda/CUDAMiner.h

The project failed to build GPU mining project after remove "using namespace std" in Miner.h.
Put std:: in front of std library types.
Check the CUDAMiner.h/cpp and CLMiner.h/cpp.
Build the project with "./build.sh cuda", and "./build.sh opencl", the build should can pass.

Fix build error after remove "using namespace std" in Miner.h

---

src/libData/BlockData/BlockHeader/DSBlockHeader.cpp
src/libData/BlockData/BlockHeader/DSBlockHeader.h
src/libMessage/Messenger.cpp
src/libMessage/ZilliqaMessage.proto

Previously, DSBlock was just defined as a `ByteArray` type, and we would just serialize it as such.
Now, to prepare for variable-length DSBlockHeader, we are defining a Protobuf-equivalent message for DSBlock with all the fields in it.

Define protobuf message and serialization for DSBlock

---

src/libDirectoryService/DSBlockPreProcessing.cpp

DS leader , if were to become a shard member (meaning, he was the oldest ds member) next epoch, while making the Sharding Structure, serializes his own IP as 0.0.0.0 : 0 and hence dies because is unable to recv messages.
Related issue : DS leader is kicker out of DS committee as shard node #205

Fix Issue of DS Leader being kicked out to shard, serializes his own IP as 0.0.0.0:0

---

src/libDirectoryService/DSBlockPostProcessing.cpp
src/libDirectoryService/DSBlockPreProcessing.cpp
src/libDirectoryService/DirectoryService.h
src/libNode/DSBlockProcessing.cpp

In the switch to protobuf (#590), the DS backup nodes are now setting their sharding and txn sharing-related members prematurely during the announcement validation.  These should be set only after consensus is done.
In this PR, the announcement data will be buffered inside temp members.  When consensus is done, we'll take advantage of move semantics to efficiently transfer the temp values into the final members for the sharding and txn sharing.

Delay setting DSBlock consensus structures until after consensus is done

---

src/libDirectoryService/DirectoryService.h
src/libDirectoryService/FinalBlockPreProcessing.cpp
src/libDirectoryService/MicroBlockProcessing.cpp
src/libMessage/Messenger.cpp
src/libMessage/Messenger.h
src/libMessage/ZilliqaMessage.proto
src/libNode/FinalBlockProcessing.cpp
src/libNode/MicroBlockProcessing.cpp

In this PR `DSInstructionType::MICROBLOCKSUBMISSION` has been protobuf-ed.
This message is sent by Node to DS (type `SHARDMICROBLOCK`) and by DS to DS (type `MISSINGMICROBLOCK`).
This PR also fixes an issue with forwarding transactions, found during testing.
If a node had to fetch missing microblocks, `Node::GetMyShardsMicroBlock` can crash because `m_microblock` was set to null inside `Node::MicroBlockValidator`.
The fix is to just not let this node forward transactions if its microblock reference is null.
Tested by avoiding sending the microblock to one backup DS in `Node::SubmitMicroblockToDSCommittee`.
Note that `m_MBSubmissionBuffer` type has been changed.
Previously we buffered the raw message.
This time the buffer already contains the deserialized components.
This is to avoid …

Make protobuf message for MicroblockSubmission

---

src/libDirectoryService/FinalBlockPostProcessing.cpp
src/libNode/Node.cpp

Previously in `ProcessFinalBlockConsensusWhenDone()`, when the vacuous epoch comes, the `m_consensusID` is updated after ethash was set up, which may be quite late, but the state was already changed to `POW_SUBMISSION`.
However under current design, when a ds receive finalblock consensus message, it will check whether it's under the correct state, otherwise it will force it to be changed to the right state for processing finalblock, and triggers `RunConsensusOnFinalBlock`.
In this case, if a node happens to send the consensus message slightly late, it will interrupt the normal procedure of the protocol.
The fix here is to solve this issue.
And there is also a minor fix on the logging of processed_count, as it's tiny, was also included here.

 Fix interruption caused by late ProcessFinalBlockConsensus

---

src/libLookup/Lookup.cpp

This PR uses the Messenger protobuf functions pushed in #580 for the remaining lookup messages.
It covers messages starting from `GETSTATEFROMSEED` (0x0A).
Here is the breakdown of changed messages:
- `GETNETWORKIDFROMSEED` - not changed (seems like this isn't called anywhere)
- `SETNETWORKIDFROMSEED` - not changed (seems like this isn't called anywhere)
- `GETSTATEFROMSEED` - changed to use Messenger
- `SETSTATEFROMSEED` - changed to use Messenger
- `SETLOOKUPOFFLINE` - changed to use Messenger
- `SETLOOKUPONLINE` - changed to use Messenger
- `GETOFFLINELOOKUPS` - changed to use Messenger
- `SETOFFLINELOOKUPS` - changed to use Messenger
- `RAISESTARTPOW` - not changed (empty message)
- `GETSTARTPOWFROMSEED` - changed to use Messenger
- `SETSTARTPOWFROMSEED` - not changed (empty message) …

Use the Messenger functions for the remaining lookup messages

---

src/libMediator/Mediator.cpp
src/libZilliqa/Zilliqa.cpp

Heartbeat is currently interfering with DS committee progress during the period between PoW submissions and the end of DSBlock consensus.
This PR temporarily disables the heartbeat thread and it also increases the estimated duration of one DS epoch.
The heartbeat should be re-enabled after we implement the prioritization between viewchange, heartbeat, and fallback (ideally only one should be triggered at a time).

Temporarily disable heartbeat check

---

release.sh
src/libUtils/UpgradeManager.cpp

In upgrading protocol, released package would be uploaded onto GitHub, and then be downloaded to each node.
Bunch of verification would be applied on the downloaded files including SHA-256 checksum, before really upgrading the nodes.
Previously, some extra information would be appended in the tail of uploaded files, to result in SHA-256 checksum failed.
This PR is to fix this bug, and enable SHA-256 checksum for downloaded files.
https://github.com/Zilliqa/Issues/issues/185

Enable SHA-256 verification for upgrading protocol

---

CMakeLists.txt

Since 8f3c6626c4b61a5731b5083edc7a42831914f2ea, build failed happened in cmake 3.10.2, ubuntu 18.04.1 LTS.
This hotfix just roll-back g3log-related installation process to clean the roadblock.

Hotfix of g3log installation failed

---

src/libMessage/Messenger.cpp
src/libMessage/Messenger.h
src/libMessage/ZilliqaMessage.proto

This PR introduces these functions to be able to set the `DSBlockHashSet`:
- `Messenger::GetDSCommitteeHash`
- `Messenger::GetShardingStructureHash`
- `Messenger::GetTxSharingAssignmentsHash`
These functions are still unused as of this PR.
Related to this, some refactoring is also done inside `ZilliqaMessage.proto` and `Messenger.cpp`.
Local test has confirmed the affected refactored messages work ok, but the refactored `LookupSetShardsFromSeed` and `LookupGetShardsFromSeed` are not tested yet. I propose we test them separately afterwards.

Added hashing functions to Messenger for the DSBlockHashSet

---

src/libData/AccountData/TransactionReceipt.cpp

This changes the type of the `success` property on `m_tranReceiptObj` to `boolean`.
It is preferable to use  an actual `boolean` value instead of `"true"` and `"false"`.
- [ x] **ready for review**

Change tx receipt success filed to boolean instead of string

---

src/libDirectoryService/DSBlockPostProcessing.cpp
src/libDirectoryService/DSBlockPreProcessing.cpp
src/libDirectoryService/DirectoryService.h
src/libDirectoryService/FinalBlockPreProcessing.cpp
src/libDirectoryService/ViewChangePostProcessing.cpp
src/libMessage/Messenger.cpp
src/libMessage/Messenger.h
src/libMessage/ZilliqaMessage.proto
src/libNode/DSBlockProcessing.cpp
src/libNode/Node.cpp
src/libNode/Node.h
src/libNode/ViewChangeBlockProcessing.cpp

This PR delays the sending of VC blocks (for ds block consensus)  to shard nodes. The sending of the vcblocks have been postponed and combined with the sending of DS Blocks. The benefit of such delays is that the DS Committee will have the sharding structure before transmission of the blocks. 
This will allows for the implementation for efficient broadcasting (tree based) of vc block(s). 
Known issue that hinder testing of this PR
- Lookup consuming too much cpu utilization on startup (https://github.com/Zilliqa/Issues/issues/224)
- https://github.com/Zilliqa/Issues/issues/225
With this issue, it is hard to observe lookup performing changing its view. However, it used the same function as the same as shard nodes. Changing of view is tested to be successful on DS Committee and Shard nodes. …

DS to send vcds message instead of vc block (before ds block consensus) to shard nodes

---

src/libData/BlockData/BlockHeader/BlockHashSet.h
src/libData/BlockData/BlockHeader/BlockHeaderBase.cpp
src/libData/BlockData/BlockHeader/BlockHeaderBase.h
src/libData/BlockData/BlockHeader/DSBlockHeader.cpp
src/libData/BlockData/BlockHeader/DSBlockHeader.h
src/libData/BlockData/BlockHeader/FallbackBlockHeader.cpp
src/libData/BlockData/BlockHeader/FallbackBlockHeader.h
src/libData/BlockData/BlockHeader/MicroBlockHeader.cpp
src/libData/BlockData/BlockHeader/MicroBlockHeader.h
src/libData/BlockData/BlockHeader/TxBlockHeader.cpp
src/libData/BlockData/BlockHeader/TxBlockHeader.h
src/libData/BlockData/BlockHeader/VCBlockHeader.cpp
src/libData/BlockData/BlockHeader/VCBlockHeader.h
src/libDirectoryService/DSBlockPreProcessing.cpp
src/libDirectoryService/FinalBlockPreProcessing.cpp
src/libDirectoryService/ViewChangePreProcessing.cpp
src/libLookup/Synchronizer.cpp
src/libMessage/Messenger.cpp
src/libMessage/Messenger.h
src/libMessage/ZilliqaMessage.proto
src/libNode/FallbackPreProcessing.cpp
src/libNode/MicroBlockPreProcessing.cpp
tests/Lookup/Test_LookupNodeForDSBlock.cpp
tests/Lookup/Test_LookupNodeForTxBlock.cpp
tests/Persistence/Test_DSPersistence.cpp
tests/Persistence/Test_TxPersistence.cpp

This PR moves out the previously named `DSCommHash` from `DSBlockHashSet` into `BlockHeaderBase` as a new type `CommitteeHash`.
Now all data blocks will have this `CommitteeHash`, which will be generated from either the DS committee or the shard that created the block. Messenger functions `GetDSCommitteeHash` and `GetShardHash` have been created for this purpose.
Locally tested, the data blocks still serialize and deserialize okay with the added member. The exception again is `VCBlock` and `FallbackBlock` which we can test again separately.

Added CommitteeHash to BlockHeaderBase and Messenger

---

src/libDirectoryService/DSBlockPreProcessing.cpp
src/libDirectoryService/DirectoryService.h
src/libNode/DSBlockProcessing.cpp

This PR starts to use the DSBlockHeader hashes added in #671, #677, and #679.
Specifically, the sharding structure hash, tx sharing assignment hash, and the DS committee hash are now checked in both DSBlock consensus and when the shard nodes receive the DSBlock.
Tested locally for both instances, and works OK.
The tricky part in this review should just be in the change to the `RunConsensusOnDSBlockWhenDSPrimary` function.  Note how the previously named `ComposeDSBlock` has been renamed to `ComputeDSBlockParameters`, because now the actual creating of the DSBlock has to be done only after computing both the DS block parameters and the new sharding structure/tx sharing assignments.

Added DSBlockHeader hashes verification

---

README.md
src/libData/AccountData/Transaction.cpp
src/libData/AccountData/Transaction.h
src/libMessage/Messenger.cpp
src/libMessage/ZilliqaMessage.proto

This is another PR for protobuf conversion, this time for `Transaction`.
This PR does these things:
1. Define `ProtoTransaction` in ZilliqaMessage.proto
2. Define `TransactionToProtobuf` and `ProtobufToTransaction` in Messenger.cpp
3. Define another constructor in Transaction.h which includes the `tranID`
4. Some maintenance
- Move the `xxxToArray` functions further up in Messenger.cpp
- Remove the commented-out code blocks inside Transaction.h and .cpp
- Change the `version` parameter in the `Transaction` constructor from `uint256_t` to `const uint256_t&`
At this time, we don't use the new Messenger.cpp functions yet. So, no expected impact on node behavior.

Made protobuf-equivalent  message for transaction (still unused)

---

src/libCrypto/Schnorr.cpp
tests/Crypto/Test_Schnorr.cpp

This PR fixes the return value (from 0 to -1) when deserialization failed in `Schnorr` library. Fixes have been applied to 
- PubKey
- PrivKey
- Signature
Issue: https://github.com/Zilliqa/Issues/issues/231
TODO:
- Check through the code coverage for the unit test. 
- Run unit tests (tests/Crypto/Test_Schnorr)

Fix DoS when Schnorr deserialization failed 

---

src/libPOW/pow.cpp
src/libPOW/pow.h
tests/POW/test_POW.cpp

This PR implements the followings
- Removal of insecure c function, `memcpy`, from `pow.cpp`
- Add boundary check to `StringToBlockhash()`
- Make static function BlockhashToHexString() and StringToBlockhash()
- `Test_Pow` to use static function `BlockhashToHexString()` and `StringToBlockhash()` instead of a duplicated function in the same test cae 
- Added unit tests for `StringToBlockhash()`
This PR fixes https://github.com/Zilliqa/Issues/issues/235

Remove insecure function `memcpy` in libPoW and add unit tests

---

src/libConsensus/ConsensusUser.cpp

This PR add a check to `ProcessConsensusMessage` to check whether `m_consensus` is `nullptr` or not before proceeding. 
This PR fixes https://github.com/Zilliqa/Issues/issues/233

Check for null consensus object in consensus user

---

scripts/ci_make_image.sh

When building a new docker image, pip will install urllib3 from the public. A recent update to urllib3 will break kube support. This PR implement a hotfix by downgrading urllib3 to a supported version

Hot fix to downgrade urllib3 for kube 7.0 support

---

src/libDirectoryService/DSBlockPreProcessing.cpp

Sometimes the DS backup failed to verify DS difficulty because received different number of DS PoW, it will trigger view change which can be avoid
Change the compare algorithm. Previous the DS leader POW window time is longer than DS backup, so the difficulty calculated should be equal or bigger than DS backup. Now the window time is the same, so DS backup may calculate the difficulty bigger than DS leader.
https://github.com/Zilliqa/Issues/issues/245
Check files changed.
Run a 200 nodes clout test, see if find difficulty mismatch problem.

Fix DS backup verify difficulty fail problem

---

src/libConsensus/ConsensusLeader.cpp

During FinalBlock consensus, When number of commits failure count exceeds tolerance, handler function is invoked. However, no handler is defined as of now. So it results in crash,
Now, we check for validity of function handler before invocation. Does nothing (no crash though) and would trigger for view change as per the flow.
Check the file changed.

Fix - DSLD node drops out when not enough commit received for Final Block Consensus

---

src/libConsensus/ConsensusBackup.cpp
src/libDirectoryService/ViewChangePreProcessing.cpp
src/libMessage/Messenger.cpp
src/libNetwork/P2PComm.cpp

This PR introduces the following fixes:
1. Fix a potential crash by creating a duplicate copy of the broadcast hash in `SendBroadcastMessage` before queueing the job.
2. Prevent `ConsensusBackup` from accepting `PROCESS_FINALCHALLENGE` in `RESPONSE_DONE` state
3. Prevent `m_msgContentValidator` failure from causing change to `ERROR` state in `ConsensusBackup`
4. Prevent challenge verification failure from causing change to `ERROR` state in `ConsensusBackup`
5. Correct the logging information about the candidate leader in `RunConsensusOnViewChangeWhenNotCandidateLeader`
6. Add more logging information about announcement signature failure in Messenger.cpp

[testnetv3-dev] Fix broadcast hash insertion and other testnet-discovered issues

---

src/libConsensus/ConsensusBackup.cpp
src/libDirectoryService/ViewChangePreProcessing.cpp
src/libMessage/Messenger.cpp
src/libNetwork/P2PComm.cpp

This PR introduces the following fixes:
1. Fix a potential crash by creating a duplicate copy of the broadcast hash in `SendBroadcastMessage` before queueing the job.
2. Prevent `ConsensusBackup` from accepting `PROCESS_FINALCHALLENGE` in `RESPONSE_DONE` state
3. Prevent `m_msgContentValidator` failure from causing change to `ERROR` state in `ConsensusBackup`
4. Prevent challenge verification failure from causing change to `ERROR` state in `ConsensusBackup`
5. Correct the logging information about the candidate leader in `RunConsensusOnViewChangeWhenNotCandidateLeader`
6. Add more logging information about announcement signature failure in Messenger.cpp
Tested along testnetv3-dev branch in #726

Fix broadcast hash insertion and other testnet-discovered issues

---

src/libNetwork/P2PComm.cpp
src/libZilliqa/Zilliqa.cpp

Lookup will use 100% of CPU even only run lookup alone. It is because some infinite look keep polling data.
Add sleep to message polling loop.
Check the two lines of code added.
Run a single lookup node, check the CPU usage.

Fix lookup node use 100% cpu problem

---

src/libDirectoryService/FinalBlockPostProcessing.cpp

When non-ds node receives the final block consensus message while infact waiting for final block from ds-node, it buffers the FB consensus message and schedules the wait for ds micro-block consensus which is incorrect. Thereby landing in-consistent state resulting in to drop out of network eventually.
Instead it should simple ignore FB consensus, if he is non-ds node.
This PR, Adds check to avoid buffering Final block consensus msg when am non-ds node.
Check the file changed.

Check to avoid buffering Final block consensus msg when am non-ds node

---

src/libDirectoryService/FinalBlockPostProcessing.cpp

When non-ds node receives the final block consensus message while infact waiting for final block from ds-node, it buffers the FB consensus message and schedules the wait for ds micro-block consensus which is incorrect. Thereby landing in-consistent state resulting in to drop out of network eventually.
Instead it should simple ignore FB consensus, if he is non-ds node.
This PR, Adds check to avoid buffering Final block consensus msg when am non-ds node.
Check the file changed

[testnetv3-dev] Check to avoid buffering Final block consensus msg when am non-ds node

---

src/libNetwork/PeerManager.cpp

Test function `PeerManager::ProcessPingAll()` has an unbounded `resize`.
This PR restricts the message size to 1k.
This function - like most of the functions currently inside `PeerManager` - is currently unused but can still prove useful for testing purposes. We should eventually enable this code only for local testing builds. See https://github.com/Zilliqa/Zilliqa/issues/759.

Bound the message size in ProcessPingAll

---

src/libDirectoryService/DSBlockPreProcessing.cpp

When we have missing pow , DS backup fetches them from DS block announcement.
However, it later results in bad pow ordering.
Issue - https://github.com/Zilliqa/Issues/issues/263
Please check the file changed.

[testnetv3-dev] Fix the Bad Pow Ordering

---

src/libDirectoryService/FinalBlockPostProcessing.cpp

While in DS Consensus Prep state, node accepts the Final block announcement for consensus, and it lands up in final block consensus state which is bug. Check should be added such that Final Block Consensus messages are not bufferred and should be ignored if Node is in DSBLOCK_CONSENSUS_PREP state.
In general, should be buffered only in MICROBLOCKSUBMISSION or VC STATE.
Issue - Zilliqa/Issues#264
Check the file changed.

Avoid buffering of FB while in MBSUBMISSION or VC State

---

src/libDirectoryService/DSBlockPreProcessing.cpp

When we have missing pow , DS backup fetches them from DS block announcement.
However, it later results in bad pow ordering.
Issue - Zilliqa/Issues#263
Please check the file changed.

Fix the Bad Pow Ordering

---

src/libNetwork/RumorManager.cpp
src/libNetwork/RumorManager.h

In testnet, we observed that one slower node receive the txn packet when RumorManager was stopped during initialization ( Start of new DS epoch ).
Before it was fully initialized, we receive the same txn packets multiple times for this epoch from peers. Now since the gossip itself is down, we currently just send the message down to dispatcher but don't gossip. This was done so that node don't miss the message in worst case.
However, This results in same txn packet being dispatched down for processing multiple time to ProcessTxnPacketFromLookup. 
Issue : https://github.com/Zilliqa/Issues/issues/267
Check the files changed,

[testnetv3-dev]  Avoid dispatching same messages when gossip is not running

---

src/libNetwork/RumorManager.cpp
src/libNetwork/RumorManager.h

In testnet, we observed that one slower node receive the txn packet when RumorManager was stopped during initialization ( Start of new DS epoch ).
Before it was fully initialized, we receive the same txn packets multiple times for this epoch from peers. Now since the gossip itself is down, we currently just send the message down to dispatcher but don't gossip. This was done so that node don't miss the message in worst case.
However, This results in same txn packet being dispatched down for processing multiple time to ProcessTxnPacketFromLookup.
Issue : Zilliqa/Issues#267
Check the file changed

Avoid dispatching same messages when gossip is not running 

---

src/libLookup/Lookup.cpp
src/libPersistence/Retriever.cpp

Missed a couple of places where `AccountStore::DeserializeDelta()` was still being checked as an unsigned int instead of bool.

Fixed incorrect check of AccountStore::DeserializeDelta result

---

src/libLookup/Lookup.cpp
src/libPersistence/BlockStorage.cpp
tests/Zilliqa/test_zilliqa_archival.py
tests/Zilliqa/test_zilliqa_local.py
tests/Zilliqa/test_zilliqa_lookup.py

The Zilliqa process parameter "toRetrieveHistory" should only be set when node recovery, rejoin, and upgrading mechanism. For the local testing without a standalone daemon, we need to make the script more flexible. Now a hotfix is just disable toRetrieveHistory for local test.
Besides, this PR also add some protection for system crash.
Follow-up:
We should support a flexible local-test script that allow to disable toRetrieveHistory at first time, and enable toRetrieveHistory then.

[Hotfix] Disable retrieveHistory for local test

---

src/libServer/Server.cpp

Fix a trivial bug in GetBalance in which 0 was returned as a number if account was not present.
Check if the quotes are present, two in number.

Fix libServer GetBalance bug

---

.travis.yml
docker/Dockerfile
docker/Dockerfile.ci
docker/Dockerfile.k8s
docker/Makefile
docker/README.md
scripts/make_image.sh

This PR refactors the entire `docker/` folder to achieve the following goals
- sort out dependencies and put them in different dockerfiles for different usage
- use working-directory-independent build instructions in main Dockerfile
It also disables the `deploy` stage on Travis due to long waiting time caused by high workloads. Now the developer with access to the private docker registry have to build and push images manually through `scripts/make_image.sh`. Read more in the help message `scripts/make_image.sh --help`

Refactor dockerfiles and docker build scripts

---

src/libDirectoryService/FinalBlockPostProcessing.cpp

Final block consensus messages are currently buffered in two states: `MICROBLOCK_SUBMISSION` and `VIEWCHANGE_CONSENSUS`.  They should also be buffered just before the start of the consensus, which is state `FINALBLOCK_CONSENSUS_PREP`.

[testnetv4-dev] Buffer final block when in FINALBLOCK_CONSENSUS_PREP state

---

src/libDirectoryService/FinalBlockPostProcessing.cpp

Final block consensus messages are currently buffered in two states: `MICROBLOCK_SUBMISSION` and `VIEWCHANGE_CONSENSUS`.  They should also be buffered just before the start of the consensus, which is state `FINALBLOCK_CONSENSUS_PREP`.

Buffer final block consensus msg when in FINALBLOCK_CONSENSUS_PREP state

---

src/libConsensus/ConsensusCommon.cpp
src/libConsensus/ConsensusLeader.cpp

Previous behavior before the consensus subsets were implemented was to proceed with challenge phase when we receive the minimum 2/3 commits.
After subsets was implemented, we now have a time window to receive as many commits as we want, even above the minimum 2/3.
This PR brings back the old behavior (just receive minimum commits, no timer) when we set `NUM_CONSENSUS_SUBSETS` to 1 in the constants file.

[testnetv4-dev] Avoid commit window when NUM_CONSENSUS_SUBSETS=1

---

src/libMessage/Messenger.cpp

Fix node crashed when calculate extra micro block info hash
Check the serialized data is empty. If it is empty, don't calculate the SHA2 and proceed without it.

Fix node crashed when calculate extra micro block info hash

---

src/libCrypto/Sha2.h

This PR fixes Sha2 wrapper Update() function when input is empty. 
- Remove LOG FATAL and replace it with an warning and returning from the function. This is because, if the input is empty, there will be nothing to update() and the hash value is the same. 
This PR also change `<= 0` to `== 0` as `size()` of `vector` will never be negative.

Fix Sha2 wrapper Update() when input is empty

---

src/libDirectoryService/DSBlockPreProcessing.cpp
src/libDirectoryService/DirectoryService.h

If we use `COMM_SIZE` in the constants file, we want to avoid this scenario:
1200 nodes --> 2 shards, 600 nodes each
1199 nodes --> 1 shard, 1199 nodes
To avoid this, we trim the extra nodes beyond multiples of `COMM_SIZE` in `SortPoWSoln`.

Trim the num of shard nodes to avoid going beyond COMM_SIZE

---

src/libMessage/CMakeLists.txt
src/libMessage/MessengerSWInfo.cpp
src/libMessage/MessengerSWInfo.h
src/libMessage/ZilliqaMessage.proto
src/libUtils/CMakeLists.txt
src/libUtils/SWInfo.cpp
src/libUtils/SWInfo.h

This PR does the conversion to Protobuf for `SWInfo`: https://github.com/Zilliqa/Zilliqa/issues/833
Since `Message` is already depending on `Utils` (for `Logger`), adding the new protobuf functions in `Message` will lead to cyclic dependency (as then `Utils` will also need to depend on `Message`). As such, I have created a new library `MessageSWInfo` and placed the protobuf functions for SWInfo inside it.
* Make ProtoDSBlock to use ProtoSWInfo, if required

protobuf swinfo serialize and deserialize

---

src/libNode/DSBlockProcessing.cpp
src/libNode/Node.cpp
src/libNode/Node.h

Upgrading mechanism would call LoadShardStructure() to fill some parameters. In that case, node rejoin should not be called when it not belongs to any shard member. (i.e. DS node)

LoadShardStructure with retrieve should not do rejoin

---

src/libLookup/Lookup.cpp

Lookup node does not require genesis keys to generate the testing transaction anymore. This PR removes the use of GENESIS_KEYS in lookup code, as a necessary step to get https://github.com/Zilliqa/testnet/pull/190 work.
N/A

Remove the dependency on GENESIS_KEYS

---

src/libMessage/MessengerSWInfo.cpp
src/libMessage/ZilliqaMessage.proto
src/libUtils/SWInfo.cpp
src/libUtils/SWInfo.h

https://github.com/Zilliqa/Zilliqa/issues/853
"major" and "minor" is preserved word in GCC 7.3.0, thus we need to rename the variables of SWInfo.

Rename SWInfo container to prevent the naming confliction for GCC 7.3.0

---

src/libRumorSpreading/RumorHolder.cpp

As the build is in release mode, `assert` will not be trigger. This PR replace `assert` in `rumourholder.cpp` with LOG FATAL. 
Note: I did a scan of usage of assert in the Zilliqa codebase (exclude depends) and this is the only place it was found.

Use log fatal instead of assert in rumourholder.cpp

---

src/libCrypto/MultiSig.cpp

In MulitSig.cpp, in certain constructors, it will proceeds to call set() even if memory allocation failed. This PR fixes this issue. In such case, the process will proceeds to de-reference a null ptr, resulting in segfault.

Avoid using set() when oom occurs in multisig.cpp

---

src/libLookup/Lookup.cpp
src/libNode/Node.cpp
src/libNode/Node.h
src/libZilliqa/Zilliqa.cpp

Fix node crash when do DS node rejoin.
Function RejoinAsDS. it will call GetTxBlockFromLookupNodes, when the node receive the Tx blocks, it trigger ProcessSetTxBlockFromSeed, it success, it call CommitTxBlocks, then it will call GetStateFromLookupNodes, when it receive State which is accounts from lookup nodes, it need to operate it, but at the same time, Node::Init is called, two threads try to operate the AccountStore instance at the same time, so node crashed.
The document for this scenario in document.
https://docs.google.com/document/d/1KHEs3DGHGyoTi-YUVBGjG_wO5tpL2doAsqlT4ug9oiM/edit
https://github.com/Zilliqa/Issues/issues/308
Check code modified.

Fix crash when do DS node rejoin

---

docker/Dockerfile
docker/Dockerfile.k8s
docker/Makefile

The installation of mongo drivers is taken out from the main compiling process and becomes a standalone `RUN` command to allow it to be cached. Along with this, the submodule update after the clone is not needed so it's removed as well.
A new target `ubuntu-1804` in Makefile is added to allow quick testing of building zilliqa on Ubuntu 18:04.
Try the following steps after checking out this branch to see the caching improvement
1. `git checkout fix/dockerfile`
2. `cd docker`
3. `make ubuntu-1804 COMMIT=a51a9c1` (the second last commit in this PR)
4. `make ubuntu-1804 COMMIT=d0a874a` (the last commit in this PR)
5. See the different of the output from the above step 4 and step 5. Locate the new layer being added and in 3 and skipped bulding in 4.

Improve caching in image build

---

src/libNode/FinalBlockProcessing.cpp

Normally, once a shard node received a finalblock, it should skip the microblock consensus state and start processing the finalblock. But this mechanism didn't cover if the node received duplicate or malicious finalblock. So we will let the verification of the finalblock being done first before triggering the state change.

[testnetv5-dev] Verify the finalblock node before forcing the state change

---

src/libNode/FinalBlockProcessing.cpp

Normally, once a shard node received a finalblock, it should skip the microblock consensus state and start processing the finalblock. But this mechanism didn't cover if the node received duplicate or malicious finalblock. So we will let the verification of the finalblock being done first before triggering the state change.

Verify the finalblock node before forcing the state change

---

src/libData/AccountData/AccountStore.cpp
src/libData/AccountData/AccountStore.h
src/libLookup/Lookup.cpp
src/libMessage/Messenger.cpp
src/libMessage/Messenger.h
src/libMessage/ZilliqaMessage.proto

The previous code for protobufing the GetState and SetState is buggy. This pr is fixing it.
Also applied shared_mutex in AccountStore to provide read concurrency

Fix Fetch AccountStates from Lookup

---

README.md
tests/Utils/Test_IPConverter.cpp

Fix the complaint from the compiler when building with boost 1.68.0 on MacOS Mojave (10.14.1). (Thanks to @xinshudong for identifying this issue)
The error was
```
../../../tests/Utils/Test_IPConverter.cpp:51:56: error: no matching conversion for functional-style cast from 'boost::multiprecision::uint128_t' (aka 'number<cpp_int_backend<128, 128, unsigned_magnitude, unchecked, void> >') to 'std::__1::string' (aka 'basic_string<char, char_traits<char>, allocator<char> >')
"Expected: 16777343. Result: " + string(result));
^~~~~~~~~~~~~
```
Using `convert_to<std::string>()` member function solves this issue. It also works with boost 1.65.1.
N/A
This is in the test cases so integration test is not necessary.

Fix boost multiprecision int to-string conversion issue 

---

src/libData/BlockChainData/BlockChain.h
src/libData/BlockData/BlockHeader/BlockHeaderBase.h
src/libData/BlockData/BlockHeader/DSBlockHeader.cpp
src/libData/BlockData/BlockHeader/TxBlockHeader.cpp
src/libLookup/Lookup.cpp

Fix lookup dead loop when node retrieve blocks before bootstrap
Check if the block chain is initilized before proceesing the request.
https://github.com/Zilliqa/Issues/issues/327
Run a 200 nodes cloud test to check if have lookup dead issue.

Fix lookup dead loop when node retrieve blocks before bootstrap

---

src/libNetwork/RumorManager.cpp

Fix: Cleanup the gossip hash-rawmessage map during re-initialization.
Please check the file changed.

Cleanup hashes during re-initialization

---

CMakeLists.txt
cmake/FindMHD.cmake
src/libData/AccountData/CMakeLists.txt
src/libServer/CMakeLists.txt

On macOS, the latest version of `libjson-rpc-cpp` installed through `brew install libjson-rpc-cpp` is 1.1.1, which affects the output of `pkg-config ` 
**before, with 1.1.0**
```console
$ pkg-config libjsonrpccpp-common --libs
-L/usr/local/Cellar/libjson-rpc-cpp/1.1.0/lib/ -ljsoncpp
```
**now, with 1.1.1**
```console
$ pkg-config libjsonrpccpp-common --libs
-Llib/pkgconfig -ljsoncpp
```
This causes the issue where `pkg_check_module` find the relative path instead of the absolute path of the library.
This PR fixes the above issue by using `find_package` to do library path search on Mac. It also comes with an improvement that the way of searching is explicilty decided by the platform. 
Others:
- The file `FindMHD.cmake` (pulled from `libjson-rpc-cpp`) is saved in the repo to make …

Use find_package to locate libjson-rpc-cpp

---

src/libMediator/Mediator.cpp

Initialize the  m_isVacuousEpoch to false in constructor of Mediator.

Initialize the m_isVacuousEpoch flag

---

build.sh

Because currently Travis build will check clang-tidy, now we support a build option "linter" for enabling clang-tidy-fix, which is disabled by default.

Build option for clang-tidy-fix

---

src/libData/AccountData/Transaction.cpp

`Transaction::GetShardIndex` uses `log2` to determine the number of bits needed to represent `numShards`.  This `log2` rounds down, so for example `log2(12)` will result in 3 instead of 4.  This means that only shards 0 to 7 will ever get assigned any transactions, while 8 to 11 get nothing.
Instead of implementing this function to support any bit length in a very generic way, it has now been revised to simply just take the last 4 bytes of the address and do a modulo operation to get the corresponding shard for it.

Fixed unbalanced transaction dispatching to shards

---

src/libData/AccountData/AccountStoreSC.tpp

Scilla contracts can output a null message, handle this case. Also the format for conveying acceptance of incoming amount is now changed in Scilla. Update accordingly to match the Scilla update.
https://github.com/Zilliqa/scilla/pull/314
Complete
- [*] **ready for review**
- No testing has been performed as the unit tests for testing contract execution is broken.

Handle null messages from the interpreter's output.json.

---

src/libDirectoryService/FinalBlockPostProcessing.cpp
src/libNode/FinalBlockProcessing.cpp

`HeartBeatPulse` BEGIN and END messages still appear in the log, even if we already disabled the heartbeat feature.  `HeartBeatPulse` execution is also unnecessary and takes up CPU time, so better to just comment out the calls to this function as well, until the time we decide to have heartbeat again.

Remove calls to HeartBeatPulse so we don't see them in logs

---

docker/Makefile

The old approach was error-prone as `zilliqa/scilla` had to be manually updated to the latest build by hand. This ensures that all images that use `zilliqa/scilla` as the `BASE_IMAGE` will always get the most up-to-date version of that image.

Ensure that zilliqa/scilla is up-to-date

---

src/libPOW/pow.cpp

Lowest two values inside `mask` are currently wrong.
Also some minor improvements:
1. Changed magic number `32` to `UINT256_SIZE`
2. Removed `9` from `mask` and just let compiler compute the size (will be 8)

Fix lowest 2 bits mask values in DifficultyLevelInInt

---

src/libPersistence/BlockStorage.cpp
src/libPersistence/BlockStorage.h

When node-rejoin, there is some probability that storing database and retrieving database at the same time, then cause crash. This PR made the database that may cause conflict (m_dsCommitteeDB, m_shardStructureDB) as thread-safe.

Make persistence database as thread-safe

---

src/libDirectoryService/PoWProcessing.cpp
src/libUtils/DataConversion.cpp
src/libUtils/DataConversion.h

This PR contains the following:
1. After calling `Messenger::GetDSPoWSubmission`, check for correct sizes of the PoW string components
2. Fix `HexStrToStdArray` and `HexStrToStdArray64` to prevent buffer overflow
3. Other minor improvements inside DataConversion class

Fix potential buffer overflow when using HexStrToStdArray

---

src/libDirectoryService/DirectoryService.cpp
src/libDirectoryService/ViewChangePreProcessing.cpp
src/libNode/FallbackPostProcessing.cpp

Check for whether node is a lookup should not be performed at the instruction handler level. 
For instance, `ProcessPoWPacketSubmission` has a message handler of `0x5` or `0x7` depending whether the node is lookup or not. However, in the Messages.h it is listed as `POWPACKETSUBMISSION = 0x07`
As such, the check for lookup node should be done at the function level. 
In addition, this PR fixes a minor inaccurate log message

Fix potential wrong messaging to wrong instruction handler and minor log message fix

---

src/libDirectoryService/Coinbase.cpp
src/libNode/Node.cpp

1. StartRetrieveHistory may call SaveCoinbase() for final blocks and micro blocks. This operation should only be applied on DS node. 
2. Regards to the scenario of entire node recovery, database would be copied from lookup node to every nodes.
Thus, for SaveCoinBase(), the shard ID should only be allowed between 0 ~ shardSize - 1.

Fix bug for StartRetrieveHistory that may cause state delta check failed

---

src/libUtils/Logger.cpp
src/libUtils/Logger.h

Zilliqa log should follow the standard timestamp format ISO 8601 (https://en.wikipedia.org/wiki/ISO_8601), to improve readability.
Ex. 18-12-06T11:21:32.007

Support ISO 8601 for log timestamp

---

src/libNetwork/P2PComm.cpp

the sleep should inside the while loop.
PR #732 not fix the problem correctly.

fix 100% CPU problem

---

src/libDirectoryService/DirectoryService.h
src/libNode/Node.cpp

An external node may use the same pubkey and try to join from different IP address, so when a node start to rejoin, it should clear all the old PoWs and pow connections, then can ProcessShardingStructure of the latest one succesffully.
Clean DS variables when start to rejoin as normal.
https://github.com/Zilliqa/Issues/issues/373
Check files changed.

Fix node rejoin and win DS PoW and then process sharding structure fail

---

src/libDirectoryService/DirectoryService.h
src/libDirectoryService/FinalBlockPreProcessing.cpp
src/libDirectoryService/MicroBlockProcessing.cpp

It looks like the value of `errorMsg` returned when calling `CheckMicroBlocks` is actually never used in some places where the function is called.  So, it's better to add a flag to indicate if we want to have the list of hashes copied into `errorMsg` or not.
Also, `DirectoryService::m_numOfAbsentMicroBlocks` is not used anywhere else outside of `CheckMicroBlocks` so I just moved it into the function as a local variable.

Avoid unnecessary errorMsg generation for some calls to CheckMicroBlocks

---

src/common/Constants.cpp
src/common/Constants.h

`COINBASE_REWARD` has to be changed from `unsigned int` to `uint128_t`.
`uint128_t` has a constructor that accepts string input, so this change is easily done by calling `ReadConstantString` instead of `ReadConstantNumeric`.
Tested locally by displaying the read-out value in my test for a very large value.

Change COINBASE_REWARD reading from constants to uint128_t

---

src/libDirectoryService/FinalBlockPostProcessing.cpp
src/libNetwork/DataSender.cpp

The message "B2 size and committee size is not identical!" is showing up in every Tx epoch when doing `ProcessFinalBlockConsensusWhenDone`.
It turns out that this is happening when the DS microblock is being sent inside `Node::CallActOnFinalblock` to the lookup nodes.
This is because the DS microblock's cosignatures are still the default values (1-bit bitmaps) after finalblock consensus.
The fix is to set the DS microblock to have the same cosig as the finalblock.

Fix DS nodes not sending DS microblock to Lookups

---

src/libServer/Server.cpp
src/libServer/Server.h

Reference issue:
https://github.com/Zilliqa/Issues/issues/222

Updating specs for JSONRPC

---

src/libConsensus/ConsensusBackup.cpp
src/libConsensus/ConsensusLeader.cpp
src/libMessage/Messenger.cpp
src/libMessage/Messenger.h
src/libMessage/ZilliqaMessage.proto
tests/Message/Test_Messenger_Consensus.cpp

`ConsensusMessageType::CONSENSUSFAILURE` is currently not validated, and can be used by a malicious node to modify the state of backup nodes.
This PR does the following:
1. Protobuf the ConsensusFailure message
2. Add the basic fields (ID, block num, etc.) to the message
3. Add the leader's signature over the basic fields
4. Add signature validation when the backups get the message
5. Some re-ordering of existing functions/messages inside ZilliqaMessage.proto and Messenger.h/.cpp
6. Add unit test for ConsensusFailure

Validate the ConsensusFailure message from the Leader

---

src/libNode/MicroBlockPostProcessing.cpp

In Node::CommitMicroBlockConsensusBuffer(), call-by-reference of a "vector" is used, and the memory address is passed to another thread. At the same time, this vector might grow (memory re-allocated) in a separated thread (Node::ProcessMicroblockConsensus()). Racing-condition might happened under this kind of scenario, thus we need to apply call-by-value to avoid this.
(reference: https://stackoverflow.com/questions/13793531/mysterious-segmentation-fault-on-destruction)
Below is detailed corestack:
[Current thread is 1 (Thread 0x7fe1e37e6700 (LWP 8763))]
(gdb) bt
#0  0x00007fe557c38428 in raise () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007fe557c3a02a in abort () from /lib/x86_64-linux-gnu/libc.so.6
#2  0x00007fe557c7a7ea in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#3 …

Fix potential race condition in CommitMicroBlockConsensusBuffer

---

src/libNode/DSBlockProcessing.cpp

This PR fixes following:
- Removed duplicate SetState
- CommitTxnPacketBuffer after InitlializeRumorManager. Incase where CommitTxnBuffer takes too long , we will be delaying Initializing RumorManager otherwise.

CommitTxnPacketBuffer after InitializeRumorManager

---

src/libDirectoryService/FinalBlockPostProcessing.cpp
src/libNode/FinalBlockProcessing.cpp

The current issue is that the DS committee is sending forwarding transaction before sending the finalblock, and the `+1` makes the lookup failed bufferring the message. So the change here includes:
1. Move the sending of forwarding transaction later than broadcasting finalblock
2. Remove the `+1` so that the message can get buffered.

Fix DS Forwarding Processed Transaction Too Early

---

src/libServer/Server.cpp

- Made `GetContractAddressFromTransactionID` compliant with the JSON RPC Specs

Fixes to RPC error message format #1084

---

src/libData/BlockChainData/BlockChain.h
src/libData/DataStructures/CircularArray.h
src/libDirectoryService/Coinbase.cpp
src/libDirectoryService/DirectoryService.h
src/libNode/Node.cpp
src/libPersistence/Retriever.cpp

1. Fix extra StateDelta being retrieved if TxBlock from DB is inconsistent
2. Fix GetBlock error e.g. `BlockNum : 3401 != GetBlockNum() : 3451, a dummy block will be used and abnormal behavior may happen!`
3. Fix unmatched type for shard_id when calling `SaveCoinBaseCore` in `SaveCoinBase` which caused integer underflow

Fix extra StateDelta being retrieved if TxBlock from DB is inconsistent

---

src/libDirectoryService/DSBlockPreProcessing.cpp
src/libDirectoryService/PoWProcessing.cpp
src/libMessage/Messenger.h
src/libNode/Node.cpp
src/libNode/PoWProcessing.cpp
src/libPOW/pow.cpp
src/libPOW/pow.h
tests/POW/test_POW.cpp

DS difficulty mining start with shard difficulty winning nonce
It is because the DS PoW start nonce use the current time, it has overlap with shard PoW nonce. The DS PoW should start from the nonce of the shard pow winning nonce, so more node can finish DS PoW, then there will be more nodes finish DS PoW, then the DS difficulty will be higher than shard difficulty.
https://github.com/Zilliqa/Issues/issues/389

DS difficulty mining start with shard difficulty winning nonce

---

src/libDirectoryService/DirectoryService.cpp
src/libNetwork/RumorManager.cpp

This PR fixed the missing clearance of subscriber list during relinitialization of Rumor Manager.
In general, it get clear itself one required message is sent to subscriber in list. However, it should always clear during initialization as well.
Please check file changed.

Clear subscriber list of rumor manager

---

docker/Dockerfile
docker/Dockerfile.cuda
docker/Makefile
docker/dev/Dockerfile

The `zilliqa/scilla:latest` image has some issues. This PR pins the last working version of scilla image.
try `make k8s COMMIT=a773cbe` from the directory `docker/`

Pin the last working scilla image in Dockerfile

---

CMakeLists.txt
README.md
scripts/ci_install_deps.sh
src/libCrypto/Schnorr.cpp

This PR downgrade the OpenSSL version to 1.1.1a until it can be correctly integrated. It involves the following changes:
- revert the only used 1.1.1a function introduced by https://github.com/Zilliqa/Zilliqa/pull/1034
- make the other changes in CMake

Roll back OpenSSL to 1.0.2g

---

src/libCrypto/CMakeLists.txt
src/libCrypto/Schnorr.cpp
src/libCrypto/generate_dsa_nonce.c
src/libCrypto/generate_dsa_nonce.h

The main part of the function is ported from OpenSSL 1.1.1a [`BN_generate_dsa_nonce`](https://github.com/openssl/openssl/blob/7835e97b6ff5cd94a10c5aeac439f4aa145a77b2/crypto/bn/bn_rand.c#L205). There're a few changes in the function to make it work, which is denoted by `FIXME` comment.

Implement BN_generate_dsa_nonce

---

src/libConsensus/ConsensusLeader.cpp

For 600-node shard, I observed that:
1. Challenge was gossiped successfully to all backups
2. All backups sent back responses
3. Leader did NOT receive all those responses successfully
4. This caused consensus to stall
I suspect that it is because of the sheer number of responses in this case.
To avoid this, step 1 can be changed back to its original code before we introduced consensus subsets.
In the original code, we don't gossip the challenge, we only send it to the backups who sent out accepted commits.
Anyway, it is useless to gossip it to backups from whom the leader did not accept the commits, because the leader will just reject the responses from those backups.
(The switch to gossip was necessary for multiple subsets, but since we are sticking to 1 subset, we don't need it anymore …

Avoid gossiping challenge if there is only one consensus subset

---

src/libNode/PoWProcessing.cpp
src/libPOW/pow.cpp
src/libPOW/pow.h
tests/POW/test_RemoteMine.cpp

Add timeout for wating pow result from mining proxy
If mining proxy don't have the pow result, the node will check result forever. Need to add a timeout for it, if doesn't finish pow in time, then need to do rejoin.

Add timeout for waiting pow result from mining proxy

---

src/libDirectoryService/FinalBlockPreProcessing.cpp
src/libDirectoryService/MicroBlockProcessing.cpp

During testing, it was observed that a DS node can accept microblocks repeatedly from the same shard. This PR discards those microblocks once a microblock from the same shard has already been accepted.
It was also observed that after a viewchange, a DS backup that was previously a DS leader (before viewchange) pushed the new DS leader's DS microblock on top of its own proposed DS microblock (for the failed consensus before viewchange).  This PR will erase any DS microblock that is in the set of microblocks before a viewchange occurs.

Drop duplicate microblocks and remove DS microblock before viewchange

---

src/libDirectoryService/DirectoryService.cpp

RAISESTARTPOW was only being send to lookups. 
Instead needs to be send to multiplier aswell. So that it reaches  seed nodes.
And new node trying to join then ask for pow start message from these seed nodes.

Fix : Send start pow message to all including multiplier

---

cmake/InstallG3log.cmake
scripts/ci_build.sh

The clang-tidy output was redirected to reduce the output. However, Travis would get timeout error when no output is detected. So the output is now printed in Travis log to avoid the timeout.
This PR also includes a fix to use a separate install folder for g3log. The install targets of g3log will not be added to Zilliqa install target any more.

Resolve build errored issue on Travis

---

src/libNode/FinalBlockProcessing.cpp

This PR addresses issue - https://github.com/Zilliqa/Issues/issues/412 
Please check file changed.

Remove redundant check on consensudID for FinalBlockProcessing

---

src/libLookup/Lookup.cpp
src/libMessage/Messenger.cpp
src/libMessage/Messenger.h
src/libMessage/ZilliqaMessage.proto

To prevent abuse of `GETSTARTPOWFROMSEED`, which can be sent by any new node, this PR adds a signature to it, with the signature generated over both the `listenport` and the current DS block number, to mitigate message replay.
Extra Fix: I noticed `SetLookupSetRaiseStartPoW` protobuf-ed the `signature` twice so I removed the duplicate call.

Add signature and DS block number to ProcessGetStartPoWFromSeed

---

src/libPersistence/BlockStorage.cpp
src/libUtils/SWInfo.cpp

From previous testnet run, it seems lookup logs roll over very quickly, mostly because of these:
```
[INFO][ 1105][19-01-13T03:17:31.140][ProcessGetDirectoryBlocksFromS] BEGIN
[INFO][ 1105][19-01-13T03:17:31.140][GetBlockLink                  ] 41
[INFO][  534][19-01-13T03:17:31.140][Serialize                     ] BEGIN
[INFO][  534][19-01-13T03:17:31.140][Serialize                     ] END
[INFO][ 1105][19-01-13T03:17:31.141][GetBlockLink                  ] 41
[INFO][ 1105][19-01-13T03:17:31.141][GetVCBlock                    ] 1195
[INFO][ 1105][19-01-13T03:17:31.141][GetBlockLink                  ] 41
[INFO][ 1105][19-01-13T03:17:31.141][GetVCBlock                    ] 1195
[INFO][ 1105][19-01-13T03:17:31.141][GetBlockLink                  ] 41
[INFO][ …
```

Removed excess LOG_MARKER to prevent lookup log bloat

---

VERSION
scripts/release.sh
src/libUtils/UpgradeManager.cpp

Since https://github.com/Zilliqa/Zilliqa/pull/1103, Scilla could be upgraded as well as Zilliqa. For more user-friendly, Zilliqa and Scilla should be able to releasing and upgrading separately.

Zilliqa and Scilla should be released and upgraded separately

---

src/libDirectoryService/ViewChangePreProcessing.cpp

In ProcessGetDSTxBlockMessage, member variables are set before all checks are fully completed. This may result in inconsistent state. This PR change the way it is handled and only set member variables after all checks have been passed.

Set member variable after all checks in ProcessGetDSTxBlockMessage

---

scripts/release.sh

Since https://github.com/Zilliqa/Zilliqa/pull/1103 and https://github.com/Zilliqa/Zilliqa/pull/1191, scilla releasing should use ENABLE_SCILLA_MULTI_VERSION defined in constant file.

Scilla upgrading should use ENABLE_SCILLA_MULTI_VERSION

---

src/libNetwork/DataSender.cpp

Fix node crash because mod zero
Previous, if tmpCommittee.size() is equal to TX_SHARING_CLUSTER_SIZE, committeeTooSmall will be false, then randomDigits % (tmpCommittee.size() - TX_SHARING_CLUSTER_SIZE) will crash.
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `zilliqa --privk 4D2BC288A046BD9AB174DF4E7CDA3486BFC5A8B724A0D7B23CFFA94E9131EF0'.
Program terminated with signal SIGFPE, Arithmetic exception.
#0  0x0000000000812c9f in DataSender::SendDataToOthers(BlockBase const&, std::deque<std::pair<PubKey, Peer>, std::allocator<std::pair<PubKey, Peer> > > const&, std::deque<std::vector<std::tuple<PubKey, Peer, unsigned short>, std::allocator<std::tuple<PubKey, Peer, unsigned short> > >, …

Fix node crash because mod zero

---

src/libLookup/Lookup.cpp

Let's say if a node query a very big range of blocks say (1 to n) and there are no such blocks from (m to n), (n-m) empty dummy block will be created and return. Setting n to be a very large int will cause a node to go OOM.
This PR fix this issue by stopping the retrieval of blocks once the dummy block is returned.

Fix issue where query very high number non-existence blocks can result in OOM

---

tests/Zilliqa/daemon_restart.py

For mainnet, the port would not be a fixed number. Thus daemon should follow correct port number instead of using a fixed port. (30303)

Daemon should use correct port instead of hard-code 30303

---

src/libLookup/Lookup.cpp
src/libServer/Server.cpp

Due to a known issue, comparator for empty `TxBlock()` and `DSBlock()` is not working accurately. This PR implements a workaround to detect empty or dummy blocks. 
In addition, previous comments on hotfix have been renamed to workaround to reflect a more accurate description of the fix.

Changes to method of identification of empty DS and Tx blocks

---

src/libDirectoryService/DirectoryService.h
src/libDirectoryService/FinalBlockPostProcessing.cpp
src/libDirectoryService/FinalBlockPreProcessing.cpp

This PR is similar to #1176, where we should remove the DS microblock from `m_microBlocks[m_currentEpochNum]` before retrying consensus.
Tested in local by making the backups drop the microblock from shard 0, and then checking if the backup was able to fetch the missing mb and re-process the announcement successfully.
@kaikawaliu I also put the same call to `RemoveDSMicroBlock` for `MISSING_TXN`, please help me review if it is ok to do so.

Remove DS microblock before retrying consensus due to MISSINGMICROBLOCK

---

src/libConsensus/ConsensusCommon.cpp
src/libConsensus/ConsensusCommon.h
src/libDirectoryService/FinalBlockPostProcessing.cpp
src/libMessage/Messenger.cpp
src/libMessage/Messenger.h
src/libMessage/ZilliqaMessage.proto
src/libNode/MicroBlockPostProcessing.cpp
tests/Message/Test_Messenger_Consensus.cpp

Add pubkey to the consensus message, verify signature before buffer it. It is alternate approach for PR https://github.com/Zilliqa/Zilliqa/pull/1245
This PR adjusts the fix made in #1214.
The issue with #1214 is that it needs to access committee to retrieve senderPubKey.  But at the time of receipt of this consensus message, it is possible that the consensus object is not yet generated.
Now put the pubkey in the message, even consensus object not generated, still can verify the sender.
https://github.com/Zilliqa/Issues/issues/419

Add pubkey to the consensus message, verify signature before buffer it

---

scripts/validateBackupDB.sh
src/libNode/Node.cpp
tests/Zilliqa/test_zilliqa_local.py

When retrieving sharding structure without ip-mapping file (using the same pod), fetching will cause coredump. This PR fixed this issue, and also fixed validateBackupDB problem caused by Zilliqa command foramt change.

Fix bug for retrieving sharding structure crash

---

daemon/ZilliqaDaemon_AWS.cpp

With the new spec. of recovery-all nodes, the script will create SUSPEND_LAUNCH file first prior to killing ZIlliqa process. In this new scenario, the daemon should send RECOVERY_ALL_SYNC for bootstraping the new launched Zilliqa process.

[release-3.4] Daemon with new recover-all mode should send syncType = RECOVERY_ALL_SYNC

---

daemon/ZilliqaDaemon_AWS.cpp

With the new spec. of recovery-all nodes, the script will create SUSPEND_LAUNCH file first prior to killing ZIlliqa process. In this new scenario, the daemon should send RECOVERY_ALL_SYNC for bootstraping the new launched Zilliqa process.

Daemon with new recover-all mode should send syncType = RECOVERY_ALL_SYNC

---

src/libLookup/Lookup.cpp
src/libNode/Node.cpp
src/libValidator/Validator.cpp

For the nodes not joining network yet, some database would be missing. Then the recovery/upgrading would be failed. For this kind of situation, we always need to copy database from lookup node before applying recovery/upgrading.

Fix recovery issue for node not joining network

---

tests/Data/Test_Contract.cpp

Add a test that does a sequence of contract calls and verifies final balances.
The new test sets up 3 contracts `A`, `B`, `C` and sends them an initial fund of 100 each.
It then invokes `A` by sending it 50. `A` accepts and calls `B`, sending it `50`. `B` also accepts and calls `C`, sending it 50. `C` does not accept. At the end, the expected balances must be 100, 150, 100. But the balances are currently 100, 150 and 150 (extra 50 created).
This is not ready to be merged as it depends on https://github.com/Zilliqa/scilla/pull/405

add test for chain call balance validation

---

src/libMessage/Messenger.cpp

This PR fix  -
Messenger::SetLookupGetNewDSGuardNetworkInfoFromLookup failed due protobuf intialization bug.

Fix protobuf initialization for NodeGetGuardNodeNetworkInfoUpdate

---

src/libNode/Node.cpp

The previous check of the epoch num when receiving txn packet is only appy for the ones receiving from lookup. For receiving from neighbors, it should has a lower number by 1, as the commit of the packet from the node who received from lookup will only happen when a new epoch is mined

Adjust the criteria for epoch num check when receiving packet from neighbors

---

src/libConsensus/ConsensusLeader.cpp
src/libCrypto/MultiSig.cpp
src/libMessage/Messenger.h
src/libNode/DSBlockProcessing.cpp
src/libNode/MicroBlockPostProcessing.cpp

For 600-node shard, running for just 50 epochs (1 hour), we already get this number of messages:
```
[INFO][  149][19-01-30T09:18:52.233][sage/Messenger.h:678][GetConsensusID      ] BEG - appears 2210 times (est size 174kB)
[INFO][  152][19-01-30T09:19:27.268][ostProcessing.cpp:87][ProcessMicroBlockCon] BEG - appears 4420 times (est size 348kB)
[INFO][  883][19-01-30T09:39:19.027][pto/MultiSig.cpp:793][VerifyResponse      ] BEG - appears 800 times (est size 63kB)
And so on...
```
These are not necessary because for the error conditions in the functions, a log will also be displayed.
We also don't need to print the DS committee inside `Node::ProcessVCDSBlocksMessage` because the call to `PutDSCommittee` immediately after it will also print the DS committee.

Clean more log messages in the shard node

---

src/libNode/MicroBlockPreProcessing.cpp
src/libNode/Node.cpp
src/libNode/Node.h

the node may stuck in MicroBlock Consensus without state changing to `WAITING_FINALBLOCK`.
but before the finalblock finally came to it, the txn packet gossiped from the other neighbors may arrive earlier than the finalblock.
as we allow processing txn packet in state = `MICROBLOCK_CONSENSUS` or `MICROBLOCK_CONSENSUS_PREP`
In such case, this packet can be directly inserted into the txn pool. 
But, in fact, we should buffer it before finishing the processing of the coming finalblock.
The effect of this is once microblock consensus stuck happen, it's very possible to have txn_missing in the next microblock consensus round.
One easy solution is temporarily adding a flag, so when the microblock announcement was made by the leader or received and get its signature verified by the backup, it …

Add a flag to avoid process txn packet in the inappropriate timing

---

src/cmd/main.cpp

A simple fix to allow the `--address NAT` to work as expected. The current behaviour complains that 'NAT' is not a valid IP address because of a spurious IP format check. This simply moves the check to inside the `if address != "NAT"` block where it makes sense to check for the IP address format.

Fix argument processing for the NAT address option.

---

src/libLookup/Lookup.cpp
src/libLookup/Lookup.h
src/libNetwork/PeerManager.cpp

No part of our current protocol operation requires the use of the broadcast list within PeerManager. Right now, this list defaults to the entire peer store.  To avoid the unnecessary rebroadcast, this PR returns an empty list, similar to what is done in our other classes like DirectoryService and Node.
**Update** (Commit 0a4c13a):
I have also changed Lookup to return an empty list for `GetBroadcastList`. It was observed during mainnet operation that when a lookup is restarted, it can potentially load the initial DS committee nodes into its peer list.  I also noticed that Lookup did not override the base `GetBroadcastList` implementation, therefore it used that initial peer list to rebroadcast messages back to the DS committee - messages such as `RAISESTARTPOW`.

Remove broadcast list from PeerManager

---

src/libNode/MicroBlockPreProcessing.cpp
src/libNode/Node.h

Fix total gas used check fail problem
Initilize the total gas used and txn fees variable in constructor. And clean the variable even there is no transactions. To avoid last tx blocks data goes into next tx block
https://github.com/Zilliqa/Issues/issues/438

Fix total gas used check fail problem

---

src/libLookup/Lookup.cpp

Fix DS micro block consensus check total reward at DS epoch
Using IncreaseEpochNum function to increase block number, so the m_isVacuousEpoch is updated.
```
[INFO][17999][19-02-08T06:33:58.739][ctoryService.cpp:382][SetState            ] [Epoch 5600] DS State = FINALBLOCK_CONSENSUS
[INFO][17999][19-02-08T06:33:58.739][eProcessing.cpp:1103][RunConsensusOnFinalB] END
[INFO][ 1087][19-02-08T06:33:59.583][work/P2PComm.cpp:304][DoSend              ] <144.202.109.176:33133> is blacklisted - blocking all messages
[WARN][ 1595][19-02-08T06:33:59.800][work/P2PComm.cpp:211][SendMessageSocketCor] Socket connect failed. Code = 110 Desc: Connection timed out. IP address: <45.76.38.88:33133>
[WARN][ 1595][19-02-08T06:33:59.800][work/P2PComm.cpp:216][SendMessageSocketCor] [blacklist] Encountered 110 …
```

Fix rejoined DS backup using the wrong vacuous epoch flag

---

src/libDirectoryService/ViewChangePreProcessing.cpp

Fixed a rare occurrence where DS leader stalled at ds consensus prep or final block consensus prep stage, will result in using wrong block hash (final block instead vc block)  as input to the hash function to select new candidate leader when multiple view change occurs. 
This issue only occurs iff
1. The stalled state is in prep. Note: This situation is unlikely as the transition from prep to consensus requires just creation of consensus object
2. More than 1 view change in the same epoch and same state

Fix a rare cornercase in view change

---

src/libDirectoryService/DirectoryService.cpp
src/libUtils/IPConverter.cpp

Fix for issue https://github.com/Zilliqa/Zilliqa/issues/1402.
Verify that the new code additions allow compilation properly on both GCC 7 and 8.
Rather simple syntax fixes to prevent GCC 8 from throwing errors (catch exception by reference and removing unnecessary const from a cast type).

Fix pedantic errors stopping GCC 8 from compiling.

---

tests/Data/ScillaTestUtil.cpp
tests/Data/ScillaTestUtil.h

`ScillaTestUtil` used by `Test_Contract.cpp` does not work in multi-versioned mode currently. This PR fixes that. `ScillaTestUtil::GetScillaTest` now takes an additional optional (default to version 0) parameter to specify a version.
- [*] **ready for review**
Local testing only.

Make ScillaTestUtil aware of multi-versions

---

tests/Data/ScillaTestUtil.cpp

Corresponding Scilla PR: https://github.com/Zilliqa/scilla/pull/452
This PR updates ScillaTestUtil to fetch the contracts and their inputs from the new updated directory structure in Scilla.
Completed and tested. 
Local testing only.

Update ScillaTestUtil for new Scilla testsuite layout.

---

src/libData/AccountData/AccountStore.cpp
src/libData/AccountData/AccountStoreTrie.h
src/libData/AccountData/AccountStoreTrie.tpp
src/libDirectoryService/FinalBlockPostProcessing.cpp
src/libPersistence/Retriever.cpp

we don't have to refill the m_addressToAccount during the retrieval, and this may cause huge memory consumption. It should be fine to get the account from the m_state when it is needed after it been initialized.

Avoid massive memory consumption during state retrieval

---

src/libDirectoryService/DSBlockPreProcessing.cpp

Copy `m_allDSPoWs` to a local variable to avoid polluting and inconsistency to the class variable when ds consensus is not yet completed.

Use a non class variable when in DS consensus is not finalized

---

CMakeLists.txt
build.sh
scripts/make_image_for_test.sh
src/libLookup/Lookup.cpp
src/libNode/FinalBlockProcessing.cpp
src/libNode/Node.cpp
src/libNode/Node.h

This PR address issue - https://github.com/Zilliqa/Issues/issues/449

Buffer and Process received final blocks after seed is syncedup

---

src/libNode/Node.cpp

During recovery, check and set `m_isVacuousEpoch`

[release-4.1] Set vacuous epoch during recovery

---

src/libLookup/Lookup.cpp
src/libLookup/Lookup.h
src/libZilliqa/Zilliqa.cpp

This PR ensures a lookup node is able to send `SETLOOKUPONLINE` to the other lookups when doing recovery instead of rejoining.
This PR also removes an incorrect check inside `Lookup::ProcessSetLookupOnline` which rejects the message from the lookup if it is not in the online list (which it obviously isn't in at that time).
Test procedure:
1. Launch small-scale cloud testnet with 2 lookups
2. Go into lookup 0 and `pkill zilliqa` to trigger rejoining and sending `SETLOOKUPOFFLINE` to lookup 1
3. Do recovery of lookup 0
4. Verify that lookup 0 recovers successfully and that lookup 1 receives `SETLOOKUPONLINE`

Fix the code for setting a lookup back online

---

src/libDirectoryService/DSBlockPostProcessing.cpp
src/libDirectoryService/DSBlockPreProcessing.cpp
src/libDirectoryService/DirectoryService.cpp
src/libDirectoryService/FinalBlockPostProcessing.cpp
src/libDirectoryService/FinalBlockPreProcessing.cpp
src/libDirectoryService/ViewChangePostProcessing.cpp
src/libNode/FallbackPostProcessing.cpp
src/libNode/MicroBlockPostProcessing.cpp

Fix race condition that may allow consensus message in the same round entering `WhenDone` function twice 

Add state check before entering WhenDone funcs for all consensus

---

src/libData/AccountData/AccountStore.cpp

in MacOS, the handling the previous way of declaring scoped lock is different from Linux, such resulted in stucking at mix usage of `lock_guard` and `shared_lock` or `unique_lock` in scoped lock.
The revised version passed the Test_AccountStore in both linux and macos system.

Fix AccountStore Lock in MacOS

---

src/libConsensus/ConsensusCommon.cpp
src/libConsensus/ConsensusCommon.h
src/libDirectoryService/DSBlockPostProcessing.cpp
src/libDirectoryService/DirectoryService.h
src/libDirectoryService/FinalBlockPostProcessing.cpp
src/libMessage/Messenger.h
src/libNode/MicroBlockPostProcessing.cpp

1. Removed unused parameters for `ProcessDSBlockConsensusWhenDone`
2. Renamed `GetConsensusID` to `PreProcessMessage` in both `ConsensusCommon` and `Messenger`
3. Added extra parameter `bytes& reserializedMessage`, which will return the re-serialized consensus message.
4. Use this `reserializedMessage` in place of the original `message` when buffering the consensus message in microblock and finalblock consensus.

Re-serialize consensus msg when buffering

---

src/libPOW/pow.cpp

when network upgrade to v4.2.0, the proxy rejects all pow requests from node because of "invalid signature".
The root cause is node send request with "timeWindow" but sign with "POW_WINDOW_IN_SECONDS".
https://github.com/Zilliqa/Zilliqa/blob/3e3339f0944218f1e6fe182ec730c7aeb5b192c5/src/libPOW/pow.cpp#L375-L384
A hotfix added in proxy code already, verify signature with fixed POW_WINDOW_IN_SECONDS.
https://github.com/DurianStallSingapore/Zilliqa-Mining-Proxy/commit/3d6534a950325e6488671ac684ac2cbe489b031a

[PoW] fix invalid signature for REMOTE_MINE

---

src/libDirectoryService/Coinbase.cpp
src/libDirectoryService/DirectoryService.h
src/libLookup/Lookup.cpp
src/libLookup/Lookup.h
src/libNode/Node.cpp

1. Removed unused function `DirectoryService::LookupCoinbase`
2. Added `m_lookupNodesStatic` which is same as `m_lookupNodes` but does not get updated whenever some lookups go offline
3. Modified `InitCoinbase` to use `m_lookupNodesStatic`. This prevents differing views between DS nodes when trying to reward lookups, as in some cases some DS nodes may consider lookups as offline and therefore not reward them (since `m_lookupNodes` would no longer contain those lookups).
4. Modified `IsLookupNode` and the calls to `VerifySenderNode` to use `m_lookupNodesStatic`. When a lookup recovers and goes back online, and then tries to send a message to a node, that node may reject the message since it still considers the lookup as offline.
5. Other cases where `m_lookupNodes` is used have been left …

Add lookup list that does not change with online/offline status

---

src/libLookup/Lookup.cpp
src/libNode/DSBlockProcessing.cpp
src/libNode/FinalBlockProcessing.cpp
src/libNode/Node.cpp
src/libNode/Node.h

Refactor `CalculateShardLeader` into `CalculateShardLeaderFromDequeOfNode` and `CalculateShardLeaderFromShard`
- `CalculateShardLeaderFromDequeOfNode` accepts `DequeOfNode` which is `vector<pair<PubKey, Peer>>`
- `CalculateShardLeaderFromShard` accepts `Shard` which is `vector<std::tuple<PubKey, Peer, uint16_t>>`
- Both function do not works on member variables directly.

Refactor and fix calculate shard leader

---

src/libDirectoryService/DSBlockPostProcessing.cpp
src/libDirectoryService/DirectoryService.cpp
src/libDirectoryService/DirectoryService.h
src/libDirectoryService/FinalBlockPostProcessing.cpp
src/libDirectoryService/ViewChangePostProcessing.cpp
src/libNetwork/DataSender.cpp
src/libNetwork/DataSender.h
src/libNode/FinalBlockProcessing.cpp
src/libNode/MicroBlockPostProcessing.cpp
src/libNode/Node.cpp
src/libNode/Node.h

Once we call recovery, turn the flag `m_forceMulticast` to true so that before the next DS epoch consensus, the finalblock will be sent to shards via multicast. And if in guard mode, the receiver will be reloaded by the shard guards so that in the new PoW phase those nodes can keep in sync.

Force multicast to shard guards after upgrading

---

src/libNode/Node.cpp

m_forceMulticast should set to true only when the node wake up as DS. if a shard node set to true then become the DS node, there is no resetting of that value until next DS epoch, so the node will keep multicast for entire one DS epoch

Only set m_forceMulticast to true for DS node

---

src/libDirectoryService/DirectoryService.cpp
src/libDirectoryService/DirectoryService.h
tests/POW/test_POW.cpp

Don't increase difficulty at 1 year epoch number
If at 1 year epoch we increase difficulty by 1, we may have the chance to increase the difficulty by 3, then we may face 0 pow submission issue. And the current method difficulty will increase naturally, no need other special algorithms.

Don't increase difficulty at 1 year epoch number

---

src/libNode/ViewChangeBlockProcessing.cpp

This PR removes the timestamp check for VC block when shard node and lookups are processing it. 
VC block will concat with DS block if view change occurs at DS block consensus. However, due to the nature of view change, it may last longer than the timestamp check if multiple view change occurs. Current checks for VC block is sufficient without a timestamp check.

Remove verification of time stamp when node is processing vcblock

---

src/libMessage/Messenger.cpp
tests/Message/CMakeLists.txt
tests/Message/Test_Messenger_Limits.cpp

There is a default protobuf limit of 64MB.
This PR reconfigures the limit to `MAX_READ_WATERMARK_IN_BYTES` for these 3 messages:
1. `SETTXBLOCKFROMSEED`
2. `SETDIRBLOCKSFROMSEED`
3. `SETSTATEFROMSEED`
File `Test_Messenger_Limits.cpp` added to test each message below and above the limit.
Also tested in local testnet by adding new nodes to make sure each message still works.

Increase protobuf limit for some Get messages

---

docker/Dockerfile

`setuptools` needs to be installed first in the Dockerfile.

Fix missing setuptools

---

src/libNode/Node.cpp
src/libNode/Node.h
src/libPersistence/BlockStorage.cpp
src/libZilliqa/Zilliqa.cpp

Fix RejoinAsNormal to handle any failures
- Fix for Rejoining of node after recovery and that not in shard is extended to all other rejoining cases that can happen for `RejoinAsNormal`
- RejoinAsNormal -> Install -> StartRetrieveFromHistory -> will skip checking of node if in shard or not.

Fix RejoinAsNormal after any failures 

---

src/libConsensus/ConsensusLeader.cpp
src/libConsensus/ConsensusLeader.h

This PR adds logging for responses stats for all subsets indicating no. of responses received from dsguards and those from nondsguards.
Logging applies only for consensus when its at ds level and if DS_GUARD_MODE is enabled.

Add responses stats for each subsets

---

src/libDirectoryService/DirectoryService.h
src/libDirectoryService/ViewChangePostProcessing.cpp
src/libDirectoryService/ViewChangePreProcessing.cpp

When view change precheck failed on a node, `cv_ViewChangeVCBlock` was not notified. As such, when the node rejoins as DS, there is a possibility of view change happening again (on that node), disrupting that particular node ability to participate in normal consensus. 
This PR fixes the aboved mention issue. This PR also refactoring the post view change cleaning up into one function.

Handle VC Precheck cornercase

---

src/libNode/FinalBlockProcessing.cpp
src/libPersistence/BlockStorage.cpp

Let lookup only update MetaType::DSINCOMPLETED only when both of states storing and microblock receiving were done.  

Fix wrong usage of updating DSINCOMPLETED for lookup node

---

src/libPersistence/Retriever.cpp

Fix the state-root check failure that occurs until 10th DS epoch since the epoch `uploadIncrDB.py` script is executed.
Eg: The consolidated state-delta that is available in the first stateDelta_103.tar.gz (being uploaded by `uploadIncrDB.py` ) was skipped. i.e. stateDelta for 100 , 101 and 102 were being skipped. Fixed the same.
**Note:** The issue remediates as soon as 10th DS epoch is crossed. Because after which we don't have consolidated stateDeltas. 
consolidated stateDelta only exist after the start/restart of uploadScript until next 10th DS epoch.

Fix stateroot failure

---

src/libUtils/SafeMath.tpp
tests/Utils/Test_SafeMath.cpp

Fix corner case of safemath
An signed integer substract, for example, type int8_t, when a = 0, b = -128, the substract is overflowed, but it is not handled. Now it has been fixed.

Fix corner case of safemath

---

src/libDirectoryService/DirectoryService.h
src/libDirectoryService/FinalBlockPostProcessing.cpp
src/libNode/FinalBlockProcessing.cpp

Before this PR:
1. DS never store DSMB
2. DS only send DSMB to lookup when 1. non-vacuous 2. TxRootHash not null
3. Lookup load every microblocks involved in the TxBlock
After this PR:
1. DS store DSMB when TxnRootHash not null
2. DS send DSMB whenever TxRootHash not null
3. Lookup won't load DSMB if TxRootHash is null
@KaustubhShamshery can check if there is anything need to be changed on the historical mb verification, basically can skip ds mb if the TxnRootHash is empty

DS store and send DSMicroBlock at every epoch

---

src/libDirectoryService/DirectoryService.cpp
src/libLookup/Lookup.cpp
src/libMessage/Messenger.cpp
src/libZilliqa/Zilliqa.cpp
tests/Data/AccountData/Test_AccountStore.cpp

This PR covers:
- limits number of txBlocks to be sent back by lookup.
- Also, fix verification of DirectoryBlock against upper seed list instead of lookup list.
- Multiple replacement to use `*FromSeed` instead of `*FromLookup`
- Fixes StateDelta issue introduced as side-effect of   PR#1617

Limit TxBlocks on lookup

---

src/libData/BlockChainData/BlockChain.h
src/libServer/Server.h

Zilliqa/Issues/issues/507
Ref Item No. 4  http://www.gotw.ca/publications/mill18.htm
```
a) you want to allow polymorphic deletion through a base pointer, in which case the destructor must be virtual and public; or b) you don't, in which case the destructor should be nonvirtual and protected, the latter to prevent the unwanted usage.
```

Protect destructors of some template classes

---

CMakeLists.txt
src/libData/BlockChainData/BlockLinkChain.cpp
src/libData/BlockData/BlockHeader/VCBlockHeader.cpp
src/libServer/LookupServer.cpp
src/libServer/LookupServer.h
src/libServer/Server.cpp
src/libUtils/Logger.cpp
src/libUtils/RootComputation.cpp
src/libUtils/SWInfo.cpp
tests/Data/Test_EIP.cpp
tests/POW/test_POW.cpp
tests/Utils/Test_SafeMath_Exhaustive.cpp

Build Zilliqa with `-pedantic`

Add pedantic flag to compiler options

---

src/libNetwork/P2PComm.cpp

- This PR covers https://github.com/Zilliqa/Issues/issues/512
- Fixed scope of mutex `m_mutexPeerConnectionCount`

Handle peer connection counter correctly

---

daemon/ZilliqaDaemon_AWS.cpp
src/libConsensus/ConsensusCommon.cpp
src/libData/AccountData/Transaction.cpp
src/libData/AccountData/Transaction.h
src/libDirectoryService/FinalBlockPreProcessing.cpp
src/libNetwork/P2PComm.cpp
src/libPersistence/ContractStorage.cpp
src/libPersistence/Retriever.cpp
tests/Data/BlockChainData/Test_BlockChain.cpp
tests/Data/Test_Block.cpp
tests/cmd/verifyMultiSignature.cpp

This PR fixes issues reported by `cppcheck`. Issues are
- Missing bracket for one of log message
- Pass in by ref where possible 
- Remove unused vars
- Remove `c_str()` from `throw`
- Use prefix operator for non-primitive type
cppcheck options used
```
cppcheck --force --enable=all .
```

Fix issues reported by cppcheck

---

src/libData/AccountData/AccountStoreSC.h
src/libData/AccountData/Transaction.cpp
src/libData/AccountData/Transaction.h
src/libData/BlockData/Block/BlockBase.h

Fix some uninitialized params & Remove explicit copy constructor for std::move 

---

scripts/release.sh

`release.sh` will fetch constant files from running testnet. For dsguard/normal nodes, currently we fetch from `normal-0`. It would be safer to fetch from `dsguard-0` instead of `normal-0`, especially now `normal-0` ~ `normal-179` are not available anymore.

Fetch constant file from dsguard instead of normal node

---

src/libLookup/Lookup.cpp
src/libLookup/Lookup.h
src/libZilliqa/Zilliqa.cpp
src/libZilliqa/Zilliqa.h

Stop lookup api server when it is synchronizing
https://github.com/Zilliqa/Issues/issues/519

Stop lookup api server when it is synchronizing

---

constants.xml
constants_local.xml
src/common/Constants.cpp
src/common/Constants.h
src/libPOW/pow.cpp

Some times because network issue, the pow request failed to send to proxy, have a retry mechanism will have more chance to success.
https://github.com/Zilliqa/Zilliqa/issues/1681

Add retry mechanism for send pow to proxy

---

src/libLookup/Lookup.cpp
src/libNode/FinalBlockProcessing.cpp
src/libNode/Node.cpp

Add log for txn hash

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
CODE_OF_CONDUCT.md
CODING_STYLE.md
CONTRIBUTING.md
ISSUE_TEMPLATE.md

Add few essential MD files.

---

src/libServer/Server.cpp

Add epoch num to GetNodeType

---

src/libMessage/Messenger.cpp

Some error log messages use `entry.address()` which is of type `bytes` and is not readable.
We should instead just use `Address address`, which is also already used for earlier log messages in some of the relevant functions.

Fix log messages for address

---

scripts/release.sh

A quick fix for `kubectl cp ...` command, missing the file name in target path.

Fix of kubectl cp command

---

src/libDirectoryService/DSBlockPostProcessing.cpp
src/libNode/DSBlockProcessing.cpp
src/libNode/PoWProcessing.cpp

Node only do sync if failed to do pow, previous it will download all the persistence from S3 which is redundant and when the block height is big, it takes long time to download persistence and give big pressure to S3.
https://github.com/Zilliqa/Issues/issues/532

Node only do sync if failed to do pow

---

src/libNode/FinalBlockProcessing.cpp

Let the lookup put epochfin during non-vacuous epoch if no microblock is loaded from finalblock.
For fixing issue of PutEpochFin didn't get triggered when no shard is formed:
https://github.com/Zilliqa/Issues/issues/535

Fix epochfin for lookup when no shard formed

---

src/libNode/Node.cpp
src/libNode/Node.h

The `ipMapping.xml` will ONLY be used in recovery the entire network. So for more user-friendly, the zilliqa process should automatically remove this file after using it.

Automatically remove ipMapping.xml after using it

---

src/cmd/validateDB.cpp
src/libNode/Node.cpp
src/libNode/Node.h

Improve validateDB logging and add continueOnError option

---

scripts/downloadIncrDB.py

https://github.com/Zilliqa/Issues/issues/553

add checksum check

---

scripts/auto_back_up.py

In order to avoid the possible crash when calling `auto_back_up.py` without Zilliqa process running, change `GetCurrentMiniEpoch` to `GetEpochFin`.

Use GetEpochFin in auto_back_up.py

---

src/libNode/Node.cpp

Fix access null pointer, the m_retriever is initialized in StartRetrieveHistory function, but for a new node, StartRetrieveHistory function is not called.
https://github.com/Zilliqa/Issues/issues/573

Fix access null pointer

---

src/libLookup/Lookup.cpp
src/libNode/DSBlockProcessing.cpp
src/libNode/Node.cpp
src/libNode/PoWProcessing.cpp

Addresses issue - https://github.com/Zilliqa/Issues/issues/572 and issue - https://github.com/Zilliqa/Issues/issues/575
Fix involves basically:
- ~~Recheck on `m_startedpow` in `StartSyncronization` which avoid calling of `ComposeAndSendGetDirectoryBlocksFromSeed` in most of time.~~  `syncType = NO_SYNC` should take care of this now.
- To handle that remaining small window, used mutex `m_mutexDSBlock` to make sure no `ProcessSetDirectoryBlocksFromSeed` and `ProcessVCDSBlock` are executed at same time.
- `ProcessVCDSBlock` checks for dsblock already and ignore adding to blocklink. Other vcblocks will be ignored already.
- Stop previous `StartSyncronization` start after pow is started. 
- set `syncType = NO_SYNC` in pow state
- skip unwanted processing of DS block in …

Fix Blocklink index 

---

src/libUtils/SysCommand.h
tests/Server/Test_ScillaIPCServer.cpp

Add a unit test in Test_ScillaIPCServer that will invoke the Scilla testsuite to run contract tests, using a state server provided by this C++ unit test.
Yes [w.r.t featre/contractmap branch]

Add a test to run scilla testsuite using external state IPC server

---

src/libData/AccountData/AccountStore.cpp
src/libData/AccountData/AccountStoreSC.h
src/libData/AccountData/AccountStoreSC.tpp

`scilla-checker` will soon charge gas for checking contracts. This PR provides a "gas remaining" argument to `scilla-checker` and also check its output for `gas_remaining` to track how much gas was consumed during the process.
No test has been run. This needs to be tested after the corresponding scilla-checker update is complete.
**NOT** ready for merge into `master`. Can possibly be merged to `feature/contractmap` (against which this PR is created).

Support gas mechanics for scilla-checker

---

src/libNode/Node.cpp
src/libPersistence/BlockStorage.cpp
src/libPersistence/BlockStorage.h

Make Validation faster by avoiding unnecessary deserialization .

Avoid deserialization in CheckIntegrity

---

src/libMessage/ZilliqaMessage.proto

Proto3 does not serialize fields that are set to default value ([reference](https://developers.google.com/protocol-buffers/docs/proto3))
This is a breaking change from proto2, and will be problematic for any of our code that relies on byte consistency (e.g., hashes based on serialized blocks).
To fix this, we force the serialization of these fields by wrapping each one in a `oneof`. ([reference](https://stackoverflow.com/questions/37034746/do-not-set-default-values-in-optional-protobuf-fields-to-minimize-data-sent-over))

Force serialization of primitive proto fields for block and tx data

---

src/common/Constants.h
src/libLookup/Synchronizer.cpp
src/libLookup/Synchronizer.h
tests/Message/CMakeLists.txt
tests/Message/Test_Messenger_Compatibility.cpp

Fix genesis DS block hash not correct problem, and also add auto test case to verify in the future in the change break block hash calculation.

Fix genesis DS block hash not correct problem

---

src/libServer/JSONConversion.cpp

`GetTransaction` API to return code and data of the transaction if present.

Return code & data if they are present

---

src/libLookup/Lookup.cpp
src/libNode/Node.cpp

Fix: For `newlookup` and `level2lookup`
- Don't add itself to lookup node list. --> This resulted in being randomly asked for MicroBlock to himself. 
- skip checking and adding itself (archival nodes) to `OfflineLookupList`.
Applicable only for lookup nodes.

[Release 5.0] Seednodes to skip itself adding to lookupnodes

---

src/libData/AccountData/Account.cpp
src/libData/AccountData/AccountStoreSC.tpp
src/libMessage/Messenger.cpp
src/libPersistence/ContractStorage2.cpp
tests/Data/AccountData/Test_AccountStore.cpp

[release-5.0] Fixes for Smart Contract execution on empty map key & RevertCommitTemp

---

src/libLookup/Lookup.cpp

For the recovered lookup, the lookup server only start after suceessfully synchronized, so before stop lookup server, need to check it is initialized or not.
It is not found because previous we don't sync lookup after recover.
https://github.com/Zilliqa/Issues/issues/576

Fix recover community testnet lookup and it crash

---

CMakeLists.txt
src/cmd/CMakeLists.txt

`data_migrate` was only needed during v5.0.0 network upgrade.  Moving forward, we can exclude it from the build (eventually we can consider removing from src as well).

Remove data_migrate from build

---

src/libUtils/ShardSizeCalculator.cpp
src/libUtils/ShardSizeCalculator.h
tests/Utils/Test_ShardSizeCalculator.cpp

Reference: https://github.com/Zilliqa/Issues/issues/593
The current `GenerateShardCounts` algorithm tries to fill up as many `COMM_SIZE` shards as possible, before allowing an additional shard to be less than `COMM_SIZE`. For example:
```
Low threshold = 500
Shard size = 600
Num nodes = 1099
Result = [ 600 ] -> Unsharded nodes = 499
```
After this PR, `GenerateShardCounts` will go through all possible sharding scenarios and pick the configuration with the least amount of wastage:
```
Low threshold = 500
Shard size = 600
Num nodes = 1099
Result = [ 550, 549 ] -> Unsharded nodes = 0
```
Here's a sample test run across some values:
```
Shard lo,mid,hi=[500,600,600] Nodes=499 Shards=[ ] Unsharded=499
Shard lo,mid,hi=[500,600,600] Nodes=500 Shards=[ 500 ] Unsharded=0
...
Shard …
```

Optimize GenerateShardCounts to minimize number of unsharded nodes

---

src/cmd/restore.cpp
src/libLookup/Lookup.cpp
src/libMediator/Mediator.cpp
src/libMediator/Mediator.h
src/libNode/Node.cpp
src/libPersistence/BlockStorage.cpp
src/libPersistence/BlockStorage.h
src/libPersistence/Retriever.cpp
src/libUtils/ThreadPool.h
src/libValidator/Validator.cpp
src/libValidator/Validator.h
src/libZilliqa/Zilliqa.h
tests/Data/AccountData/Test_Transaction.cpp
tests/Persistence/Test_TxPersistence.cpp

The goal of this PR is to speed up the operation of `Node::CheckIntegrity`, particularly in the part where we check each TxBlock for the presence of both microblocks and transaction bodies. The idea is to perform concurrent checking across a fixed number of threads.
1. Changed `BlockStorage::GetAllTxBlocks` result from `list` to `deque` since `deque` has random element access
1. Templatized `Validator::CheckTxBlocks` so that it supports both these containers of txblocks:
- `deque<TxBlockSharedPtr>` which we get from `BlockStorage::GetAllTxBlocks`
- `vector<TxBlock>` which is the type of `Lookup::m_txBlockBuffer`
1. Removed `ValidatorBase` because doing step 2 above complicates the hierarchy, and also because we never actually have other derived classes besides `Validator`
1. Removed the …

Make txblock check in Node::CheckIntegrity threaded

---

src/libLookup/Lookup.cpp

Keep Updating coinbase during syncup of DS Node to avoid failure ( Failed to verify the Byzantine nodes to be removed) at next DS block consensus.
Issue# - Zilliqa/Issues#601

Keep Updating coinbase during syncup of DS Node

---

scripts/upload_incr_DB.py

This PR will allow reducing of txblk time which could have been blocker for joining and rejoining.
i.e. downloadIncrDB would have gone in loop with small txblk time.

support uploading to incremental db every two epoch instead of one epoch

---

src/libNode/Node.cpp
src/libZilliqa/Zilliqa.cpp

Fix the crash on lookup nodes while recovery due to unitialized `m_shardmemeber` variable.

Avoid sending request for blacklist removal by lookup nodes

---

src/libDirectoryService/DirectoryService.cpp
src/libDirectoryService/DirectoryService.h
src/libLookup/Lookup.cpp
src/libZilliqa/Zilliqa.cpp

After the dsguard pod/instance is deleted and started back, add explicitly check if dsguard was pod deleted explicitly and continue syncing until vacuous

[release-5.2] check if dsguard was pod deleted explicitly

---

src/libDirectoryService/DirectoryService.cpp
src/libDirectoryService/DirectoryService.h
src/libLookup/Lookup.cpp
src/libZilliqa/Zilliqa.cpp

After the dsguard pod/instance is deleted and started back, add explicitly check if dsguard was pod deleted explicitly and continue syncing until vacuous

check if dsguard was pod deleted explicitly

---

src/common/Constants.h

Constants.h still has the constants for cryptographic sizes, which we usually use for serialization.
Since libSchnorr has been moved to its own repo, Zilliqa repo should no longer use those constants.
https://github.com/Zilliqa/Issues/issues/604

Remove unused cryptographic sizes constant

---

src/libZilliqa/Zilliqa.cpp

This PR will fix the corner case where new node can potentially accept any message before its ready.
Issue - https://github.com/Zilliqa/Issues/issues/608

New mining node to block message before its ready

---

src/libNode/Node.cpp
src/libPersistence/BlockStorage.cpp
src/libPersistence/BlockStorage.h
src/libValidator/Validator.cpp
src/libValidator/Validator.h

This PR removes the use of `GetAllTxBlocks` from `CheckIntegrity`.
It also removes the call to `CheckTxBlocks` which used the output of `GetAllTxBlocks`.
Since `CheckTxBlocks` is no longer called, `CheckTxBlocks` has also been reverted back to its simpler non-template version before PR https://github.com/Zilliqa/Zilliqa/pull/1922 (since `deque` of TxBlocks won't be used anymore).
Performance-wise, checking of Tx blocks is still threaded.
However, blocks are now fetched on the fly.
Each Tx block check requires fetching block `n` and block `n-1` (for prevhash check).
Additional logs are displayed to stdout for easier evaluation of checking time.  Here you can see checking of the Tx blocks for 11 months worth of mainnet chain data takes around 11 minutes.
``` …
```

Avoid loading all Tx blocks in valdb

---

src/libNode/DSBlockProcessing.cpp

`LoadShardingStructure` is using IP to check for self's presence in the list.  This is an issue in cases where IP has changed, particularly when re-bootstrapping the testnet during a recovery operation.
Tested during mainnet recovery rehearsal.
Recent change to libSchnorr git commit is also included in this PR.

Check PubKey, not IP, in LoadShardingStructure

---

src/libLookup/Lookup.cpp

In `ProcessGetCosigsRewardsFromSeed`, in the event that all retries are exhausted, `retryCount == 0` does not evaluate to true because the check `retryCount-- > 0` changes `retryCount` to -1.  This causes a crash in the lookups.
Tested during upgrade rehearsal.

Fix retryCount corner case

---

src/libNode/DSBlockProcessing.cpp
src/libNode/Node.cpp

Currently we delete ipMapping.xml the moment it's been used in `StartRetrieveHistory`.
The safer deletion point is after the first DS epoch has passed.
Tested during upgrade rehearsal.

Remove ipMapping.xml only after first DS epoch

---

src/libData/AccountData/AccountStoreSC.h
src/libData/AccountData/AccountStoreSC.tpp
src/libData/AccountData/TransactionReceipt.cpp
src/libData/AccountData/TransactionReceipt.h
tests/Data/AccountData/Test_TransactionReceipt.cpp

- Change m_curContractAddr -> curContractAddr to avoid chain call affecting the current caller address;
- Change m_depth -> m_edge with more relevant meaning
- Add "depth" field in receipt transition field to indicate the current depth in the transition tree of the message

Use Buffered address when append and add DEPTH in transition field

---

scripts/miner_info.py
src/libMediator/Mediator.cpp
src/libMediator/Mediator.h
src/libNode/FinalBlockProcessing.cpp
src/libServer/StatusServer.cpp
src/libServer/StatusServer.h

This PR provides a clean way of taking down a node.
The local API DisablePoW prevents the node from mining in the next epoch, thereby excluding it from being sharded. Once excluded, it is then easier to take down the node permanently.
This way is "clean" as opposed to taking down a node in the middle of an epoch, which interrupts the progress of consensus.
Before disabling:
```
root@nunez2-normal-10:/run/zilliqa# python /zilliqa/scripts/miner_info.py type
Shard Node of shard 0
```
Disable:
```
root@nunez2-normal-10:/run/zilliqa# python /zilliqa/scripts/miner_info.py disable_pow
True
```
After disabling, node stays stuck in vacuous epoch:
```
root@nunez2-normal-10:/run/zilliqa# python /zilliqa/scripts/miner_info.py epoch
5
```
Sample log:
```
[INFO][ …
```

Add DisablePoW

---

scripts/license_checker.sh

license_checker includes the copyright line, which has the year hard-coded to 2019.
This causes the checker to fail for new files with copyright year 2020.
Better to just exclude the copyright line from the check.

Exclude copyright line from license_checker

---

constants.xml
constants_local.xml
src/common/Constants.cpp
src/common/Constants.h
src/libLookup/Lookup.cpp
src/libLookup/Lookup.h
src/libServer/CMakeLists.txt
src/libServer/JSONConversion.cpp
src/libServer/JSONConversion.h
src/libServer/StakingServer.cpp
src/libServer/StakingServer.h
src/libZilliqa/Zilliqa.cpp
src/libZilliqa/Zilliqa.h

This PR adds a new `StakingServer` RPC server that listens on port `4501` (default `STAKING_RPC_PORT` value in `constants.xml`).
This server supports two queries: `GetRawDSBlock` and `GetRawTxBlock`.
The implementation (including setup) mirrors `LookupServer`.
`StakingServer` will be enabled for level2lookup nodes by setting `ENABLE_STAKING_RPC=true` in `constants.xml`.

Add StakingServer

---

src/libDirectoryService/DSBlockPostProcessing.cpp
src/libNode/Node.h

Currently,  ipMapping.xml is only removed for normal shard nodes after first DS epoch has passed.
Same should apply for dsnodes.

Remove ipMapping for dsnodes

---

src/libData/BlockChainData/BlockChain.h
src/libPersistence/Retriever.cpp

Related Issue:
https://github.com/Zilliqa/Issues/issues/614 
Actually the retrieval of all the txn blocks into memory is not essential, which were used to serve getting the lastest block number...
Besides, `CircularArray` was also modified so no need to populate the array with every blocks in history to get the latest view of the blockchain.

Optimize StartRetrieveHistory->RetrieveTxBlocks

---

src/libDirectoryService/DirectoryService.cpp

**Issue observed in mainnet**: 
IP change is broadcasted to lookup nodes but not seed nodes.
So during recovery of any node, it eventually fetches stale DS info from seed node. This resulted in DS IP mismatch for recovered node.
We didn't had this issue with prev release version, may be before we never use to fetch the dsinfo before marking it as synced. we must have been relying on persistence from incr db which have updated ds info. (edited) 
but now, while we fetch other few blocks from upper seed we also fetch latest DS info  but we got it broken now since upper seed don't have updated ds info in this scenario
So, this fix is to send the update to upper seed as well.

Send updated ds identity to upper seeds (l2ls)

---

src/libUtils/UpgradeManager.cpp
src/libUtils/UpgradeManager.h

As https://github.com/Zilliqa/Issues/issues/616 saying, we need to provide following:

Refactor LoadInitialDS

---

src/depends/libDatabase/LevelDB.cpp
src/depends/libDatabase/LevelDB.h
src/depends/libDatabase/MemoryDB.cpp
src/depends/libDatabase/MemoryDB.h
src/depends/libDatabase/OverlayDB.cpp
src/depends/libDatabase/OverlayDB.h
src/libData/AccountData/AccountStore.cpp
src/libData/AccountData/AccountStore.h
src/libDirectoryService/FinalBlockPostProcessing.cpp
src/libLookup/Lookup.cpp
src/libNode/FinalBlockProcessing.cpp
src/libPersistence/BlockStorage.cpp
src/libPersistence/ContractStorage2.cpp
tests/Data/AccountData/Test_AccountStore.cpp

This PR resolves the size limit of account state trie. 
We used to observe an unlimited growth of disk usage of state trie DB even there is only update operation to it. The old solution is to repopulate the whole trie in the end of a DS epoch, but this may take too long to process if the size of accounts in trie is getting huge. Which is not what we want in the long run.
In the old dependency, the deleted trie nodes were not committed to the disk when we update a specific node in the Merkle Partria Tree. In this fix, we dump all the deleted nodes in memory and delete from LevelDB.
Besides, the deletion doesn't take effects in LevelDB until running compaction. Which is normally triggered when we reopen the DB or run compact mannualy. Since compaction won't eliminate LOG and MANIFEST files …

Commit deleted trie nodes from mem to disk & compact LevelDB by reopening

---

src/libNode/Node.h
src/libNode/ViewChangeBlockProcessing.cpp

Few of the normal nodes went in syncing forever due to its incorrect BlockLink Index.
Incorrect BlockLink Index was due duplicate processing of VC block.
mutex has been added to ProcessVCblock to avoid the same.

[release-6.2] Add mutex to fix duplicate processing of vcblock

---

src/libNode/Node.h
src/libNode/ViewChangeBlockProcessing.cpp

Few of the normal nodes went in syncing forever due to its incorrect BlockLink Index.
Incorrect BlockLink Index was due duplicate processing of VC block.
mutex has been added to `ProcessVCblock` to avoid the same.

Add mutex to fix duplicate processing of vcblock

---

ISOLATED_SERVER_setup.md
src/cmd/isolated_server.cpp
src/libServer/IsolatedServer.cpp
src/libServer/IsolatedServer.h

Add option `-t` to enable time trigger.
For example.
```bash
./build/bin/isolatedServer -f isolated-server-accounts.json -t 100
``` 
would increment the abstract blocknum in isolated server every 100 ms or 0.1 s

Add automatic increment to isolated server

---

scripts/miner_info.py
src/libLookup/Lookup.cpp
src/libMediator/Mediator.cpp
src/libMediator/Mediator.h
src/libServer/LookupServer.cpp
src/libServer/StatusServer.cpp
src/libServer/StatusServer.h

`ToggleDisableTxns` is added to the `StatusServer` API, which will set or reset `Mediator::m_disableTxns`.
It's used in 4 places:
1. `LookupServer::CreateTransaction` to prevent new transactions
2. `LookupServer::StartCollectorThread` to prevent forwarding packets to upper seeds
3. `Lookup::SendTxnPacketToNodes` to prevent dispatching packets to shards
4. `Lookup::ProcessForwardTxn` to prevent processing forwarded packets

Add ToggleDisableTxns to local server

---

src/libRumorSpreading/RumorHolder.cpp

This PR is to fix a small issue about setting class filed `m_maxNeighborsPerRound`.

fix(libRumorSpreading): set peer size to class variable other than function argument

---

src/libNode/Node.cpp

This PR address the issue where epoch is incremented twice due to following situation:
1. Incoming message of FinalBlock `437115`  arrived while node was syncing. <-- BUG
2. Node fetched the latest FinalBlock `437115`  from lookup and epoch was increased to `437116` and FB stored to chain.
3. message received at `step 1` is also being processed at same time and while storing to blockchain it does complains
```
[WARN][  270][20-05-27T12:28:54.183][ata/BlockChain.h:113][AddBlock            ] Failed to add 437715 437715
```
However, it still incremented epoch by another one i.e. 437717
**Issue :**  FB Message is not being blocked while in sync. This could potentially happen also with DSBlock message.
**Fix** is to block FB/VCDS block message while normal node is syncing

Block incoming fb/vcds msg while normal node syncing

---

src/libNetwork/Peer.cpp
tests/Network/CMakeLists.txt
tests/Network/Test_Peer.cpp

The goal of the PR is use IPConverter utility function for printing IP address for debugging purpose.
The PR addresses one of the review comment mentioned in the below issue.
https://github.com/Zilliqa/Zilliqa/pull/528

Enhancement - Use IPConverter namespace's utility function for Printing Peer IP address

---

README.md

The git checkout by tag command should be : git checkout tags/v6.2.0

Correct the checkout by tag command in README.md file

---

src/libDirectoryService/DSBlockPreProcessing.cpp
src/libDirectoryService/DirectoryService.h
src/libDirectoryService/GasPricer.cpp
src/libDirectoryService/PoWProcessing.cpp
src/libMessage/Messenger.cpp

For PoWSolution in DirectoryService.h, it is recommended to prepend member variables with m_ as per naming convention

Naming convention fix for struct members of DirectoryService.h file  #378

---

src/libServer/LookupServer.cpp
src/libServer/LookupServer.h
src/libServer/StatusServer.cpp

PR #1976 only enforces sending contract call transactions to DS inside `ProcessForwardTxn`, which is called when a lookup receives txn packets from seed nodes.
This means if a lookup node directly processes `CreateTransaction` itself, the enforcement is not triggered.
This PR adds the checking for `m_sendSCCallsToDS` inside `CreateTransaction` so that the enforcement is covered here as well. It will use the `priority` field only if `m_sendSCCallsToDS` is false, to preserve original behavior.

Check m_sendSCCallsToDS in CreateTransaction

---

docker/Dockerfile
docker/Dockerfile.k8s
docker/Makefile
docker/requirements2.k8s.txt
docker/requirements2.preq.txt
docker/requirements2.txt
docker/requirements3.txt

Version locks python2 and 3 dependencies to requirement files.
Create a testnet cluster from the image built by this commit (2aab02a) and test functionalities.

[release-6.3] Fix/python dependencies

---

src/libNode/Node.cpp

The corresponding error can potentially suppress any other primary error related to the same txnhash.

[release-6.3] Suppress Mempool_already_present (Error 23)

---

scripts/ci_make_image.sh

Version locks python2 and 3 dependencies to requirement files.
Create a testnet cluster from the image built by this commit (cbe057d) and test functionalities.

[release-6.2] replaced ci_make_image.sh

---

src/libDirectoryService/DirectoryService.cpp
src/libDirectoryService/DirectoryService.h
src/libDirectoryService/ViewChangePreProcessing.cpp

This addresses VC8 test issue where multiple nodes perform `RunConsensusOnViewChange` due to the processing of buffered final blocks.
Also, renamed `ProcessGetDSTxBlockMessage` to `ProcessVCPushLatestDSTxBlock` since the message name is `VCPUSHLATESTDSTXBLOCK`.

Abort RunConsensusOnViewChange on DS_SYNC

---

src/libNode/FinalBlockProcessing.cpp

The goal of the PR is to optimize `AddPendingTxn` function where the mutex `m_mutexShards` is acquired twice in one flow.
The code is changed to acquire `m_mutexShards` onetime.
Please refer to below PR for more details:
https://github.com/Zilliqa/Zilliqa/pull/2086#discussion_r435901498

Optimize AddPendingTxn mutex locking code

---

src/libNode/MicroBlockPreProcessing.cpp

Fix logical comparison in GetPendingTxn

Fix logical comparison in GetPendingTxn

---

src/common/Messages.h
src/libDirectoryService/DirectoryService.cpp
src/libDirectoryService/DirectoryService.h
src/libLookup/Lookup.cpp
src/libMessage/Messenger.cpp
src/libMessage/Messenger.h
src/libMessage/ZilliqaMessage.proto
src/libNetwork/P2PComm.cpp
src/libNetwork/P2PComm.h
src/libNetwork/RumorManager.cpp
src/libNetwork/RumorManager.h
src/libNode/DSBlockProcessing.cpp
src/libNode/FinalBlockProcessing.cpp
src/libNode/Node.cpp
src/libNode/Node.h

This PR cover following:
- Shard guard pod deletion scenario where new IP of shard guard is broadcasted to its shard and it joins to shard eventually.
- Recovered shardguard and miner node which is already part of shard will now starts at state `WAITING_FINALBLOCK` instead of `MICROBLOCK_CONSENSUS`. This allows get rid of timing issue and starts with being ready to receive next FinalBlock.
Note: If the recovery takes time which usually will be the case, it will get some missing finalblock which will trigger `RejoinAsNormal`.
- Optimization is done now to check if number of missing txblocks are not more than `NUM_FINALBLOCK_NUM`. If so, it synchronizes those missing ones from seed nodes instead which will be quick. If not, it continues from S3 as usual. 
- Fix the deadlock issue due to …

ShardGuard Pod deletion and few optimization/bug fix

---

src/cmd/isolated_server.cpp
src/libServer/IsolatedServer.cpp
src/libServer/IsolatedServer.h
src/libServer/WebsocketServer.cpp

Enable Websockets on Zilliqa Isolated server.
Also add block-related APIs to time-trigger setup
* GetTxBlock
* GetLatestTxBlock

Add websocket to isolated server

---

scripts/miner_info.py
src/libLookup/Lookup.cpp
src/libNetwork/Blacklist.cpp
src/libNetwork/Blacklist.h
src/libNetwork/P2PComm.cpp
src/libNode/Node.cpp
src/libServer/StatusServer.cpp
src/libServer/StatusServer.h

This PR addresses issue : https://github.com/Zilliqa/Issues/issues/644
**Old behavior:**
The seed nodes registered in multiplier were whitelisted globally. So even if there was connection timeout, they were not blacklisted which resulted in the issue mentioned above.
**New behavior:**
The seed nodes registered in multiplier will be not be whitelisted globally instead will be marked under different category i.e. `seedswhitelist`.
With this, if any of these seed nodes (found in `seedswhitelist` store) results in connection timeout at lookup node, it will be blacklisted under `relaxed` category ( not strict catgeory). This allows such seed node to be relaunched and get itself removed from lookup's blacklist by sending blacklist removal message to lookup.
Also, maintaining separate …

Handle blacklisting of seed node elegantly

---

constants.xml
constants_local.xml
src/common/Constants.cpp
src/common/Constants.h
src/libPOW/pow.cpp

support `MINING_PROXY_TIMEOUT_IN_MS` constant, to control pow proxy connection timout.

MINING_PROXY_TIMEOUT_IN_MS constant added to control connection timout.

---

constants.xml
constants_local.xml
scripts/miner_info.py
src/common/Constants.cpp
src/common/Constants.h
src/libData/BlockChainData/BlockLinkChain.h
src/libDirectoryService/DSComposition.cpp
src/libDirectoryService/DSComposition.h
src/libMediator/Mediator.cpp
src/libMediator/Mediator.h
src/libNode/DSBlockProcessing.cpp
src/libNode/Node.cpp
src/libNode/Node.h
src/libNode/ViewChangeBlockProcessing.cpp
src/libPersistence/BlockStorage.cpp
src/libServer/StatusServer.cpp
src/libServer/StatusServer.h
src/libValidator/Validator.cpp
src/libValidator/Validator.h

This PR allows lookup and seed nodes to perform persistence validation on demand by sending `SetValidateDB` message through the `StatusServer` API server.
The validation shares the same `Node::CheckIntegrity` function used by `src/cmd/validateDB.cpp`, with some adjustments:
1. Some log messages are disabled to prevent flooding the zilliqa log (look for `showLogs` in the changes).
1. New function `CheckDirBlocksNoUpdate` is used instead of `CheckDirBlocks` (to avoid modifying the run-time variables and just load blocks from persistence)
1. Lambda `validateOneTxBlock` is called sequentially to keep the entire validation sequence single-threaded

In-node validation using StatusServer

---

src/libMediator/Mediator.h
src/libServer/JSONConversion.cpp

Since the `rewards` field in the actual TxBlock can mean for Transaction fees incurred during non-vacuous epoch and also coinbase reward during vacuous epoch. For avoid misunderstanding we decided to explain it into two fields in API level, `TxnFees` and `Rewards` respectively as below:
```
| TxnFees | Rewards
Non-vacuous       | fees    | 0
Vacuous           | 0       | coinbase
```

Divert naming of rewards field in different epoch

---

daemon/ZilliqaDaemon.cpp

`upload_incr_DB` in backup mode (different S3 location) is not used for anything right now.
Better to omit it and relieve `lookup-0` of having to do both persistence backup and incremental DB updating.
Before:
`lookup-0`: `auto_backup` and `upload_incr_DB`
`lookup-1`: `upload_incr_DB (backup S3 location)`
After:
`lookup-0`: `upload_incr_DB`
`lookup-1`: `auto_backup`

Move auto_backup to lookup-1 and skip upload_incr_DB backup

---

src/libServer/GetWorkServer.cpp
src/libServer/GetWorkServer.h

It's possible for `GetWorkServer::submitWork` to receive another solution in the time between `StopMining` for difficulty and `StartMining` for ds_difficulty.
When this happens, `GetWorkServer::UpdateCurrentResult` will trigger `m_cvGotResult` prematurely, causing `Node::StartPoW` to stop mining for DS difficulty and submitting this second solution (which may not satisfy ds_difficulty) to DS committee.
The fix is to keep track of current difficulty inside `GetWorkServer` using a new `m_currentTargetDifficulty` member variable.
1. Set value to difficulty level during `GetWorkServer::StartMining`
1. Pass this value as a parameter into `GetWorkServer::UpdateCurrentResult`
1. Just before accepting PoW result inside `GetWorkServer::UpdateCurrentResult`, double-check that the passed parameter …

Fix race condition where GetWorkServer will put difficulty solution for ds_difficulty mining

---

src/libServer/JSONConversion.cpp

Previously governance header was part of `result` header.The PR makes governance info as a part of DS block header.
Output of GetDsBlock api.
`{
"id": "1",
"result": {
"header": {
"BlockNum": "5",
"Difficulty": 3,
"DifficultyDS": 13,
"GasPrice": "1000000000",
"Governance": [
{
"ProposalId": 14,
"ShardVotes": [
{
"VoteCount": 1,
"VoteValue": 14
}
]
},
{
"ProposalId": 15,
"ShardVotes": [
{
"VoteCount": 1,
"VoteValue": 15
}
]
}
],
"LeaderPubKey": "0x022D2FEEB232EB40A72C919840258E9E610A5B77F1A157EEFB9EE307860970D60A",
"PoWWinners": [
"0x03E43265761E26FD6AC7CEF2786625730D80D0CE6C7548A659E3964E0FDBBD24CF"
],
"PrevHash": "a70507269a0d7775c5563850f127db0e79c77cb8663ad16128b54ef87da54d3e",
"Timestamp": "1599644494320586"
},
"signature": …

[release-7.0] Make governance output as part of DS block header instead of separate header

---

src/libServer/JSONConversion.cpp

Previously governance header was part of `result` header.The PR makes governance info as a part of DS block header.
Output of GetDsBlock api.
`{
"id": "1",
"result": {
"header": {
"BlockNum": "5",
"Difficulty": 3,
"DifficultyDS": 13,
"GasPrice": "1000000000",
"Governance": [
{
"ProposalId": 14,
"ShardVotes": [
{
"VoteCount": 1,
"VoteValue": 14
}
]
},
{
"ProposalId": 15,
"ShardVotes": [
{
"VoteCount": 1,
"VoteValue": 15
}
]
}
],
"LeaderPubKey": "0x022D2FEEB232EB40A72C919840258E9E610A5B77F1A157EEFB9EE307860970D60A",
"PoWWinners": [
"0x03E43265761E26FD6AC7CEF2786625730D80D0CE6C7548A659E3964E0FDBBD24CF"
],
"PrevHash": "a70507269a0d7775c5563850f127db0e79c77cb8663ad16128b54ef87da54d3e",
"Timestamp": "1599644494320586"
},
"signature": …

Make governance output as part of DS block header instead of separate header

---

CMakeLists.txt
docker/Dockerfile

Binary `data_migrate` is needed for the next upgrade. It's currently part of build but not in the Docker image. Running it in the Docker will be easier since it requires Scilla as well to run.

[release-7.0] Add data_migrate to Docker image

---

src/libNetwork/Blacklist.cpp
src/libNetwork/Blacklist.h
src/libServer/StatusServer.cpp

AddToSeedsWhitelist gives misleading error msg Could not add IP Address in whitelisted seed list, already present when node is yet to be synced ( i.e. when blacklisting/whitelisting is turned off ).

[release-7.0] Misleading error msg for AddToSeedsWhitelist

---

src/libNetwork/Blacklist.cpp
src/libNetwork/Blacklist.h
src/libServer/StatusServer.cpp

`AddToSeedsWhitelist` gives misleading error msg `Could not add IP Address in whitelisted seed list, already present` when node is yet to be synced ( i.e. when blacklisting/whitelisting is turned off ).

Misleading error msg for AddToSeedsWhitelist

---

src/cmd/main.cpp

The goal of the PR is to provide option to send zilliqa application logs to `stdout` instead of file.
The change introduces new command line parameter `--stdoutlog` which if provided , will send application logs to standard output instead of files.This is applicable for `zilliqa`, `state` , `epoch` logs.

Send Zilliqa application logs to STDOUT

---

src/common/TxnStatus.h
src/libNode/MicroBlockPreProcessing.cpp

When a txn reaches the lookup at the stage when a the lookup did not update the  account nonce in its own local memory
but when the same was recv by DS it was already too late (the txn with same nonce was already processed). It results in rejection of the txn as the nonce does not match.

Add NONCE_TOO_LOW error to dropped txns

---

src/libZilliqa/Zilliqa.cpp

Addresses issue https://github.com/Zilliqa/Issues/issues/670 and also remediate issue https://github.com/Zilliqa/Issues/issues/669

[release-6.4] Redefine recovery process of normal and dsguard nodes

---

scripts/miner_info.py
src/libLookup/Lookup.cpp
src/libMediator/Mediator.cpp
src/libMediator/Mediator.h
src/libNode/FinalBlockProcessing.cpp
src/libServer/StatusServer.cpp
src/libServer/StatusServer.h

For mining proxy server, `GetWorkServer::SetNextPoWTime` is called in two places (after receiving new Tx block):
1. `Lookup::ProcessSetTxBlockFromSeed`
1. `Mediator::IncreaseEpochNum`
Proxy miners then use `GetSecondsToNextPoW` to estimate when the next PoW window will begin.
Currently, next PoW time is estimated using fixed value `TX_DISTRIBUTE_TIME_IN_MS + ANNOUNCEMENT_DELAY_IN_MS` multiplied by the remaining Tx blocks before the end of the current DS epoch.
This block duration is not an accurate estimate because:
1. Actually `ANNOUNCEMENT_DELAY_IN_MS` is not done just once, but twice: during MB and FB consensus
1. Actual block time varies depending on performance of nodes
This PR adds a new variable `Mediator.m_aveBlockTimeInSeconds`
1. It is initially set to `TX_DISTRIBUTE_TIME_IN_MS …

Improve accuracy of GetWorkServer::GetSecondsToNextPoW

---

src/libLookup/Lookup.cpp

It is observed that in master branch, miner node pow submission is breaking because of bug in the code where node goes to fetch `DSInfo` from lookup nodes instead of l2l nodes(seed nodes)
Below is the reference:
https://github.com/Zilliqa/Zilliqa/pull/2283#discussion_r512692382
Note: Once PR is reviewed, will port the fix to `release-7.0` branch

Miner node is not able to do pow submission

---

CMakeLists.txt
build.sh
src/cmd/CMakeLists.txt
src/cmd/migrate_mbs.cpp
src/depends/libDatabase/LevelDB.cpp
src/depends/libDatabase/LevelDB.h
src/libDirectoryService/FinalBlockPostProcessing.cpp
src/libDirectoryService/MicroBlockProcessing.cpp
src/libLookup/Lookup.cpp
src/libMessage/Messenger.cpp
src/libMessage/Messenger.h
src/libMessage/ZilliqaMessage.proto
src/libPersistence/BlockStorage.cpp
src/libPersistence/BlockStorage.h
src/libServer/IsolatedServer.cpp

**MB storage before:**
[microBlocks] hash -> body
**MB storage now:**
[microBlockKeys] hash -> key (epoch+shardid)
[microBlocks] key -> body
Migration to new storage:
1. Validate existing persistence using the `validateDB` from before this PR
1. `./build.sh migrate_mbs` (to enable MIGRATE_MICROBLOCKS flag) on this PR
1. Run `migrate_mbs` on the persistence
1. Replace `microBlocks` levelDB with the newly created `microBlocksNew` levelDB
1. `./build.sh` (to disable MIGRATE_MICROBLOCKS flag) on this PR
1. Run `validateDB` on the migrated persistence
Additional testing:
1. Launch new testnet on migrated persistence
1. Compare output of GetTransactionsForTxBlock between mainnet and testnet for multiple blocks

[release-7.0] Index microblocks by epoch number and shard ID

---

docker/Dockerfile
docker/requirements3.txt

**problem:**
we start a container with bash as the PID1 process
```
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root     24989  0.0  0.0  18484  3492 pts/0    Ss   04:29   0:00 bash
root     25015  0.0  0.0  34424  2828 pts/0    R+   04:29   0:00  \_ ps auxf
root         1  0.0  0.0   4404   704 ?        Ss   Oct20   0:00 tail -f /dev/null
root       288  0.0  0.0  26064  2460 ?        Ss   Oct20   0:00 /usr/sbin/cron
root       290  0.0  0.0      0     0 ?        Z    Oct20   0:00 [bash] <defunct>
root       309  0.0  0.0  22300  2656 ?        Ss   Oct20   0:00 zilliqad 33133 --synctype 5 --nodetype
root       310  0.0  0.0  22300  2684 ?        S    Oct20   0:00  \_ zilliqad 33133 --synctype 5 --node
root       312  0.0  0.0   4500   740 ?        S    Oct20 …
```

add tini and supervisord to image

---

src/libLookup/Lookup.cpp
src/libServer/LookupServer.cpp

Newly created transactions can be accidentally deleted before being dispatched to upper_seed, because the mutex on the txn-shard map is acquired twice: first for creating FORWARDTXN message, and then for deletion of the map. If a transaction is added to the map in between the two steps, it is deleted before dispatch.

[release-7.0] Keep one mutex for both reading and deletion of txn shard map

---

constants.xml
constants_local.xml
scripts/download_incr_DB.py
scripts/upload_incr_DB.py
src/common/Constants.cpp
src/common/Constants.h
src/libPersistence/BlockStorage.cpp
src/libPersistence/BlockStorage.h

After #2311 and #2316, `microBlocks` and `txBodies` leveldbs can now be indexed by epoch number.
This PR will roll over these leveldbs to new folders after every `NUM_EPOCHS_PER_PERSISTENT_DB`th epoch is crossed.
A pointer is maintained for each folder.
Naming convention (assume rollover after 1M epochs):
`microBlocks` (0 to 1M-1)
`microBlocks_1` (1M to 2M-1)
`microBlocks_2` (2M to 3M-1)
...

[release-7.0] Rolling leveldb for microBlocks and txBodies

---

src/libLookup/Lookup.cpp

This PR fix the typo:
`RejoinAsLookup` -> `RejoinAsNewlookup`. Though functionally its still rejoins successfully in both cases but might miss fetching of MB.

[release-7.0] fix the typo

---

scripts/auto_backup.py
scripts/download_incr_DB.py
scripts/download_static_DB.py
scripts/upload_incr_DB.py

This PR cover following:
- Upload incremental script ( running on `lookup-0`) will skip the uploading blockchain-data to incremental db in S3.
- Download incremental script to download blockchain-data from S3 only if node is ` Exclude_microBlocks == False and Exclude_txnBodies == False` which is true only for `seedprv`, `seedpub`, `lookup` and exchange seed nodes.

[release-7.0] Upload and download incr db script to handle blockchain-data

---

src/cmd/migrate_mbs_txns.cpp
src/libPersistence/BlockStorage.cpp
src/libPersistence/BlockStorage.h

`migrate_mbs_txns.cpp` currently skips over microblocks that have 0 txns (root hash = 0).
While non-full nodes (like DS guards) indeed do not store these mbs in their persistence, full nodes (like lookups) actually store these mbs (except if it is for the mb generated by the DS committee). And these mbs are required by dsguards during recovery operation to re-create coinbase for the current DS epoch.
This is why for TxBlocks that have at least one empty mb, dsguards are asking for them from seedpubs.
It's also why seedpubs are failing during `ProcessGetCosigsRewardsFromSeed`, because they themselves also do not have these mbs.
Also changing the mutex type for microBlocks and txBodies since we require exclusive access now.

[release-7.0] Don't skip storing empty mb during migrate_mbs_txns

---

src/libData/AccountData/AccountStoreSC.h
src/libData/AccountData/AccountStoreSC.tpp

A new field `_origin` implying the address of contract sender will be appended to the scilla input message
Related PR in scilla repo:
https://github.com/Zilliqa/scilla/pull/921

[master] Adding _origin field in input message

---

src/libData/BlockChainData/BlockLinkChain.cpp
src/libData/BlockChainData/BlockLinkChain.h
src/libPersistence/BlockStorage.cpp
src/libPersistence/Retriever.cpp

During node launch, `Retriever::RetrieveBlockLink` pollutes the logs with too many messages for:
1. Retrieving entire blocklinks leveldb (each blocklink number is displayed)
2. Reconstruction of DS committee from the blocklinks (member insertion/removal details are displayed)
3. Addition of each processed blocklink into `m_blocklinkchain`
Another such excessive logging happens in `BlockStorage::GetLatestTxBlock` (each 1000th block number retrieved is displayed).
After this PR, we will only display a single message such as:
1. `Retrieving blocklinks...`
2. `Retrieving latest Tx block...`
3. `Reconstructing DS committee from blocklinks (this may take some time)...`

[master] Reduce log messages during node initialization

---

docker/Dockerfile
scripts/make_image_for_test.sh
src/libNode/MicroBlockPreProcessing.cpp

1. Added missing change for `powver` test
2. Added more tx processing logs (`ProcessTransactionWhenShardLeader` and `ProcessTransactionWhenShardBackup` changes should be identical)
3. Corrected the expected nonce for "nonce too small" message
4. Removed `data_migrate` from Dockerfile

[release-7.1] Add more verbose logging to txn processing

---

src/libData/AccountData/TxnPool.h

Fix the issue where in entry from GasIndex for smaller gas price is not removed when one with higher price is added.

[master] Remove GasIndex entry for smaller gas price

---

.gitmodules
CMakeLists.txt
cmake/InstallCryptoUtils.cmake
docker/Dockerfile

There is change in zilliqa repo to use inbuild `cryptoutils` library instead of etash.This requires changes in the `Dockerfile` and fetching of modules. please refer to [https://github.com/Zilliqa/Zilliqa/commit/86263ba52dfd629fcac9830a6a1a548c45076e81](url) for more details.
The PR address the build failure with docker.
Following are the changes.
1)  Update cmake version from 3.10 to 3.19 from the steps specified by @vaivaswatha  in the `cryptoutils` PR merge.
2) Fetch `cryptoutils` repo.

[master] Fix docker build failure in master branch code

---

daemon/ZilliqaDaemon.cpp
daemon/ZilliqaDaemon.h

Daemon is improved to start the process if it fails to monitor the previous running process.
I also stop the `scilla-server` process if running whenever new `zilliqa` process is started.

Improve Daemon to start new process when failed to monitor previous process

---

src/libData/AccountData/AccountStore.cpp

This reverts lookup/seed to old behavior, i.e., skipping init of Scilla component during node startup.
Reference: https://github.com/Zilliqa/Zilliqa/pull/2357#discussion_r538100827

[master] Avoid Scilla init for lookups and seeds

---

src/libNetwork/P2PComm.cpp
src/libNetwork/P2PComm.h

In `p2pseed` branch, we observed deadlock situation during testing for testnet termination scenarios or this could probably also happen if all seed nodes are down for long time(say 2-4 mins).Below is explanation.
When the  testnet is terminated, the seedpubs will always send `BEV_EVENT_ERROR`.
On the client side `GetVCFinalBlockFromL2lDataProvider` is run in the infinite loop.The sender application thread calling `SendMsgToSeedNodeOnWire()` keeps waiting always after taking `m_mutexBufferEvent` in function `bufferevent_write`.This happens randomly if one of the libevent callbacks is received out of order.
The `CloseAndFreeBevP2PSeedConn` function is also waiting to acquire lock.This cause deadlock.
Solution:
We should perform `bufferevent_write()` only if the socket is connected.This way, …

[master] Fix for libevent deadlock in p2pseed

---

constants.xml
constants_local.xml
src/common/Constants.cpp
src/common/Constants.h
src/libServer/JSONConversion.cpp
src/libServer/LookupServer.cpp
src/libServer/LookupServer.h

This PR adds a new field `NumPages` to `GetTxBlock` result:
```
~$ curl -d '{
>     "id": "1",
>     "jsonrpc": "2.0",
>     "method": "GetTxBlock",
>     "params": ["2"]
> }' -H "Content-Type: application/json" -X POST "https://pagination8-api.dev.z7a.xyz/" | jq .
...
{
"id": "1",
"result": {
...
"header": {
"BlockNum": "2",
...
"NumMicroBlocks": 4,
"NumPages": 3,
"NumTxns": 30,
}
}
}
```
It also adds 2 new API:
- `GetTransactionsForTxBlockEx`
- Request format is same as `GetTransactionsForTxBlock` except it has a second parameter (page number)
- Response format is map{"Transactions":[], "CurrPage": int, "NumPages": int}
- `GetTxnBodiesForTxBlockEx`
- Request format is same as `GetTxnBodiesForTxBlock` except it has a second parameter (page number)
- Response format is …

[master] Support pagination for fetching transaction list and transaction bodies

---

src/libDirectoryService/DSBlockPreProcessing.cpp
src/libDirectoryService/DSComposition.cpp

This PR makes sure that `ejected dscommittee members` which are now `shard-members` are removed from blacklist of existing 
ds-committee members.
This change should take effect only at `UPGRADE_TARGET_DS_NUM`

[master] De-blacklist ejected dscommittee members

---

src/libLookup/Lookup.cpp
src/libLookup/Lookup.h
src/libNetwork/P2PComm.cpp
src/libNetwork/P2PComm.h
src/libZilliqa/Zilliqa.cpp

In p2pseed code, client seed is always responsible for closing socket connection on successful response message or no response message.server seed will close upon receipt of `BEV_EVENT_EOF` from client.
However if the key is not whitelisted in our seedpubs, it is better to close connection from server side immediately.In this scenario, client will receive `BEV_EVENT_EOF` from server and terminate socket connection on it's end.
In the same PR, added some optimization in client seed code.
1) To set timeout on bufferevent only if socket connect is successful.
2) Remove `RemoveBevFromMap` from `Zillqa.cpp` for clearing entry from map.Anyway this would be cleared in another call to `RemoveBevFromMap` in `EventCbServerSeed`

[master] P2pseed: close connection from server if the key is not whitelisted.

---

scripts/miner_info.py
src/libLookup/Lookup.h
src/libNode/FinalBlockProcessing.cpp
src/libServer/IsolatedServer.cpp
src/libServer/JSONConversion.cpp
src/libServer/JSONConversion.h
src/libServer/LookupServer.cpp
src/libServer/StatusServer.cpp
src/libServer/StatusServer.h

This adds a way to temporarily disable #2438 (specifically, the `NumPages` field in `GetTxBlock` API response) until 7.2.0 is officially released

[release-7.2] Add ToggleNumPages

---

src/libData/AccountData/AccountStoreSC.h
src/libData/AccountData/AccountStoreSC.tpp
src/libPersistence/ContractStorage2.cpp
src/libPersistence/ContractStorage2.h
tests/Data/CMakeLists.txt
tests/Data/ScillaTestUtil.cpp
tests/Directory/CMakeLists.txt
tests/POW/CMakeLists.txt
tests/Server/CMakeLists.txt

1. `query.mapdepth` may be set to -1 by Scilla (in case of external states, Scilla cannot know this value). The blockchain needs to fetch the value from its database and use it for the lookup.
2. `query.ignoreval` may be set for nonmap fields too. In such a case, the blockchain only needs to return the type of the field and not the value.
3. Field not found should no more be an error. `foundVal` needs to be set to `false` and that's it. This will enable Scilla to check for presence of a field in a contract without it becoming an error.

[master] Updates to external state fetch in ContractStorage2 

---

src/libNetwork/RumorManager.cpp
src/libServer/LookupServer.cpp
src/libUtils/AddressConversion.cpp
src/libUtils/AddressConversion.h
src/libUtils/CMakeLists.txt
tests/Utils/CMakeLists.txt
tests/Utils/Test_AddressConversion.cpp

To add Bech32 utilities and allow the following API to accept both base16 and bech32 for now.
GetBalance
GetSmartContractCode
GetSmartContractInit
GetSmartContracts
GetSmartContractState
GetSmartContractSubState
Was tested with a local isolated server, testing with the bech32 and base16 address

[master] Add bech32 utilities and initial migration to bech32 address

---

src/libDirectoryService/DSBlockPreProcessing.cpp
src/libDirectoryService/DSComposition.cpp
src/libLookup/Lookup.cpp
src/libNode/Node.cpp
src/libNode/Node.h

This PR basically does folllowing:
- Include `shardleader` in `NUM_NODES_TO_SEND_LOOKUP`  while dispatching txnpkt.
Previously, leader is excluded.
- Shard leader is first in the queue to be sent.
- Redundant usage of constant `UPGRADE_TARGET_DS_NUM` is removed.

[master] Lookup to dispatch txn packet to shard leader as well

---

src/common/Constants.h
src/libDirectoryService/Coinbase.cpp
src/libDirectoryService/DSBlockPreProcessing.cpp
src/libDirectoryService/PoWProcessing.cpp

To prevent shard guards from being affected by the reputation, priority is being set to the highest for SHARD_GUARD_TOL percent of nodes.
This will be further trimmed in the SortPoWSoln to fit the shard structure.
There will only be a maximum of SHARD_GUARD_TOL percent of shard guards in the shards.

[master] Exclude shard guards from PoW reputation

---

src/libLookup/Lookup.cpp

This fixes the timing issue with syncing of `extseed` which uses pubkey whitelisting.
- Basically flag `m_vcFinalBlockProcessed` can remains unset in some corner case with timing issue in `GetVCFinalBlockFromL2lDataProvider`. 
- Same also applies for `GetDSBlockFromL2lDataProvider`

[master] Fix timing issue with GetVCFinalBlock

---

src/libDirectoryService/DSBlockPreProcessing.cpp
src/libDirectoryService/PoWProcessing.cpp

A fix for removing the restrictions on maximum shard guards when the total nodes are lesser than the EXPECTED_SHARD_NODE_NUM, else there can be only SHARD_GUARD_TOL amount of total nodes that can be shard guards.

[master] Allow shard guards to fill slots when not enough nodes

---

src/libLookup/Lookup.cpp
src/libLookup/Lookup.h

`Lookup::GenTxnToSend` is used by developer testnets to generate test transactions.
Currently these test transactions are not inserted into the remote db.
Notes:
1. In `SendTxnPacketToNodes`, `SendTxnPacketPrepare` is called twice (`SendTxnPacketPrepare` in turn calls `GenTxnToSend`), so we need to avoid duplicate insertion into the remote db during the second call.
1. I also moved the check for `USE_REMOTE_TXN_CREATOR` from `GenTxnToSend` to `SendTxnPacketPrepare` so that we no longer see pointless "GenTxnToSend failed" messages in mainnet.

[master] Add generated test txns to remote storage DB

---

src/libLookup/Lookup.cpp
src/libZilliqa/Zilliqa.cpp

This PR handles the corner case where it is lagging in previous epoch before starting `RejoinAs*** -> StartSyncronization`.
**Before fix:** Node receives txblock from latest ds epoch however misses the tailend txepoch from previous ds epoch. This is because upperseeds only sends txblocks from latest dsepoch.
**After fix:** It identifies the broken txblock chain and rejoin instead.

[master] Fix corner case : handle receving of stale txblocks

---

.travis.yml
CMakeLists.txt
docker/Dockerfile
docker/Dockerfile.cuda
src/cmd/data_migrate.cpp
src/libData/AccountData/AccountStore.cpp
src/libData/AccountData/AccountStore.h
src/libData/AccountData/AccountStoreSC.h
src/libData/AccountData/AccountStoreSC.tpp
src/libData/AccountData/ScillaClient.cpp
src/libData/AccountData/ScillaClient.h
src/libPersistence/Retriever.cpp
src/libPersistence/Retriever.h
src/libUtils/ScillaUtils.cpp
src/libUtils/ScillaUtils.h

This PR updates the state migration code to perform disambiguation (using the Scilla disambiguation tool). This can be enabled under the new `--disambiguation true` flag to the executable.
N/A

[master] Scilla disambiguation during state migration

---

src/libNode/FinalBlockProcessing.cpp
src/libNode/MicroBlockPreProcessing.cpp
src/libNode/Node.cpp
src/libNode/Node.h

This PR cover:
- Skip waiting on txn processing in vacuous epoch
- Clean all created txns on receiving FB with my shard MB generated but not contributed by me(shard node).
- set `m_txn_distribute_window_open` on rejoin ( No previous  microblock consensus in recovery/rejoin case )
- wait on `cv_FBWaitMB` only if my shard MB generated but not contributed by me and also if node is not in `MICROBLOCK_CONSENSUS_PREP/MICROBLOCK_CONSENSUS` state.
- small-scale cloud test

[release-8.0] Skip waiting on txn processing in vacuous epoch

---

src/libDirectoryService/FinalBlockPostProcessing.cpp
src/libNode/FinalBlockProcessing.cpp
src/libUtils/CMakeLists.txt
src/libUtils/CommonUtils.cpp
src/libUtils/CommonUtils.h

To fix the continuous increase of memory, clean up the memory cache for STL containers for `seeds` , `lookup`, `ds` and `normal` node.
Lookup, seed = Clear every Tx epoch
DS, Miner node = Clear every vacuous epoch.

[master] Fix memory increase issue of lookups/seed nodes

---

constants.xml
constants_local.xml
src/common/Constants.cpp
src/common/Constants.h
src/libData/AccountData/AccountStore.cpp

[release-8.0] Add exclusion list to disambiguation

---

src/libNode/DSBlockProcessing.cpp
src/libNode/Node.cpp

This PR fixes deadlock issue.
- Basically, set `m_txn_distribute_window_open = true` in `Node::StartFirstTxEpoch()`
- Avoid tx packet cleanup in `CleanCreatedTransaction()` when already have packets waiting for state `MICROBLOCK_CONSENSUS_PREP` in order to be distributed to others. Otherwise, it would cause deadlock.

[release-8.0] Avoid deadlock issue

---

scripts/auto_backup.py

We set `isBackup` to true when backup is completed, and set it back to `false` when epoch 0 is reached.
However, I suspect `isBackup` is not being set back to false in time.
This can happen when `backUp()` takes a long time to run (and it might finish beyond epoch 0).
In any case, I don't see the need to keep `isBackup` flag.

[master] Remove isBackup flag from auto_backup.py

---

src/libPersistence/ContractStorage2.cpp
src/libPersistence/ContractStorage2.h

to check if the key was empty, we used to fetch the whole key's value.
Optimize it to just return if it is non-empty

[release-8.0] Make checking for an empty key more optimized

---

src/libDirectoryService/DirectoryService.cpp
src/libLookup/Lookup.cpp
src/libLookup/Lookup.h

This PR tries remediate issue : https://github.com/Zilliqa/Issues/issues/728

[master] Request twice for txblocks when ds node syncing to avoid lagging

---

scripts/download_incr_DB.py
scripts/download_static_DB.py

This PR addresses : https://github.com/Zilliqa/Issues/issues/732
Now, seeds/lookup on Rejoin from S3, will not fetch data from bucket `blockchain-data` instead will reuse the one stored earlier at startup of node.

[master] Avoid fetching BlockChainData(historical MB/TxBodies) for seeds/lookups in case of rejoin from S3

---

daemon/ZilliqaDaemon.cpp

Daemon will clear persistence when dsnode or normal node died, in case persistence were corrupted
https://github.com/Zilliqa/Issues/issues/705
- [] This is not a breaking change

[master] Clear persistence for dsnode and normal node when relaunched by daemon

---

src/libData/AccountData/AccountStoreSC.tpp

This PR addresses issue: https://github.com/Zilliqa/Issues/issues/734

[master] Avoid transfer balance for contract deployment txn

---

src/cmd/restore.cpp
src/libData/AccountData/AccountStore.cpp
src/libData/AccountData/AccountStore.h
src/libDirectoryService/FinalBlockPostProcessing.cpp
src/libLookup/Lookup.cpp
src/libMediator/Mediator.cpp
src/libMediator/Mediator.h
src/libNode/FinalBlockProcessing.cpp
src/libPersistence/Retriever.cpp
src/libServer/IsolatedServer.cpp
src/libServer/LookupServer.cpp
tests/Data/AccountData/Test_AccountStore.cpp

[master] Init Trie calculation made more streamlined

---

CMakeLists.txt
build.sh
scripts/make_image_for_test.sh
src/libDirectoryService/FinalBlockPostProcessing.cpp

Same commit as https://github.com/Zilliqa/Zilliqa/pull/2612

Add VC9 - Suspend before response

---

src/libDirectoryService/FinalBlockPostProcessing.cpp

This PR addresses issue : https://github.com/Zilliqa/Issues/issues/738

[release-8.1] Fix to avoid delay in switching to POW_SUBMISSION state 

---

src/libLookup/Lookup.cpp

`RejoinNetwork` only when there's no other rejoin happening. If the node tries to rejoin from two places, it may crash while downloading persistence.

[master] Do not rejoin twice for responses

---

src/libLookup/Lookup.cpp
src/libNode/Node.cpp

This PR does two things:
- Node to do hard Init instead of soft Init for AccountStore.
- Lookup nodes also calls AccountStore initialization before rejoining.

[release-8.1] Fix for protobuf deserialization issue on lookups during first rejoin attempt

---

src/libLookup/Lookup.cpp

When a normal node is syncing and reached at the start of a new DS epoch If goes for fetching DSInfo and starts POW only when DSInfo is fetched. 
It's been observed in the testnet that If one of the seedpub is down, it can results in a timeout for the normal node while fetching DSInfo and in such a scenario, the normal node doesn't do POW and does not progress. Below are the logs for the isssue.
```
[INFO][  278][21-06-16T05:31:53.534][okup/Lookup.cpp:5705][SetSyncType         ] [Epoch 2904100] Set sync type to 0
[INFO][  278][21-06-16T05:31:53.534][okup/Lookup.cpp:3119][PrepareForStartPow  ] BEG
[INFO][  278][21-06-16T05:31:53.534][okup/Lookup.cpp:3122][PrepareForStartPow  ] [Epoch 2904100] At new DS epoch now, already have state. Getting DSInfo.
[INFO][ …
```

[release-8.1] Fix node is not syncing upon failure to receive DS info during pow start.

---

src/libData/AccountData/AccountStore.cpp
src/libData/AccountData/AccountStoreTrie.tpp

During API calls, the state root if changed can cause an issue during `DeserializeDelta` hence, only make the change in a temporary variable.

[release-8.1] Change root only temporarily

---

src/libDirectoryService/FinalBlockPostProcessing.cpp
src/libNode/FinalBlockProcessing.cpp

Same as https://github.com/Zilliqa/Zilliqa/pull/2652/  and https://github.com/Zilliqa/Zilliqa/pull/2650

[release-8.1] Clean STL cache every tx epoch for normal and ds nodes

---

src/depends/safeserver/safehttpserver.cpp
src/depends/safeserver/safehttpserver.h
src/libServer/StakingServer.cpp
src/libZilliqa/Zilliqa.cpp

Temporary fix for port 4501 CLOSE_WAIT stall on EPOLL.
In this PR, port 4201 and isolated server will still use EPOLL
Port 4501 will use SELECT

Temp fix for port 4501 CLOSE_WAIT stall

---

src/depends/safeserver/safehttpserver.cpp
src/depends/safeserver/safehttpserver.h
src/libServer/StakingServer.cpp
src/libZilliqa/Zilliqa.cpp

Temporary fix via putting port 4501 to use SELECT, and other ports to use EPOLL, due to CLOSE_WAIT on port 4501

[master] temp fix for CLOSE_WAIT stall on epoll in port 4501

---

src/libLookup/Lookup.cpp
src/libLookup/Lookup.h

Remove partialRetrieve bool from RetrieveDSBlocks

[release-8.1] Remove partialRetrieve from RetrieveDSBlocks

---

src/libDirectoryService/DSBlockPostProcessing.cpp
src/libDirectoryService/FinalBlockPreProcessing.cpp

Fix issue:
https://github.com/Zilliqa/Issues/issues/743
https://github.com/Zilliqa/Issues/issues/744

[release-8.1] Add extra txn distribution time before FB consensus when no shard

---

src/libLookup/Lookup.cpp
src/libLookup/Lookup.h

Removing partialRetrieve variable and other code that won't affect the lowBlockNum calculation

[master] Remove partialRetrieve from RetrieveDSBlocks

---

constants.xml
constants_local.xml
src/common/Constants.cpp
src/common/Constants.h
src/depends/safeserver/safehttpserver.cpp
src/depends/safeserver/safehttpserver.h
src/libZilliqa/Zilliqa.cpp

Fixing the CLOSE_WAIT issue by adding 2 timeout
1st timeout is at `notify_connection_callback` for all connections passing by (Usually set to 1 second)
2nd timeout is at `SafeHttpServer::callback` where it look for our callback methods (Here we set it back to unlimited)
This filter out the CLOSE_WAIT connections, which will get eliminated in 1 second.
If we were to turn off the timeout feature, we can just set all timeout in constant to zero. (Zero = No timeout limit)

[master] Fix for CLOSE_WAIT on EPOLL

---

constants.xml
constants_local.xml
src/common/Constants.cpp
src/common/Constants.h
src/depends/safeserver/safehttpserver.cpp
src/depends/safeserver/safehttpserver.h
src/libZilliqa/Zilliqa.cpp

Fixing the CLOSE_WAIT issue by adding 2 timeout
1st timeout is at notify_connection_callback for all connections passing by (Usually set to 1 second)
2nd timeout is at SafeHttpServer::callback where it look for our callback methods (Here we set it back to unlimited)
This filter out the CLOSE_WAIT connections, which will get eliminated in 1 second.
If we were to turn off the timeout feature, we can just set all timeout in constant to zero. (Zero = No timeout limit)

[release-8.1] Fix for CLOSE_WAIT on EPOLL

---

src/depends/safeserver/safehttpserver.cpp
src/depends/safeserver/safehttpserver.h

Putting the timeout for all connections at start daemon.
In case where connections may not reach the notify_connection function.

[master] Set timeout at start daemon for all connections

---

src/libZilliqa/Zilliqa.cpp

Displays the following information:
- Whitelisting mode
- IP Address
- Public Key
- Listening Port
- Staking RPC Status
Refer to this issue for more details : https://github.com/Zilliqa/Issues/issues/741
Example Output:
```
$ ./build/bin/zilliqa --privk B4DB39E759A483387B6ED166A88B020********************************* --pubk 02BB82C9DDD949375907E5B08AC22CA1F********************************* --address 127.0.0.1 --port 33133 --synctype 6 -o --logpath ./tmp/
[46568][21-09-09T19:09:57.178][liqa/Zilliqa.cpp:185][Zilliqa             ] Node startup Information
Whitelisting mode   = IP whitelisting mode
IP Address          = 127.0.0.1
ExtSeed Public Key  = N/A
Listening Port      = 33133
Staking RPC status  = Disabled
$ ./build/bin/zilliqa --privk …
```

[master] Improve node startup logging information

---

src/depends/safeserver/safehttpserver.cpp
src/depends/safeserver/safehttpserver.h

Putting the timeout for all connections at start daemon.
In case where connections may not reach the notify_connection function.

[release-8.1] Set timeout at start daemon for all connections

---

src/libNode/DSBlockProcessing.cpp

If the normal node is not included in the shard structure. It goes for `StartSyncronization`. However, we do not set the SYNC_TYPE to `NORMAL_SYNC`.This causes the thread launched in `StartSyncronization` to terminate immediately and further sync does not happen.
As testing is done on `release-8.1` branch. I will create a clone to master later on.

[release-8.1] Fix syncing issue if node is not part of shard

---

src/libData/AccountData/AccountStore.cpp
src/libData/AccountData/AccountStore.h
src/libServer/IsolatedServer.cpp
src/libServer/LookupServer.cpp
src/libServer/WebsocketServer.cpp
src/libValidator/Validator.cpp

Prioritize `AccountStore::DeserializeDelta` call and all readers updated to wait for the lock if there is any `DeserializeDelta` calls
Issue: https://github.com/Zilliqa/Issues/issues/752
We can now prioritize "write" calls with this mechanism implemented in this PR for `AccountStore`
Currently is there is any calls for `DeserializeDelta`, all read calls will be halted until it gets hold of the mutex. All write calls will still be contending for the mutex.
Below are some performance counters with the following code of 100 requests per second for 200 seconds:
```go
package main
import (
"encoding/json"
"fmt"
"time"
"github.com/Zilliqa/gozilliqa-sdk/provider"
)
var ADR0 = "17444c65ed1b02b508d8343a1e8d943c0102f91a"
var ADR1 = "2773ddfb707749717354fbb83176093112670483"
var ADR2 = …
```

[master] Prioritize DeserializeDelta call for AccountStore

---

src/libNode/PoWProcessing.cpp

Change sending of POW submission to send individually as to prevent shards pow submission being delayed or gone missing leading to mainnet having little shard nodes
Issue: https://github.com/Zilliqa/Issues/issues/751
Current testnet is running at `epoch 150` without any VC.
If there is any other suggestions for the above issue, please do let me know on how to improve this PR

[master] Individual POW submission to DS Committee

---

src/libServer/ScillaIPCServer.cpp
tests/Server/Test_ScillaIPCServer.cpp

This PR fixes the Scilla IPC tests which broke after https://github.com/Zilliqa/Zilliqa/pull/2757. The IPC server now needs (at least a dummy) a blockchain-info provider to be set.
Ready to review and merge.

[master] Fix Scilla IPC tests. Add BCInfo provider

---

src/cmd/isolated_server.cpp
src/libPersistence/Retriever.cpp
src/libPersistence/Retriever.h
src/libServer/IsolatedServer.cpp
src/libServer/IsolatedServer.h

Allow isolated server to run testnet or mainnet persistence.
New paramter added : `nonisoload`
This flag should be set so that isolated server can load mainnet/testnet persistence which can also have statedeltas.
```
desc.add_options()("help,h", "Print help message")(
"file,f", po::value<string>(&accountJsonFilePath),
"Json file containing bootstrap accounts")(
"port,p", po::value<uint>(&port),
"Port to run server on {default: 5555")(
"blocknum,b", po::value<string>(&blocknum_str),
"Initial blocknumber {default : 1 }")(
"time,t", po::value<uint>(&timeDelta),
"the automatic blocktime for incrementing block number (in ms)  "
"(Disabled by default)")(
"load,l", po::bool_switch()->default_value(false),
"Load from persistence folder (False by default)")(
"nonisoload,n", …
```

[master] Added flag nonisoload to allow generate state from statedeltas

---

.travis.yml
docker/Dockerfile
docker/Dockerfile.cuda
src/libServer/ScillaIPCServer.cpp
tests/Data/Test_Contract.cpp

To add support for timestamp in fetchBlockchainInfo.
The timestamp obtained will be from 1 txBlock before the queried one.

[master] Support timestamp in fetchBlockchainInfo for Scilla IPC server

---

constants.xml
constants_local.xml
src/common/Constants.cpp
src/common/Constants.h
src/libConsensus/ConsensusBackup.cpp
src/libConsensus/ConsensusBackup.h
src/libConsensus/ConsensusCommon.cpp
src/libConsensus/ConsensusCommon.h
src/libConsensus/ConsensusLeader.cpp
src/libConsensus/ConsensusLeader.h
src/libDirectoryService/Coinbase.cpp
src/libDirectoryService/DSBlockPostProcessing.cpp
src/libDirectoryService/DSBlockPreProcessing.cpp
src/libDirectoryService/FinalBlockPreProcessing.cpp
src/libDirectoryService/ViewChangePreProcessing.cpp
src/libLookup/Lookup.cpp
src/libLookup/Lookup.h
src/libMessage/Messenger.cpp
src/libMessage/Messenger.h
src/libMessage/ZilliqaMessage.proto
src/libNode/DSBlockProcessing.cpp
src/libNode/MicroBlockPreProcessing.cpp
src/libServer/LookupServer.h
src/libServer/StatusServer.cpp
src/libUtils/CMakeLists.txt
src/libUtils/DNSUtils.cpp
src/libUtils/DNSUtils.h
tests/Message/Test_Messenger_Consensus.cpp
tests/Utils/CMakeLists.txt
tests/Utils/Test_DNSUtils.cpp

To move upper_seeds, l2l_dataprovider and multiplier IPs from constants.xml to getting fetched from DNS
The constants.xml IP still stays, in event where dns is unable to be accessed, we will fall back to the static IPs in there.
**DNS cache**
- This is maintained on a separate thread, to be updated on every DS epoch.
- The `AttemptPopulateLookupsDnsCache` is called at every end of a DS epoch.
- It is separate so that it would not be blocking our nodes function while querying.
- A retry constant `QUERY_DNS_MAX_TRIES` can be use to query again if DNS query failed.
**Local list**
- These are all in the lookup's class. `m_lookupNodes`, `m_seedNodes`, `m_l2lDataProviders`
- These will be updated via looking into the **DNS cache** at every end of DS epoch.
- Because of the DNS querying delay, …

[master] Adding DNS query function for seed nodes

---

.travis.yml
docker/Dockerfile
docker/Dockerfile.cuda
src/libServer/ScillaIPCServer.cpp
tests/Data/Test_Contract.cpp

Add support for fetching Chain ID in `fetchBlockchainInfo` in `ScillaIPCServer.cpp`
The Chain ID fetched is from the one stated in `constants.xml`

[master] Support fetching of Chain ID in fetchBlockchainInfo in Scilla IPC server

---

.travis.yml
VERSION
docker/Dockerfile
docker/Dockerfile.cuda
src/libUtils/SWInfo.h

This PR sets the Scilla version in the new `release-8.2` branch to the one used for v8.1.1 along the `release-8.1` branch.
The Zilliqa version is also set to v8.2.0-alpha.0.

[release-8.2] To Zilliqa v8.2.0-alpha.0 and Scilla v0.11.0

---

ISOLATED_SERVER_setup.md
constants.xml
src/common/Constants.cpp
src/common/Constants.h
src/libData/AccountData/EvmClient.cpp
src/libUtils/EvmUtils.cpp
src/libUtils/EvmUtils.h

Set EVM_SERVER_BINARY to the full path of the binary. The default is /usr/local/bin/evm-ds.

[evm_support_main] Clean up constants related to evm-ds.

---

scripts/download_incr_DB.py

Download historical data first before actual persistence download. The reason for doing so is because of the increasing size of persistence, historical data download takes a long time(around ~15 mins). By the time, the data gets downloaded, it may be possible that we are in a new DS epoch already and this may cause the node to unnecessarily rejoin. This scenario can happen if the node operator starts a seed node at later TX epochs of DS epoch.

[release-8.2] Download historical data before actual persistence download

---

src/libServer/JSONConversion.cpp

Fix bug where the address given to evm call has an 0x prefix and it is not stripped: https://github.com/Zilliqa/evm_ds_test/pull/4

[master] fix bug where 0x is not stripped

---

src/common/Constants.cpp

Add defaults for new constants - that way, when you deploy to the testnet you can avoid having to edit the constants.xml to add new fields.

[master] Use defaults for constants file

---

constants.xml
constants_local.xml
src/common/Constants.cpp
src/common/Constants.h
src/libNode/Node.cpp

Need to add the excluded microblock in the release 8.1.2.
Context explained in the case: https://zilliqa-docs.atlassian.net/wiki/spaces/ZILLIQA/pages/618463233/Updated+validator+config+with+excluded+microblocks
Issue mentioned in the case: https://zilliqa-docs.atlassian.net/wiki/spaces/ZILLIQA/pages/618463233/Updated+validator+config+with+excluded+microblocks

[release-8.1.2] Bypass validation for missing microblock

---

src/libEth/Eth.cpp
src/libEth/Eth.h
src/libServer/JSONConversion.cpp
src/libServer/JSONConversion.h
src/libServer/LookupServer.cpp
src/libServer/LookupServer.h

This PR adds support for eth_getBlockByNumer call. It lacks full transaction conversion to json (if requested by a caller). There're also no tests yet. I decided to keep this PR short and add missing things in next PRs
- [X ] This is not a breaking change
- [X ] **ready for review**

[master] Basic eth-getBlockByNum implementation

---

CMakeLists.txt
src/cmd/CMakeLists.txt
src/cmd/buildTxBlockHashesToNums.cpp
src/common/Constants.h
src/depends/libTrie/TrieDB.h
src/libData/AccountData/AccountStore.cpp
src/libData/AccountData/AccountStore.h
src/libData/AccountData/AccountStoreSC.tpp
src/libData/AccountData/AccountStoreTrie.h
src/libData/AccountData/AccountStoreTrie.tpp
src/libData/BlockChainData/BlockChain.h
src/libDirectoryService/FinalBlockPostProcessing.cpp
src/libLookup/Lookup.cpp
src/libLookup/Synchronizer.cpp
src/libNode/FinalBlockProcessing.cpp
src/libPersistence/BlockStorage.cpp
src/libPersistence/BlockStorage.h
src/libRemoteStorageDB/RemoteStorageDB.cpp
src/libServer/IsolatedServer.cpp
src/libServer/LookupServer.cpp
src/libServer/LookupServer.h
tests/Data/BlockChainData/Test_BlockChain.cpp
tests/Persistence/Test_TxPersistence.cpp

This PR adds possibility to retrieve transaction block by providing a hash. GetBlockByHash is not fully implemented (although some parts of LookupServer has already been touched) as the PR would've become even bigger. Sorry for the unreviewable changes in `TrieDB.h`, but this file became a victim of clang format. The only relevant change made the is `const` specifier for two functions + `mutable` for a class field. That was a consequence of fixing const-ness in Serialize method (from AccountStore classes). 
This is not a breaking change since I'm only adding new things to new leveldb tables. 

[master] Block by hash support

---

src/libServer/LookupServer.cpp
src/libServer/LookupServer.h

Determine shard membership equivalently for CONTRACT_CALL and CONTRACT_CREATION.
Unlike Scilla, creating a contract involves running the EVM code (constructor).
As we only run EVM on DS at the moment, we must use the same logic for both creation
and calls.
This change also does the same for Scilla, which should not be a problem as contract
creation is rare.

[master] Determine shard membership equivalently for CONTRACT_CALL and CONTRACT_CREATION

---

src/libServer/IsolatedServer.cpp
src/libServer/LookupServer.cpp
src/libServer/LookupServer.h
tests/EvmLookupServer/Test_EvmLookupServer.cpp

This PR adds missing eth_getBlockByHash call
[X] **ready for review**
[X ] local machine test

Adding missing  eth_getBlockByHash api call

---

.gitmodules
README.md

🔥 🔥 🔥  MASSIVE THANKS TO STEVE @CSideSteve FOR FINDING THIS BUG 🔥 🔥 🔥 
This fix which is required for etherum uncompressed signatures seems to cause schorr signing to fail when gossiping: https://github.com/Zilliqa/schnorr/pull/15/files
I have split the fix_bn2 branch into just the BN fix and just the signature fix, in order to isolate the issue. This points to a branch that has both (so does not yet fix the issue)

[master] Update Schnorr submodule

---

src/libServer/IsolatedServer.cpp
src/libServer/JSONConversion.cpp
src/libServer/JSONConversion.h
src/libServer/LookupServer.cpp
src/libServer/LookupServer.h
tests/EvmLookupServer/Test_EvmLookupServer.cpp

This PR adds support for eth_getTransactioByHash call. It's been tested manually with IsolatedServer and a unit tests has been added.

[master] Eth-get-transaction-by-hash

---

scripts/ci_build.sh

Allows us to skip CI when it is about something that is not tested by the CI, such as:
- emergency fixes that need to be merged now
- dependency bumps
- etc.

[master] Disable CI when 'NOCI' is present in the commit message

---

src/libServer/IsolatedServer.cpp

The microblock TX root hash was always empty when running in isolated server. This meant that the api calls for get block by hash etc. always thought that there was no transactions in the block.
This sets it to the hash of one of the TXs if there is one there, which enables it to work. I have grepped the codebase for where `m_txnRootHash` is set and I am a little confused how it is supposed to be used in prod.
- [X ] This is not a breaking change

[master] fix on isolated server for microblock tx hash

---

src/libServer/IsolatedServer.cpp
src/libServer/LookupServer.cpp
src/libServer/LookupServer.h
tests/EvmLookupServer/Test_EvmLookupServer.cpp

The goal of this PR is to add new eth calls for getting transactions count in block (either retrieved by hash or num). PR has been tested locally with IsolatedServer and unit tests.
[X] This is not a breaking change
[X] **ready for review**

[master] Adding support for two new eth calls

---

src/libCrypto/EthCrypto.cpp
src/libEth/Eth.cpp
tests/EvmLookupServer/Test_EvmLookupServer.cpp

When testing, it was discovered that the RLP will throw if you feed it incorrect data (in this case, it was the bytecode rather than a raw TX). I had thought that throws were caught by the http framework, but perhaps it only catches the rpc exceptions. In any case, this switches the behaviour to a fail, and it is handled further down.

[master] Saeed fix when contract deploy

---

src/libEth/Eth.cpp

Must handle R and S as numbers, and cast them to 256 bit arrays. Otherwise, bignums that start with at least 0 zeros would lose a byte in the encoding, making the signature invalid for the verifying code later.

[master] Fix padding on R and S elements of the signature

---

src/libServer/LookupServer.h

This PR fixes `eth_getBalance` call which unnecessarily prepends `0x` to a balance of non-existing account (ultimately returning `0x0x0` string). Tested locally with isolated server.

[master] Fix get balance

---

src/libData/AccountData/AccountStore.cpp
src/libPersistence/ContractStorage.cpp
src/libServer/IsolatedServer.cpp
src/libValidator/Validator.cpp

* Replace std::bind1st which is no longer supported in C++17 by
an equivalent lambda.
* Instantiate a Retriever in IsolatedServer to avoid a warning (and
crash) on a null pointer.

[master] Several fixes to support more recent versions of gcc & C++:

---

tests/evm_ds_test/evm_ds_test/api.py
tests/evm_ds_test/evm_ds_test/test_case.py
tests/evm_ds_test/run_test_loop.sh
tests/evm_ds_test/scripts/fund_accounts.py
tests/evm_ds_test/tests/__init__.py
tests/evm_ds_test/tests/conftest.py
tests/evm_ds_test/tests/test_erc20.py
tests/evm_ds_test/tests/test_parent_child.py
tests/evm_ds_test/tests/test_transfer.py

`evm_ds_test` now only depends on the web3 (eth compatible) APIs. No Zilliqa APIs should be used.
To make this work in your local environment,  replace the address `381f4008505e940ad7681ec3468a719060caf796` with `f0cb24ac66ba7375bf9b9c4fa91e208d9eaabd2e`. This is the address correspoding to the private key `d96e9eb5b782a80ea153c937fa83e5948485fbfc8b7e7c069d7b914dbc350aba`.
Correspondingly, the same address is replaced in the genesis accounts fed to the devnet deployment scripts with ` --genesis-address-file` argument:
`s/381F4008505E940AD7681EC3468A719060CAF796/F0CB24AC66BA7375BF9B9C4FA91E208D9EAABD2E/`
The same account in the Internal EVM Testnet has been generously funded.

[master] Remove dependency on pyzil. Normalize amounts in tests

---

build.sh
evm-ds/src/main.rs
tests/EvmLookupServer/constants.xml

A small cleanup of how evm-ds starts

[master] Clean-up around calling evm-ds: fail gently on logs config, not crash

---

evm-ds/src/main.rs
evm-ds/src/scillabackend.rs
src/libServer/ScillaIPCServer.cpp

We pass the original caller of the transaction to evm-ds anyways, no need for a callback.
Maybe other instructions shall be re-implemented in a similar way in the following PRs.

[master] Reimplement ORIGIN instruction by passing the argument without a callback

---

docker/Dockerfile
docker/Makefile
scripts/ci_make_image.sh

Add the REGISTRY argument to the Dockerfile and the Makefile to specify the internal ECR docker registry for the deps image.
Fix the image build issue affecting the Zilliqa Private Image Manual Trigger Jenkins Job.
The ci_make_image.sh script was failing pulling the Zilliqa dependency image as the
zilliqa:v8.2.0-deps is not available on the hub.docker.com and the FROM instruction of the Dockerfile wasn't specifying the full registry image URL.

[master] fix(): Specify the internal docker registry for the deps container

---

CMakeLists.txt
README.md
cmake/InstallJsonrpccpp.cmake

1. Stop compiling jsonrpccpp with code coverage.
2. Update minimum CMake version in CMakeLists.txt & README.

[master] ZIL-4805: don't compile jsonrpccpp with code coverage.

---

src/libServer/LookupServer.h

bugfix - when queried, the TX count will throw if the account does not exist - ethereum expects this to return 0

[master] bugfix to transaction count 

---

tests/evm_ds_test/evm_ds_test/test_case.py

The logic of this gas price is the following:
Min gas price of 0.002 ZIL (2,000,000 gwei) divided by 420 (21000 / 50) would give 4761. However the price in the testnet is closer to 2x the min price.
100000 ensures that the price is about 2x the rounded up 5000 gwei price.
Once the 420 factor fix is in, we can remove the 420 multiplier, and leave just 10000 gwei as the gas price.

[master] Gas price fixes.

---

src/libServer/JSONConversion.cpp

I tried Remix IDE with the Ropsten testnet, and it also works by just sending a txn and waiting for the receipt, and it works.
While with Zilliqa it takes forever.  Could be because of the to address mismatch.

[master] Make the format of receipts similar to that of Eth testnets

---

src/libServer/LookupServer.cpp
src/libServer/LookupServer.h

For most new networks in chainlist.org net_version is the same as eth_chainId, regardless of whether it is mainnet or testnet.

[master] Fix net_version call

---

src/libServer/JSONConversion.cpp

Off by one error when deriving the contract address when populating a TX receipt

[master] fix contract TX receipt issue

---

tests/EvmAcceptanceTests/README.md
tests/EvmAcceptanceTests/hardhat.config.js
tests/EvmAcceptanceTests/helper/ZilliqaHelper.js
tests/EvmAcceptanceTests/test/rpc/eth_blockNumber.js
tests/EvmAcceptanceTests/test/rpc/eth_call.js
tests/EvmAcceptanceTests/test/rpc/eth_coinbase.js
tests/EvmAcceptanceTests/test/rpc/eth_gasPrice.js
tests/EvmAcceptanceTests/test/rpc/eth_getBalance.js
tests/EvmAcceptanceTests/test/rpc/eth_getBlockByNumber.js
tests/EvmAcceptanceTests/test/rpc/eth_getTransactionCount.js
tests/EvmAcceptanceTests/test/rpc/eth_getTransactionReceipt.js
tests/EvmAcceptanceTests/test/rpc/eth_getUncleByBlockHashAndIndex.js
tests/EvmAcceptanceTests/test/rpc/eth_getUncleByBlockNumberAndIndex .js
tests/EvmAcceptanceTests/test/rpc/eth_mining.js
tests/EvmAcceptanceTests/test/rpc/eth_protocolVersion.js
tests/EvmAcceptanceTests/test/rpc/eth_sendRawTransaction.js
tests/EvmAcceptanceTests/test/rpc/eth_sendTransaction.js
tests/EvmAcceptanceTests/test/rpc/eth_sign.js
tests/EvmAcceptanceTests/test/rpc/eth_signTransaction.js
tests/EvmAcceptanceTests/test/rpc/eth_syncing.js
tests/EvmAcceptanceTests/test/rpc/net_listening.js
tests/EvmAcceptanceTests/test/rpc/net_peerCount.js
tests/EvmAcceptanceTests/test/rpc/net_version.js
tests/EvmAcceptanceTests/test/rpc/web3_clientVersion.js
tests/EvmAcceptanceTests/test/rpc/web3_sha3.js

Test results should be as cleanest as we can. just failure or success of tests. I added `--debug` flag so that if it's passed to `npx hardhat test` then logs will be appeared on the screen.

Add debug flag to tests so that log messages will be printed only if this flag is set. [skip ci]

---

src/libServer/JSONConversion.cpp

0x is a valid answer for data as per this link: https://ethereum.org/en/developers/docs/apis/json-rpc/#conventions

[master] revert bad value in extra data

---

Jenkinsfile

Add upper bound on CI duration so that pods don't hang around forever if there is a hang in the build etc.

[master] add jenkins timeout

---

CMakeLists.txt

I noticed that one of the runs in this PR of the unit test (change default iso accounts...) didn't complete its unit tests. The pod is still alive in AWS which is suboptimal. In order to avoid this, add a timeout to the ctests (although there should be some other mechanism to kill the pod after some time)

[master] Force unit tests to have a timeout of 90s

---

CMakeLists.txt
scripts/ci_build.sh
vcpkg-configuration.json
vcpkg-registry/ports/g3log/vcpkg.json
vcpkg-registry/ports/libmicrohttpd/fix-msvc-project.patch
vcpkg-registry/ports/libmicrohttpd/portfile.cmake
vcpkg-registry/ports/libmicrohttpd/vcpkg.json
vcpkg-registry/ports/schnorr/portfile.cmake
vcpkg-registry/versions/baseline.json
vcpkg-registry/versions/l-/libmicrohttpd.json
vcpkg.json

This includes several changes to allow compilation on a M1 Mac:
* Updating the g3log & libmicrohttpd ports by simply removing the restriction that prevents compilation ARM machines.
* Forking libff to prevent unused parts from compiling on ARM. This necessitates updating the CryptoUtils submodule.
This requires invoking: `git submodule update --init --recursive`
**These changes are untested on ARM and are only meant as preliminary changes to start moving in this direction.**

[master] ZIL-4812: support compilation on Mac (M1)

---

tests/EvmAcceptanceTests/contracts/Revert.sol
tests/EvmAcceptanceTests/test/ContractRevert.js

We have one disabled test in `ContractRevert.js` which is addressed in this PR as well as adding two more new tests to revert tests.

[master] Fix revert test, add two new revert tests

---

src/cmd/isolated_server.cpp
src/common/Constants.cpp
src/common/Constants.h

You always want the isolated server to start in lookup mode and can forget to modify constants.xml every so often. Force it such that it is always true to avoid getting random segvs etc.

[master] force to lookup mode in isolated server

---

src/common/Constants.cpp
src/common/Constants.h
src/libData/AccountData/EvmClient.cpp

disables automatic startup of evm-ds allowing you to start and stop your own in the debugger, needs host process to start client first.
- [X ] This is a breaking change
Set LAUNCH_EVM_DAEMON false to stop the dameon launch - default to true

[master] Simple debug helper

---

src/libServer/JSONConversion.cpp

I was reading https://blog.ethereum.org/2021/11/29/how-the-merge-impacts-app-layer, and realized that after the Merge, ethereum no longer has uncles, and also that hashing empty string is wrong, and it should be hasing of RLP([]).

Correct constant for sha3Uncles

---

src/libServer/EthRpcMethods.cpp
tests/EvmAcceptanceTests/test/rpc/eth_getStorageAt.js

The key in the key value pair of storage to value is uppercase. This means if you queried a location in lowercase it would not work. Force uppercase on queries to the storage and enable the requisite test.
It looks like the map lookup code `keccack(LeftPad32(key, 0), LeftPad32(map position, 0))` is working correctly as the data is at a hashed address.

fix bug where contract map addresses did not work correctly

---

ISOLATED_SERVER_setup.md

I just spent a while trying to work out why Scilla contracts couldn't be created, until I eventually tracked it down to an error from the checker which said `BoolUtils` not found. That led me to seeing that my `SCILLA_LIB` constant was pointing at something non-existent.

[master] ZIL-4987: Mention `SCILLA_LIB` in isolated server documentation

---

src/libServer/EthRpcMethods.cpp

Do not allow non-eth TXs to have get TX receipt called on them as this will fail when it tries to reparse the TX into a RLP. Found by @CSideSteve while running scilla tests on the node

[master] Not allow lookup receipt non evm

---

README.md
tests/Server/CMakeLists.txt
vcpkg-configuration.json
vcpkg-registry/ports/websocketpp/cxx20.patch
vcpkg-registry/ports/websocketpp/portfile.cmake
vcpkg-registry/ports/websocketpp/vcpkg.json
vcpkg-registry/versions/baseline.json
vcpkg-registry/versions/w-/websocketpp.json
vcpkg.json

* Add a vcpkg port to patch websocketpp for higher gcc versions with C++20.
* Add a link to the license in README.md (are we required to include the full copy?)
* This might be a temporary solution as there's already a PR in the websocketpp repo for this but for master (and not 0.8.2).

[master] ZIL-5000: patch websocketpp 0.8.2 to compile on gcc in C++20.

---

evm-ds/log4rs.yml

This PR will change the default format of the evm-ds log4rs from plain text to json format.
The json logs produced can be directly indexed by OpenSearch and searchable through Kibana without any additional/custom manipulation or filter.

[master] feat: evm-ds log4rs json format

---

evm-ds/src/convert.rs
evm-ds/src/main.rs
evm-ds/src/precompiles/blake2.rs
evm-ds/src/precompiles/ec.rs
evm-ds/src/precompiles/ecrecover.rs
evm-ds/src/precompiles/identity.rs
evm-ds/src/precompiles/modexp.rs
evm-ds/src/precompiles/ripemd160.rs
evm-ds/src/precompiles/sha2_256.rs
evm-ds/src/scillabackend.rs
src/libData/AccountData/AccountStoreSCEvm.cpp
src/libServer/EthRpcMethods.cpp
src/libUtils/Evm.proto

Change evm-ds logging to fit in one line, so we don't have to look for context
Additionally, provide context, whether this is TXN ID, or estimate or eth_call.

[master] change evm-ds logging to fit in one line

---

src/libData/AccountData/EvmClient.cpp

The evm will segv when parallel JS tests are run against it otherwise

[master] allow parallel runs by locking EVM calls

---

scripts/download_incr_DB.py

These changes come from the following understanding for the behaviour of the existing implementation.
The script downloads all objects from the `incremental/` and `statedelta/` directories from an S3 bucket into a specified local directory. Before starting the download, the script clears the local directory.
The S3 bucket contains a `.currentTxBlk` file specifying the TX block at which the data was uploaded. The script checks this file before and after downloading objects. If there has been newer TX blocks since the download, the script attempts to catch up by downloading what it assumes are the new files. There is some extra logic to restart the download completely if a DS epoch has been crossed during the download period.
Finally, there is some logic to extract `.tar.gz` files after …

[master] ZIL-4799: Simplify and improve `download_incr_DB.py`

---

build.sh

I'm not sure if we should also move these lines earlier too:
```
if [ ${run_clang_tidy_fix} -ne 0 ]; then cmake --build "${build_dir}" --config ${build_type} --target clang-tidy-fix; fi
if [ ${run_clang_format_fix} -ne 0 ]; then cmake --build "${build_dir}" --config ${build_type} --target clang-format-fix; fi
if [ ${run_code_coverage} -ne 0 ]; then cmake --build "${build_dir}" --config ${build_type} --target Zilliqa_coverage; fi
```

[master] Move linting earlier in build process

---

src/depends/jsonrpccpp/common/procedure.cpp
src/libNetwork/Executable.h
vcpkg-registry/ports/opentelemetry-cpp/mac-fix.patch
vcpkg-registry/ports/opentelemetry-cpp/portfile.cmake
vcpkg-registry/ports/opentelemetry-cpp/vcpkg.json
vcpkg-registry/versions/baseline.json
vcpkg-registry/versions/o-/opentelemetry-cpp.json
vcpkg.json

We see this warning:
```
/Users/nhutton/repos/Zilliqa/src/depends/jsonrpccpp/common/procedure.cpp:27:24: error: passing an object that undergoes default argument promotion to 'va_start' has undefined behavior [-Werror,-Wvarargs]
va_start(parameters, returntype);
^
/Users/nhutton/repos/Zilliqa/src/depends/jsonrpccpp/common/procedure.cpp:25:33: note: parameter of type 'jsonrpc::jsontype_t' is declared here
jsontype_t returntype, ...) {
```

[master] disable warning so mac build passes

---

src/libNetwork/CMakeLists.txt

For me, the networking needs to use the hashing functions:
```Undefined symbols for architecture arm64:
"_SHA256_Final", referenced from:
P2PComm::ProcessBroadCastMsg(std::__1::vector<unsigned char, std::__1::allocator<unsigned char> >&, Peer const&) in libNetwork.a(P2PComm.cpp.o)
P2PComm::SendBroadcastMessage(std::__1::vector<Peer, std::__1::allocator<Peer> > const&, std::__1::vector<unsigned char, std::__1::allocator<unsigned char> > const&) in libNetwork.a(P2PComm.cpp.o)
P2PComm::SendBroadcastMessage(std::__1::deque<Peer, std::__1::allocator<Peer> > const&, std::__1::vector<unsigned char, std::__1::allocator<unsigned char> > const&) in libNetwork.a(P2PComm.cpp.o)
SHA2<256u>::FromBytes(std::__1::vector<unsigned char, std::__1::allocator<unsigned char> > const&) in …
```

[master] link to hashing libraries as it fails on mac

---

docker/Dockerfile

Reinstates symlinks to ccache after COPY follows them to the binary.

[master] Fix Dockerfile due to ccache symlinks hanging on Ubuntu 22.04.

---

src/libData/AccountStore/AccountStore.h
src/libData/AccountStore/AccountStoreTrie.cpp
src/libData/AccountStore/AccountStoreTrie.h
src/libServer/EthRpcMethods.cpp

1. Remove the inheritance of `AccountStore` on `AccountStoreSC` - it doesn't have to, as all smart contract interactions are done via the `m_accountStoreTemp`.
Next steps planned are the following:
* Merge `AccountStore` with `AccountStoreTrie`, as there's no other accounts trie in the system - it is a real singleton.
* When the current AccountStore-like object is needed, get AccountStoreTrie instance, and wrap it into a caching AccountStoreTemp on demand.
* Remove AccountStoreSC from the hierarchy as it doesn't have anything related to account store itself, only transaction processing.

[master] AccountStore refactoring: Step 1

---

scripts/auto_backup.py
scripts/download_incr_DB.py
scripts/download_static_DB.py
scripts/upload_incr_DB.py

If the `AWS_ENDPOINT_URL` environment variable is set, the scripts will use the provided URL instead of the default.
This can be used with (for example) localstack to mock AWS locally by setting `AWS_ENDPOINT_URL=http://localhost:4566`.

[master] Make AWS URL configurable in persistence scripts

---

evm-ds/src/evm_server_run.rs
evm-ds/src/pretty_printer.rs

Right now on testnet I'm just not able to find them.   Because usually we search by transation ID, or by source/destination address etc.  Log messages with just EVM results are not super useful unfortunately.

[master] Log the EVM result in the same message as the summary

---

docker/Dockerfile
src/common/MessageNames.h
src/common/Messages.h
src/libCps/CpsAccountStoreInterface.h
src/libCps/CpsExecuteValidator.h
src/libCps/CpsExecutor.h
src/libData/AccountData/TxnPool.h
src/libData/AccountStore/AccountStoreSC.h
src/libDirectoryService/DirectoryService.cpp
src/libDirectoryService/DirectoryService.h
src/libLookup/Lookup.cpp
src/libLookup/Lookup.h
src/libMessage/Messenger.cpp
src/libMessage/Messenger.h
src/libMessage/ZilliqaMessage.proto
src/libNode/MicroBlockPreProcessing.cpp
src/libNode/Node.cpp
src/libNode/Node.h
src/libServer/EthRpcMethods.cpp
src/libServer/EthRpcMethods.h

Added an (Eth) RPC method 'GetDSLeaderTxnPool' (so ENABLE_EVM must be true in constants.xml).
This is sent to a lookup node which then requests the (memory) transaction pool from the DS leader and returns the list of transactions as an array of JSON objects.

EM-39: retrieve txn pool from DS leader

---

src/libServer/WebsocketServerImpl.cpp

I measured the idle timeout on mainnet as 60 seconds. I didn't test the handshake timeout, but 60 seconds feels like a reasonbly uncontroversial number so we've used that too.

[master] EM-37: Change websocket timeouts

---

docker/Dockerfile
scripts/auto_backup.py

Currently, `auto_backup.py` script spent 2 hours just to compress the data. This causes the next few epoch of persistence not to get backed up and also will slow down the mainnet deployment time.
With the use of pigz tool, the `m5.4xlarge` machine can compress the persistence in 15 mins.
Here is the testnet PR for the same where we use the same tool for the extraction of zipped persistence.
https://github.com/Zilliqa/testnet/pull/1002
To merge or hold the PR depends if everyone is ok with the change.

[master] Use pigz for faster compression of persistence

---

src/libMetrics/Logging.cpp
src/libMetrics/Tracing.h
src/libUtils/Logger.cpp
src/libUtils/Logger.h
vcpkg-registry/ports/g3log/extra_data.patch
vcpkg-registry/ports/g3log/portfile.cmake
vcpkg-registry/ports/g3log/vcpkg.json
vcpkg-registry/versions/baseline.json
vcpkg-registry/versions/g-/g3log.json
vcpkg.json

Patch g3log to be able to attach extra data to LogMessage. When logging, request the trace & span Ids at the time of logging so that they're available to every sink.

[master] ZIL-5114: carry the trace & span Ids when logging

---

tests/EvmAcceptanceTests/README.md
tests/EvmAcceptanceTests/hardhat.config.ts
tests/EvmAcceptanceTests/scripts/FundAccountsFromZil.ts

When you start a testnet, your funds are initially in zil addresses, which is inconvenient. This script takes the private keys you have in your hardhat config, and moves half of the funds at that address to the same address, but eth style.

[master] Add funding script for testnets

---

src/libNode/MicroBlockPreProcessing.cpp

m_txnProcessingFinished wasn't always protected by the mutex (m_mutexCVTxnProcFinished) used by the condition variable (cv_TxnProcFinished) to check whether transaction processing had finished. In addition, waiting wasn't done properly and can be done more correctly in C++20.
This fix solves the situation where WaitUntilTxnProcessingDone() was called after the condition variable had been signaled making it wait until the next epoch, ultimately causing a crash.

[master] EM-49: Protect m_txnProcessingFinished with a mutex consistently to prevent race condition

---

.github/workflows/ci-image-dev.yml
README.md
src/libNetwork/P2PComm.cpp

During testing of a rehearsal network, it would fail to generate microblocks for the shard of normals.
This was during a period of the consensus where normals would respond to the leader with a direct message (as opposed to the rumor system which is used to propagate the first step in consensus which is sharing the proposed microblock).
High rates of network timeout/failure were observed, and the peer queue would be ~200. The issue was determined to be that the backlog parameter in `evconnlistener_new_bind` defaults to 128 (the backlog of allowed pending connections), which is less than the 519 connections the leader would have to recieve at this point. This made it such that it could not be replicated on smaller networks as they wouldn't get to this network limit.

[master] Networking fix

---

src/libCps/CpsAccountStoreInterface.h
src/libCps/CpsExecutor.cpp
src/libCps/CpsRunScilla.cpp
src/libData/AccountStore/AccountStoreCpsInterface.h
src/libData/AccountStore/AccountStoreSC.cpp

In case of a few scilla interpreter errors transaction shouldn't be dropped. 
Also, for non-contract calls via legacy API nonce should be incremented.

[master] Accept contract deployment failures in some cases

---

scripts/replay-txn.py

Allows you to replay transactions from one network on another network, assuming the validity properties are the same (e.g. the same network ID and state).
For example,
```
python replay-txn.py 0x2afa7221cbf2784b5ea631ac14bdb82968abbe1b592587bf9fd4e28611a8757c 'https://api.zilliqa.com' 'https://v880-rehearsal3-l2api.mainnet.aws.zilliqa.com'
```

[master] Add replay transaction script

---

src/libServer/LookupServer.cpp

[release/v8.9] ZIL-5144: Don't send Scilla contract creation to ARCHIVAL_SEND_SHARD unless you are actually a lookup or archival node

---

src/libNode/DSBlockProcessing.cpp
src/libNode/Node.cpp
src/libNode/Node.h

If a node is not a part of the shard, we should allow it to sync after reading complete persistence. So at a point where the node determines that it is not part of the shard, we called the `StartSynchronization` function. The `StartSynchronization` function allows the node to perform normal sync with the network i.e fetch block one by one. I have to introduce `m_allowRecoveryAllSync` to make sure that the code does not change the node's state anytime. When the POW window is reached, the node attempts to perform POW and if it joins the network successfully then it gets ProcessVCDSBlocksMessage  where I reset the variable m_allowRecoveryAllSync

[release/v8.9] Zil 5176 : Allow node to sync if not in shard

---

src/libNetwork/SendJobs.cpp

Previously we treated it as a permanent error. This meant nodes could get strictly blacklisted during the startup of the network.

[master] ZIL-5145: Treat `TIMED_OUT` as a transient error

---

CMakeLists.txt
build.sh
src/libServer/IsolatedServer.cpp
src/libServer/LookupServer.cpp
src/libServer/Server.cpp
src/libServer/Server.h
src/libServer/StatusServer.cpp

This PR provides a simple `GetVersion` endpoint for all Zilliqa servers which tells you the version number specified in the code, and the commit id you were running. You may want to NAK the commit-id, since it does require additions to `build.sh` which may be annoying for some.
Please make sure it works (particularly on various flavours of OS X - I'm afraid my branches are in too hectic a state to really know), check that you are happy with the output format, and look over the source.

[master] ZIL-5126: A GetVersion endpoint.

---

tests/EvmAcceptanceTests/test/Transfer.ts

In this test, the value is too small when testing against a local network with realistic gas charges, to actually pay for the transaction. Also, it needs to block to wait for the funding transaction to clear.

[master] Fix gas consistency test against local network

---

src/libNetwork/P2PComm.cpp

This wasn't the cause of the bug, but it also didn't cause any problems so we think its safest to raise the value. The mainnet network is larger than the rehearsal, so the queue may need to be larger to handle the extra traffic.

[master] ZIL-5185: Increase libevent queue to 4096

---

docker/Dockerfile.lite

This means nodes can download and unzip persistence.

[master] MVP-5173: Install `pigz` in `Dockerfile.lite`

---

src/libDirectoryService/DSBlockPostProcessing.cpp
src/libDirectoryService/DSBlockPreProcessing.cpp
src/libDirectoryService/DirectoryService.cpp
src/libDirectoryService/FinalBlockPostProcessing.cpp
src/libDirectoryService/FinalBlockPreProcessing.cpp
src/libDirectoryService/PoWProcessing.cpp
src/libDirectoryService/ViewChangePreProcessing.cpp
src/libEth/filters/PendingTxnUpdater.cpp
src/libLookup/Lookup.cpp
src/libLookup/Lookup.h
src/libNode/FinalBlockProcessing.cpp
src/libNode/MicroBlockPostProcessing.cpp
src/libNode/MicroBlockPreProcessing.cpp
src/libNode/Node.cpp
src/libNode/PoWProcessing.cpp
src/libPersistence/Retriever.cpp

The goal is to fix the ubiquitious error in using condition variables, where the condition is not being checked before waiting itself, which results into the recepient never aware that the message has arrived, in case it had arrived quickly.
This will be a sequence of PRs, so that the blast radius of each is limited.

[master] Fixing condition variables - Lookup.cpp

---

README.md
src/libCps/Amount.h
src/libCps/CpsRunEvm.cpp

This checks that the refunded amount from contracts is EXACT. Before it was incorrectly understanding 'fund' to mean how much to transfer, when it was what the (non-contract) account value should become.
The logic should be the same.

[master] Rework zil mint check on selfdestruct

---

tests/EvmAcceptanceTests/test/ContractRevert.ts

I've tested on Sepolia and the behaviour is consistent there - the contract does not revert, it fails with an out of gas error.

[master] ZIL-5001: Enable and fix out of gas test

---

src/libServer/LookupServer.cpp

Previously, devex would hang when trying to load any screen which contained an EVM transaction, because the response contained an error. Now, devex copes slightly better (but still crashes and displays a blank screen if you click on the transaction).

[master] Encode EVM init data as hexadecimal

---

src/common/Constants.cpp
src/common/Constants.h
src/libServer/APIServer.h

We also adjust the defaults to 65536 and 64, which is closer to the values from v8.1.0.

[master] ZIL-5214: Make request queue size and threads configurable

---

scripts/localdev.py

Localdev: move isolated server block numbers on periodically so that block number sensitive tests will pass.
Review code and test.

[master] (feat) ZIL-5230: Move isolated server blocks on.

---

src/libServer/EthRpcMethods.cpp
src/libServer/EthRpcMethods.h

This is what the documentation tells us to do and some clients (notably Metamask as of the latest update) validate this format.

[master] ZIL-5249: Format response from `net_version` as a decimal

---

daemon/ZilliqaDaemon.cpp

The create new process method should also killl evm-ds as well as scilla-server
Make it possible to restart the zilliqa process from the zilliqa dameon.
- [X ] This is not a breaking change

Zil 5267 zilliiqad should terminate evm ds as well as scilla in its start new processes method

---

src/libServer/EthRpcMethods.cpp

The specification doesn't explicitly document this, but its implied by the fact that most implementations return all hex data in lowercase.
Without this, some contract verification tools break, because they detect a mismatch in the compiled and deployed bytecode.

[release/v9.1] Return response from `eth_getCode` in lowercase

---

docs/localdev.md
scripts/localdev.py

(fix) ZIL-5280 Localdev down should resume properly on interruption 
(fix) ZIL-5280 isolated-server-accounts=true should be the default.
(fix) ZIL-5280 Localdev reup should work without an explicit image
(fix) ZIL-5280 Add some FAQs to the docs.
Look at the code and try running it.
- [x ] **ready for review**
- [ x] local machine test

[master] ZIL-5280: Various localdev fixes

---

src/libScilla/ScillaClient.cpp
src/libScilla/ScillaClient.h

The JSON-RPC library has some parsing issues that led to the scilla server not restarting itself. The PR fixes the error condition for starting the scilla.
Note: In the `v8.1.2` release scilla restart used to work fine when the scilla server process crashes for some reason.

[release/v9.2] Fix scilla restart condition for v9.0.1 mainnet outage

---

src/cmd/isolated_server.cpp
src/libServer/EthRpcMethods.cpp
src/libServer/EthRpcMethods.h
src/libServer/IsolatedServer.cpp
tests/EvmAcceptanceTests/test/ChainedCalls.ts
tests/EvmAcceptanceTests/test/OtterTests.ts

In the tests, it is possible in a devnet it is testing the otter and trace tx tests against a network that doesn't have the trace flag on.
This adds an endpoint so that the flag can be externally set. This lets the test make sure it is set before it runs (it will still fail if you are not running against a seed node though, ie one with ARCHIVAL_LOOKUP set to true)

[master] API enable otterscan extended tracing

---

scripts/localdev.py

Make scilla-server run again on x64.
Check code. Run isolated on OS X and x64 (works on x86, OS X/x86 for me - can't test aarch64)
- [X ] **ready for review**

[master] Zil 5287 isolated server scilla fix

---

src/libData/AccountStore/AccountStore.cpp
src/libData/AccountStore/AccountStoreSCEvm.cpp

when estimating gas, you don't want to save the otter output. This made it print a warning but it was spurious.

[master] make spurious otter messages go away

---

src/common/Constants.cpp
src/common/Constants.h
src/libNetwork/SendJobs.cpp

Added the following (optional) constants:
* CONNECTION_TIMEOUT_IN_MS
* RECONNECT_INTERVAL_IN_MS
The reconnection timer is initially used to enforce a timeout before invoking async_connect.

[master] ZIL-5298: add connection timer and make reconnection time configurable

---

src/libServer/JSONConversion.cpp
tests/EvmAcceptanceTests/test/scilla/ContractDeployment.ts

We did not respect the version of the transaction, meaning all contract addresses were calculated using the Ethereum standard. This meant the contract address from `eth_` APIs was wrong for Scilla contract deployments.

[master] ZIL-5302: Fix `contractAddress` calculation for non-Eth transactions

---

src/libServer/JSONConversion.cpp
tests/EvmAcceptanceTests/test/scilla/ContractDeployment.ts

We did not respect the version of the transaction, meaning all contract addresses were calculated using the Ethereum standard. This meant the contract address from `eth_` APIs was wrong for Scilla contract deployments.

[release/v9.2] ZIL-5302: Fix `contractAddress` calculation for non-Eth transactions

---

src/libServer/EthRpcMethods.cpp

The first fix of ZIL-5305 did not take into account that the blockNumber is changed further up in the function if it is equal to 0 when passed in.
Change adds a boolean value which checks whether blockNumber is passed in as 0 and is then used instead
Fix for ZIL-5306 ensures that if there is no error, it returns the string "0x" to indicate there was no error instead of null
Fix for ZIL-5307 ensures that if there were no internal operations, it returns an empty array instead of null

[master] Fix issues ZIL-5305 to ZIL-5307

---

docs/setup/installme.sh

installme.sh requires that the contents of docs/setup/ are copied into the home directory before being executed.
This change adds a check for the files in the directory and will print a message if not and exit.
The first condition checks whether the executing script is located in the home directory. If the script can be executed elsewhere as long as the other files are in the home directory, then we can remove this check.
The second and third check for the presence of setenv.sh and runlocaldev.sh in the home directory.

[master] Added check for correct files in home directory

---

src/libServer/EthRpcMethods.cpp

Added a simple line that adds this new field.
Question: I see that in the above function `GetBlockDetails`, it gets the transaction count using `txBlock.GetHeader().GetNumTxs()`. Does this have any performance benefits over `transactions.size()`?

[master] Added transactionCount field to fullblock object

---

src/libServer/EthRpcMethods.cpp

I removed the line that caused this API call to constantly return "0x1" as the GasLimit of a block.

[master] Fixed function so correctly returns GasLimit

---

src/depends/jsonrpccpp/common/procedure.cpp
src/depends/jsonrpccpp/common/procedure.h
src/depends/jsonrpccpp/common/specification.h
src/libServer/EthRpcMethods.cpp
src/libServer/EthRpcMethods.h
src/libServer/IsolatedServer.cpp
tests/EvmAcceptanceTests/test/rpc/eth_estimateGas.ts

Cherry-pick #3728 
* (fix) ZIL-5313: Allow an optional block_or_tag argument in eth_estimateGas
* (fix) ZIL-5313: Write an apitest command to check that it worked.
* (fix) ZIL-5313: Remove rust API tests and roll into the EvmAcceptanceTests that were already there.

[release/v9.2] Cherry pick PR-3728(Fix Eth Gas Estimate) on release/v9.2 branch

---

src/libServer/JSONConversion.cpp

The spec says
> nonce: DATA, 8 Bytes - hash of the generated proof-of-work. null when its pending block.
> When encoding unformatted data (byte arrays, account addresses, hashes, bytecode arrays): encode as hex, prefix with "0x", two hex digits per byte.
Therefore, the nonce should always be 8 bytes long (e.g. `0x0000000000000000`). However, we respond with `0x0`. This causes problems for some particularly picky client (e.g. ethers.rs).

[master] Fix nonce from `eth_getBlockBy{Hash,Number}`

---

src/libServer/EthRpcMethods.cpp
src/libServer/EthRpcMethods.h
src/libServer/IsolatedServer.cpp
tests/EvmAcceptanceTests/helpers/parallel-tests/Display.ts
tests/EvmAcceptanceTests/helpers/parallel-tests/Scenario.ts
tests/EvmAcceptanceTests/helpers/parallel-tests/Worker.ts
tests/EvmAcceptanceTests/tasks/InitSigners.ts
tests/EvmAcceptanceTests/tasks/ParallelTest.ts
tests/EvmAcceptanceTests/test/ChainedCalls.ts
tests/EvmAcceptanceTests/test/ERC20isZRC2.ts
tests/EvmAcceptanceTests/test/Transfer.ts
tests/EvmAcceptanceTests/test/contract-deployment/ContractDeploymentEthers.ts
tests/EvmAcceptanceTests/test/openzeppelin/access-control/Ownable.ts
tests/EvmAcceptanceTests/test/otterscan/ots_getInternalOperations.ts
tests/EvmAcceptanceTests/test/otterscan/ots_getTransactionError.ts
tests/EvmAcceptanceTests/test/otterscan/ots_searchTransactions.ts
tests/EvmAcceptanceTests/test/otterscan/ots_traceTransaction.ts
tests/EvmAcceptanceTests/test/rpc/eth_getBalance.ts
tests/EvmAcceptanceTests/test/rpc/eth_getBlockByNumber.ts
tests/EvmAcceptanceTests/test/rpc/eth_getTransactionByHash.ts
tests/EvmAcceptanceTests/test/rpc/eth_getUncleByBlockHashAndIndex.ts
tests/EvmAcceptanceTests/test/rpc/eth_getUncleByBlockNumberAndIndex.ts
tests/EvmAcceptanceTests/test/rpc/eth_sendTransaction.ts
tests/EvmAcceptanceTests/test/rpc/eth_sign.ts
tests/EvmAcceptanceTests/test/subscriptions/OneIndexedParameters.ts

Many Ethereum tools send requests to (e.g.) `eth_getBlockByNumber` as an integer, rather than a string. Other Ethereum clients support this, so we should support this. The following list is the APIs I touched on in this PR:
- eth_getBalance
- eth_getStorageAt
- eth_getTransactionCount
- eth_getBlockTransactionCountByNumber
- eth_getUncleCountByBlockNumber
- eth_getCode
- eth_getBlockByNumber
- eth_getTransactionByBlockNumberAndIndex
- eth_getUncleByBlockNumberAndIndex

[master] Support integer block numbers in eth APIs.

---

src/libDirectoryService/FinalBlockPostProcessing.cpp
src/libScilla/ScillaClient.cpp
src/libScilla/ScillaClient.h

https://zilliqa-jira.atlassian.net/jira/software/c/projects/ZIL/issues/ZIL-5327
TODO: Remove debug logs before merge.

[release/v9.2] Restart the scilla process at every vacuous epoch

---

scripts/license_checker.sh
src/libServer/JSONConversion.cpp

ZIL-5354 blank response in data not handled by ethers 6, switched to 0x0
Fix bug outlined in ZIL-5354 
- [X ] This is not a breaking change
In testing, tests passed locally

[master] ZIL-5354 sendTransaction doesn't work - response handled differently in ethers 6, looking for 0x0 in data not empty string.

---

src/common/BaseType.h
src/common/Constants.cpp
src/common/Constants.h
src/libCps/CpsRunEvm.cpp
src/libCrypto/CMakeLists.txt
src/libCrypto/EthCrypto.cpp
src/libCrypto/EthCrypto.h
src/libData/AccountData/Account.cpp
src/libData/AccountData/Transaction.cpp
src/libData/AccountData/Transaction.h
src/libEth/Eth.cpp
src/libEth/Eth.h
src/libMessage/Messenger.cpp
src/libMessage/ZilliqaMessage.proto
src/libServer/EthRpcMethods.cpp
src/libServer/JSONConversion.cpp
src/libServer/JSONConversion.h
tests/EvmAcceptanceTests/test/Transfer.ts

A brief description of how these transaction types differ and the potentially controversial choices I made while supporting them...
Type 1 transactions are defined in EIP-2930 and allow access lists to be provided with transactions. In Zilliqa, access lists are completely ignored and do not have any affect on gas accounting, but we do keep track of them so the transaction can be reconstructed later.
Type 2 transactions are defined in EIP-1559 and accept access lists, plus they allow for a different model for gas accounting. Instead of setting a single `gasPrice` for a transaction, you set a 'priority fee' which is paid in addition to the block's base fee. A maximum fee is also sent in transactions which limits the total fee the user is willing to pay (base fee + priority fee). In Zilliqa, …

[master] ZIL-5376: Support type 1 and type 2 Ethereum transactions

---

src/common/Constants.cpp
src/common/Constants.h
src/libData/MiningData/DSPowSolution.cpp
src/libData/MiningData/DSPowSolution.h
src/libDirectoryService/DSBlockPreProcessing.cpp
src/libDirectoryService/DirectoryService.h
src/libDirectoryService/PoWProcessing.cpp
src/libMessage/Messenger.cpp
src/libMessage/Messenger.h
src/libMessage/ZilliqaMessage.proto
src/libNode/Node.h
src/libNode/PoWProcessing.cpp
src/libPOW/pow.cpp
src/libPOW/pow.h
src/libServer/GetWorkServer.cpp
src/libServer/GetWorkServer.h
src/libUtils/DataConversion.h
tests/Data/Test_DSPowSolution.cpp
tests/POW/test_POW.cpp
tests/POW/test_RemoteMine.cpp

See https://github.com/Zilliqa/zilliqa-developer/pull/262 for documentation of the interface.

[master] ZIL-5447: Implement header hash customisation for remote miners

---

src/libServer/EthRpcMethods.cpp
src/libServer/EthRpcMethods.h

Fix ots_hasCode so that otterscan doesn't choke when calling it.
- [] This is not a breaking change
Check that otterscan now works with ZQ1 (in particular, txn details and logs)

[master] US-322: ots_hasCode() should take an integer as its second argument.

---

scripts/download_incr_DB.py
scripts/upload_incr_DB.py

This PR add the capability to bypass the CDN while downloading the levelDB files which contains the updated structure of the persistence content. As the default configuration for the CDN cache is 1d, while downloading files such us CURRENT which keeps the id of the current leveldb MANIFEST, the id was pointing to the old instead of the current manifest file leaving the downloaded persistence inconsistent/corrupted.

[master] fix(ZIL-5493): add CDN bypass header MANIFEST, CURRENT, LOG and lock files

---

src/libDirectoryService/DSBlockPostProcessing.cpp
src/libNode/DSBlockProcessing.cpp

A newly joined node receives an invalid gossip message for DS_FINALBLOCKCONSENSUS. As the newly joined node wasn't part of the ds block consensus, it has no consensus object created. But because of timing issues, it receives late gossip messages for DS block consensus which we should ignore as the consensus object is not initialized.
If the consensus object is created by other message, the state check would automatically handle the message or reject it.

[master] Check null condition before accessing dsblock consensus object

---

src/libServer/GetWorkServer.cpp

There are two code paths into `VerifySubmit`. One comes from the `eth_submitWork` API and does not pass any `extraData`. In this case we retain the old behaviour and still validate the submitted header is the same as the header we expect for this bit of work. The other case comes from the `zil_submitWorkWithExtraData` API. This takes `extraData` instead of a `header` and computes a new header based on the data. In this case, we skip the check which validates the calculated header is the same as the original work header, because it will always fail.

[master] ZIL-5496: Don't validate work header if extra data was submitted

---

src/libServer/EthRpcMethods.h
tests/EvmAcceptanceTests/test/ChainedCalls.ts
tests/EvmAcceptanceTests/test/otterscan/ots_getInternalOperations.ts
tests/EvmAcceptanceTests/test/otterscan/ots_getTransactionBySenderAndNonce.ts
tests/EvmAcceptanceTests/test/otterscan/ots_getTransactionError.ts
tests/EvmAcceptanceTests/test/otterscan/ots_searchTransactions.ts
tests/EvmAcceptanceTests/test/otterscan/ots_traceTransaction.ts

Disable ots_enable; ots_enable allows you to enable tracing on seedpubs, which would be dangerous even if seedpub tracing did work. It doesn't (for various reasons), and the time taken to fail tends to break the seedpub. 
Build and test.

[master] (fix) ZIL-5492: Disable ots_enable

---

src/libDirectoryService/DSBlockPostProcessing.cpp

A DS node is removed from the consensus because of not signing enough blocks or competition performs rejoins. This means it downloads complete persistence and syncs again which is a very time-consuming process. The fix is to allow the node to start syncing to join in the next epoch.

[master] Allow syncing of ds nodes if they kicked out of ds comm instead of rejoin from scrach
