- CMakeLists.txt
- src/depends/NAT/nat.cpp
- src/depends/common/FixedHash.h
- src/depends/common/Miner.h
- src/libUtils/SWInfo.cpp
- src/libUtils/SWInfo.h
Fix build for 20.04 Ubuntu.
* Check for all possible suffixes for boost python
* Change g3log to fix errors with gcc9
* Fix errors in the core repo to be compatible with gcc9
> Fix Build for gcc9 (Including fixes for 20.04)

- scripts/scan_consolidate.py
1. Support any number of shards
2. Add log folder to input args
3. Add instructions to start of script
4. Sort shard stats by shard ID
5. Sort block stats by block number
Sample results.csv
```
Block Number,Shard id,Consensus Time (ms),Num Txs,FB Consensus time (ms),DS MBLK Wait time (ms),FB block time,Total Txns
1,0,56,1000.0,46,18250,21416.5,1100
2,0,54,1000.0,46,18178,21334.7,0
3,0,43,0.0,45,18336,21520.1,1100
4,0,53,1000.0,53,18167,21330.9,0
5,0,51,1000.0,45,18290,21459.5,1100
6,0,44,0.0,46,18179,21357.399999999998,0
7,0,45,0.0,45,18256,21410.3,1100
8,0,44,0.0,46,78,3142.58,0
10,0,54,1000.0,44,18257,113461.0,0
```
> Improve benchmarking script

- scripts/scan_consolidate.py
- src/libNode/FinalBlockProcessing.cpp
`scan_consolidate.py` creates 2 reports: `results.csv` and `extra_results.csv`. This makes it hard to digest the report.
Also, the results in `extra_results.csv` include shard-level information which can be placed into `results.csv`.
This PR merges the reports and also makes the final report much more readable.
Sample output (1 shard):
```
Epoch #,Shard Details,,,,DS Wait (MBs) (ms),Block Time (ms),Gas Used,TPS
,ID,Cons (ms),# Txns,MB Size (bytes),,,,
1,0,48,0,452,18187,113452,0,0
,1,44,0,0,,,,
2,0,56,1000,326455,18256,21410,1100,51.3778
,1,44,100,33052,,,,
3,0,44,0,452,18192,21345.8,0,0
,1,46,0,0,,,,
4,0,53,1000,327285,18312,21474,1100,51.2247
,1,46,100,33152,,,,
5,0,48,0,452,18195,21350.7,0,0
,1,47,0,0,,,,
6,0,58,1000,327455,18269,21437.4,1100,51.3122
,1,44,100,33152,,,, …
```
> Merge CSVs in scan_consolidate.py

- scripts/scan_consolidate.py
- src/libLookup/Lookup.cpp
- src/libNode/FinalBlockProcessing.cpp
- src/libNode/Node.cpp
- src/libZilliqa/Zilliqa.cpp
Sample result (2 shards, 2 lookups):
```
Epoch #,Shard Details,,,,,,,DS Details,,,,,,Epoch Details,,
,ID,Lookup,Pkt #Txs,Prev FB receipt->Pkt proc (ms),Cons (ms),# Txns,MB Size (bytes),Lookup,Pkt #Txns,DS Wait (MBs) (ms),Cons (ms),# Txns,MB Size (bytes),Block Time (ms),Gas Used,TPS
1,0,0,600,NA,43,0,452,0,400,18189,46,0,0,114843,0,0
,,1,0,NA,,,,1,0,,,,,,,
,1,0,400,NA,43,0,452,,,,,,,,,
,,1,0,NA,,,,,,,,,,,,
2,0,0,600,22071,59,600,196055,0,400,18236,47,100,33052,21396.9,1100,51.4092
,,1,0,0,,,,1,0,,,,,,,
,1,0,400,21845,49,400,130854,,,,,,,,,
,,1,0,0,,,,,,,,,,,,
3,0,0,600,22024,44,0,452,0,400,18178,48,0,0,21333.5,0,0
,,1,0,0,,,,1,0,,,,,,,
,1,0,400,21795,43,0,452,,,,,,,,,
,,1,0,0,,,,,,,,,,,,
4,0,0,600,22121,49,600,196553,0,400,18293,43,100,33152,21458.2,1100,51.2624
,,1,0,0,,,,1,0,,,,,,, …
```
> Add lookup txn packet info into benchmarking report

- src/libNode/FinalBlockProcessing.cpp
- src/libServer/JSONConversion.cpp
- src/libServer/JSONConversion.h
- src/libServer/WebsocketServer.cpp
- src/libServer/WebsocketServer.h
Add TXN LOG to websocket query
The query takes input an address and if a txn is sent from or to that account, displays the following
ID,amount,success,fromAddr,toAddr
```json
{"query" : "TxnLog" , "addresses" : ["0xb50c2404e699fd985f71b2c3f032059f13d6543b"]}
< {"query" : "TxnLog" , "addresses" : ["0xb50c2404e699fd985f71b2c3f032059f13d6543b"]}
< {
"type" : "Notification",
"values" : 
[
{
"query" : "TxnLog",
"value" : 
[
{
"address" : "b50c2404e699fd985f71b2c3f032059f13d6543b",
"log" : 
[
{
"ID" : "cb773dbd95d2ec7a4ec9539f92dc92c7f62d515fcc9b052e0b64bc06dde50e7b",
"amount" : "2718000000000",
"fromAddr" : "42fb82623b9ea0b9dbf41e74304a39908a378cfd",
"success" : true,
"toAddr" : "b50c2404e699fd985f71b2c3f032059f13d6543b"
}
]
}
]
}
]
}
```
> Add txn log to ws

- CMakeLists.txt
- constants.xml
- constants_local.xml
- scripts/scan_consolidate.py
- src/cmd/CMakeLists.txt
- src/cmd/genaccounts.cpp
- src/common/Constants.cpp
- src/common/Constants.h
- src/libLookup/Lookup.cpp
- src/libLookup/Lookup.h
- src/libNode/MicroBlockPreProcessing.cpp
- src/libNode/Node.cpp
Multiple changes to existing `scan_consolidate.py` script and addition of new tool `genaccounts`.
All core changes are only activated by `USE_REMOTE_TXN_CREATOR` and `LOG_PARAMETERS` and should not affect mainnet operation.
> Support multiple txn dispatchers for benchmarking tests

- docker/Dockerfile
- docker/Dockerfile.cuda
- docker/dev/Dockerfile.k8s
> fix setuptools ends python2 support

- scripts/ci_report_coverage.sh
> suppress gcov output

- scripts/scan_consolidate.py
- src/libNode/Node.cpp
> Record txn packet size for benchmarking

- src/libServer/LookupServer.cpp
> Fix nonce origin when calculating contract address

- src/libMessage/Messenger.cpp
Use smart pointer instead of raw pointer, don't repeat allocate same object inside a loop
Optimization
> Use smart pointer instead of raw pointer

- scripts/miner_info.py
- src/libServer/StatusServer.cpp
- src/libServer/StatusServer.h
Add reglist_extseed to miner_info
> Add reglist_extseed to miner_info

- src/libServer/LookupServer.cpp
This PR is to make LookupServer::ValidateTxn more clever by checking both gas fee and amount.
> fix: consider gas fee while doing transaction validation

- src/libServer/IsolatedServer.cpp
- src/libServer/IsolatedServer.h
PR adds two APIs
1. GetTransactionForTxBlock
2. GetRecentTransactions
> Isolated Server : Add APIs for explorer

- src/libData/AccountData/AccountStore.h
- src/libLookup/Lookup.cpp
- src/libProtoServer/Server.cpp
- src/libServer/IsolatedServer.cpp
- src/libServer/LookupServer.cpp
- src/libServer/WebsocketServer.cpp
> Apply primary mutex for external call of AccountStore::GetAccount

- src/libNode/Node.cpp
This PR fix issue where in when testnet is bootsrapped from existing previous testnet and when zilliqa node is not sharded it triggers rejoin. However, the incremental db is not yet uploaded by lookup to S3.
lookup starts uploading incr data to S3 once new txblock is mined.
So fix is to wait for next another txblock so that lookup can perform upload. After which `RejoinAsNormal` will proceed as usual.
> Fix issue with  bootstrap joining of non-sharded node

- VERSION
- docker/Dockerfile
- docker/Dockerfile.cuda
- src/libUtils/SWInfo.h
> To v6.3.0-alpha.0

- src/libNode/MicroBlockPostProcessing.cpp
- src/libNode/Node.cpp
https://github.com/Zilliqa/Issues/issues/641
>  [release-6.3] Fix crash when receving mb consensus message and accepting from nonshard peer

- src/libData/AccountData/AccountStoreSC.tpp
- src/libData/AccountData/ScillaClient.cpp
> Log exception in receipt from Scilla Server

- src/libNode/MicroBlockPostProcessing.cpp
- src/libNode/Node.cpp
- src/libNode/Node.h
> [release-6.3] Avoid duplicate txnpkt bufferring and processing

- src/libData/AccountData/AccountStoreSC.tpp
- src/libData/AccountData/ScillaClient.cpp
> [release-6.3] Log exception in receipt from Scilla Server

- docker/Dockerfile
- docker/Dockerfile.cuda
- src/libUtils/SWInfo.h
> To Zilliqa v6.3.0-alpha.1 and Scilla 0.7.1-alpha.0

- src/libNode/Node.cpp
The corresponding error can potentially suppress any other primary error related to the same txnhash
> Suppress Mempool_already_present (Error 23)

- src/libDirectoryService/DirectoryService.cpp
- src/libDirectoryService/DirectoryService.h
- src/libDirectoryService/ViewChangePreProcessing.cpp
(cherry picked from commit b59e2a1bd3a7ccae052e1b8e26c54ddd26e1cb92)
> [release-6.3] Abort RunConsensusOnViewChange on DS_SYNC

- docker/Dockerfile
- docker/Dockerfile.cuda
- src/libUtils/SWInfo.h
> To Zilliqa v6.3.0-alpha.2 and Scilla v0.7.1

- src/libNode/Node.cpp
- src/libNode/Node.h
> Avoid duplicate txnpkt bufferring and processing

- src/libDirectoryService/FinalBlockPreProcessing.cpp
- src/libDirectoryService/ViewChangePostProcessing.cpp
Fix accessing microblocks without lock
> Fix accessing microblocks without lock

- src/libNode/MicroBlockPreProcessing.cpp
- src/libServer/LookupServer.cpp
#2139 for release 6.3
#2142 for release 6.3
> [Release-6.3]Fix  GetPendingTxn

- src/libServer/LookupServer.cpp
Change `Status` to `code` for consistency
> Change Status to code

- docker/Dockerfile
- docker/Dockerfile.cuda
- src/libUtils/SWInfo.h
Also, Schnorr submodule commit updated
> To v6.3.0-alpha.3

- README.md
> Update README to v6.3.0

- src/libNode/DSBlockProcessing.cpp
This PR fix the possible race condition on `m_ds->m_shards`.
> Fix for possible possible race condition on m_shards

- docker/Dockerfile
- docker/Dockerfile.k8s
- docker/requirements2.k8s.txt
- docker/requirements2.preq.txt
- docker/requirements2.txt
- docker/requirements3.txt
- scripts/list_shards.py
- scripts/profile_time.py
- scripts/replace_header_guard.py
- scripts/report_bastion.py
- scripts/scan_consolidate.py
- scripts/stall_checker.py
- tests/Zilliqa/daemon_restart_local.py
Change Python from python 2.7 to python 3.5 inside ubuntu16 docker image and convert zilliqa scripts to python3 format.
> Change python environment and code to python3 for zilliqa repo

- src/libData/AccountData/AccountStoreSC.tpp
Fix issue: https://github.com/Zilliqa/Issues/issues/646
> Add missing RemoveAccount if deployment failed

- src/libData/AccountData/TxnPool.h
- src/libNode/MicroBlockPreProcessing.cpp
- src/libNode/Node.cpp
- tests/Data/AccountData/Test_TxnPool.cpp
* Transaction A comes with  gas price, nonce  = x
* `m_createdTxns` successfully add txn to pool and return true
* Transaction B comes with a higher gas price, nonce = x
* `m_createdTxns` successfully add txn to pool, return true but delete A (silently)
> Add txns dropped due to higher gas txn in the log and dropped txns

- docker/Dockerfile
- docker/Dockerfile.cuda
- docker/requirements3.cuda.txt
- tests/cmd/verifyMultiSignature.cpp
The goal of the PR is to upgrade OS running inside docker to `Ubuntu 18.04`.
> Modify docker file to upgrade Ubuntu os running inside docker to 18.04

- docker/Dockerfile
- docker/Dockerfile.cuda
Updated the scilla version from `scilla:v0.8.0-alpha.0` to `scilla:v0.8.0` in dockerfiles.
> Update scilla tag to v0.8.0 in dockerfiles

- src/libNode/FinalBlockProcessing.cpp
> Skip cosig check for DSMB

- README.md
1. Use the new dev portal mining link, deprecate this [wiki page](https://github.com/Zilliqa/Zilliqa/wiki/Mining)
2. Add `./build.sh style` instructions directly in README, to deprecate this [wiki section](https://github.com/Zilliqa/Zilliqa/wiki/Developer-Tools#clang-format-and-clang-tidy)
> Update README mining link and build instructions

- constants_local.xml
- tests/Node/pre_run.sh
- tests/Node/test_node_simple.sh
- tests/Zilliqa/test_zilliqa_local.py
The PR does below:
1. Run status server on individual ports in `local testnet`
Output from the run : 
[Node 1  ] [Port 5001]  [Status Server Port 4301] ./local_run/node_0001
[Node 2  ] [Port 5002]  [Status Server Port 4302] ./local_run/node_0002
[Node 3  ] [Port 5003]  [Status Server Port 4303] ./local_run/node_0003
[Node 4  ] [Port 5004]  [Status Server Port 4304] ./local_run/node_0004
[Node 5  ] [Port 5005]  [Status Server Port 4305] ./local_run/node_0005
[Node 6  ] [Port 5006]  [Status Server Port 4306] ./local_run/node_0006
[Node 7  ] [Port 5007]  [Status Server Port 4307] ./local_run/node_0007
[Node 8  ] [Port 5008]  [Status Server Port 4308] ./local_run/node_0008
[Node 9  ] [Port 5009]  [Status Server Port 4309] ./local_run/node_0009
[Node 10 ] [Port 5010]  [Status Server Port 4310] …
> Local testnet code optimization

- src/libNode/Node.cpp
> Avoid using GetLatestTxBlock for in-node persistence validation

- src/cmd/isolated_server.cpp
- src/libPersistence/BlockStorage.cpp
- src/libServer/IsolatedServer.cpp
- src/libServer/IsolatedServer.h
> Isolated Server Persistence

- src/libDirectoryService/Coinbase.cpp
- src/libNode/MicroBlockPreProcessing.cpp
> Make TxnFees back to void Coinbase address

- docker/Dockerfile
- docker/Dockerfile.cuda
> To Scilla 0.9.0-alpha.0

- VERSION
- docker/Dockerfile
- docker/Dockerfile.cuda
- src/libUtils/SWInfo.h
> To v7.0.0-alpha.0

- tests/Data/Test_Contract.cpp
> Fixed ErrTxnStatus compile error

- tests/Data/Test_Contract.cpp
> [release-7.0] Fixed ErrTxnStatus compile error

- docker/Dockerfile
- docker/Dockerfile.cuda
- src/libUtils/SWInfo.h
> To v7.0.0-alpha.1

- src/libServer/IsolatedServer.cpp
- src/libServer/JSONConversion.cpp
- src/libServer/LookupServer.cpp
> [release-7.0] API fixes for release 7.0.0

- docker/Dockerfile
- docker/Dockerfile.cuda
- src/libUtils/SWInfo.h
> To v7.0.0-alpha.2

- src/libServer/IsolatedServer.cpp
- src/libServer/JSONConversion.cpp
- src/libServer/LookupServer.cpp
> API fixes for release 7.0.0

- src/libData/AccountData/AccountStore.cpp
- src/libData/AccountData/AccountStoreSC.tpp
- src/libData/AccountData/ScillaClient.cpp
- src/libData/AccountData/ScillaClient.h
- src/libPersistence/ContractStorage2.cpp
- src/libPersistence/ContractStorage2.h
> [release-7.0] Fix MPT for non-map and migrating corruption

- docker/Dockerfile
- docker/Dockerfile.cuda
- src/libUtils/SWInfo.h
> To v7.0.0-alpha.3

- src/libData/AccountData/AccountStore.cpp
- src/libData/AccountData/ScillaClient.cpp
- src/libData/AccountData/ScillaClient.h
> [release-7.0] Fix possible node crash due to scilla-server slow responding

- docker/Dockerfile
- docker/Dockerfile.cuda
- src/libUtils/SWInfo.h
> To v7.0.0-alpha.4

- src/libData/AccountData/AccountStore.cpp
- src/libData/AccountData/AccountStoreSC.tpp
- src/libData/AccountData/ScillaClient.cpp
- src/libData/AccountData/ScillaClient.h
- src/libPersistence/ContractStorage2.cpp
- src/libPersistence/ContractStorage2.h
Master is missing equivalent PRs for #2206 and #2208
> Merge PR 2206 and 2208 to master

- src/libServer/LookupServer.cpp
Make the error consistent with `GetTransaction`
> Fix GetTransactionStatus API error

- src/libServer/LookupServer.cpp
> [release-7.0] Fix GetTransactionStatus API error

- docker/Dockerfile
- docker/Dockerfile.cuda
- src/libUtils/SWInfo.h
> To Zilliqa v7.0.0-alpha.5 and Scilla v0.9.0

- src/libData/AccountData/AccountStore.cpp
> [release-7.0] fix ignored is_library

- src/libPersistence/BlockStorage.cpp
> [release-7.0] Reduce logs in BlockStorage::GetLatestTxBlock

- docker/Dockerfile
- docker/Dockerfile.cuda
- src/libUtils/SWInfo.h
> To v7.0.0-alpha.6

- src/libData/AccountData/AccountStore.cpp
> fix ignored is_library

- src/libData/AccountData/Account.cpp
- src/libData/AccountData/Account.h
- src/libData/AccountData/AccountStore.cpp
- src/libPersistence/ContractStorage2.cpp
- src/libPersistence/ContractStorage2.h
> [release-7.0] Fix state fetching for toDeleteIndices during migration & Fix state feeding for DeserializingDelta when temp is false

- docker/Dockerfile
- docker/Dockerfile.cuda
- src/libUtils/SWInfo.h
> To v7.0.0-alpha.7

- scripts/auto_backup.py
Change introduced in #2179 seems to not work, so executing rsync twice instead as separate bash commands
> [release-7.0] Fix rsync call inside auto_backup.py

- src/libData/AccountData/Account.cpp
- src/libData/AccountData/Account.h
- src/libData/AccountData/AccountStore.cpp
- src/libPersistence/ContractStorage2.cpp
- src/libPersistence/ContractStorage2.h
> Fix state fetching during migration & Fix state hashing for merging Delta to permanent

- scripts/auto_backup.py
> Fix rsync call inside auto_backup.py

- docker/Dockerfile
- docker/Dockerfile.cuda
- src/libUtils/SWInfo.h
> To v7.0.0-beta.0

- src/common/TxnStatus.h
- src/libNode/MicroBlockPreProcessing.cpp
> [release-7.0] Add NONCE_TOO_LOW error to dropped txns

- docker/Dockerfile
- docker/Dockerfile.cuda
- src/libUtils/SWInfo.h
> To v7.0.0-beta.1

- src/libData/AccountData/AccountStore.cpp
> [release-7.0] Init ScillaClient when launching

- docker/Dockerfile
- docker/Dockerfile.cuda
- docker/Dockerfile.k8s
- docker/Makefile
- docker/requirements2.k8s.txt
- docker/requirements2.preq.txt
- docker/requirements2.txt
- docker/requirements3.txt
- src/libData/AccountData/AccountStoreSC.tpp
- src/libData/AccountData/ScillaClient.cpp
- src/libDirectoryService/DirectoryService.cpp
- src/libDirectoryService/DirectoryService.h
- src/libDirectoryService/ViewChangePreProcessing.cpp
- src/libNode/MicroBlockPostProcessing.cpp
- src/libNode/MicroBlockPreProcessing.cpp
- src/libNode/Node.cpp
- src/libNode/Node.h
- src/libServer/LookupServer.cpp
- src/libUtils/SWInfo.h
Branch creation:
```
git clone git@github.com:Zilliqa/Zilliqa.git
cd Zilliqa
git branch release-6.4 295c1e1000fd81111ce685e09d42822a47c2590c
git push origin release-6.4
```
Merging:
```
git clone git@github.com:Zilliqa/Zilliqa.git
cd Zilliqa
git checkout release-6.3
git fetch
git checkout release-6.4
git fetch
git merge release-6.3 --squash
git commit -a
git checkout -b merge-v630-into-v640
git push origin merge-v630-into-v640
```
> [release-6.4] Merge all release-6.3 commits into release-6.4

- scripts/auto_backup.py
This is a combination of the script changes in #2179 and #2231 along release-7.0
Good to have inside release-6.4 also for lookup-1 backup uploading operation
> [release-6.4] Repeat rsync during persistence backup

- src/libData/AccountData/AccountStoreSC.tpp
> [Release-6.4] Use atomic balance as sender balance

- VERSION
- docker/Dockerfile
- docker/Dockerfile.cuda
- src/libUtils/SWInfo.h
> To v6.4.0-alpha.0

- docker/requirements2.txt
> [release-6.4] Remove request module

- docker/requirements2.txt
> Merging 6.4 python removal into 6.4/isolated

- docker/Dockerfile.cuda
> [release-6.4] Remove request module from CUDA docker image

- src/libDirectoryService/DSComposition.cpp
> [release-6.4] Reduce INFO logs for UpdateDSCommitteeCompositionCore

- docker/Dockerfile
- docker/Dockerfile.cuda
- src/libUtils/SWInfo.h
> To v6.4.0-alpha.1

- scripts/download_incr_DB.py
Check before refetching for selective txblks in download incrdb script
> [release-6.4] Check before refetching for selective txblks in download incrdb script

- docker/Dockerfile
- docker/Dockerfile.cuda
- src/libUtils/SWInfo.h
> To v6.4.0-alpha.2

- docker/Dockerfile
- docker/Dockerfile.cuda
- src/libUtils/SWInfo.h
> To Zilliqa v6.4.0-alpha.3 and Scilla v0.9.0-backport.16.04

- .github/workflows/autoassign.yaml
Add auto assign to assign prs to core PRs in development column when a new pr is created.
> Added github actions.

- src/libData/AccountData/AccountStoreSC.tpp
> Use atomic balance as sender balance

- scripts/download_incr_DB.py
> Check before refetching for selective txblks in download incrdb script

- CMakeLists.txt
- docker/Dockerfile
> Add data_migrate to Docker image

- src/libServer/LookupServer.cpp
> [release-6.4] API gas error message fix for lookup server on contract creation

- .github/workflows/autoassign.yaml
> [release-7.0] Added github actions

- src/libZilliqa/Zilliqa.cpp
same as https://github.com/Zilliqa/Zilliqa/pull/2271
> [release-7.0] Redefine recovery process of normal and dsguard nodes

- src/libZilliqa/Zilliqa.cpp
same as https://github.com/Zilliqa/Zilliqa/pull/2271
> [master] Redefine recovery process of normal and dsguard nodes

- scripts/download_incr_DB.py
Sometimes it's observed that if there are simultaneous downloads from many nodes, some files are getting skipped in downloading even tough valid 200 OK response is returned from S3 with content-length.
It's observed in one of the run that download api response is 200 OK with valid content-length, but somehow the file is actually not downloaded .`connection reset by peer` message is seen if we put exception handling code in `request` api call.
Fix : Catch the exception in downloading and retry again until `retry_counter` limit is reached.
**Test Results:**
Exception occured:http://c5b68604-8540-4887-ad29-2ab9e680f997.s3.amazonaws.com/incremental/try640withubuntu18/persistence/contractCode/002038.ldb
[Retry: 1] Downloading again http://c5b68604-8540-4887-ad29-2ab9e680f997.s3.amazonaws.com/in …
> [release-6.4] Fix missing download file in case of connection reset by peer

- scripts/download_incr_DB.py
> [release-7.0] Check before refetching for selective txblks in download incrdb script

- src/libDirectoryService/DSComposition.cpp
> Reduce INFO logs for UpdateDSCommitteeCompositionCore

- src/libDirectoryService/DSComposition.cpp
> [release-7.0] Reduce INFO logs for UpdateDSCommitteeCompositionCore

- scripts/upload_incr_DB.py
- src/libLookup/Lookup.cpp
- src/libLookup/Lookup.h
- src/libMessage/ZilliqaMessage.proto
- src/libNode/DSBlockProcessing.cpp
- src/libNode/FinalBlockProcessing.cpp
- src/libNode/Node.cpp
- src/libNode/PoWProcessing.cpp
same as https://github.com/Zilliqa/Zilliqa/pull/2185
> [release-7.0] NewLookup/Level2lookup/Lookup fails to resync if lagging by ds epochs

- scripts/download_incr_DB.py
> [master] Fix missing download file in case of connection reset by peer

- scripts/download_incr_DB.py
> [release-7.0] Fix missing download file in case of connection reset by peer

- src/libServer/LookupServer.cpp
> API gas error message fix for lookup server on contract creation

- src/libPersistence/BlockStorage.cpp
> Reduce logs in BlockStorage::GetLatestTxBlock

- src/libServer/LookupServer.cpp
> [release-7.0] API gas error message fix for lookup server on contract creation

- README.md
Update latest release version from `v6.3.0` to `v6.4.0` in zilliqa repo readme file
> Update release version from 6.3.0 to 6.4.0 in Readme.md file

- VERSION
- docker/Dockerfile
- docker/Dockerfile.cuda
- src/libUtils/SWInfo.h
> To Zilliqa v6.4.1

- README.md
Zilliqa release tag is updated from `6.4.0` to `6.4.1` in README.md file.
> Update release version from 6.4.0 to 6.4.1 in Readme.md file

- src/libData/AccountData/AccountStoreSC.h
- src/libData/AccountData/AccountStoreSC.tpp
- src/libPersistence/ContractStorage2.cpp
> [release-6.4] Fix delete reverting

- src/libUtils/ScillaUtils.cpp
> [release-7.0] remove -disable-validate-json

- src/libData/AccountData/AccountStoreSC.h
- src/libData/AccountData/AccountStoreSC.tpp
- src/libPersistence/ContractStorage2.cpp
> [release-7.0] Fix deleted key reverting

- src/libUtils/ScillaUtils.cpp
> remove -disable-validate-json

- scripts/miner_info.py
- src/libLookup/Lookup.cpp
- src/libMediator/Mediator.cpp
- src/libMediator/Mediator.h
- src/libNode/FinalBlockProcessing.cpp
- src/libServer/StatusServer.cpp
- src/libServer/StatusServer.h
> [release-7.0] Improve accuracy of GetWorkServer::GetSecondsToNextPoW

- README.md
Update zilliqa release version from 6.4.1 to 6.4.2 in readme file.
> Update zilliqa release version to 6.4.2

- docker/Dockerfile
- docker/Dockerfile.cuda
> Removed backport ppa

- .github/workflows/autoprtitleupdate.yaml
[FEATURE/AUTOPRTITLEUPDATE](https://url/to/browse/ticket/FEATURE/AUTOPRTITLEUPDATE)
> Added github action to prepend branch name to PR title

- .github/workflows/autoprtitleupdate.yaml
> [release-7.0] Added github action to prepend branch name to PR title

- scripts/download_incr_DB.py
In the recent mainnet deployment, we have faced issue of missing persistence file in incremental db download.Some files are missing when  data is downloaded. This results into application issues while loading the data in app.
Below are the implementation details:
1) Download script first fetches the list of files.It is stored in python list as `list_of_keyurls`
2) when the call for each url happens for download , script maintains a lists - `DOWNLOAD_STARTED_LIST`
2) As the file gets downloaded successfully, it is pushed to another list - `DOWNLOADED_LIST`
4) We compare the diff of both `DOWNLOAD_STARTED_LIST` and `DOWNLOADED_LIST` against `list_of_keyurls`
5) If there's missing data, we retry to download missing files until `MAX_FAILED_DOWNLOAD_RETRY = 2` attempt.
6) If the file still not …
> Optimize download incremental db script -Implement file diff check

- src/libLookup/Lookup.cpp
> [release-7.0] Miner node is not able to do pow submission

- scripts/download_incr_DB.py
> [release-7.0] Optimize download incremental db script -Implement file diff check

- src/cmd/isolated_server.cpp
- src/libPersistence/Retriever.cpp
- src/libPersistence/Retriever.h
- src/libServer/IsolatedServer.cpp
- src/libServer/IsolatedServer.h
Enable processing of state deltas in case of mainnet persistence
> fix loading of mainnet persistence into iso-server

- CMakeLists.txt
- build.sh
- src/cmd/CMakeLists.txt
- src/cmd/genTxnBodiesFromS3.cpp
- src/cmd/migrate_mbs_txns.cpp
- src/depends/libDatabase/LevelDB.cpp
- src/depends/libDatabase/LevelDB.h
- src/libLookup/Lookup.cpp
- src/libMessage/Messenger.cpp
- src/libMessage/Messenger.h
- src/libMessage/ZilliqaMessage.proto
- src/libNode/FinalBlockProcessing.cpp
- src/libPersistence/BlockStorage.cpp
- src/libPersistence/BlockStorage.h
- src/libServer/IsolatedServer.cpp
- tests/Persistence/CMakeLists.txt
- tests/Persistence/Test_TxBody.cpp
This builds on top of #2311.
**Txn storage before:**
[txBodies] hash -> body
**Txn storage now:**
[txEpochs] hash -> epoch
[txBodies] hash -> body
Migration to new storage:
1. Validate existing persistence using the `validateDB` from before this PR
1. `./build.sh migrate_mbs_txns` (to enable MIGRATE_MBS_TXNS flag) on this PR
1. Run `migrate_mbs_txns` on the persistence
1. Replace `microBlocks` levelDB with the newly created `microBlocksNew` levelDB
1. Replace `txBodies` levelDB with the newly created `txBodiesNew` levelDB
1. `./build.sh` (to disable MIGRATE_MBS_TXNS flag) on this PR
1. Run `validateDB` on the migrated persistence
> [release-7.0] Index txns by epoch number

- docker/Dockerfile
- docker/requirements3.txt
> [release-7.0] add tini and supervisord to image

- src/libData/AccountData/AccountStore.cpp
- src/libData/AccountData/AccountStore.h
- src/libData/AccountData/AccountStoreSC.tpp
- src/libData/AccountData/ScillaClient.cpp
- src/libData/AccountData/ScillaClient.h
- src/libNode/MicroBlockPreProcessing.cpp
> [release-7.0] Fix NotifyTimeout

- src/libData/AccountData/AccountStore.cpp
- src/libData/AccountData/AccountStore.h
- src/libData/AccountData/AccountStoreSC.tpp
- src/libData/AccountData/ScillaClient.cpp
- src/libData/AccountData/ScillaClient.h
- src/libNode/MicroBlockPreProcessing.cpp
> Fix NotifyTimeout

- src/libLookup/Lookup.cpp
- src/libServer/LookupServer.cpp
> [master] Keep one mutex for both reading and deletion of txn shard map

- CMakeLists.txt
- build.sh
- constants.xml
- constants_local.xml
- scripts/download_incr_DB.py
- scripts/upload_incr_DB.py
- src/cmd/CMakeLists.txt
- src/cmd/genTxnBodiesFromS3.cpp
- src/cmd/migrate_mbs.cpp
- src/cmd/migrate_mbs_txns.cpp
- src/common/Constants.cpp
- src/common/Constants.h
- src/depends/libDatabase/LevelDB.cpp
- src/depends/libDatabase/LevelDB.h
- src/libDirectoryService/FinalBlockPostProcessing.cpp
- src/libDirectoryService/MicroBlockProcessing.cpp
- src/libLookup/Lookup.cpp
- src/libMessage/Messenger.cpp
- src/libMessage/Messenger.h
- src/libMessage/ZilliqaMessage.proto
- src/libNode/FinalBlockProcessing.cpp
- src/libPersistence/BlockStorage.cpp
- src/libPersistence/BlockStorage.h
- src/libServer/IsolatedServer.cpp
- tests/Persistence/CMakeLists.txt
- tests/Persistence/Test_TxBody.cpp
Cherry-picked commits from
#2311 Index microblocks by epoch number and shard ID 
#2316 Index txns by epoch number
#2326 Rolling leveldb for microBlocks and txBodies
> [master] microBlocks and txBodies changes

- src/libServer/WebsocketServer.cpp
- src/libServer/WebsocketServer.h
> [release-7.0] Add response to websocket http health check

- src/libServer/WebsocketServer.cpp
- src/libServer/WebsocketServer.h
> [master] Add response to websocket http health check

- docker/Dockerfile
- docker/Dockerfile.cuda
- src/libUtils/SWInfo.h
> [release-7.0] To Zilliqa 7.0.0-beta.2 and Scilla 0.9.1-alpha.0

- src/libData/AccountData/AccountStoreSC.tpp
> [release-7.0] Use atomic balance as sender balance

- src/cmd/CMakeLists.txt
- src/cmd/migrate_mbs_txns.cpp
- src/libLookup/Synchronizer.h
> [release-7.0] Fix migrate_mbs_txns

- scripts/download_static_DB.py
> [release-7.0] Add download_static_DB.py

- scripts/auto_backup.py
`auto_backup.py`, which runs inside a lookup pod, performs regular backup of entire persistence folder.
Starting v7.0.0 we will be moving some static leveldb folders into `s3://<bucket>/blockchain-data/<testnet>`.
This PR will exclude those leveldb folders from the auto backup.
> [release-7.0] Update auto_backup to exclude blockchain-data folders

- CMakeLists.txt
- docker/Dockerfile
> [release-7.0] Add migrate_mbs_txns to INSTALL_DIR

- src/libLookup/Lookup.cpp
> [master] fix the typo

- docker/Dockerfile
- docker/Dockerfile.cuda
- src/libUtils/SWInfo.h
> [release-7.0] To v7.0.0-beta.3

- src/libPersistence/BlockStorage.cpp
> [release-7.0] Minor fix to RefreshDB(TX_BODY)

- scripts/download_static_DB.py
> [release-7.0] Fix download_static_DB

- docker/Dockerfile
- docker/Dockerfile.cuda
- src/libUtils/SWInfo.h
> [release-7.0] To v7.0.0-beta.4

- README.md
> [master] chore: General update to readme

- src/libPersistence/BlockStorage.cpp
> [master] Minor fix to RefreshDB(TX_BODY)

- scripts/auto_backup.py
- scripts/download_incr_DB.py
- scripts/download_static_DB.py
- scripts/upload_incr_DB.py
Cherry-picked commits from:
#2352 
#2351 
#2362 
#2365
> [master] Add blockchain-data PRs from release-7.0 branch

- docker/Dockerfile
- docker/Dockerfile.cuda
- src/libUtils/SWInfo.h
> [release-7.0] To v7.0.0-beta.5

- docker/Dockerfile
- docker/Dockerfile.cuda
- src/libUtils/SWInfo.h
> [release-7.0] To v7.0.0-beta.6

- docker/Dockerfile
- docker/Dockerfile.cuda
- src/libUtils/SWInfo.h
> [release-7.0] To Zilliqa v7.0.0 and Scilla v0.9.1

- scripts/miner_info.py
- src/libServer/StatusServer.cpp
- src/libServer/StatusServer.h
Although we have `BLACKLIST_NUM_TO_POP`, in some situations we may need an IP removed earlier from a node's blacklist. This PR adds two more functions to miner_info:
* blacklist_check \<IP address\>
* blacklist_remove \<IP address\>
> [master] Add blacklisted IP check and removal to local server

- daemon/ZilliqaDaemon.cpp
This PR addresses issue https://github.com/Zilliqa/Issues/issues/683
> [master] kill scilla-server in daemon

- README.md
1. Specified the live version for both Mainnet and Testnet
2. Changed the mining page link (system requirements) from the old wiki page to the more recent dev portal page
3. Indicated in the "Build Dependencies" section that Ubuntu 18.04 will be the official OS effective v7.0.0
4. Added section "Build Scilla for Smart Contract Execution"
5. Other cosmetic changes (capitalization, removal of "codename Durian")
> [master] Update README.md

- src/libLookup/Lookup.cpp
- src/libNetwork/RumorManager.cpp
> [release-7.0] Requests from whitelisted

- scripts/miner_info.py
- src/libMediator/Mediator.cpp
- src/libMediator/Mediator.h
- src/libServer/LookupServer.cpp
- src/libServer/StatusServer.cpp
- src/libServer/StatusServer.h
> [release-7.0] Add switch for GetSmartContractState

- scripts/miner_info.py
- src/common/Messages.h
- src/libMessage/Messenger.cpp
- src/libMessage/Messenger.h
- src/libMessage/ZilliqaMessage.proto
- src/libNode/DSBlockProcessing.cpp
- src/libNode/Node.cpp
- src/libNode/Node.h
- src/libServer/StatusServer.cpp
- src/libServer/StatusServer.h
> [release-7.0] Add GETVERSION message

- VERSION
- docker/Dockerfile
- docker/Dockerfile.cuda
- src/libUtils/SWInfo.h
> [release-7.0] To v7.0.1

- src/libNetwork/P2PComm.cpp
> [release-7.0] Add debug log to p2pcomm and revert PR 2161 

- docker/Dockerfile
- docker/Dockerfile.cuda
- src/libUtils/SWInfo.h
> [release-7.0] To v7.0.2

- README.md
Just correcting some incorrect links in the README
> Incorrect README Links

- src/libPersistence/BlockStorage.cpp
- src/libPersistence/BlockStorage.h
> [master] Add PR 2372 to master

- src/libNetwork/P2PComm.cpp
> [master] Add PR 2398 to master

- src/libLookup/Lookup.cpp
- src/libNetwork/RumorManager.cpp
> [master] Add PR 2389 to master

- scripts/miner_info.py
- src/libMediator/Mediator.cpp
- src/libMediator/Mediator.h
- src/libServer/LookupServer.cpp
- src/libServer/StatusServer.cpp
- src/libServer/StatusServer.h
> [master] Add PR 2390 to master

- .travis.yml
> [master] update travis build os to bionic

- src/cmd/isolated_server.cpp
- src/libData/AccountData/AccountStoreSC.h
- src/libData/AccountData/AccountStoreSC.tpp
- src/libServer/IsolatedServer.cpp
- src/libServer/IsolatedServer.h
- src/libUtils/ScillaUtils.cpp
- src/libUtils/ScillaUtils.h
Add an API called `ExportPersistence` for exporting persistence
Add bootstrap option --path for choosing a tar file from where to load persistence
> [master] Add importing and exporting of persistence

- CMakeLists.txt
- build.sh
- constants.xml
- constants_local.xml
- src/common/Constants.cpp
- src/common/Constants.h
- src/libDirectoryService/PoWProcessing.cpp
- src/libMessage/Messenger.cpp
- src/libMessage/Messenger.h
- src/libMessage/ZilliqaMessage.proto
- src/libNode/PoWProcessing.cpp
> [release-7.1] Check version in PoW submission

- src/libData/AccountData/TxnPool.h
- src/libNode/MicroBlockPreProcessing.cpp
- src/libNode/Node.cpp
Fix the issue where in entry from GasIndex for smaller gas price is not removed when one with higher price is added.
Add check on  UPGRADE_TARGET to enable this change.
> [release-7.1] Remove GasIndex entry for smaller gas price

- VERSION
- docker/Dockerfile
- docker/Dockerfile.cuda
- src/libUtils/SWInfo.h
> [release-7.1] To v7.1.0

- daemon/ZilliqaDaemon.cpp
> [release-7.1] Revert PR 2382

- daemon/ZilliqaDaemon.cpp
> [master] Revert PR 2382

- src/libNetwork/P2PComm.cpp
This PR addresses issue : https://github.com/Zilliqa/Issues/issues/690
> [master] Avoid unnecessary errno checks for write call

- src/libLookup/Lookup.cpp
- src/libServer/LookupServer.cpp
This PR addresses: https://github.com/Zilliqa/Issues/issues/675
> [master] Allow txn dispatching to ds-shard when no other shard exists

- scripts/miner_info.py
- src/libLookup/Lookup.cpp
- src/libLookup/Lookup.h
- src/libServer/LookupServer.cpp
- src/libServer/StatusServer.cpp
- src/libServer/StatusServer.h
> [master] add status api for sending txns to ds

- src/libNode/MicroBlockPreProcessing.cpp
This is same as #2415 (along `release-7.1`) except it excludes the fix for nonce too low log since that fix was already pushed in #2413
> [master] Add more verbose logging to txn processing

- src/libDirectoryService/PoWProcessing.cpp
- src/libMessage/Messenger.cpp
- src/libMessage/Messenger.h
- src/libMessage/ZilliqaMessage.proto
- src/libNode/PoWProcessing.cpp
Same as #2414 except
- `POW_TEST_VERSION_CHECK` and code blocks under this are not included (since tested already in `release-7.1`)
- `V710_TARGET_DS_NUM` not included (since version check will be in effect by default moving forward)
- Schnorr submodule updated
> [master] Check version in PoW submission

- README.md
> [master] Update Zilliqa version 7.1.0 in README.md

- CMakeLists.txt
Update `cmake` version to 3.16 or above in top level `CMAKELists.txt`.
> [master] Update cmake version 3.16 or above

- VERSION
- docker/Dockerfile
- docker/Dockerfile.cuda
- src/libUtils/SWInfo.h
> [release-7.2] To v7.2.0-alpha.0

- docker/Dockerfile.cuda
> [master] Update cmake 3.19 in cuda dockerfile

- docker/Dockerfile.cuda
same as [https://github.com/Zilliqa/Zilliqa/pull/2445](url)
> [release-7.2] Update cmake 3.19 in cuda dockerfile

- src/libDirectoryService/DSBlockPreProcessing.cpp
UPGRADE_TARGET_DS_NUM will be used in #2440 
UPGRADE_TARGET_DS_NUM should not be used anywhere else
> [release-7.2] Remove outdated use of UPGRADE_TARGET_DS_NUM

- docker/Dockerfile
- docker/Dockerfile.cuda
- src/libUtils/SWInfo.h
> [release-7.2] To v7.2.0-alpha.1

- src/libDirectoryService/DSBlockPreProcessing.cpp
> [master] Remove outdated use of UPGRADE_TARGET_DS_NUM

- docker/Dockerfile
- docker/Dockerfile.cuda
- src/libUtils/SWInfo.h
> [release-7.2] To v7.2.0

- src/libDirectoryService/DirectoryService.cpp
- src/libDirectoryService/DirectoryService.h
- src/libDirectoryService/PoWProcessing.cpp
- src/libNode/Node.cpp
This PR addresses issue : https://github.com/Zilliqa/Issues/issues/706
> [release-7.2] Ignore pow submission which are received late

- src/libServer/JSONConversion.cpp
- src/libServer/JSONConversion.h
- src/libServer/LookupServer.cpp
- src/libServer/LookupServer.h
- tests/Server/CMakeLists.txt
- tests/Server/Test_DSBlockSer.cpp
Expose the bitmap in Tx and DS block
Expose the PoW rejects in DS Block
> [master] Expose more data in APIs

- docker/Dockerfile
> [isoserver/v7.2.0] Updated git tag in dockerfile for isolated server

- src/cmd/isolated_server.cpp
- src/common/Constants.cpp
- src/common/Constants.h
- src/libData/AccountData/AccountStore.cpp
> [master] Enable Scilla Server for Isolated Server

- src/libDirectoryService/DirectoryService.cpp
- src/libDirectoryService/DirectoryService.h
- src/libDirectoryService/PoWProcessing.cpp
- src/libNode/Node.cpp
same as https://github.com/Zilliqa/Zilliqa/pull/2453
> [master] reject pow submissions received after pow window

- .travis.yml
- CMakeLists.txt
- constants.xml
- constants_local.xml
- scripts/ci_build.sh
- src/libData/AccountData/ScillaClient.cpp
- src/libData/AccountData/ScillaClient.h
> [master] enable scilla unit tests in travisCI

- src/libMessage/Messenger.cpp
> [master] Minor fix to Messenger::SetNodeForwardTxnBlock

- constants.xml
- constants_local.xml
- src/common/Constants.cpp
- src/common/Constants.h
- src/libDirectoryService/DSBlockPostProcessing.cpp
- src/libDirectoryService/DSBlockPreProcessing.cpp
- src/libDirectoryService/DirectoryService.h
- src/libDirectoryService/PoWProcessing.cpp
This PR revises algorithm in `DirectoryService::FindTopPriorityNodes` for getting the shortlisted set of PoW submitters to consider for the sharding step. By enforcing a `MIN_NODE_REPUTATION_PRIORITY` reputation record for existing miners, this PR gives new miners (which do not have a reputation record) a better chance of getting shortlisted, while at the same time making sure the network performance is preserved.
**Previous algorithm:**
1. Sort all submissions by priority value
- Priority = log2(reputation)
- New miners have reputation = 0
2. Return the first `MAX_SHARD_NODE_NUM` entries
**New algorithm:**
1. Set aside submissions from new miners (i.e., no reputation value)
2. Sort remaining submissions by priority value
3. Insert the new miner submissions before existing miners with …
> [master] Add MIN_NODE_REPUTATION_PRIORITY

- src/common/Constants.cpp
- src/common/Constants.h
- src/libData/AccountData/AccountStoreSC.tpp
- src/libPersistence/ContractStorage2.cpp
- src/libUtils/ScillaUtils.cpp
- tests/Data/ScillaTestUtil.cpp
- tests/Data/ScillaTestUtil.h
- tests/Data/Test_Contract.cpp
This PR adds a unit test (that was missing in #2167) for remote state fetch. During the process, issues in the unit test framework for contracts (Test_Contract) have been fixed.
> [master] Unit test for remote state fetch

- src/libPersistence/ContractStorage2.cpp
- tests/Data/ScillaTestUtil.cpp
> [master] Fix compile error in ScillaTestUtil

- src/libCrypto/Sha2.h
- src/libPersistence/ContractStorage2.cpp
> [release-7.2] Add SHA Update func that accepts string

- .travis.yml
- docker/Dockerfile
- docker/Dockerfile.cuda
> [master] Use Scilla commit along remote_state_reads branch

- src/libCrypto/Sha2.h
- src/libPersistence/ContractStorage2.cpp
> [master] Add SHA Update func that accepts string

- README.md
> [master] Update versions for live mainnet and testnet in README

- src/libLookup/Lookup.cpp
Do not return when txns generated is empty.
> [master] Fix dispatch when txn generator is disable

- src/libLookup/Lookup.cpp
To avoid having to toggle this during every upgrade operation.
We can change default back to false when smart contract sharding feature is available.
> [master] Change default value for m_sendSCCallsToDS to true

- src/libDirectoryService/DSBlockPreProcessing.cpp
To fix a bug in filling up the gaps when there is not enough nodes after trimming
> [master] Fix shard guard gaps filling

- src/libNode/DSBlockProcessing.cpp
This PR fixes the issue: https://github.com/Zilliqa/Issues/issues/713
> [master] Fix rejoining issue after lost pow

- VERSION
- docker/Dockerfile
- docker/Dockerfile.cuda
- src/libUtils/SWInfo.h
> [release-8.0] To v8.0.0-alpha.0

- src/libNode/PoWProcessing.cpp
> [release-8.0] Notify wait in InitMining when pow is lost

- src/libNode/FinalBlockProcessing.cpp
- src/libNode/MicroBlockPreProcessing.cpp
- src/libNode/Node.cpp
- src/libNode/Node.h
> [master] skip wating on txnprocessing in vacuous epoch

- src/cmd/gentxn.cpp
> [release-8.0] TxnGenerator: Change GAS_LIMIT for txn to 50

- src/libNode/PoWProcessing.cpp
> [master] Notify wait in InitMining when pow is lost 

- src/cmd/gentxn.cpp
> [master] TxnGenerator: Change GAS_LIMIT for txn to 50

- .travis.yml
- docker/Dockerfile
- docker/Dockerfile.cuda
- src/libData/AccountData/AccountStore.cpp
- src/libData/AccountData/AccountStore.h
- src/libData/AccountData/AccountStoreSC.h
- src/libData/AccountData/AccountStoreSC.tpp
- src/libPersistence/ContractStorage2.cpp
- tests/Data/Test_Contract.cpp
> [release-8.0] Fetch from atomic instead of temp for scilla remote read

- docker/Dockerfile
- docker/Dockerfile.cuda
- src/libUtils/SWInfo.h
> [release-8.0] To v8.0.0-alpha.1

- src/libData/AccountData/AccountStore.cpp
> [release-8.0] Commit disambiguated states to disk

- docker/Dockerfile
- docker/Dockerfile.cuda
- src/libUtils/SWInfo.h
> [release-8.0] To v8.0.0-alpha.2

- src/libDirectoryService/FinalBlockPostProcessing.cpp
- src/libNode/FinalBlockProcessing.cpp
- src/libUtils/CMakeLists.txt
- src/libUtils/CommonUtils.cpp
- src/libUtils/CommonUtils.h
> [release-8.0] Fix memory increase issue of lookups/seed nodes

- src/libDirectoryService/DSBlockPostProcessing.cpp
- src/libDirectoryService/DirectoryService.cpp
- src/libDirectoryService/DirectoryService.h
- src/libDirectoryService/FinalBlockPostProcessing.cpp
- src/libNode/DSBlockProcessing.cpp
- src/libNode/FinalBlockProcessing.cpp
- src/libNode/Node.cpp
- src/libZilliqa/Zilliqa.cpp
-  [x] Recover network from another testnet 
-  [x] Recover dsguard
-  [x] Recover shardguard
> [release-8.0] Skip MB submission wait for current ds epoch after upgrade only

- docker/Dockerfile
- docker/Dockerfile.cuda
- src/libUtils/SWInfo.h
> [release-8.0] To v8.0.0-alpha.3

- src/libDirectoryService/DSBlockPostProcessing.cpp
- src/libDirectoryService/DirectoryService.cpp
- src/libDirectoryService/DirectoryService.h
- src/libDirectoryService/FinalBlockPostProcessing.cpp
- src/libNode/DSBlockProcessing.cpp
- src/libNode/FinalBlockProcessing.cpp
- src/libNode/Node.cpp
- src/libZilliqa/Zilliqa.cpp
Same as https://github.com/Zilliqa/Zilliqa/pull/2517
> [master] skip mb submission wait after upgrade for current ds epoch

- src/libData/AccountData/AccountStore.cpp
> [master] Commit disambiguated states to disk

- .travis.yml
- docker/Dockerfile
- docker/Dockerfile.cuda
- src/libData/AccountData/AccountStore.cpp
- src/libData/AccountData/AccountStore.h
- src/libData/AccountData/AccountStoreSC.h
- src/libData/AccountData/AccountStoreSC.tpp
- src/libPersistence/ContractStorage2.cpp
- tests/Data/Test_Contract.cpp
> [master] Fetch from atomic instead of temp for scilla remote read

- .travis.yml
- docker/Dockerfile
- docker/Dockerfile.cuda
- src/libUtils/SWInfo.h
> [release-8.0] To v8.0.0-alpha.4

- scripts/miner_info.py
- src/libMediator/Mediator.cpp
- src/libMediator/Mediator.h
- src/libServer/LookupServer.cpp
- src/libServer/StatusServer.cpp
- src/libServer/StatusServer.h
> [release-8.0] Add disabling of GetPendingTxns API to status server

- src/libCrypto/Sha2.h
- src/libMessage/Messenger.cpp
- src/libMessage/Messenger.h
- src/libMessage/ZilliqaMessage.proto
- src/libNode/DSBlockProcessing.cpp
- src/libNode/FinalBlockProcessing.cpp
- src/libNode/Node.h
1. In shard sender, generate hash of the txn hashes inside the PENDINGTXN message
2. In lookup, reject PENDINGTXN message if hash already exists in set
3. Clear the set once DS block is processed
> [release-8.0] Avoid processing duplicate pending txn lists

- src/libLookup/Lookup.cpp
- src/libNode/FinalBlockProcessing.cpp
- src/libRemoteStorageDB/RemoteStorageDB.cpp
- src/libRemoteStorageDB/RemoteStorageDB.h
> [release-8.0] fix processing of duplicate updates

- src/libDirectoryService/FinalBlockPostProcessing.cpp
- src/libNode/MicroBlockPreProcessing.cpp
This PR covers: https://github.com/Zilliqa/Issues/issues/720
> [release-8.0] Detach the commit mb submission before waiting on cv

- src/libDirectoryService/FinalBlockPostProcessing.cpp
- src/libNode/FinalBlockProcessing.cpp
- src/libUtils/CMakeLists.txt
- src/libUtils/CommonUtils.cpp
- src/libUtils/CommonUtils.h
> [release-7.2] Release unclaimed memory back to heap

- docker/Dockerfile
- docker/Dockerfile.cuda
- src/libUtils/SWInfo.h
> [release-8.0] To v8.0.0-alpha.5

- docker/Dockerfile
- docker/Dockerfile.cuda
- src/libUtils/SWInfo.h
> [release-8.0] To v8.0.0

- src/libDirectoryService/FinalBlockPostProcessing.cpp
- src/libNode/MicroBlockPreProcessing.cpp
Same as https://github.com/Zilliqa/Zilliqa/pull/2528
> [master] Detach the commit mb submission before waiting on cv

- src/libNode/DSBlockProcessing.cpp
- src/libNode/Node.cpp
Same as https://github.com/Zilliqa/Zilliqa/pull/2542
> [master] Avoid deadlock issue

- scripts/miner_info.py
- src/libMediator/Mediator.cpp
- src/libMediator/Mediator.h
- src/libServer/LookupServer.cpp
- src/libServer/StatusServer.cpp
- src/libServer/StatusServer.h
> [master] Add disabling of GetPendingTxns API to status server

- src/libCrypto/Sha2.h
- src/libMessage/Messenger.cpp
- src/libMessage/Messenger.h
- src/libMessage/ZilliqaMessage.proto
- src/libNode/DSBlockProcessing.cpp
- src/libNode/FinalBlockProcessing.cpp
- src/libNode/Node.h
> [master] Avoid processing duplicate pending txn lists

- README.md
> [master] Update README

- src/libNode/FinalBlockProcessing.cpp
> [release-8.0] Add ARCHIVAL_LOOKUP check to ignore sending txns to shard

- docker/Dockerfile
- docker/Dockerfile.cuda
- src/libUtils/SWInfo.h
> [release-8.0] To v8.0.1

- scripts/upload_incr_DB.py
> [master] handle exception (I/O error) with retries

- src/libLookup/Lookup.cpp
- src/libNode/PoWProcessing.cpp
> [release-8.0] Notify wait in InitMining when pow mine is timedout

- VERSION
- docker/Dockerfile
- docker/Dockerfile.cuda
- src/libUtils/SWInfo.h
> [release-8.0] To v8.0.2

- scripts/upload_incr_DB.py
> [release-8.0] handle exception (I/O error) with retries

- VERSION
- docker/Dockerfile
- docker/Dockerfile.cuda
- src/libUtils/SWInfo.h
> [release-8.0] To v8.0.3

- src/libDirectoryService/DirectoryService.cpp
- src/libLookup/Lookup.h
> [release-8.0] notify cv for cosigreward

- src/libNode/FinalBlockProcessing.cpp
> [master] Avoid cleaning txns if no shard mb was included in fb itself

- src/libDirectoryService/PoWProcessing.cpp
> [master] Check blocknum of pow submission

- README.md
> [master] Update readme zilliqa release version v8.0.3

- src/libData/AccountData/AccountStoreSC.tpp
In case of early notify, the contract call cv is mistakenly notified.
Add a flag to check if the contract call timer is already notified.
> [release-8.0] Add flag to check if contract call CV is already notified

- src/libNode/Node.cpp
PR addressess issue https://github.com/Zilliqa/Issues/issues/724
> [release-8.0] Ask for cosig when only one shard

- src/libNode/Node.cpp
Same as https://github.com/Zilliqa/Zilliqa/pull/2573
> [master] Ask for cosig when only one shard

- docker/Dockerfile
- docker/Dockerfile.cuda
- src/libUtils/SWInfo.h
> [release-8.0] To v8.0.4-alpha.0

- VERSION
- docker/Dockerfile
- docker/Dockerfile.cuda
- src/libUtils/SWInfo.h
> [release-8.0] To v8.0.4

- src/libNode/FinalBlockProcessing.cpp
same as https://github.com/Zilliqa/Zilliqa/pull/2552
> [master] Add ARCHIVAL_LOOKUP check to ignore sending txns to shard

- src/libPersistence/ContractStorage2.cpp
- src/libPersistence/ContractStorage2.h
> [master] Optimize checking for empty key

- src/libData/AccountData/AccountStoreSC.tpp
> [master] Add flag to check if it is already notified

- src/libLookup/Lookup.cpp
- src/libNode/PoWProcessing.cpp
same as https://github.com/Zilliqa/Zilliqa/pull/2556
> [master] Notify wait in InitMining when pow mine is timedout

- scripts/miner_info.py
- src/libServer/StatusServer.cpp
- src/libServer/StatusServer.h
Adding a empty healthcheck so that we can check if zilliqa process is running
> [master] Add health check in jsonrpc

- README.md
> [master] Update release version - zilliqa -v8.0.4 and scilla - v0.10.1

- src/libDirectoryService/DSBlockPostProcessing.cpp
- src/libDirectoryService/FinalBlockPostProcessing.cpp
> [master] Microblock timeout to use EXTRA_TX_DISTRIBUTE_TIME_IN_MS correctly

- src/libLookup/Lookup.cpp
Addresses issue : https://github.com/Zilliqa/Issues/issues/730
> [master] Add check on incoming-lowblknum against latest blk num on disk

- scripts/download_incr_DB.py
- scripts/download_static_DB.py
- scripts/upload_incr_DB.py
This PR addressess: https://github.com/Zilliqa/Issues/issues/733
> [master] downloading compressed blockchaindata instead of multiple files

- src/libDirectoryService/DirectoryService.cpp
- src/libLookup/Lookup.h
Bringing missing changes from  `release-8.0` branch related to cosig fetch.
https://github.com/Zilliqa/Zilliqa/pull/2563/files
> [master] Wait for cosig to be received

- src/libLookup/Lookup.cpp
> [master] Ignore tx blocks which are already received before

- src/libLookup/Lookup.cpp
This PR addresses : https://github.com/Zilliqa/Issues/issues/736
> [master] Skip sender's IP check against dscommitte

- src/libDirectoryService/MicroBlockProcessing.cpp
> [master] Fix EXTRA_TX_DISTRIBUTE_TIME_IN_MS to seconds

- src/libMessage/Messenger.cpp
Issue: The pending hash just had the txn list, hence if the code of the pending txn changes, it might be marked as duplicate and be rejected.
> [master] Add code of pending txn in hashing

- src/cmd/data_migrate.cpp
- src/libData/AccountData/AccountStore.cpp
- src/libData/AccountData/AccountStore.h
- src/libData/AccountData/AccountStoreSC.tpp
- src/libData/AccountData/AccountStoreTrie.tpp
- src/libData/DataStructures/TraceableDB.h
- src/libDirectoryService/FinalBlockPostProcessing.cpp
- src/libMessage/Messenger.cpp
- src/libPersistence/ContractStorage.cpp
- src/libPersistence/Retriever.cpp
- src/libPersistence/Retriever.h
duplicate of #2589
has same cherry-picked commits
> [master] Reduce logs for MPT (rebased)

- src/libData/AccountData/AccountStore.cpp
- src/libData/DataStructures/TraceableDB.h
Add missing parameters to fix build
> [master] Fix MoveUpdatesToDisk missing parameters

- src/libNode/FinalBlockProcessing.cpp
- src/libNode/MicroBlockPreProcessing.cpp
- src/libNode/Node.h
> [master] Mark txns as "PRESENT_VALID_CONSENSUS_NOT_REACHED" when No MB found in FB

- VERSION
- docker/Dockerfile
- docker/Dockerfile.cuda
- src/libUtils/SWInfo.h
> [release-8.1] To v8.1.0-alpha.0

- constants.xml
- constants_local.xml
- src/libData/AccountData/AccountStore.cpp
Change KEEP_HISTORICAL_DATA to true
Fix data migrate
> [release-8.1] Update KEEP_HISTORICAL_DATA and fix data migrate

- CMakeLists.txt
- build.sh
- scripts/make_image_for_test.sh
- src/libDirectoryService/FinalBlockPostProcessing.cpp
Add VC9 test
DS Leader halt consensus at final challenge 1
Then VC
Then the next leader halt consensus again once
In the same period got to spam smart contracts
> [master] Add VC9 - Suspend before response

- src/libNode/MicroBlockPreProcessing.cpp
> [release-8.1] Fix dm7 

- src/libDirectoryService/DirectoryService.cpp
Addresses issue : https://github.com/Zilliqa/Issues/issues/737
> [release-8.1] Remove check against IP for dscommitte in FinishRejoinAsDS

- constants.xml
- constants_local.xml
- src/libData/AccountData/AccountStore.cpp
> [master] Update KEEP_HISTORICAL_DATA

- src/libNode/MicroBlockPreProcessing.cpp
same as https://github.com/Zilliqa/Zilliqa/pull/2613
> [master] Fix dm7 

- src/libDirectoryService/FinalBlockPostProcessing.cpp
Same as https://github.com/Zilliqa/Zilliqa/pull/2615/commits
> [master] Fix to avoid delay in switching to POW_SUBMISSION state

- src/libDirectoryService/DirectoryService.cpp
same as https://github.com/Zilliqa/Zilliqa/pull/2611/
> [master] Remove check against IP for dscommitte in FinishRejoinAsDS

- src/libDirectoryService/FinalBlockPostProcessing.cpp
> [release-8.1] Fix vc9 checks

- src/libDirectoryService/FinalBlockPostProcessing.cpp
Change condition to every epoch except vacaous for vc9
- [z] This is not a breaking change
- [z] **ready for review**
> [master] fix vc9 check on every epoch except vacaous epoch

- docker/Dockerfile
- docker/Dockerfile.cuda
- src/libUtils/SWInfo.h
> [release-8.1] To v8.1.0-alpha.1

- src/libData/AccountData/AccountStoreTrie.h
- src/libData/AccountData/AccountStoreTrie.tpp
- src/libMessage/Messenger.cpp
- src/libServer/LookupServer.cpp
- src/libServer/WebsocketServer.cpp
After VC in after a vacous epoch, the `GetAccount` function was returning wrong values
> [release-8.1] Fix Nonce 0 issue after VC after a vacous epoch

- src/libData/AccountData/AccountStoreTrie.h
- src/libData/AccountData/AccountStoreTrie.tpp
- src/libMessage/Messenger.cpp
- src/libServer/LookupServer.cpp
- src/libServer/WebsocketServer.cpp
fix GetNonce
change reset Root default
Duplicate of #2627
> [master]  Fix Nonce 0 issue after VC after a vacous epoch

- cmake/InstallJsonrpccpp.cmake
- constants.xml
- constants_local.xml
- src/common/Constants.cpp
- src/common/Constants.h
- src/depends/safeserver/CMakeLists.txt
- src/depends/safeserver/safehttpserver.cpp
- src/depends/safeserver/safehttpserver.h
Upgrade JSONRPC and add new MHD flags
Add logs to safehttpserver
> [release-8.1] Upgrade jsonrpc to v1.3.0 and add epoll flags to MHD methods

- cmake/InstallJsonrpccpp.cmake
- constants.xml
- constants_local.xml
- src/common/Constants.cpp
- src/common/Constants.h
- src/depends/safeserver/CMakeLists.txt
- src/depends/safeserver/safehttpserver.cpp
- src/depends/safeserver/safehttpserver.h
Upgrade JSONRPC and add new MHD flags
Add logs to safehttpserver
> [master] Upgrade jsonrpc to v1.3.0 and add epoll flags to MHD methods

- src/depends/libDatabase/LevelDB.cpp
- src/depends/libDatabase/LevelDB.h
- src/depends/libDatabase/OverlayDB.cpp
> Add logs to make db issues verbose

- src/libLookup/Lookup.cpp
> [release-8.1] Do not rejoin twice for responses

- docker/Dockerfile
- docker/Dockerfile.cuda
- src/libUtils/SWInfo.h
> [release-8.1] To v8.1.0-alpha.2

- src/libLookup/Lookup.cpp
- src/libNode/Node.cpp
Same as https://github.com/Zilliqa/Zilliqa/pull/2640
> [master] Fix for protobuf deserialization issue on lookups during first rejoin attempt 

- src/libLookup/Lookup.cpp
Reset max rejoin attempt after successful rejoin of seed node in the network.
> [release-8.1] Reset max rejoining attempts

- src/libLookup/Lookup.cpp
> [master] Reset max rejoining attempts

- src/libPersistence/ContractStorage.cpp
This PR addresses issue: https://github.com/Zilliqa/Issues/issues/739
> [release-8.1] Avoid adding for re-deletion in temp  if already marked as to be deleted in main

- src/libPersistence/ContractStorage.cpp
during updation, the state values were being stored in p_*, however this caused updated states to be deleted.
> [release-8.1] Fix State disappearing after a revert

- src/depends/libDatabase/LevelDB.cpp
- src/depends/libDatabase/LevelDB.h
- src/depends/libDatabase/OverlayDB.cpp
- src/depends/libDatabase/OverlayDB.h
- src/libData/DataStructures/TraceableDB.cpp
- src/libData/DataStructures/TraceableDB.h
Add a check in `ExecutePurge` to not purge newly inserted keys.
> [release-8.1] Purge only unnecessary keys.

- src/libPersistence/ContractStorage.cpp
Same as https://github.com/Zilliqa/Zilliqa/pull/2643/
> [master] Avoid adding for re-deletion in temp if already marked as to be deleted in main

- docker/Dockerfile
- docker/Dockerfile.cuda
- src/libUtils/SWInfo.h
> [release-8.1] To v8.1.0-alpha.3

- src/libDirectoryService/FinalBlockPostProcessing.cpp
> [release-8.0] Clear STL cache every TX epoch for dsnodes as well

- VERSION
- docker/Dockerfile
- docker/Dockerfile.cuda
- src/libUtils/SWInfo.h
> [release-8.0] To v8.0.5

- src/libNode/FinalBlockProcessing.cpp
> [release-8.0] Clean memory for normal nodes

- VERSION
- docker/Dockerfile
- docker/Dockerfile.cuda
- src/libUtils/SWInfo.h
> [release-8.0] To v8.0.6

- VERSION
- docker/Dockerfile
- docker/Dockerfile.cuda
- src/libUtils/SWInfo.h
> [release-8.0] To v8.0.7

- src/depends/libDatabase/LevelDB.cpp
- src/depends/libDatabase/LevelDB.h
- src/depends/libDatabase/OverlayDB.cpp
- src/depends/libDatabase/OverlayDB.h
- src/libData/AccountData/AccountStore.cpp
- src/libData/AccountData/AccountStoreTrie.tpp
- src/libData/DataStructures/TraceableDB.cpp
- src/libData/DataStructures/TraceableDB.h
- src/libPersistence/ContractStorage.cpp
> [master] MPT fixes into master

- scripts/upload_incr_DB.py
> [release-8.1] sync newly added state and contractTrie purge dbs for upload incremental

- src/libDirectoryService/FinalBlockPostProcessing.cpp
- src/libNode/FinalBlockProcessing.cpp
> [master] Clean STL cache every tx epoch for ds and normal nodes

- docker/Dockerfile
- docker/Dockerfile.cuda
- src/libUtils/SWInfo.h
> [release-8.1] To v8.1.0-alpha.4

- src/libData/AccountData/Account.cpp
- src/libData/DataStructures/TraceableDB.cpp
- src/libPersistence/ContractStorage.cpp
- src/libServer/LookupServer.cpp
This PR covers:
- Free unclaimed memory after serving `GetSmartContractState` request for contracts which can be huge for big contracts.
- Log contract address for `GetSmartContractState`
- Removed unnecessary logmarkers
- Added log indicating if purging was done or not.
> [release-8.1] Release unclaimed memory for FetchStateJson

- docker/Dockerfile
- docker/Dockerfile.cuda
> [release-8.1] To v8.1.0-alpha.5

- src/depends/libDatabase/LevelDB.cpp
> [release-8.1] Reduce leveldb logging

- scripts/miner_info.py
- src/depends/safeserver/safehttpserver.cpp
- src/libLookup/Lookup.cpp
- src/libLookup/Lookup.h
- src/libServer/StatusServer.cpp
- src/libServer/StatusServer.h
> [release-8.1] Change JsonRpc port start stop mechanism

- src/libData/AccountData/Account.cpp
- src/libData/DataStructures/TraceableDB.cpp
- src/libPersistence/ContractStorage.cpp
- src/libServer/LookupServer.cpp
> [master] Release unclaimed memory for FetchStateJson

- README.md
Update mainnet version from `v8.0.4` to `v8.0.7`
> [master] Update mainnet version

- scripts/miner_info.py
- src/depends/safeserver/safehttpserver.cpp
- src/libLookup/Lookup.cpp
- src/libLookup/Lookup.h
- src/libServer/StatusServer.cpp
- src/libServer/StatusServer.h
> [master] Change JsonRpc port start stop mechanism

- src/depends/libDatabase/LevelDB.cpp
- src/depends/libDatabase/MemoryDB.cpp
- src/libData/AccountData/AccountStoreTrie.tpp
Do not remove any roothash before expiry. (even if it is not refrenced)
> [release-8.1] Store Every Hash

- docker/Dockerfile
- docker/Dockerfile.cuda
- src/libUtils/SWInfo.h
> [release-8.1] To v8.1.0-alpha.6

- src/depends/libDatabase/LevelDB.cpp
- src/depends/libDatabase/LevelDB.h
- src/depends/libDatabase/MemoryDB.cpp
- src/depends/libDatabase/OverlayDB.cpp
- src/libData/AccountData/AccountStoreTrie.tpp
> [master] Update master to release-8.1 (MPT Commits)

- src/depends/libDatabase/LevelDB.cpp
- src/depends/libDatabase/MemoryDB.cpp
- src/depends/libDatabase/MemoryDB.h
- src/depends/libDatabase/OverlayDB.cpp
- src/libData/DataStructures/TraceableDB.cpp
- src/libPersistence/ContractStorage.cpp
> [release-8.1] Improved memory release and other minor bug fixes

- src/libData/DataStructures/TraceableDB.cpp
> [release-8.1] Fix memleak and force db compaction after each key delete

- docker/Dockerfile
- docker/Dockerfile.cuda
- src/libUtils/SWInfo.h
> [release-8.1] To v8.1.0-alpha.7

- src/cmd/data_migrate.cpp
- src/libData/AccountData/AccountStore.cpp
- src/libData/AccountData/AccountStore.h
- src/libPersistence/Retriever.cpp
- src/libPersistence/Retriever.h
Moveupdatetodisk after every N accounts of migration
> [release-8.1] Moveupdatetodisk after every N accounts of migration

- docker/Dockerfile
- docker/Dockerfile.cuda
- src/libUtils/SWInfo.h
> [release-8.1] To v8.1.0-alpha.8

- docker/Dockerfile
- docker/Dockerfile.cuda
- src/libUtils/SWInfo.h
> [release-8.1] To v8.1.0

- src/libDirectoryService/DSBlockPostProcessing.cpp
- src/libDirectoryService/FinalBlockPreProcessing.cpp
> [master] Add extra txn distribution time before FB consensus when no shard

- src/cmd/data_migrate.cpp
- src/libData/AccountData/AccountStore.cpp
- src/libData/AccountData/AccountStore.h
- src/libPersistence/Retriever.cpp
- src/libPersistence/Retriever.h
> [master] Moveupdatetodisk after every N accounts of migration

- src/depends/libDatabase/LevelDB.cpp
- src/depends/libDatabase/MemoryDB.cpp
- src/depends/libDatabase/MemoryDB.h
- src/depends/libDatabase/OverlayDB.cpp
- src/libData/DataStructures/TraceableDB.cpp
- src/libPersistence/ContractStorage.cpp
> [master] Improved memory release and other minor bug fixes

- src/libData/DataStructures/TraceableDB.cpp
> [master] Fix memleak and force db compaction after each key delete

- README.md
Update Zilliqa and Scilla release version.
> [master] Update release version v8.1.0

- src/libNode/DSBlockProcessing.cpp
> [master] Fix syncing issue if node is not part of shard

- scripts/upload_incr_DB.py
> [release-8.1] Fix corrupt base state due to timing issue

- docker/Dockerfile
- docker/Dockerfile.cuda
- src/libUtils/SWInfo.h
> [release-8.1] To v8.1.1

- README.md
- SECURITY.md
Our HackerOne bug bounty just went public. This PR updates the bug bounty link
> [master] Update bug bounty link

- scripts/upload_incr_DB.py
same as https://github.com/Zilliqa/Zilliqa/pull/2709
> [master] Fix corrupt base state due to timing issue

- src/cmd/isolated_server.cpp
- src/libServer/IsolatedServer.cpp
- src/libServer/IsolatedServer.h
> [release-8.1]  Add pause API in isolated server

- VERSION
- docker/Dockerfile
- docker/Dockerfile.cuda
> [release-8.1] To v8.1.1-isolated

- src/libPersistence/ContractStorage.cpp
- src/libServer/LookupServer.cpp
- src/libUtils/CommonUtils.cpp
> [release-8.1] Reduced logging of GetSmartContractState api request handler

- src/libPersistence/ContractStorage.cpp
- src/libServer/LookupServer.cpp
- src/libUtils/CommonUtils.cpp
same as https://github.com/Zilliqa/Zilliqa/pull/2725
> [master] Reduced logging of GetSmartContractState api request handler

- src/libServer/LookupServer.cpp
Only print the contract addresses associated with the account.
> [master] Remove contract states from GetSmartContractState

- src/libServer/LookupServer.cpp
> [release-8.1] Remove state from GetSmartContracts

- src/cmd/isolated_server.cpp
- src/libServer/IsolatedServer.cpp
- src/libServer/IsolatedServer.h
> [master] Add pause API in isolated server

- src/libServer/LookupServer.cpp
This PR addresses issue : https://github.com/Zilliqa/Issues/issues/752
> [release-8.1] Improve API GetSmartContracts to avoid holding primary mutex for long time

- src/libServer/LookupServer.cpp
Same as https://github.com/Zilliqa/Zilliqa/pull/2735
> [master] Improve API GetSmartContracts to avoid holding primary mutex for long time

- CMakeLists.txt
- src/cmd/CMakeLists.txt
- src/cmd/compress_persistence.cpp
```
$./compress_persistence --help
Options:
-h [ --help ]                         Print help messages
-p [ --db name ] arg (=/home/sandip/temp)
name of leveldb that resides in 
persistence folder and is to be 
compressed
```
To be ran with PWD same as where `persistence` folder exists.
> [master] command line utility to compress specific persistence db

- src/libData/AccountData/AccountStore.cpp
- src/libData/AccountData/AccountStore.h
- src/libServer/IsolatedServer.cpp
- src/libServer/LookupServer.cpp
- src/libServer/WebsocketServer.cpp
- src/libValidator/Validator.cpp
Release branch PR for  https://github.com/Zilliqa/Zilliqa/pull/2748
> [release 8.1] Prioritize DeserializeDelta call for AccountStore 

- src/libNode/PoWProcessing.cpp
Release PR for https://github.com/Zilliqa/Zilliqa/pull/2750
> [release-8.1] Individual POW submission to DS Committee

- constants.xml
- constants_local.xml
- src/common/Constants.cpp
- src/common/Constants.h
- src/libNode/Node.cpp
> Fix persistence validation failure due to missing Microblock

- docker/Dockerfile
- src/libData/AccountData/Account.cpp
- src/libData/AccountData/Account.h
- src/libData/AccountData/AccountStore.cpp
- src/libData/AccountData/AccountStoreBase.tpp
- src/libData/AccountData/AccountStoreSC.h
- src/libData/AccountData/AccountStoreSC.tpp
- src/libMessage/Messenger.cpp
- src/libUtils/ScillaUtils.cpp
- src/libUtils/ScillaUtils.h
Following issues are observed and fixed during scilla external library testing.
1) Return an error if the library has any syntax error as reported by the scilla checker.
2) Allow library calls to silently pass to scilla-checker if someone calls library address. Below is the slack discussion around it.
https://zilliqa-team.slack.com/archives/GCBRD8Z1B/p1638291802234700
3) Allow multiple external libraries to import in the contract. Earlier if the user imports more than one library in the contract then blockchain says "Library not found" for the second library.
4) Distinguish between a contract and a library. Below is the related discussion for the same.
https://zilliqa-team.slack.com/archives/GF28P7PRQ/p1638247188267500?thread_ts=1638181641.263200&cid=GF28P7PRQ
Below are the test cases …
> [master] Invoke scilla for external library call

- docker/Dockerfile
Changed the scilla image with the latest scilla master commit hash.
This is the latest master branch generated scilla docker image.
https://hub.docker.com/layers/zilliqa/scilla/4ca5930e/images/sha256-a9b712ea9dfe5dac6a28a2b7764ecc079a8771c023d5338fb777cdb858086847?context=explore
> [master] Update scilla image to latest master

- constants.xml
- constants_local.xml
- src/common/Constants.cpp
- src/common/Constants.h
- src/libNode/Node.cpp
> [master] Bypass validation for missing microblock

- src/libData/AccountData/AccountStore.cpp
- src/libData/AccountData/AccountStoreSC.tpp
- src/libServer/ScillaIPCServer.cpp
- src/libServer/ScillaIPCServer.h
Remove unused `m_rootHash` member variable.
Reference : https://github.com/Zilliqa/Issues/issues/762
> [master] Remove unused m_rootHash member variable and code references

- src/libData/AccountData/Account.h
Remove unused member variable `m_storage` from the code.
Reference: https://github.com/Zilliqa/Issues/issues/758
> [master] Remove unused m_storage member variable

- src/libData/AccountData/AccountStoreSC.h
https://github.com/Zilliqa/Issues/issues/761
> [master] Removed unused code

- src/libData/AccountData/AccountStore.cpp
- src/libData/AccountData/AccountStoreSC.h
- src/libData/AccountData/AccountStoreSC.tpp
- src/libServer/ScillaIPCServer.cpp
- src/libServer/ScillaIPCServer.h
- src/libUtils/ScillaUtils.cpp
- src/libUtils/ScillaUtils.h
References:
https://github.com/Zilliqa/scilla/pull/1056
https://github.com/Zilliqa/scilla-compiler/wiki/Interaction-with-Blockchain#blockchain-queries
Existing unit tests cover this.
> [master] Provide block number to Scilla via IPC instead of blockchain JSON

- scripts/download_incr_DB.py
> [master] Download historical db before persistence download

- ISOLATED_SERVER_setup.md
This PR updates the official Zilliqa JavaScript SDK repo name (`Zilliqa-JavaScript-Library` -> `zilliqa-js`).
https://github.com/Zilliqa/zilliqa-js
> [master] docs: Zilliqa-JavaScript-Library -> zilliqa-js

- .travis.yml
- docker/Dockerfile
- docker/Dockerfile.cuda
- src/libData/AccountData/Account.cpp
- src/libData/AccountData/Account.h
- src/libPersistence/ContractStorage.cpp
- tests/Data/Test_Contract.cpp
To support contract's codehash in Scilla IPC Server for https://github.com/Zilliqa/scilla/pull/1067
> [master] Support for contract's codehash in Scilla IPC Server

- scripts/ci_report_coverage.sh
> [master] Fix lcov report uploading to CodeCov

- scripts/ci_report_coverage.sh
> [release-8.2] Fix lcov report uploading to CodeCov

- .travis.yml
- VERSION
- docker/Dockerfile
- docker/Dockerfile.cuda
- src/libUtils/SWInfo.h
> [release-8.2] To Zilliqa v8.2.0-alpha.0 and Scilla v0.12.0-alpha.0

- .travis.yml
- docker/Dockerfile
- docker/Dockerfile.cuda
- src/libServer/ScillaIPCServer.cpp
- tests/Data/Test_Contract.cpp
Update scilla tag for travis and docker to `v0.12.0-alpha.1`
> [release-8.2] Support fetching of Chain ID in fetchBlockchainInfo in Scilla IPC server

- src/libData/AccountData/AccountStore.cpp
> [master] Notify cv for priority mutex for Account

- .travis.yml
- docker/Dockerfile
- docker/Dockerfile.cuda
- src/libUtils/SWInfo.h
> [release-8.2] To Zilliqa v8.2.0-alpha.1 and Scilla v0.12.0-alpha.2

- docker/Dockerfile
- docker/Dockerfile.cuda
This brings `release-8.2` branch on par with `release-8.1` branch at v8.1.1, with the exception of #2706
> [release-8.2] To Scilla v0.11.0

- constants.xml
- constants_local.xml
- src/cmd/isolated_server.cpp
- src/common/Constants.cpp
- src/common/Constants.h
- src/depends/safeserver/safehttpserver.cpp
- src/depends/safeserver/safehttpserver.h
- src/libNode/Node.cpp
- src/libServer/IsolatedServer.cpp
- src/libServer/IsolatedServer.h
This PR cherry-picks commits from `release-8.1` after the `v8.1.1` tag into `release-8.2`.
Here is the summary of commit cherry-picking along `release-8.1`:
| Commits in release-8.1 after v8.1.1 tag  | Cherry-picked? |
| ------------- | ------------- |
| Set timeout at start daemon for all connections (#2712) - e4d4b5aa85cc82e89189dc609ea7250d72fd3cae | Yes |
| add pausing facility (#2722) - 9b14817f939ac13f01a2637954d0ae3c900d82a3 | Yes |
| Reduced logging of GetSmartContractState api request handler (#2725) - 5ebb9b583fcedef38115840b32e5f638e9e4b54d | |
| remove contract states (#2728) - a955455950afcb6fc2bebbe0b3575e7f72a41172 | |
| Attempt to acquire read lock for each account to give other thread if any waiting to acquire write lock (#2735) - f6d850334b7956c50fd9500e3965983c76358eaa …
> [release-8.2] Cherry-pick commits from release-8.1 into release-8.2

- ISOLATED_SERVER_setup.md
- README.md
- SECURITY.md
- scripts/ci_report_coverage.sh
- src/cmd/isolated_server.cpp
- src/libConsensus/ConsensusBackup.cpp
- src/libConsensus/ConsensusBackup.h
- src/libConsensus/ConsensusCommon.cpp
- src/libConsensus/ConsensusCommon.h
- src/libConsensus/ConsensusLeader.cpp
- src/libConsensus/ConsensusLeader.h
- src/libDirectoryService/DSBlockPreProcessing.cpp
- src/libDirectoryService/FinalBlockPreProcessing.cpp
- src/libDirectoryService/ViewChangePreProcessing.cpp
- src/libMessage/Messenger.cpp
- src/libMessage/Messenger.h
- src/libMessage/ZilliqaMessage.proto
- src/libNode/MicroBlockPreProcessing.cpp
- src/libPersistence/Retriever.cpp
- src/libPersistence/Retriever.h
- src/libServer/IsolatedServer.cpp
- src/libServer/IsolatedServer.h
- tests/Message/Test_Messenger_Consensus.cpp
This PR cherry-picks commits from the following PRs into `release-8.2`.
- #2772
- #2776
- #2719
- #2774
( FYI these PRs are along `master` and done before `release-8.3` branch was made )
> [release-8.2] Cherry-pick commits from release-8.3 into release-8.2

- VERSION
- docker/Dockerfile
- src/libUtils/SWInfo.h
Following the renaming of `release-8.2` branch to `release-8.3`, this PR changes the version name from `v8.2.0-alpha.1` to `v8.3.0-alpha.0`
> [release-8.3] To v8.3.0-alpha.0

- src/libData/AccountData/AccountStoreSC.tpp
- src/libUtils/EvmJsonResponse.cpp
- src/libUtils/EvmJsonResponse.h
- src/libUtils/nlohmann/json.hpp
Because it is exactly key/value pairs.
> [evm_support_main] Rename AddressPair to KeyValue

- docker/Dockerfile
Rust needs to be build on an 18.04 enviornment otherwise it crashes when being tried to be used.
> [master] Fix rust building on devnet

- src/libData/AccountData/Account.cpp
- src/libNetwork/P2PComm.cpp
- src/libNode/FinalBlockProcessing.cpp
- src/libPersistence/Retriever.cpp
- src/libUtils/CMakeLists.txt
- src/libUtils/ProcessStats.cpp
- src/libUtils/ProcessStats.h
- src/libZilliqa/Zilliqa.cpp
Introduce sleep or extend sleep duration for long-running loops in code to prevent CPU starvation.
> [release-8.2] Fix CPU starvation during node start

- src/libData/AccountData/AccountStore.cpp
- src/libData/AccountData/AccountStoreSC.h
- src/libData/AccountData/AccountStoreSC.tpp
- src/libData/AccountData/TransactionReceipt.cpp
- src/libData/AccountData/TransactionReceipt.h
- src/libServer/IsolatedServer.cpp
- src/libServer/JSONConversion.cpp
- src/libServer/JSONConversion.h
- src/libServer/LookupServer.cpp
- src/libServer/LookupServer.h
- src/libUtils/EvmJsonResponse.cpp
- src/libUtils/EvmJsonResponse.h
1. GetEthCall for viewing calls
2. Handle Logs being added in the receipt
> [master] Get eth_call analogue working

- src/libData/AccountData/AccountStoreSC.tpp
- src/libData/AccountData/TransactionReceipt.cpp
- src/libData/AccountData/TransactionReceipt.h
- tests/Data/AccountData/Test_TransactionReceipt.cpp
fix the bug found in the enable_evm_call PR
Check the changes in the AccountsStoreSc.tpp in handling any json parse error
I realize that an error in parsing should result in a jsonrpc error response, but can not find at this moment how this should be done/handled. This is open for discussing.
> [master] #ZIL-4655 after pr fixes, changed the parse handeling

- src/libData/AccountData/AccountStoreSC.tpp
- src/libUtils/EvmJsonResponse.h
- src/libUtils/EvmUtils.cpp
- src/libUtils/EvmUtils.h
- tests/Utils/CMakeLists.txt
- tests/Utils/Test_EvmJsonResponse.cpp
Add test routines to EvmJsonResponse to highlight fture potential errors.
WIP but this is useful enough to add now as team working in this area.
> [master] Zil 4644 testroutines

- src/libServer/ScillaIPCServer.cpp
Fix base64 encoding of JSONRPC replies.
See also https://github.com/Zilliqa/evm-ds/pull/3
> [master] Fix base64 encoding for JSONRPC interface

- constants.xml
- src/common/Constants.cpp
- src/common/Constants.h
- src/libPOW/pow.h
- src/libServer/CMakeLists.txt
- src/libServer/IsolatedServer.cpp
- src/libServer/LookupServer.cpp
- src/libServer/LookupServer.h
- tests/EvmLookupServer/Test_EvmLookupServer.cpp
- tests/EvmLookupServer/constants.xml
Implementation of the Ethereum basics API messages in the LookupServer, see ticket ZIL-4373 for details
- [-] This is a breaking change
There are no integration test implemented in this branch
> [master] Zil 4673 implement basic ethereum api support into lookup server

- constants.xml
- docker/Dockerfile
- src/common/Constants.cpp
- src/common/Constants.h
- src/libData/AccountData/EvmClient.cpp
- tests/EvmLookupServer/constants.xml
> [master] Add configurable logging for the EVM

- src/libData/AccountData/AccountStoreSC.tpp
- src/libData/AccountData/EvmClient.cpp
- src/libData/AccountData/EvmClient.h
Hi priority fix to solve reliability issues encoutered on the recent devnet deployment.
To remove possibility of a deadlock occuring when a transaction fails inflight between any client and all subsequent hops.
To better handle connection errors to EVM-DS and minimise unneccassary restarts.
Addresses the repeatable error as described in Jira 4679
- [ x] This is not a breaking change
upgrade evm-ds , evm_ds_test and Zilliqa.
Pay special attention to the new settings for evm-ds regarding the log file placement, works fine for for devnet and testnet
requires customising for local tests.
This is an interim fix with a hardcoded timeout fo 30000 milliseconds on evm-ds calls, this can be made configurable but was hardcoded as the fix is urgent so not to block further testing.
Follow instructions …
> [master] To reproduce with the Isolated Server.

- CMakeLists.txt
- src/cmd/CMakeLists.txt
- src/cmd/compress_persistence.cpp
> [release-8.2] compress specific leveldb in persistence

- src/libServer/IsolatedServer.cpp
- src/libServer/LookupServer.cpp
- src/libServer/LookupServer.h
- tests/EvmLookupServer/Test_EvmLookupServer.cpp
Implementation of two uncle-related eth calls. Also minor refactor to EVM test suite (reduces code repetitions). 
There are not integration tests implemented.
> [master] Adding eth-uncle related calls

- docker/Dockerfile
- docker/Dockerfile.cuda
- src/libUtils/SWInfo.h
> [release-8.1.2] To v8.12

- README.md
> [master] Update readme with latest v8.1.2 tag

- docker/Dockerfile
Bump the bundled evm-ds version
> [master] Bump the evm-ds version bundled with the image

- src/libServer/JSONConversion.cpp
- src/libServer/LookupServer.cpp
- tests/EvmLookupServer/Test_EvmLookupServer.cpp
This PR adds tests and fixes minor issues that came out during testing.
> [master] Eth get block by num tests

- docker/Dockerfile
> [master] Bump the EVM-DS dependency

- src/libServer/LookupServer.cpp
> [master] Fix an error message when target account doesn't exist

- README.md
- docker/Dockerfile
- src/libData/AccountData/AccountStoreSC.tpp
- src/libUtils/EvmUtils.cpp
This PR fixes multiple problems related to contracts creating other contracts.
> [master] Fix constructor value sending and contracts creating contracts

- src/libServer/LookupServer.cpp
- tests/EvmLookupServer/Test_EvmLookupServer.cpp
This PR adds support for queries using TAGs (earliest, pending, latest). Test locally with unit tests.
[X] This is not a breaking change
> [master] Adding support for retrieving block by tag

- .travis.yml
- docker/Dockerfile
- docker/Dockerfile.cuda
- src/libData/AccountData/Account.cpp
- src/libData/AccountData/Account.h
- src/libData/AccountData/AccountStore.cpp
- src/libData/AccountData/AccountStoreSC.h
- src/libData/AccountData/AccountStoreSC.tpp
- src/libPersistence/ContractStorage.cpp
- src/libServer/ScillaIPCServer.cpp
- src/libServer/ScillaIPCServer.h
- src/libUtils/ScillaUtils.cpp
- src/libUtils/ScillaUtils.h
- tests/Data/Test_Contract.cpp
- tests/Server/Test_ScillaIPCServer.cpp
Following PRs have been cherry-picked from the `release-8.3` branch.
https://github.com/Zilliqa/Zilliqa/pull/2757/files
https://github.com/Zilliqa/Zilliqa/pull/2773/files
https://github.com/Zilliqa/Zilliqa/pull/2775/files
https://github.com/Zilliqa/Zilliqa/pull/2779/files
> [release/v8.2]  Cherrypick PR for the blockchain release v8.2.0

- scripts/download_incr_DB.py
> [release/v8.2] Download historical data before actual persistence download

- docker/Dockerfile
- docker/Dockerfile.cuda
- src/libUtils/SWInfo.h
Tag the alpha release - `v.8.2.0rc0`
> [release/v8.2] To v.8.2.0rc0

- src/libServer/IsolatedServer.cpp
- src/libServer/LookupServer.cpp
- src/libServer/LookupServer.h
- tests/EvmLookupServer/Test_EvmLookupServer.cpp
This PR adds new eth calls for getting transactions from block by specifying index. Tested locally with unit tests.
> [master] Another two eth calls for getting tx from block

- src/libCrypto/EthCrypto.cpp
> [master] Fix handling of R and S in signature verification

- src/libEth/Eth.cpp
- src/libEth/Eth.h
- src/libServer/IsolatedServer.cpp
- src/libServer/IsolatedServer.h
- src/libServer/JSONConversion.cpp
- src/libServer/LookupServer.cpp
- src/libServer/LookupServer.h
- tests/EvmLookupServer/Test_EvmLookupServer.cpp
This PR fixes a couple of minor issues that ethers complained about. Tested locally with ethers and isolated server.
> [master] Make ethers happy

- src/libCrypto/EthCrypto.cpp
If you set the chainID to 0 or 1 you can get a confusing message when attempting pub key recover - this is less confusing.
> [master] Tweak incorrect chain ID string

- src/cmd/genTxnBodiesFromS3.cpp
- src/libData/AccountData/Account.cpp
- src/libData/AccountData/AccountStore.cpp
- src/libData/AccountData/AccountStoreAtomic.cpp
- src/libData/AccountData/AccountStoreBase.cpp
- src/libData/AccountData/AccountStoreBase.h
- src/libData/AccountData/AccountStoreSC.cpp
- src/libData/AccountData/AccountStoreSC.h
- src/libData/AccountData/AccountStoreTrie.cpp
- src/libData/AccountData/AccountStoreTrie.h
- src/libData/AccountData/CMakeLists.txt
- src/libDirectoryService/Coinbase.cpp
- src/libDirectoryService/GasPricer.cpp
- src/libLookup/Lookup.cpp
- src/libMessage/Messenger.cpp
- src/libMessage/MessengerAccountStoreBase.cpp
- src/libMessage/MessengerAccountStoreTrie.cpp
- src/libNode/MicroBlockPreProcessing.cpp
- src/libNode/Node.cpp
- src/libPersistence/BlockStorage.cpp
- src/libServer/LookupServer.cpp
- src/libUtils/TimestampVerifier.h
Most of the change is actually recovering #includes lost because of lack of transitive includes from the removed .tpp
> [master] Move templates from .tpp to .cpp with explicit instantiation

- .travis.yml
- ci_script.sh
- scripts/ci_build.sh
- scripts/integration_test.sh
- tests/EvmLookupServer/Test_EvmLookupServer.cpp
> [master] feat: move the process from Travis to Jenkins

- src/libServer/JSONConversion.cpp
> [master] Change representation of nonce and gas fields in response of eth calls

- src/libEth/Eth.cpp
- src/libEth/Eth.h
- src/libServer/JSONConversion.cpp
- src/libServer/LookupServer.cpp
- tests/EvmLookupServer/Test_EvmLookupServer.cpp
This PR fixes transaction receipt in case of contract deployment (contractAddress field should provide created contract address). Also there are a few fixes for returned block json. Tested on isolated server.
> [master] Fixing receipt for contract deployment

- src/libCrypto/EthCrypto.cpp
> [master] Fix the signature verification error

- src/libServer/JSONConversion.cpp
Minor fixes ethers complained about. Tested on isolated server.
> [master] Minor ethers-js fixes

- src/libCrypto/EthCrypto.cpp
- src/libCrypto/EthCrypto.h
- src/libData/AccountData/Account.cpp
- src/libServer/JSONConversion.cpp
> [master] Strip the EVM prefix in JSONRPC transaction response and in code hash

- tests/EvmAcceptanceTests/helper/ZilliqaHelper.js
- tests/EvmAcceptanceTests/test/ContractDeployment.js
> [master] Remove to field from transaction request in order to fix unable to verify error

- scripts/license_checker.sh
- tests/evm_ds_test/.gitignore
- tests/evm_ds_test/README.md
- tests/evm_ds_test/evm_ds_test/__init__.py
- tests/evm_ds_test/evm_ds_test/api.py
- tests/evm_ds_test/evm_ds_test/test_case.py
- tests/evm_ds_test/evm_ds_test/utils.py
- tests/evm_ds_test/pyproject.toml
- tests/evm_ds_test/run_test_loop.sh
- tests/evm_ds_test/scripts/fund_accounts.py
- tests/evm_ds_test/tests/__init__.py
- tests/evm_ds_test/tests/conftest.py
- tests/evm_ds_test/tests/contracts/ERC20.sol
- tests/evm_ds_test/tests/test_contract_install.py
- tests/evm_ds_test/tests/test_erc20.py
- tests/evm_ds_test/tests/test_evm_ds_test.py
- tests/evm_ds_test/tests/test_parent_child.py
- tests/evm_ds_test/tests/test_revert.py
- tests/evm_ds_test/tests/test_transfer.py
Move `evm_ds_test` to the main repository. After this is merged, the `evm_ds_test` repo will be deprecated.
> [master] Add evm_ds_test to the main repository

- docker/Dockerfile
Followup to the PR merging the repositories
> [master] Build EVM-DS from this repo on the builder node

- src/libData/AccountData/EvmClient.cpp
- src/libEth/Eth.cpp
- src/libEth/Eth.h
- src/libServer/JSONConversion.cpp
- src/libServer/LookupServer.cpp
- tests/EvmLookupServer/Test_EvmLookupServer.cpp
> [master] Fixing eth_getTransactionRecipe and minor fixes

- Jenkinsfile
- scripts/jenkins_pipeline.sh
- scripts/setup_environment.sh
> [master] feat: add Jenkins pipeline

- src/libServer/IsolatedServer.cpp
- src/libServer/IsolatedServer.h
- src/libServer/JSONConversion.cpp
- src/libServer/LookupServer.cpp
- src/libServer/LookupServer.h
- tests/EvmLookupServer/Test_EvmLookupServer.cpp
This PR fixes some type incompatibilities for API call responses. Also, missing feature of getBlockBy* calls has been implemented when caller queries for full transaction inclusion. 
A few calls were registered previously twice (hence some removals are present).
> [master] Fix some eth incompatibilities

- tests/EvmAcceptanceTests/hardhat.config.js
- tests/EvmAcceptanceTests/test/ContractDeployment.js
> [master] Change the default test network to ganache

- Jenkinsfile
> [master] chore: pipeline cosmetics

- tests/evm_ds_test/evm_ds_test/test_case.py
> Bump RPC timeout for evm_ds_test

- tests/EvmAcceptanceTests/helper/ZilliqaHelper.js
- tests/EvmAcceptanceTests/test/ContractDeployment.js
> [master] Get rid of zilliqa js dependency in evm acceptance tests

- tests/EvmAcceptanceTests/hardhat.config.js
- tests/EvmAcceptanceTests/helper/GeneralHelper.js
- tests/EvmAcceptanceTests/helper/Web3Helper.js
- tests/EvmAcceptanceTests/helper/ZilliqaHelper.js
- tests/EvmAcceptanceTests/test/ContractDeployment.js
> [master] Skip zilliqa helper tests when ganache is selected.

- Jenkinsfile
> [master] fix: Jenkins agents node selector

- tests/EvmAcceptanceTests/start_ganache.sh
- tests/EvmAcceptanceTests/test/rpc/eth_syncing.js
> [master] ZIL-4760 add test for getting the syncing state

- docker/Dockerfile
- docker/Dockerfile.cuda
- src/libUtils/SWInfo.h
> [release/v8.2] To v.8.2.0rc1

- src/libServer/IsolatedServer.cpp
- src/libServer/LookupServer.h
- tests/EvmAcceptanceTests/hardhat.config.js
- tests/EvmAcceptanceTests/test/rpc/eth_sendTransaction.js
- tests/EvmAcceptanceTests/test/rpc/eth_sign.js
- tests/EvmAcceptanceTests/test/rpc/eth_signTransaction.js
Test implementation for the non supported eth api calls:
- eth_sign
- eth_signTransaction
- eth_sendTransaction
- removed the interfaces in the lookup server etc.
> [master] Zil 4740 add eth sign test

- src/libServer/GetWorkServer.h
- src/libServer/LookupServer.cpp
- tests/EvmAcceptanceTests/hardhat.config.js
- tests/EvmAcceptanceTests/helper/GeneralHelper.js
- tests/EvmAcceptanceTests/start_ganache.sh
- tests/EvmAcceptanceTests/test/rpc/eth_mining.js
Added js test for eth api call eth_mining.
> [master] Zil 4761 add eth mining test

- CMakeLists.txt
- README.md
- cmake/InstallJsonrpccpp.cmake
- docker/Dockerfile
> [master] ZIL-4805: re-add libssl-dev

- CMakeLists.txt
- README.md
- cmake/InstallJsonrpccpp.cmake
- docker/Dockerfile
> [master] ZIL-4805: add libssl-dev

- docker/Dockerfile
> [master] ZIL-4805: fixed Dockerfile - missin REGISTRY parameter in FROM

- Jenkinsfile
> [master] limit build pod storage to 20GB

- tests/evm_ds_test/evm_ds_test/test_case.py
- tests/evm_ds_test/tests/test_transfer.py
> [master] Yet another fix due to high gas prices before scaling fix

- src/common/Constants.cpp
- src/libServer/IsolatedServer.cpp
- src/libServer/LookupServer.cpp
- src/libServer/LookupServer.h
- src/libUtils/GasConv.h
- tests/EvmLookupServer/Test_EvmLookupServer.cpp
- tests/evm_ds_test/evm_ds_test/test_case.py
This PR fixes some issues found out during testing.
> [master] Fix eth gas price

- src/libServer/LookupServer.cpp
In certain conditions the gas was returned as decimal rather than hex - fix this.
> [master] Bugfix for tx receipt cum gas

- src/libServer/JSONConversion.cpp
- src/libServer/LookupServer.cpp
- tests/EvmLookupServer/Test_EvmLookupServer.cpp
- tests/evm_ds_test/scripts/fund_accounts.py
> [master] fix tests and clang-format

- src/libServer/LookupServer.cpp
Support all tags, including numerical refernces to blocks. But execute only at the latest block.
> [master] Fix eth_call

- src/libServer/LookupServer.cpp
> [master] GetBlockByTransactionHash lookup only 5 blocks

- constants.xml
- src/common/Constants.cpp
- src/common/Constants.h
- src/libServer/LookupServer.cpp
- tests/EvmLookupServer/constants.xml
> [master] Make configurable EVM_BLOCK_LOOKUP_LIMIT

- src/libServer/LookupServer.cpp
- src/libServer/LookupServer.h
Block number is already present in receipt, it should be used as is.
> [master] Get block number directly from receipt

- src/libServer/LookupServer.cpp
Epoch number is kept as string.
> [master] Epoch number is kept as string

- src/libData/AccountData/Transaction.cpp
- src/libServer/JSONConversion.cpp
> [master] Fix gas scaling

- docker/Dockerfile
- docker/Dockerfile.cuda
- src/libUtils/SWInfo.h
> [release/v8.2] To v.8.2.0rc2

- src/libServer/LookupServer.h
Increase the default Gas estimate to make most transactions pass by default, even if more expensive
> [master] Increase the default Gas estimate

- constants.xml
- src/common/Constants.h
- tests/EvmLookupServer/constants.xml
> [master] Cleanup constants

- src/libServer/LookupServer.cpp
> [master] Fix parsing of incoming gas value for eth_call

- tests/EvmAcceptanceTests/test/rpc/eth_coinbase.js
> [master] ZIL4762 eth_coinbase test with default values

- src/libServer/IsolatedServer.cpp
- tests/EvmAcceptanceTests/test/rpc/eth_blockNumber.js
> [master] ZIL-4730 added test for get block number

- src/libCrypto/EthCrypto.cpp
- src/libCrypto/EthCrypto.h
- src/libData/AccountData/Transaction.cpp
- src/libServer/JSONConversion.cpp
Re-use the functions in EthCrypto. Tests to follow.
> [master] vrs add to signature

- evm-ds/src/main.rs
> [master] improved EVM logging

- src/libUtils/EvmJsonResponse.cpp
> [master] Attempting to fix JSON conversion

- cmake/InstallJsonrpccpp.cmake
- src/libConsensus/ConsensusLeader.cpp
- src/libCrypto/EthCrypto.cpp
- src/libData/AccountData/AccountStoreSC.cpp
- src/libNetwork/P2PComm.cpp
- src/libPersistence/BlockStorage.cpp
- src/libUtils/GetTxnFromFile.h
- tests/Data/AccountData/Test_AccountStore.cpp
- tests/Data/Test_TxnOrder.cpp
- tests/EvmLookupServer/Test_EvmLookupServer.cpp
> [master] ZIL-4807: support compilation on clang

- tests/EvmAcceptanceTests/contracts/Deployment.sol
- tests/EvmAcceptanceTests/helper/Web3Helper.js
- tests/EvmAcceptanceTests/helper/ZilliqaHelper.js
- tests/EvmAcceptanceTests/test/ContractDeployment.js
This PR adds web3-js coverage for contract deployment tests. I decided to rewrite a bit web3j helper which should be more convenient to use now hopefully.
> [master] Adding missing web3 contract deployment tests

- scripts/integration_test.sh
- src/libData/AccountData/Transaction.cpp
- src/libPersistence/BlockStorage.cpp
- src/libServer/LookupServer.cpp
- tests/EvmLookupServer/Test_EvmLookupServer.cpp
One of the tests in evm server fails and was merged to master - comments are inline
> [master] Fix broken test in master

- src/libServer/LookupServer.cpp
- src/libServer/LookupServer.h
- tests/EvmAcceptanceTests/test/rpc/eth_gasPrice.js
- tests/EvmAcceptanceTests/test/rpc/eth_sendTransaction.js
- tests/EvmAcceptanceTests/test/rpc/eth_sign.js
- tests/EvmAcceptanceTests/test/rpc/eth_signTransaction.js
- tests/EvmAcceptanceTests/test/rpc/net_version.js
fix the js test outcome and expectations so that most RPC tests not fail
> [master] fix test outcome

- tests/EvmLookupServer/Test_EvmLookupServer.cpp
> [master] fix broken tests

- docker/Dockerfile
- src/libPOW/CMakeLists.txt
- src/libServer/CMakeLists.txt
- src/libUtils/CMakeLists.txt
- tests/POW/CMakeLists.txt
2. Don't re-compile cryptoutils in dependencies each time.
> [master] ZIL-4688: fix missing pip3

- .travis.yml
- tests/EvmLookupServer/Test_EvmLookupServer.cpp
Travis always passes. This makes it such that it does not always pass if your tests fail. You can see here if you look at the commits I make travis fail when the test fails (when before it passes). Changing ; to && fixes this
> [master] Fix travis test issue

- CMakeLists.txt
- src/libPythonRunner/CMakeLists.txt
- src/libUtils/CMakeLists.txt
> [master] ZIL-4694: let CMake find Python with PythonLib instead of Python3

- tests/EvmAcceptanceTests/README.md
- tests/EvmAcceptanceTests/helper/GeneralHelper.js
- tests/EvmAcceptanceTests/helper/Web3Helper.js
- tests/EvmAcceptanceTests/helper/ZilliqaHelper.js
- tests/EvmAcceptanceTests/test/ContractDeployment.js
- tests/EvmAcceptanceTests/test/ContractDestruction.js
- tests/EvmAcceptanceTests/test/ContractInteraction.js
- tests/EvmAcceptanceTests/test/rpc/eth_blockNumber.js
- tests/EvmAcceptanceTests/test/rpc/eth_chainId.js
- tests/EvmAcceptanceTests/test/rpc/eth_coinbase.js
- tests/EvmAcceptanceTests/test/rpc/eth_estimateGas.js
- tests/EvmAcceptanceTests/test/rpc/eth_gasPrice.js
- tests/EvmAcceptanceTests/test/rpc/eth_getBalance.js
- tests/EvmAcceptanceTests/test/rpc/eth_getTransactionCount.js
- tests/EvmAcceptanceTests/test/rpc/eth_getTransactionReceipt.js
- tests/EvmAcceptanceTests/test/rpc/eth_getUncleByBlockHashAndIndex.js
- tests/EvmAcceptanceTests/test/rpc/eth_getUncleByBlockNumberAndIndex .js
- tests/EvmAcceptanceTests/test/rpc/eth_mining.js
- tests/EvmAcceptanceTests/test/rpc/eth_protocolVersion.js
- tests/EvmAcceptanceTests/test/rpc/eth_sendRawTransaction.js
- tests/EvmAcceptanceTests/test/rpc/eth_sendTransaction.js
- tests/EvmAcceptanceTests/test/rpc/eth_sign.js
- tests/EvmAcceptanceTests/test/rpc/eth_signTransaction.js
- tests/EvmAcceptanceTests/test/rpc/eth_syncing.js
- tests/EvmAcceptanceTests/test/rpc/net_listening.js
- tests/EvmAcceptanceTests/test/rpc/net_peerCount.js
- tests/EvmAcceptanceTests/test/rpc/net_version.js
- tests/EvmAcceptanceTests/test/rpc/web3_clientVersion.js
- tests/EvmAcceptanceTests/test/rpc/web3_sha3.js
It formats JS code according to defined rules.
> [master] Formatting js code

- Jenkinsfile
> fix: [skip ci] PR skip ci ignored in a feature branch

- tests/EvmAcceptanceTests/.eslintrc.json
- tests/EvmAcceptanceTests/helper/ZilliqaHelper.js
- tests/EvmAcceptanceTests/test/ContractDeployment.js
- tests/EvmAcceptanceTests/test/ContractInteraction.js
- tests/EvmAcceptanceTests/test/rpc/eth_getBalance.js
- tests/EvmAcceptanceTests/test/rpc/eth_getTransactionCount.js
- tests/EvmAcceptanceTests/test/rpc/eth_getTransactionReceipt.js
- tests/EvmAcceptanceTests/test/rpc/eth_sendRawTransaction.js
> [master] Refactor and fix Zilliqa helper class and related tests

- evm-ds/src/scillabackend.rs
- src/libServer/ScillaIPCServer.cpp
Mostly add forgotten fetchBlockchainInfo JSONRPC binding. Also fix the Rust call for gasprice and timestamp.
> [master] Fetch blockchain info fixes

- src/libServer/EthRpcMethods.cpp
> [master] Make ethers.js happy with transaction hash.

- Jenkinsfile
> [skip ci]: fix the pod limits definition

- evm-ds/src/scillabackend.rs
We shouldn't worry about what the right timeout is, as this mechanism will go away eventually.
> [master] On DevNets, things are not as fast, need to bump the timeout

- src/libServer/ScillaIPCServer.cpp
- tests/evm_ds_test/tests/contracts/bcinfo.sol
- tests/evm_ds_test/tests/test_bcinfo.py
Remove calling the method that crashes the node for now. Making the crash more benign until fixed.
> [master] Test BCInfo [skip ci]

- src/libEth/Eth.cpp
Adding missing logIndex (currently set to 0) in logs fields.
> Adding hardcoded logIndex [skip ci]

- tests/EvmAcceptanceTests/helper/Web3Helper.js
- tests/EvmAcceptanceTests/test/ContractDeployment.js
> Fix one failing test of web3.js [skip ci]

- src/libEth/Eth.cpp
- src/libEth/Eth.h
- src/libServer/EthRpcMethods.cpp
Adds logIndex to exposed logs which is required by ethers.
> Fix log index

- Jenkinsfile
> [master] chore: improve pipeline error messages ([skip ci])

- scripts/ci_make_deps_image.sh
> [master] feat: DEVOPS-239 move the dependencies image to DockerHub

- Jenkinsfile
> [skip ci] do not consider CHANGE_TITLE if in a feature branch

- tests/EvmAcceptanceTests/contracts/Precompiles.sol
- tests/EvmAcceptanceTests/test/precompiles/EvmPrecompiles.js
This PR adds acceptance test for `ecrecover` rust evm precompile.
> Adding test for ecrecover precompile

- src/cmd/isolated_server.cpp
- tests/EvmAcceptanceTests/test/rpc/eth_getBlockByNumber.js
> [master] ZIL-4874 revert block number '0' and fix getBlockByNumber tests

- tests/EvmAcceptanceTests/contracts/ERC20.sol
- tests/EvmAcceptanceTests/hardhat.config.js
- tests/EvmAcceptanceTests/start_ganache.sh
- tests/EvmAcceptanceTests/test/Erc20.js
- tests/EvmAcceptanceTests/test/precompiles/EvmPrecompiles.js
> Move erc20 tests from evm-ds-tests to integration tests [skip ci]

- src/libData/AccountData/AccountStoreSC.h
- src/libData/AccountData/AccountStoreSCEvm.cpp
- src/libServer/EthRpcMethods.cpp
- src/libServer/EthRpcMethods.h
- src/libUtils/EvmJsonResponse.cpp
- tests/EvmAcceptanceTests/contracts/Revert.sol
- tests/EvmAcceptanceTests/helper/Web3Helper.js
- tests/EvmAcceptanceTests/test/ContractRevert.js
- tests/EvmLookupServer/Test_EvmLookupServer.cpp
Saeed check the test code
Steve check the lookupserver code changes
> [master] Zil 4827 evm reverts do not have correct error handling

- tests/EvmAcceptanceTests/helper/Web3Helper.js
- tests/EvmAcceptanceTests/test/ParentChild.js
> Move parent-child tests from evm-ds-test to js tests [skip ci]

- .husky/pre-commit
- tests/EvmAcceptanceTests/README.md
- tests/EvmAcceptanceTests/contracts/ForwardZil.sol
- tests/EvmAcceptanceTests/test/Transfer.js
> [master] Move transfer tests from evm-ds-tests to js test [skip ci]

- tests/EvmAcceptanceTests/test/ContractDeployment.js
> [master] Add remaining tests of Contract Deployment

- tests/EvmAcceptanceTests/contracts/Interaction.sol
- tests/EvmAcceptanceTests/test/ContractInteraction.js
> [master] Add remaining tests of contract interactions.

- evm-ds/Cargo.lock
- evm-ds/Cargo.toml
- evm-ds/src/precompiles/ec.rs
- evm-ds/src/precompiles/mod.rs
- tests/EvmAcceptanceTests/contracts/Precompiles.sol
- tests/EvmAcceptanceTests/test/precompiles/EvmPrecompiles.js
Add more precompiled contracts to `evm-ds`.
> [master] ZIL-4892: Implement `ec{Add,Mul,Pairing}` precompiled contracts

- src/libData/AccountData/EvmClient.cpp
Send die command to evm to tell evm to close down gracefully, if this collects an exception then resort to brute force approach of killing the task with a pkill as we did in previous generations.
Try to gracefully close the evm engine, if this fails then shoot it with a pkill
fix the unit tests from hanging in 8.3 release candidate,
- [ x] This is a breaking change
> [master] ZIL-4894-unit-tests-hang-on-latest-master

- tests/EvmAcceptanceTests/test/ContractDeployment.js
- tests/EvmAcceptanceTests/test/ContractInteraction.js
- tests/EvmAcceptanceTests/test/ParentChild.js
> [master] Change raw matchers to hardhat chai matchers.

- tests/EvmAcceptanceTests/README.md
- tests/EvmAcceptanceTests/hardhat.config.js
- tests/EvmAcceptanceTests/scripts/FeedDevnet.js
> Add FeedDevnet.js script to tests[skip ci]

- src/libData/AccountData/AccountStoreSCEvm.cpp
- src/libUtils/EvmJsonResponse.cpp
- tests/EvmAcceptanceTests/test/ParentChild.js
This PR fixes an issue with json parsing that skipped delete action returned from evm. 
Part of a bigger json parsing code has been moved to different function too.
It also seems that RemoveAccount doesn't work - for now the balance of the destructed contract is deliberately set to 0 in case parent contract destructs child contract and - as a result - receives child's funds over and over.
> Fixing ParentChild tests

- src/libUtils/DetachedFunction.h
- src/libUtils/JoinableFunction.h
- src/libUtils/TimeLockedFunction.h
std::result_of -> std::invoke_result to fix building on Mac with C++17.
> [master] ZIL-4676: fix C++17 Mac build.

- tests/EvmAcceptanceTests/test/Transfer.js
> [master] Fix one failing test of Transfer scenario.

- src/libServer/EthRpcMethods.cpp
- tests/EvmAcceptanceTests/hardhat.config.js
- tests/EvmAcceptanceTests/test/ParentChild.js
- tests/EvmAcceptanceTests/test/rpc/eth_sendRawTransaction.js
> [master] Zil 4910 make integration tests work against the evmdev

- build.sh
Also wrap conditions into 'if' statements to the script return code is 0 on success.
> [master] Skip check_guard.sh on OS X, as it seems to be failing

- evm-ds/src/main.rs
- src/libServer/EthRpcMethods.cpp
- src/libServer/EthRpcMethods.h
- src/libUtils/EvmCallParameters.h
- src/libUtils/EvmUtils.cpp
- tests/EvmAcceptanceTests/contracts/ERC20.sol
- tests/EvmAcceptanceTests/helper/Web3Helper.js
- tests/EvmAcceptanceTests/test/Erc20.js
- tests/EvmAcceptanceTests/test/GasEstimations.js
- tests/EvmLookupServer/Test_EvmLookupServer.cpp
Adding eth_estimateGas functionality (that reverts in case of calling failing contract methods).
> [master] Adding eth_estimateGas

- src/cmd/validateDB.cpp
- src/libCrypto/CMakeLists.txt
- src/libPersistence/BlockStorage.cpp
> [release/v8.3] Use std::unique_ptr to manage the lifetime of LevelDB itereators

- tests/EvmAcceptanceTests/contracts/ERC20.sol
- tests/EvmAcceptanceTests/test/Erc20.js
> [master] Revert erc20 contract changes

- tests/EvmAcceptanceTests/test/Erc20.js
> [master] Fix ERC20 test.

- tests/EvmAcceptanceTests/contracts/openzeppelin/access-control/RoleBased.sol
- tests/EvmAcceptanceTests/test/openzeppelin/access-control/RoleBased.js
> [master] Add openzeppelin role based contract tests

- src/libData/AccountData/AccountStoreSCEvm.cpp
- src/libData/AccountData/CMakeLists.txt
- src/libEth/CMakeLists.txt
- src/libEth/Eth.cpp
- src/libEth/Eth.h
- src/libEth/utils/EthUtils.cpp
- src/libEth/utils/EthUtils.h
- src/libServer/EthRpcMethods.cpp
- src/libServer/IsolatedServer.cpp
It seems that evm-ds doesn't take into account cost related to contract deployment (code cost, account creation cost, etc). 
I added new method that considers calldata fee and new account cost (both defined in yellow paper). 
Overall gas usage is now adjusted based on total cost, not only EVM gas consumption.
Worth noting is that in case of contract calls evm-ds consumes proper amounts of gas (e.g. deploying new contracts via create/create2).
> [master] Gas estimation fixes

- src/libData/AccountData/AccountStoreSC.h
- src/libData/AccountData/AccountStoreSCEvm.cpp
- vcpkg.json
Removed another unused variable that was a hangover from the scilla origin.
Cleanup
- [ x] This is a breaking change
> [master] Lambda unused variable removed and removed version parameter entirely.

- src/libData/AccountData/Account.cpp
- src/libData/AccountData/Account.h
- src/libData/AccountData/AccountStore.cpp
- src/libData/AccountData/AccountStoreBase.cpp
- src/libData/AccountData/AccountStoreSC.cpp
- src/libData/AccountData/AccountStoreSC.h
- src/libMessage/Messenger.cpp
- src/libUtils/ScillaUtils.cpp
- src/libUtils/ScillaUtils.h
Cherrypick #3019 from `release/v8.2` into `release/v8.3` branch.
> [release/v8.3] Cherrypick/zil 4699 scilla external library v8.3

- src/libServer/EthRpcMethods.cpp
It looks account exists with an address having all zeros. There are similar checks in other places checking the same thing so this has been just missed here.
> [master] Debug estimate gas

- src/libEth/Eth.cpp
What it says in the title. We still store contracts as HEX with EVM prefix.
> [master] Fix contract size check

- src/libServer/EthRpcMethods.cpp
Wrapping with try/catch blocks. In other cases, converting directly to uint_xxx types (which don't throw due to `unchecked` parameter passed to a template).
> [master] Fixing temporarily stoul usage

- src/libData/AccountData/AccountStoreSCEvm.cpp
- src/libEth/filters/FiltersUtils.cpp
- src/libPersistence/BlockStorage.cpp
- src/libServer/EthRpcMethods.cpp
- src/libUtils/DataConversion.h
Adding two helpers for basic unsinged and boost types. They allow for optional fallback otherwise throw. 
Only replaced usage in places we touched.
> [master] Adding strToInt helpers

- evm-ds/src/precompiles/blake2.rs
- evm-ds/src/precompiles/mod.rs
- tests/EvmAcceptanceTests/contracts/Precompiles.sol
- tests/EvmAcceptanceTests/test/precompiles/EvmPrecompiles.js
> [master] Add blake2 precompile

- tests/EvmAcceptanceTests/contracts/Storage.sol
- tests/EvmAcceptanceTests/test/rpc/eth_getStorageAt.js
> [master] Add eth_getStorageAt tests

- src/libEth/filters/BlocksCache.cpp
- src/libEth/filters/FiltersUtils.cpp
- src/libEth/filters/SubscriptionsImpl.cpp
A few fixes allowing for successful event responses.
> [master] Fixing subscriptions

- docs/persistence.md
- src/libData/BlockChainData/BlockLinkChain.cpp
Add some documentation for what we store in persistence.
Note that the document isn't complete, but I figured its better to merge something incomplete than nothing at all.
> [master] ZIL-4948: Persistence documentation

- src/libNetwork/P2PComm.cpp
> [release/v8.2] Strict blacklist the node if IP is changed

- evm-ds/src/main.rs
- evm-ds/src/precompiles/blake2.rs
- evm-ds/src/precompiles/mod.rs
- evm-ds/src/scillabackend.rs
> [master] Run cargo fmt on evm-ds

- src/libServer/EthRpcMethods.cpp
- src/libUtils/EvmJsonResponse.cpp
- src/libUtils/EvmJsonResponse.h
- tests/EvmAcceptanceTests/contracts/Revert.sol
- tests/EvmAcceptanceTests/test/ContractRevert.js
- tests/EvmAcceptanceTests/test/openzeppelin/access-control/Ownable.js
- tests/EvmAcceptanceTests/test/openzeppelin/access-control/RoleBased.js
- tests/EvmAcceptanceTests/test/openzeppelin/tokens/ERC20.js
- tests/EvmLookupServer/Test_EvmLookupServer.cpp
> [master] Handling Reverts specially to provide more compatible error handling

- src/libServer/LookupServer.cpp
We also need to decrement the nonce for Zil-style transactions before calculating contract addresses.
> [master] ZIL-4967: Fix Zil contract address calculation

- src/libData/AccountData/AccountStore.cpp
- src/libData/AccountData/AccountStoreSCEvm.cpp
- src/libServer/EthRpcMethods.cpp
- tests/EvmAcceptanceTests/contracts/ForwardZil.sol
- tests/EvmAcceptanceTests/test/Transfer.js
> [master] Fix simple send of value to an EVM contract

- constants.xml
- src/libData/AccountData/EvmClient.cpp
> [master] Fix constant in constants for not starting evm

- constants.xml
- constants_local.xml
- src/libData/AccountData/AccountStore.cpp
- src/libLookup/Lookup.cpp
- src/libServer/LookupServer.cpp
The following are the changes:
- Add EVM-specific constants in `constants.xml`
- Revert logic for contract creation call to send to normal shard. It's the existing behavior running in the mainnet.
> [release/v8.3] Fix enable scilla when evm enabled is disabled

- tests/EvmAcceptanceTests/contracts/Delegatecall.sol
- tests/EvmAcceptanceTests/test/Delegatecall.js
> [master] Add delegatecall tests.

- tests/EvmAcceptanceTests/contracts/Revert.sol
- tests/EvmAcceptanceTests/test/ContractRevert.js
> [master] Add disabled test for out of gas [skip ci]

- src/libData/AccountData/EvmClient.h
> [master] Disable socket logging, as it just writes unreadable base64 now

- docker/Dockerfile
- docker/Dockerfile.deps
> [release/v8.3] Update the tag in Dockerfile.

- README.md
> [release/v8.3] Update the main README.md

- src/common/Constants.h
- src/common/FatalAssert.h
- src/depends/common/CMakeLists.txt
- src/depends/common/Common.h
- src/depends/common/CommonData.h
- src/depends/common/FixedHash.h
- src/depends/common/vector_ref.h
- src/depends/libTrie/TrieCommon.h
- src/libData/AccountData/EvmClient.h
- src/libData/AccountData/LogEntry.cpp
- src/libData/AccountData/ScillaClient.h
- src/libUtils/Logger.cpp
- src/libUtils/Logger.h
- tests/Data/Test_LogEntry.cpp
A necessary refactor to break (one) cyclic dependency in our code so that we can later also inject constants instead of hard-coding them all across the code.
> [master] ZIL-5002: break cyclic dependency with Logger

- evm-ds/Cargo.lock
> [master] Point to the new version of jsonrpc Rust libs with a more correct fix

- build.sh
- src/libData/AccountData/AccountStore.cpp
Add additional logging to transaction processing
two new log messages
start with [AS] and contain the Transaction Id and Status of Successfully or Failed.
> [master] Added diagnostic logging to AccountStore

- tests/EvmAcceptanceTests/test/Subscriptions.js
This should help with non-deterministic behavior and sporadically failing tests (due to e.g. hang websocket connection, etc).
> [master] Fixing subscription tests

- src/libPersistence/BlockStorage.cpp
Let's print something to have better understanding of what's been happening.
> [master] Added some logging for hash to num catchup

- src/libServer/EthRpcMethods.cpp
- src/libServer/JSONConversion.cpp
- src/libServer/JSONConversion.h
- tests/EvmLookupServer/Test_EvmLookupServer.cpp
Fixing hardcoded bloom filter in block response.
> [master] Attach proper bloom filter in block response

- Jenkinsfile
- docker/Dockerfile.base
- docker/Dockerfile.devbase
> [release/v8.4] ZIL-5011: fix packages in Docker files

- src/libData/AccountData/AccountStoreSC.cpp
> [master] Enable logging of transaction hash

- tests/EvmAcceptanceTests/contracts/Create2.sol
- tests/EvmAcceptanceTests/test/Create2.js
Add test for create2 operation
> [master] add the create2 test

- docker/Dockerfile
Update the scilla image to v0.13.1-alpha.
> [release/v8.4] - Update scilla image

- src/libServer/EthRpcMethods.cpp
> [master] Fixing eth_call

- Jenkinsfile
- docker/Dockerfile.ccache
> [master] [release/v8.4] - fix scilla image tag  & ccache docker image

- src/libData/AccountData/AccountStoreSCEvm.cpp
- src/libServer/JSONConversion.cpp
Respond in Eth units on Eth APIs.
> [master] Fix gas limit response

- src/libScilla/ScillaIPCServer.cpp
Simply remove an old counter increment with a bade counter name, containing spaces.
- [ x] **ready for review**
- [] small-scale cloud test
> [master] Remove bad counter name

- scripts/integration_test_js.sh
- tests/EvmAcceptanceTests/hardhat.config.js
- tests/EvmAcceptanceTests/helper/Parallelizer.js
- tests/EvmAcceptanceTests/test/openzeppelin/tokens/ERC20.js
> [master] Enable running JS tests run in parallel in CI

- tests/EvmAcceptanceTests/scripts/Accounts.ts
- tests/EvmAcceptanceTests/scripts/FeedDevnet.ts
> Move test scripts to typescript [skip ci]

- tests/EvmAcceptanceTests/Typescript.md
> Add typescript quick start guide [skip ci]

- src/libNode/FinalBlockProcessing.cpp
A broken dangling reference for modern compilers
> [master]  fix master

- tests/EvmAcceptanceTests/README.md
- tests/EvmAcceptanceTests/hardhat.config.ts
- tests/EvmAcceptanceTests/package-lock.json
- tests/EvmAcceptanceTests/package.json
> [master] Add scilla-checker task

- tests/EvmAcceptanceTests/.env
- tests/EvmAcceptanceTests/AddConfigHelpersToHre.ts
- tests/EvmAcceptanceTests/README.md
- tests/EvmAcceptanceTests/hardhat.config.ts
- tests/EvmAcceptanceTests/package-lock.json
- tests/EvmAcceptanceTests/package.json
> [master] Use .env file to feed test settings instead of raw env vars.

- .github/workflows/ci-image-dev.yml
- .github/workflows/ci-image-release.yml
- .github/workflows/security-scan.yml
> [master] feat: enable CI pipeline in GitHub Actions

- tests/EvmAcceptanceTests/AddConfigHelpersToHre.ts
- tests/EvmAcceptanceTests/README.md
- tests/EvmAcceptanceTests/hardhat.config.ts
- tests/EvmAcceptanceTests/helpers/EnvVarParser.ts
> [master] Tests code cleanup.

- tests/EvmAcceptanceTests/README.md
> Add Typescript quick start guide to tests readme [skip ci]

- .github/workflows/ci-image-dev.yml
- .github/workflows/ci-image-release.yml
> [master] fix: replace buildx with docker build

- scripts/download_incr_DB.py
… (#3246)"
https://zilliqa-jira.atlassian.net/browse/ZIL-5099
This reverts commit 16acbc696bedf09534026d6fc2f2014c0b4b38f2.
> [master] Revert [master] ZIL-4799: Simplify and improve `download_incr_DB.py`

- src/libData/AccountStore/AccountStore.cpp
- src/libData/AccountStore/AccountStoreSC.cpp
- src/libMetrics/Metrics.cpp
- tests/Data/AccountData/Test_Transaction.cpp
> [master] [WIP] Corrected histogram scales and latency measures

- src/libCps/CpsRunEvm.cpp
- src/libData/AccountData/Transaction.cpp
- src/libData/AccountStore/AccountStore.cpp
- src/libData/AccountStore/AccountStoreSC.cpp
- src/libMetrics/Api.h
- src/libMetrics/MetricFilters.h
- src/libMetrics/Metrics.cpp
- src/libMetrics/internal/mixins.h
- src/libScilla/ScillaIPCServer.cpp
- src/libServer/APIServerImpl.cpp
- src/libZilliqa/Zilliqa.cpp
- tests/Data/AccountData/Test_Transaction.cpp
> Corrected histogram scales and latency measures

- constants.xml
- constants_local.xml
- infra/k8s/base/configmap/constants.xml
> [master] Update missing constants in constants_local.xml and make default ENABLE_EVM to true

- src/libCps/CpsExecutor.cpp
> [master] Fix estimate revert case

- docs/local-network.md
> [master] Update docs for local network.

- src/libNetwork/SendJobs.cpp
> [release/v8.6] Cherry pick PR- #3385

- VERSION
- src/libUtils/SWInfo.h
> [release/v8.6] Update software tag

- evm-ds/src/evm_server_run.rs
> [master] Log evm results.

- VERSION
- src/libUtils/SWInfo.h
> [release/v8.6] Update software version v8.6.0rc2

- VERSION
> [release/v8.6] correct version file

- Tiltfile
> [master] fix: remove Tiltfile duplicated lines

- tests/EvmAcceptanceTests/test/rpc/eth_getTransactionByHash.ts
> [master] Add eth_getTransactionByHash tests.

- Tiltfile
> [master] add: conditioanl observability tier

- Tiltfile
> [master] fix: add the prometheus service monitor

- Tiltfile
> [master] fix: syntax error for prometheus-reader manifest

- src/cmd/validateDB.cpp
> [master] Add g3log sink in validateDb

- src/libCps/CpsRunScilla.cpp
> [master] Fix scilla messages ordering

- .github/workflows/ci-image-test.yml
- evm-ds/rust-toolchain.toml
> feat: add clippy test

- evm-ds/build.rs
- evm-ds/src/continuations.rs
- evm-ds/src/convert.rs
- evm-ds/src/evm_server.rs
- evm-ds/src/evm_server_run.rs
- evm-ds/src/main.rs
- evm-ds/src/pretty_printer.rs
- evm-ds/src/scillabackend.rs
> [master] Appease clippy

- .github/workflows/ci-image-test.yml
- [ x] This is not a breaking change
> [master] add: protobuf in the agent

- .github/workflows/ci-image-test.yml
> [master] feat: upgrade clippy check action

- .github/workflows/ci-image-test.yml
- evm-ds/src/evm_server_run.rs
- scripts/integration_test.sh
- scripts/integration_test_js.sh
- scripts/license_checker.sh
- tests/EvmAcceptanceTests/test/BlockchainInstructions.ts
- tests/EvmAcceptanceTests/test/ContractRevert.ts
- tests/EvmAcceptanceTests/test/GasEstimations.ts
- tests/EvmAcceptanceTests/test/openzeppelin/access-control/Ownable.ts
- tests/EvmAcceptanceTests/test/rpc/eth_getTransactionByHash.ts
- tests/EvmAcceptanceTests/test/scilla/ByStr.ts
- tests/EvmAcceptanceTests/test/scilla/ContractDeployment.ts
- tests/EvmAcceptanceTests/test/scilla/HelloWorld.ts
- tests/EvmAcceptanceTests/test/scilla/SendZil.ts
- tests/EvmAcceptanceTests/test/scilla/SetGet.ts
- tests/EvmFiltersAPI/Test_EvmFiltersAPI.cpp
> [master] fix: tests dependency and clippy error

- build.sh
- scripts/mim.sh
- src/libCps/CpsRunEvm.cpp
- src/libData/AccountStore/AccountStore.cpp
- src/libData/AccountStore/AccountStore.h
- src/libData/AccountStore/AccountStoreSCEvm.cpp
- src/libEth/Eth.cpp
- src/libMetrics/Api.cpp
- src/libMetrics/Api.h
- src/libMetrics/CMakeLists.txt
- src/libMetrics/MetricFilters.h
- src/libMetrics/Metrics.cpp
- src/libMetrics/Tracing.h
- src/libServer/EthRpcMethods.cpp
- src/libServer/LookupServer.cpp
- tests/EvmAcceptanceTests/package-lock.json
Testing metrics and traces adding traces throughout transaction flow
- [ x] This is not a breaking change
> [master] Added lots of traces and status

- src/libCps/CpsRunScilla.cpp
- src/libCps/ScillaHelpersCall.cpp
Edge was and is used to determine the depth. We only increase the edge when new level of runs is scheduled.
This is for CPS only.
> [master] Max depth fixes

- docs/local-network.md
- src/cmd/isolated_server.cpp
- src/cmd/main.cpp
- src/libCps/CpsExecutor.cpp
- src/libCps/CpsRunEvm.cpp
- src/libData/AccountData/Transaction.cpp
- src/libData/AccountStore/AccountStore.cpp
- src/libData/AccountStore/AccountStoreSC.cpp
- src/libData/AccountStore/AccountStoreSCEvm.cpp
- src/libData/AccountStore/services/evm/EvmClient.cpp
- src/libMetrics/Api.cpp
- src/libMetrics/Api.h
- src/libMetrics/Metrics.cpp
- src/libMetrics/internal/mixins.h
> [master] Cleanup and testing of metrics.

- build.sh
- docs/local-network.md
- src/cmd/isolated_server.cpp
- src/cmd/main.cpp
Couple of corrections from previous PR and removal of test code.
> [master] Overflow from last PR of comments made to self.

- src/libData/AccountStore/AccountStoreSCEvm.cpp
- src/libServer/EthRpcMethods.cpp
- src/libServer/EthRpcMethods.h
- src/libServer/IsolatedServer.cpp
Should work with something like: 
```
curl http://localhost:5555/ -X POST -H "Content-Type: application/json" --data '{"method":"debug_traceCall","params":[{"from":"0xf0cb24ac66ba7375bf9b9c4fa91e208d9eaabd2e","to":"0xa8cae66f62648529eb6ac2f026893fc436107510","data":"0x12CBB1AD0000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000030000000000000000000000009FB20310353B553E99904B2E71CDDADAD76A361200000000000000000000000084D15E9E4B1A134EDAB531DAE33908018FD84A9A000000000000000000000000A8CAE66F62648529EB6AC2F026893FC436107510"}, "latest", {"tracer" : "callTracer"}],"id":1,"jsonrpc":"2.0"}'
```
> [master] Add debug trace call

- tests/EvmAcceptanceTests/test/ContractRevert.ts
> [master] Fix and enable contract revert tests in CI

- evm-ds/src/evm_server_run.rs
> [master] Log EVM execution summary on Traps too

- src/libServer/EthRpcMethods.cpp
This must have sneaking in accidentally.
> [master] Fix gas issue

- docker/Dockerfile
- scripts/auto_backup.py
- src/libCps/CpsExecutor.cpp
- src/libCps/CpsMetrics.h
- src/libCps/CpsRunEvm.cpp
- src/libCps/CpsRunEvm.h
- src/libCps/CpsRunTransfer.h
- src/libMetrics/Api.h
- src/libMetrics/MetricFilters.h
- src/libMetrics/Tracing.h
> [master] Cps metrics and relaxed validation

- tests/Data/AccountData/Test_AccountStore.cpp
Initialised test fixture for observability as the tests need some basic services to run.
> [master] Addinit of observability in test fixture.

- src/libUtils/Logger.cpp
- src/libUtils/Logger.h
> [master] hotfix for logger and trace ids (multithreading related)

- src/libCps/CpsExecutor.cpp
- src/libCps/CpsRunEvm.cpp
- src/libCps/CpsRunScilla.cpp
> [master] Instrumenting CPS Scilla

- constants.xml
- infra/k8s/base/configmap/constants.xml
Test devnet with spanid and traceid fix for json logs
> [master] Test devnet

- src/libNetwork/P2PComm.cpp
> [master] dont send zero-length messages (protobuf-related)

- build.sh
AMend build script to use all but 90% of cpus on machines with more than 10 cpus.
> [master] Final settings

- src/libServer/LookupServer.cpp
- src/libServer/LookupServer.h
Please refer to the ticket details for a conversation regarding the requirement.
https://zilliqa-jira.atlassian.net/browse/ZIL-5121
`curl --request POST \
--url http://chetan-master-api-2-l2api.dev.z7a.xyz/ \
--header 'Content-Type: application/json' \
--data '{
"id": "1",
"method": "GetTotalCoinSupply",
"params": [""]
}'`
Response:
`{
"id": "1",
"result": "12600152995.523188406040"
}` 
`curl --request POST \
--url http://chetan-master-api-2-l2api.dev.z7a.xyz/ \
--header 'Content-Type: application/json' \
--data '{
"id": "1",
"method": "GetTotalCoinSupplyAsInt",
"params": [""]
}'`
Response:
`{
"id": "1",
"result": 12600152995
}`
> [master] Add API to get total coin supply as uint long

- infra/k8s/base/configmap/constants.xml
- src/libCps/CpsExecutor.cpp
- src/libCps/CpsRunEvm.cpp
- src/libCps/CpsRunScilla.cpp
- src/libMetrics/Tracing.h
- src/libServer/EthRpcMethods.cpp
- src/libZilliqa/Zilliqa.cpp
Created a new permission class called TXN
Moved scilla and evm traces to TXN permission class
use 
<TRACE_ZILLIQA_MASK>TXN</TRACE_ZILLIQA_MASK>
in constants.xml to minimise traces to just this class
Please run on a real network
> [master] Minimal Traces in order to not flood network

- docs/grafana_dashboards/chain_overview.json
- docs/grafana_dashboards/consensus.json
- src/libDirectoryService/DirectoryService.cpp
- src/libLookup/Lookup.cpp
- src/libMediator/Mediator.cpp
- src/libNode/FinalBlockProcessing.cpp
- src/libNode/Node.cpp
- src/libServer/GetWorkServer.cpp
> [master] More metrics

- src/libDirectoryService/Coinbase.cpp
- src/libDirectoryService/DirectoryService.h
- src/libNode/DSBlockProcessing.cpp
- src/libNode/MicroBlockPostProcessing.cpp
- src/libNode/MicroBlockPreProcessing.cpp
- src/libNode/Node.cpp
- src/libNode/PoWProcessing.cpp
- vcpkg-registry/ports/opentelemetry-cpp/portfile.cmake
- vcpkg-registry/ports/opentelemetry-cpp/proto-shared.patch
> [master] ZIL-5127: fix assertion/crash due to OTel protobuf 

- src/libMessage/Messenger.cpp
> [master] ZIL-5131: remove unnecessary logging in serialization code.

- infra/k8s/base/dsguard/kustomization.yaml
- infra/k8s/base/normal/kustomization.yaml
Revert code to original until python code is fixed to accommodate more guards.
> [master] Increase dsgaurds to five and 20 normal nodes.

- docker/Dockerfile
DOckerfile requires and apt-get update to allow python to build
> [master] Fix Dockerfile to add necessary apt-get update

- .gitignore
- docker/Dockerfile
- docker/Dockerfile.lite
- docs/local-network.md
- scripts/localdev.py
- vcpkg-registry/ports/cryptoutils/portfile.cmake
- vcpkg-registry/ports/schnorr/portfile.cmake
Add a script to automate running localdev via minikube and the testnet repository.
Scan the code, verify that I haven't touched Zilliqa proper - the script is just a bolt-on. Check that Dockerfile.lite does basically the same things as Dockerfile. Try it and see if it works for you
> [master] ZIL-5135: Add localdev script

- src/libConsensus/ConsensusBackup.cpp
- src/libConsensus/ConsensusBackup.h
- src/libConsensus/ConsensusLeader.cpp
- src/libConsensus/ConsensusLeader.h
- src/libData/AccountStore/AccountStore.cpp
- src/libMediator/Mediator.cpp
- src/libMetrics/Metrics.cpp
- src/libMetrics/TracedIds.h
- src/libMetrics/Tracing.cpp
- src/libMetrics/Tracing.h
- src/libNode/FinalBlockProcessing.cpp
- src/libPersistence/BlockStorage.cpp
- src/libPersistence/ContractStorage.cpp
- src/libUtils/DetachedFunction.h
- [] This is a breaking change
> [master] ZIL-5143: add tracing for epoch, consesnsus & blockstorage.

- VERSION
- src/libConsensus/ConsensusBackup.cpp
- src/libConsensus/ConsensusBackup.h
- src/libConsensus/ConsensusLeader.cpp
- src/libConsensus/ConsensusLeader.h
- src/libData/AccountStore/AccountStore.cpp
- src/libMediator/Mediator.cpp
- src/libMetrics/Metrics.cpp
- src/libMetrics/TracedIds.h
- src/libMetrics/Tracing.cpp
- src/libMetrics/Tracing.h
- src/libNode/FinalBlockProcessing.cpp
- src/libPersistence/BlockStorage.cpp
- src/libPersistence/ContractStorage.cpp
- src/libUtils/DetachedFunction.h
- src/libUtils/SWInfo.h
Cherry-picked (https://github.com/Zilliqa/Zilliqa/pull/3521) from master into v8.9.
> [master] ZIL-5143: cherry pick into v8.9

- evm-ds/Cargo.lock
> [master] cargo update for evm-ds

- src/libServer/JSONConversion.cpp
- src/libUtils/DataConversion.cpp
- src/libUtils/DataConversion.h
> [release/v8.9] hexify get TX

- evm-ds/Cargo.lock
- evm-ds/Cargo.toml
> [master] Update jsonrpc dependency to point to a Zilliqa repository

- scripts/integration_test_js.sh
> [master] Reduce test timeout for isolated server to 20 seconds.

- tests/EvmAcceptanceTests/test/Transfer.ts
Testing against local cluster - there was a race condition where the test didn't wait for TX to be executed before checking result. This was hidden on iso server since it basically instamines.
> [master] Fix one transfer test

- constants.xml
- src/cmd/isolated_server.cpp
- src/cmd/main.cpp
- src/libMetrics/Common.h
- src/libMetrics/Logging.cpp
- src/libMetrics/Logging.h
- src/libMetrics/Metrics.cpp
- src/libMetrics/Metrics.h
- src/libMetrics/Tracing.cpp
- tests/Data/AccountData/Test_AccountStore.cpp
- tests/Data/AccountData/Test_Transaction.cpp
- tests/Data/Test_Contract.cpp
- tests/libTestUtils/TestUtils.cpp
- tests/libTestUtils/TestUtils.h
- vcpkg-registry/ports/opentelemetry-cpp/portfile.cmake
- vcpkg-registry/ports/opentelemetry-cpp/thread-safe.patch
> [master] ZIL-5146: only allow lookup & seedprv node types to use telemetry 

- .github/workflows/ci-image-dev.yml
- .github/workflows/ci-image-test.yml
- src/libCps/CpsRunScilla.cpp
- src/libMetrics/Metrics.cpp
- src/libPersistence/BlockStorage.cpp
- vcpkg-registry/ports/opentelemetry-cpp/mac-fix.patch
- vcpkg-registry/ports/opentelemetry-cpp/portfile.cmake
- vcpkg-registry/ports/opentelemetry-cpp/vcpkg.json
- vcpkg-registry/versions/baseline.json
- vcpkg-registry/versions/o-/opentelemetry-cpp.json
- vcpkg.json
> [master] ZIL-5178: Upgrade to OTel 1.8.3

- src/libNode/Node.cpp
- src/libNode/Node.h
> Zil 5176 sync instead of rejoin normal nodes v8.9

- src/libNode/Node.cpp
- src/libNode/Node.h
Cherry-pick from #3557
* Allow node to sync if not in shard
* Remove debug log
> [master] Zil 5176 : Allow node to sync if not in shard

- src/depends/common/FixedHash.h
- tests/Data/AccountData/CMakeLists.txt
- tests/Data/AccountData/Test_Transaction.cpp
> [master] ZIL-5189: fix undefined behaviour issues

- SECURITY.md
Remove the outdated HackerOne bug bounty program references.
> [master] SEC-10: fix SECURITY.md

- src/libNode/MicroBlockPreProcessing.cpp
This reverts commit 2a7f4f371cc793c51a2bf6675dd987415fdf0a89.
The bug we found in this commit is that one of the `notify_all` wake up points does not set the `m_txnProcessingFinished` flag, but is still meant to notify the waiting thread to progress. With the new overload of `wait_for`, the call is not returned from unless the condition is met, despite the `notify_all` call. This means the sleeping thread does not wake, when it previously did.
This is clearly a very poor use of condition variables - We're using the same condition variable in two different code paths in two different ways - The first uses it to synchronise access to the `m_txnProcessingFinished` flag, while the second uses it to synchronise execution points like a barrier.
We could re-attempt to fix this, however we feel …
> [master] Revert "Protect m_txnProcessingFinished with a mutex consistently so that (#3502)"

- src/libCps/CpsRunScilla.cpp
We should apply penalty only on failed runs.
> [master] Fix scilla gas usage for successful deployment

- scripts/localdev.py
A `localdev isolated`  command, tested on Linux and OS X
Try it and see if it works :-)
> [master] ZIL-5186: localdev isolated server

- src/libCps/CpsExecutor.cpp
- tests/EvmAcceptanceTests/contracts/GasTransferTest.sol
- tests/EvmAcceptanceTests/test/Transfer.ts
- tests/EvmAcceptanceTests/test/gas-transfer/GasTransferTest.ts
* Scale EVM gas so we don't undercharge (equiv to #3599 )
* Round gas used so that deployments are zero-sum
* Trivial test case for the same.
> [master] ZIL-5208: fix evm gas rrw

- src/libServer/APIServerImpl.cpp
Fix the ZIL-5217 and use access control correctly
Add the access control to the error response as well as normal response.
add access control to error response.
- [x ] **ready for review**
> [master] Fix bug 5217

- scripts/localdev.py
- src/libData/AccountStore/services/evm/EvmClient.cpp
See summary.
review code, try it and see if it works ..
> [master] (feat) ZIL-5228: Allow evm-ds to be optionally disabled in isolated server for debugging.

- README.md
> [master] Update mainnet running version in readme file

- evm-ds/src/precompiles/scilla_read.rs
- src/libCps/CpsRunEvm.cpp
- src/libCps/CpsRunScilla.cpp
- src/libCps/ScillaHelpers.cpp
- src/libCps/ScillaHelpers.h
- src/libData/AccountData/TransactionReceipt.cpp
- src/libData/AccountData/TransactionReceipt.h
- src/libData/AccountStore/AccountStore.cpp
- src/libEth/Eth.cpp
- src/libScilla/ScillaIPCServer.cpp
- src/libScilla/ScillaIPCServer.h
- src/libScilla/ScillaUtils.cpp
- src/libScilla/ScillaUtils.h
- tests/EvmAcceptanceTests/test/ERC20Interop.ts
- tests/EvmAcceptanceTests/test/ERC20isZRC2.ts
- tests/Server/Test_ScillaIPCServer.cpp
Scilla contracts were not exported at some places - which wasn't expected and - in result it returned empty json. 
Also, we should wait for receipt otherwise accounts are not updated at the time the assertion is made.
> [master] Interop fixes

- TESTING.md
This document should be a reference for all of the test suites, procedures, and tools we have.
> [master] Add testing document.

- tests/EvmAcceptanceTests/.npmrc
- tests/EvmAcceptanceTests/hardhat.config.ts
- tests/EvmAcceptanceTests/package-lock.json
- tests/EvmAcceptanceTests/package.json
> [master] Check node version before running acceptance tests

- src/libMetrics/Tracing.cpp
cleaned up 5246 so its only a single change
> [master] styled

- tests/EvmAcceptanceTests/test/OtterTests.ts
> [release/v9.2] Disable otterscan tests in release

- docker/Dockerfile
> [master] Update scilla image version in dockerfile

- VERSION
- src/libUtils/SWInfo.h
> [release/v9.2] Update version to v9.2.0rc3

- VERSION
- src/libUtils/SWInfo.h
> [release/v9.2] Update version to v9.2.0rc4

- scripts/localdev.py
> [master] ZIL-5288: Add a --native option to build-scilla to allow building it natively.

- VERSION
- src/libUtils/SWInfo.h
> [release/v9.2] Update version -9.2.0rc5

- tests/EvmAcceptanceTests/README.md
- tests/EvmAcceptanceTests/hardhat.config.ts
- tests/EvmAcceptanceTests/tasks/Transfer.ts
> [master] Add transfer task.

- tests/EvmAcceptanceTests/README.md
- tests/EvmAcceptanceTests/tasks/Transfer.ts
> [master] Wait for transaction receipt in transfer task

- tests/EvmAcceptanceTests/tasks/Transfer.ts
> [master] Fix a tiny bug in transfer task

- daemon/ZilliqaUpdater.cpp
- src/libUpdater/UpdatePipe.cpp
1. Fix SHA256 calculation.
2. Fix parsing JSON.
> [release/v9.2] ZIL-5281: several fixes

- src/libNetwork/SendJobs.cpp
> [release/v9.2] ZIL-5298: cancel timer upon connection

- src/libNetwork/SendJobs.cpp
> ZIL-5298: drop connection if timeout timer fires

- README.md
- docs/setup/README.md
- docs/setup/installme.sh
- docs/setup/runlocaldev.sh
- docs/setup/setenv.sh
- scripts/localdev.py
Fixes localdev messaging and adds from-scratch setup scripts.
Try running the code :-)
- [X ] **ready for review**
> [master] Zil 5301 localdev setup

- src/libData/AccountStore/AccountStore.cpp
- src/libData/AccountStore/AccountStore.h
- src/libServer/DedicatedWebsocketServer.cpp
- src/libServer/EthRpcMethods.cpp
- src/libServer/IsolatedServer.cpp
- src/libServer/LookupServer.cpp
- src/libValidator/Validator.cpp
Cherrypick reverted commit from the `v9.0.3` release into the release/v9.2 branch.
> [release/v9.2] ZIL-5214: Revert priority mutex implementation for AccountStore

- src/libServer/APIThreadPool.cpp
- src/libServer/APIThreadPool.h
- src/libUtils/Queue.h
Cherry-picked - 0624ee3e6daba385a4cf0e861478800240d4f278, 7190711f2ee2fe2777ac60383724de13e16ba8e5, 4e30477021e6c0be59a09856d5193150f4b623a8
> [release/v9.2] Debug logging for api issue

- src/libData/AccountStore/AccountStore.cpp
- src/libData/AccountStore/AccountStore.h
- src/libServer/DedicatedWebsocketServer.cpp
- src/libServer/EthRpcMethods.cpp
- src/libServer/IsolatedServer.cpp
- src/libServer/LookupServer.cpp
- src/libValidator/Validator.cpp
Cherrypick reverted commit from the v9.0.3 release into the master branch.
> [master] ZIL-5214: Revert priority mutex implementation for AccountStore

- docs/setup/installme.sh
- docs/setup/runlocaldev.sh
- docs/setup/setenv.sh
- scripts/license_checker.sh
Fix license headers so that isolated server builds again.
Build isolated server :-)
- [ X] **ready for review**
> [master] (fix) ZIL-5315: Fix license headers on setup scripts and license_checker.sh error message.

- tests/EvmAcceptanceTests/test/ERC20isZRC2.ts
This fixes sporadic transaction-replaced issues. There could be more in other test suites and we should fix them in the same way.
> [q4-working-branch] Fixing test

- src/libServer/APIThreadPool.cpp
- src/libServer/APIThreadPool.h
- src/libUtils/Queue.h
This reverts commit daedca12a0608e6ff69491978702e755fd4f7a14.
> [release/v9.2] Revert PR 3718 - Remove debug logs for 503 API issue

- src/libPersistence/ContractStorage.cpp
- tests/Data/AccountData/Test_Account.cpp
- tests/EvmAcceptanceTests/test/scilla/Codehash.ts
> [master] Fix codehash feature to retrieve only contract code hash

- tests/EvmAcceptanceTests/helpers/parallel-tests/Worker.ts
- tests/EvmAcceptanceTests/tasks/ParallelTest.ts
- tests/EvmAcceptanceTests/tasks/Test.ts
> [master] Support grep in running tests in parallel mode.

- VERSION
- src/libUtils/SWInfo.h
> [release/v9.2] Update version to 9.2.3

- tests/EvmAcceptanceTests/README.md
- tests/EvmAcceptanceTests/hardhat.config.ts
- tests/EvmAcceptanceTests/helpers/parallel-tests/Worker.ts
- tests/EvmAcceptanceTests/tasks/ParallelTest.ts
- tests/EvmAcceptanceTests/test/scilla/Codehash.ts
> [master] Support running tests in user-specified files in parallel mode.

- tests/EvmAcceptanceTests/helpers/parallel-tests/Scenario.ts
- tests/EvmAcceptanceTests/helpers/parallel-tests/SignerPool.ts
- tests/EvmAcceptanceTests/helpers/parallel-tests/Worker.ts
- tests/EvmAcceptanceTests/package-lock.json
- tests/EvmAcceptanceTests/package.json
- tests/EvmAcceptanceTests/tasks/ParallelTest.ts
> [master] Support nested describes in parallel mode.

- build.sh
Simplified jobs variable as build was hanging on small 16gb systems
- [ x] This is a breaking change
> [q4-working-branch] simplified n_parallel jobs

- tests/EvmAcceptanceTests/helpers/parallel-tests/Display.ts
- tests/EvmAcceptanceTests/tasks/Balances.ts
- tests/EvmAcceptanceTests/tasks/InitSigners.ts
- tests/EvmAcceptanceTests/tasks/ParallelTest.ts
- tests/EvmAcceptanceTests/tasks/Setup.ts
- tests/EvmAcceptanceTests/test/contract-deployment/ContractDeploymentEthers.ts
- tests/EvmAcceptanceTests/test/openzeppelin/access-control/Ownable.ts
> [master] Speed up init signers script.

- tests/EvmAcceptanceTests/helpers/parallel-tests/Display.ts
> [master] Fix time display in output results.

- src/libServer/JSONConversion.cpp
Just merge in the fix so our tests get corrected
- [ X] This is not a breaking change
> [q4-working-branch] Fix reciept output as per spec

- tests/EvmAcceptanceTests/hardhat.config.ts
> [master] Update tests config. Remove useless networks.

- src/libPersistence/ContractStorage.cpp
- tests/Data/AccountData/Test_Account.cpp
- tests/EvmAcceptanceTests/test/scilla/Codehash.ts
> Q4 working branch + codehash fix

- docker/Dockerfile
> [master] Fixed vcpkg binary cache URL.

- docker/Dockerfile
- vcpkg-registry/ports/cryptoutils/vcpkg.json
- vcpkg-registry/ports/schnorr/fix-compiler-flags.patch
- vcpkg-registry/ports/schnorr/portfile.cmake
- vcpkg-registry/ports/schnorr/vcpkg.json
- vcpkg-registry/versions/baseline.json
- vcpkg-registry/versions/c-/cryptoutils.json
- vcpkg-registry/versions/s-/schnorr.json
- vcpkg.json
> [master] ZIL-5355: upgrade to OpenSSL 3

- .github/workflows/ci-image-dev.yml
> [master] feat: add push dev image to GCP

- .github/workflows/ci-image-dev.yml
> [master] feat: improve dev pipeline readability

- .gitignore
- tests/EvmAcceptanceTests/hardhat.config.ts
- tests/EvmAcceptanceTests/package-lock.json
- tests/EvmAcceptanceTests/package.json
- tests/EvmAcceptanceTests/tasks/Test.ts
> [master] Relax restriction on nodejs version for acceptance tests.

- .github/workflows/ci-image-release.yml
> [master] feat: add prd image push on GCP

- tests/EvmAcceptanceTests/test/zilrpc/GetBalance.ts
> [master] Add tests for GetBalance method of zilliqa API.

- src/libNetwork/SendJobs.cpp
> [master] ZIL-5298: adapt fix to changes in P2P.

- src/libRemoteStorageDB/RemoteStorageDB.cpp
- src/libRemoteStorageDB/RemoteStorageDB.h
- src/libServer/LookupServer.cpp
> [master] GetTransactionStatus Should respect txn query with or without 0x.

- src/libDirectoryService/FinalBlockPostProcessing.cpp
- src/libScilla/ScillaClient.cpp
- src/libScilla/ScillaClient.h
same as #3758 except debug logs are removed from the code.
The code is already tested on community testnet.
> [master] Restart scilla process at vacuous epoch (#3758)

- tests/EvmAcceptanceTests/contracts/Event.sol
- tests/EvmAcceptanceTests/test/EventsLogs.ts
> [master] Add logs count in transaction receipt tests. (#5352)

- tests/EvmAcceptanceTests/test/ParentChild.ts
- tests/EvmAcceptanceTests/test/Transfer.ts
- tests/EvmAcceptanceTests/test/openzeppelin/access-control/RoleBased.ts
- tests/EvmAcceptanceTests/test/rpc/eth_getTransactionByHash.ts
- tests/EvmAcceptanceTests/test/scilla/ManualNonce.ts
> [master] Re-enable all the tests and have them pass.

- src/libDirectoryService/DSBlockPreProcessing.cpp
Remove commented code and debug statement.
> [debug/master-pow-ds-submission] Remove commented code and debug statement.

- src/libDirectoryService/DSBlockPreProcessing.cpp
- src/libDirectoryService/PoWProcessing.cpp
> [debug/master-pow-ds-submission] Remove debug logs added for issue investigation

- .github/workflows/ci-image-dev.yml
- .github/workflows/ci-image-release.yml
> [master] feat: publish images in GCP in public registry prd

- src/libRemoteStorageDB/RemoteStorageDB.cpp
- src/libRemoteStorageDB/RemoteStorageDB.h
- [] This is not a breaking change
> [master] ZIL-5420: use environment variables for MongoDB host port & db name.

- src/common/Constants.cpp
- src/common/Constants.h
- src/libRemoteStorageDB/RemoteStorageDB.cpp
> [master] ZIL-5420: add a REMOTESTORAGE_DB_CONN_STRING

- src/libLookup/Lookup.cpp
On lookup node, the remote storage db wasn't recording the txn before dispatching to DS shard.The PR fixes it.
> [master] Allow insertion of txn to db at lookup node

- docs/reward_control.md
Document the procedure for shipping production reward control contracts.
Read and understand. If feeling enthusiastic, follow them! Note that the zilliqa-developer code mentioned is in a users/richard branch whilst the contract is reviewed.
> [master] (feat) ZIL-5423: Deployment instructions for reward control contracts.

- docs/reward_control.md
Merge master to release branch.
> [release/v9.3] Merge master to release/v9.3

- VERSION
- src/libUtils/SWInfo.h
> [release/v9.3] Update release version to v9.3.0rc1

- src/libDirectoryService/DSBlockPostProcessing.cpp
- src/libDirectoryService/FinalBlockPostProcessing.cpp
- src/libDirectoryService/FinalBlockPreProcessing.cpp
> [master] Fixing double enter into consensus in case gossip arrives early

- VERSION
- src/libUtils/SWInfo.h
> [release/v9.3] Update release version to v9.3.0rc2

- scripts/integration_test_js.sh
> Fix CI issue regarding installing nodejs

- scripts/integration_test_js.sh
> Install node using nvm

- tests/EvmAcceptanceTests/tasks/Setup.ts
> [master] Increase initial funds of signers in acceptance tests.

- tests/EvmAcceptanceTests/helpers/SignersHelper.ts
- tests/EvmAcceptanceTests/tasks/Balances.ts
- tests/EvmAcceptanceTests/tasks/InitSigners.ts
- tests/EvmAcceptanceTests/tasks/RefundSigners.ts
- tests/EvmAcceptanceTests/tasks/SetRewards.ts
- tests/EvmAcceptanceTests/tasks/Setup.ts
> [master] Change balances task so that it gets balances in parallel.

- src/libServer/EthRpcMethods.h
- src/libServer/IsolatedServer.h
> [master] Return 0x0 if the signature passed to eth_sendRawTransaction is invalid.

- src/libDirectoryService/DSBlockPreProcessing.cpp
> [master] Introduce delay for backup to reach DS consensus PREP state for fresh network

- docker/requirements3.txt
- scripts/download_incr_DB.py
> [release/v9.3] Exclude complete persistence from cdn cache

- scripts/download_incr_DB.py
> [master] Exclude complete persistence from cdn cache

- docker/Dockerfile
> [master] fix: enable files cache for vcpkg dependencies

- scripts/upload_incr_DB.py
> [master] Set cache control off in upload script

- src/libLookup/Lookup.cpp
- src/libNode/FinalBlockProcessing.cpp
- src/libRemoteStorageDB/RemoteStorageDB.cpp
> [master] Allow refresh whitelist to whitelist seed node by IP only

- scripts/localdev.py
- src/libServer/DedicatedWebsocketServer.cpp
Please make sure to add the following settings in `/etc/hosts` file.
`192.168.49.2 localdev-l2api-ws.localdomain`
> [master] Add support for websocket on localdev

- tests/EvmAcceptanceTests/contracts/ERC20isZRC2.sol
- tests/EvmAcceptanceTests/test/ERC20isZRC2.ts
- tests/EvmAcceptanceTests/test/Errorneous.ts
To align the implementation of ERC20isZRC2 with what we have on other repos. The main change is to include `name` `decimals` and `symbol` in the proxy such that EVM wallets can detect the proxy tokens correctly
I have also extracted the scilla interoperability functions to a separate library to improve reusability of this code.
> [master] Update ERC20isZRC2 example in EVMAcceptanceTests

- src/libEth/Eth.cpp
- tests/EvmAcceptanceTests/test/rpc/eth_getTransactionReceipt.ts
> [master] Fix ZIL-5568 : TransactionIndex field is not hex string.

- .github/workflows/ci-image-dev.yml
- .github/workflows/ci-image-release.yml
- .github/workflows/ci-image-test.yml
> [master] (fix): update the pipelines for the new GHA runners

- VERSION
> [release/v9.3] (fix): update VERSION to v9.3.5

- src/libEth/filters/APICache.cpp
> [release/v9.3] Increase eth logs retention to approximately 7 days

- src/libEth/filters/APICache.cpp
> [master] Increase eth logs retention to approximately 7 days

- docker/Dockerfile
- src/libServer/EthRpcMethods.cpp
- src/libServer/EthRpcMethods.h
- src/libServer/IsolatedServer.cpp
- tests/EvmAcceptanceTests/common/eip1898TestParams.js
- tests/EvmAcceptanceTests/test/rpc/eth_call.ts
- tests/EvmAcceptanceTests/test/rpc/eth_getBalance.ts
- tests/EvmAcceptanceTests/test/rpc/eth_getCode.ts
- tests/EvmAcceptanceTests/test/rpc/eth_getStorageAt.ts
- tests/EvmAcceptanceTests/test/rpc/eth_getTransactionCount.ts
Presently, any request using the [EIP-1898](https://eips.ethereum.org/EIPS/eip-1898) format is rejected with an `RPC_INVALID_PARAMS` error. This PR aims to support such requests and return the appropriate results
> [release/v9.3] Make jsonrpc api interface compatible with eip-1898
