- README.md
> Update Readme (Dependencies update)

- src/libUtils/Logger.cpp
> Use snprintf instead of sprintf for safety

- README.md
Add travis-cl build status badge
> Add travis-cl badge

- build.sh
- build_lookup.sh
- tests/Consensus/test_broadcast_local.sh
- tests/Consensus/test_consensus_local.sh
- tests/Directory/test_ds_simple.sh
- tests/Node/test_node_late.sh
- tests/Node/test_node_lookup.sh
- tests/Node/test_node_server.sh
- tests/Node/test_node_simple.sh
Specifying the shell interpreter explicitly.
> add shebang for all scripts

- tests/Crypto/.gitignore
- tests/Data/.gitignore
- tests/Network/.gitignore
- tests/Persistence/.gitignore
- tests/Utils/.gitignore
- tests/Zilliqa/.gitignore
- used leading `/` to ensure exact match instead of glob
> project : built test binaries added to `.gitignore` files

- src/libNode/DSBlockProcessing.cpp
- src/libNode/ShardingInfoProcessing.cpp
- tests/Node/test_node_late.sh
- Set new node joining from 1 to 5
- Comment clean up
- Set m_isConnectedToNetwork when new node win pow1
> Minor update to lookup process

- src/common/Constants.h
- src/libServer/Server.cpp
- src/libServer/Server.h
- src/libZilliqa/Zilliqa.cpp
- src/libZilliqa/Zilliqa.h
> [WIP] Solution to pointer issue in server.

- src/libDirectoryService/FinalBlockPreProcessing.cpp
- src/libUtils/TxnRootComputation.cpp
Fixed deadlock arising from PR #116 
Add log_marker() to various function
> Fix deadlock and add log_marker() to various functions

- CMakeLists.txt
- src/depends/libTrie/Trie.cpp
- src/libData/AccountData/AccountStore.cpp
- src/libDirectoryService/DSBlockPostProcessing.cpp
- src/libDirectoryService/DSBlockPreProcessing.cpp
- src/libDirectoryService/DirectoryService.cpp
- src/libDirectoryService/FinalBlockPreProcessing.cpp
- src/libLookup/Lookup.cpp
- src/libLookup/Synchronizer.cpp
- src/libNetwork/P2PComm.cpp
- src/libNetwork/P2PComm.h
- src/libNode/DSBlockProcessing.cpp
- src/libNode/Node.cpp
- src/libPersistence/BlockStorage.cpp
- src/libUtils/Logger.cpp
- tests/Lookup/Test_LookupNodeForTxBlock.cpp
- tests/Persistence/Test_TxPersistence.cpp
Enable the flags and fix the existing errors.
@bb111189 please take a look at the fix (09441f1) for #128.
> Treat all warnings as errors

- src/libConsensus/ConsensusLeader.cpp
- src/libDirectoryService/FinalBlockPreProcessing.cpp
- src/libNode/FinalBlockProcessing.cpp
- src/libNode/MicroBlockProcessing.cpp
- If node is still at Microblock consensus, but already receive final block. It will set itself to final block state
- Consensus indentation fix 
- Log message fix
> Node states fix, log message fix, indentation fix 

- src/libServer/Server.cpp
Input validation added to 
Get Tx/Ds Block : if string is not numeric , error json 
GetTransaction : size of string checked
GetAccount : size of string checked
> Add input validation

- tests/Node/thrmonitor.sh
USAGE:
watch -n1 ./tests/Node/thrmonitor.sh <zilliqa>
> Add script thrmonitor.sh for monitoring thread number under each process

- src/libServer/Server.cpp
- src/libServer/Server.h
* GetTransactionRate : the num of blocks considered for taking the avg rate can be adjusted. (now 3)
* GetRecentTransactions : the num of transactions which are returned can be adjusted (now 100)
> [WIP]API modification : GetTransactionRate / GetRecentTransaction

- src/libServer/JSONConversion.cpp
* Nonce in CreateTransaction was assumed to be an int before, now is a string.
> Changed nonce to a string json

- src/libServer/JSONConversion.cpp
> Revert "Changed nonce to a string json"

- src/libData/AccountData/AccountStore.cpp
- src/libNode/FinalBlockProcessing.cpp
> Reduce logging

- src/depends/libDatabase/LevelDB.cpp
- src/libPersistence/BlockStorage.cpp
Remove/comment out excessive logging
> remove excessive log

- README.md
- build.sh
- build_lookup.sh
Add git to installation instruction.
> Update readme (Add git)

- src/libNode/FinalBlockProcessing.cpp
Reduce the printing to log file from from 1s to 1min
> ProcessForwardTransaction: Reduce the printing of busy waiting logging

- src/libUtils/Logger.cpp
- src/libUtils/Logger.h
https://github.com/Zilliqa/Issues/issues/28
> log rotation using logrotate

- src/libCrypto/Sha2.h
https://github.com/Zilliqa/Issues/issues/27
> Remove inefficient sha2 update and use openssl update function

- src/libDirectoryService/DSBlockPostProcessing.cpp
- src/libDirectoryService/DirectoryService.h
- src/libDirectoryService/FinalBlockPostProcessing.cpp
- src/libDirectoryService/ShardingPostProcessing.cpp
https://github.com/Zilliqa/Issues/issues/22
https://github.com/Zilliqa/Issues/issues/23
> Use condition variable instead of busyloop on ProcessDSBlockConsensus and ProcessShardingConsensus

- src/libNetwork/P2PComm.cpp
- src/libPersistence/BlockStorage.cpp
- tests/Network/Test_P2PComm.cpp
https://github.com/Zilliqa/Zilliqa/issues/290
> Fix memory leakage for P2PComm, BlockStorage

- src/libServer/Server.cpp
Fix for disappearing blocks of data in explorer
> Add more funcs to blockchain info

- src/libDirectoryService/DirectoryService.cpp
- src/libDirectoryService/FinalBlockPostProcessing.cpp
- src/libDirectoryService/MicroBlockProcessing.cpp
- src/libDirectoryService/PoW1Processing.cpp
- src/libDirectoryService/PoW2Processing.cpp
- src/libDirectoryService/ShardingPostProcessing.cpp
- src/libNode/FinalBlockProcessing.cpp
- src/libNode/MicroBlockProcessing.cpp
- src/libNode/PoW1Processing.cpp
- src/libNode/PoW2Processing.cpp
- src/libNode/ShardingInfoProcessing.cpp
- tests/Lookup/Test_LookupNodeForTxBlock.cpp
https://github.com/Zilliqa/Zilliqa/issues/305
> Replace sizeof(uint256_t) to UINT256_SIZE

- src/depends/common/CommonData.h
- src/depends/common/FixedHash.h
- src/depends/common/vector_ref.h
- src/depends/libDatabase/LevelDB.cpp
- src/depends/libTrie/TrieCommon.h
- src/depends/libTrie/TrieDB.h
- src/libCrypto/Schnorr.cpp
- src/libCrypto/Sha2.h
- src/libCrypto/Sha3.h
- src/libData/AccountData/Account.cpp
- src/libData/AccountData/Transaction.cpp
- src/libData/AccountData/Transaction.h
- src/libData/BlockChainData/DSBlockChain.cpp
- src/libData/BlockChainData/TxBlockChain.cpp
- src/libData/BlockData/Block/MicroBlock.cpp
- src/libData/BlockData/Block/TxBlock.cpp
- src/libDirectoryService/DSBlockPostProcessing.cpp
- src/libDirectoryService/FinalBlockPreProcessing.cpp
- src/libPersistence/DB.cpp
- tests/Persistence/Test_DSPersistence.cpp
- tests/Persistence/Test_TxPersistence.cpp
https://github.com/Zilliqa/Zilliqa/issues/304
> Replace assert to LOG_GENERAL with FATAL

- tests/POW/test_POW.cpp
https://github.com/Zilliqa/Zilliqa/issues/308
> Modify Test_POW test case in order to shorten testing time.

- src/libCrypto/Schnorr.h
- src/libData/AccountData/AccountStore.h
- src/libPOW/pow.h
> Tiny refactoring: Delete copy ctors and assignment operators for

- src/libConsensus/ConsensusBackup.cpp
- src/libConsensus/ConsensusBackup.h
- src/libConsensus/ConsensusCommon.cpp
- src/libConsensus/ConsensusCommon.h
- src/libConsensus/ConsensusLeader.cpp
Modified the consensus to include the leader in the cosig
> Add leader to consensus cosig

- README.md
> Fixed minor typo (additional slash) in readme

- CMakeLists.txt
> Hotfix: add libNAT to install dir (fix #353)

- src/libData/AccountData/Account.h
- src/libServer/Server.cpp
- src/libServer/Server.h
Functions to fetch all SCs for an address.
> Added and fixed issues for fetching SCs

- src/libDirectoryService/PoW1Processing.cpp
- src/libDirectoryService/PoW2Processing.cpp
- src/libNode/PoW1Processing.cpp
- src/libNode/PoW2Processing.cpp
- src/libPOW/pow.cpp
* Added signature to PoW messages
* Signature verified by DS nodes
* Mixhash Verification
* [WIP] IP filter
>  PoW submission signature verification and PoW mixhash verification

- scripts/ci_make_image.sh
This PR adds the installation of [`kubernetes-python`](https://github.com/kubernetes-client/python) in the ci-built image. It's required by Zilliqa/testnet#84
N/A
> docker: add kubernetes-python to ci-built image

- src/libConsensus/ConsensusCommon.cpp
- src/libConsensus/ConsensusCommon.h
- src/libDirectoryService/DSBlockPostProcessing.cpp
- src/libDirectoryService/DirectoryService.cpp
- src/libDirectoryService/DirectoryService.h
- src/libDirectoryService/FinalBlockPostProcessing.cpp
- src/libDirectoryService/ShardingPostProcessing.cpp
- src/libDirectoryService/ViewChangePostProcessing.cpp
- src/libNode/MicroBlockProcessing.cpp
- src/libNode/Node.cpp
- src/libNode/Node.h
Implemented a GetStateString function across DS, Node, and ConsensusCommon classes to improve log readability.
Code style is based on recent work in PR #425.
**ready for review**
> Improve log readability by showing state strings

- constants.xml
- constants_local.xml
- src/common/Constants.cpp
- src/common/Constants.h
- src/libData/AccountData/Account.cpp
- src/libData/AccountData/AccountStoreSC.h
- src/libData/AccountData/AccountStoreSC.tpp
- Support "-libdir" flag
- Support "_create_block" for contract Init data
- Refactor scilla directory constants
> Updates for Scilla

- constants.xml
- constants_local.xml
- src/common/Constants.cpp
- src/common/Constants.h
- src/libData/AccountData/Account.cpp
- src/libData/AccountData/AccountStore.cpp
- src/libData/AccountData/AccountStore.h
- src/libData/AccountData/AccountStoreSC.h
- src/libData/AccountData/AccountStoreSC.tpp
- src/libNode/Node.cpp
Avoid `SubmitTransaction` keep looping for valid transaction to submit endlessly.
> While loop keep searching for prefill txn

- README.md
- constants.xml
Our repository has been migrated to travis-ci.com so the build status link needs to be updated. The constants.xml has some XML format [issue](https://github.com/Zilliqa/Zilliqa/pull/430#pullrequestreview-138723374).
N/A
> Fixes for constants.xml and README

- constants_local.xml
This line was accidently removed by previous commit, simply put it back
https://github.com/Zilliqa/Zilliqa/commit/b3e935f187c5bfd93e269792c80898f7c82d1820
> Put wallet_address back

- tests/POW/test_POW.cpp
Fix auto test of POW take too long problem.
Change the auto test for mining from full to light.
This PR fixes #308 
Check the Test_Pow.cpp.
Run the ./build/tests/POW/Test_POW to check the running time.
> Change the mining auto test case into light mine

- src/libUtils/DataConversion.h
* Better tomorrow
* fix compile on the armv7 arch problem.
* fix issues #342 
* docker pull arm32v7/ubuntu:16.04
* docker run it
* build_lookup.sh
> fix issues #342, solve fail to complile on armv7 arch

- src/libNode/Node.cpp
- src/libNode/Node.h
Just making the checkstate of Node match that of DS, including GetActionString.  Refer to recent changes in #455 for how it was done in DS.
Make sure the mapping of states and actions in CheckState maintains the code logic from the previous implementation.
> Rewrite Node checkstate to match DirectoryService

- src/common/Messages.h
- src/libDirectoryService/DirectoryService.cpp
- src/libDirectoryService/DirectoryService.h
After #465 and #467, messages AllPoWConnRequest and AllPoWConnResponse are no longer used and are free to remove.
> [PoW Merge] Remove unused AllPoWConnRequest and AllPoWConnResponse

- src/libNode/FinalBlockProcessing.cpp
Remove redundant AccountStore::InitTemp which may cause state delta mismatch.
> Remove redundant InitTemp

- src/libDirectoryService/DSBlockMessage.h
- src/libDirectoryService/ShardingPreProcessing.cpp
This is a similar effort to #464 and #474 where sharding / txn sharing info serialization were moved to DSBlockMessage.h.  This time, deserialization of sharding info has been moved to that same file.
Coming up in next PRs:
1. Update Lookup to use the deserialization function
2. Update Node::SHARDING message to use the same sharding info serialization/deserialization functions
3. Move txn sharing info deserialization code
Check that the deserialize function basically just retrieves the same sharding structure format
Notice also that the checks have been moved out of deserialization, and it is now up to the calling function (e.g., ShardingValidator) to check the IP info in the sharding structure.  This is in preparation for the Node class to be able to …
> [PoW Merge] Move sharding deserialization code

- src/libConsensus/ConsensusBackup.cpp
- src/libConsensus/ConsensusBackup.h
- src/libConsensus/ConsensusLeader.cpp
- src/libConsensus/ConsensusLeader.h
Minor enhancement similar to #455 and #456.
Make sure the mapping of states and actions in CheckState maintains the code logic from the previous implementation.
> Rewrite consensus leader/backup checkstate to match node/ds

- src/libNode/Node.cpp
Increase the initial genesis account balance
N/A
> Increase initial genesis account balance

- src/common/Constants.cpp
- src/common/Constants.h
- src/libDirectoryService/DirectoryService.h
- src/libDirectoryService/PoWProcessing.cpp
- src/libLookup/Lookup.cpp
This PR does 2 things:
1. Remove the limit on the number of PoW submissions
2. Use `ShardingStructure::Deserialize()` in `Lookup::ProcessEntireShardingStructure()`
I have NOT yet removed MAX_POW_WINNERS from constants.xml and constants_local.xml so I don't affect other people's test environments. That can come later when we remove the PoW2 constants as well.
Coming up in next PR: Move the sharding structure and txn sharing assignments into PoW consensus.
> [PoW Merge] Remove the max PoW submission limit

- src/libDirectoryService/FinalBlockPostProcessing.cpp
- src/libNode/FinalBlockProcessing.cpp
- src/libNode/MicroBlockProcessing.cpp
- src/libNode/Node.h
This PR is to put the transaction and state delta forwarding after the microblock consensus being done.
https://github.com/Zilliqa/Zilliqa/pull/488
Most of the newly inserted functions are transplanted from FinalBlockProcessing.cpp
> Put transactions & state delta forwarding after microblockconsensus done

- src/libDirectoryService/DSBlockPostProcessing.cpp
- src/libDirectoryService/FinalBlockPostProcessing.cpp
- src/libNode/DSBlockProcessing.cpp
- src/libNode/FinalBlockProcessing.cpp
- src/libNode/MicroBlockProcessing.cpp
- tests/Data/Test_Block.cpp
This PR fixes https://github.com/Zilliqa/Issues/issues/89 and https://github.com/Zilliqa/Issues/issues/90. 
1. Fixes ds block number for microblock (https://github.com/Zilliqa/Issues/issues/89)
2. Fixes log printing of variables that are uint8. (https://github.com/Zilliqa/Issues/issues/90)
- difficulty
- block type
> Fix log printing and ds block number for microblock

- src/libDirectoryService/DSBlockPostProcessing.cpp
- src/libDirectoryService/DSBlockPreProcessing.cpp
- src/libDirectoryService/DirectoryService.cpp
- src/libDirectoryService/FinalBlockPostProcessing.cpp
- src/libDirectoryService/FinalBlockPreProcessing.cpp
- src/libDirectoryService/ViewChangePostProcessing.cpp
- src/libDirectoryService/ViewChangePreProcessing.cpp
- src/libLookup/Lookup.cpp
- src/libMediator/Mediator.cpp
- src/libMediator/Mediator.h
- src/libNode/Coinbase.cpp
- src/libNode/DSBlockProcessing.cpp
- src/libNode/FinalBlockProcessing.cpp
- src/libNode/MicroBlockProcessing.cpp
- src/libNode/Node.cpp
- src/libNode/Node.h
- src/libNode/PoWProcessing.cpp
- src/libNode/ViewChangeBlockProcessing.cpp
- src/libServer/Server.cpp
Which is a pre-requirement for implement DS microblock. As it doesn't affect any functionality on master, pls merge first for the sack avoid conflicts resolving which may happen.
> Use shard_ptr for m_DSCommittee and m_myShardMembers

- CMakeLists.txt
- README.md
- build.sh
- scripts/ci_install_deps.sh
- src/depends/CMakeLists.txt
- src/libPOW/CMakeLists.txt
- src/libPOW/pow.cpp
Make  build with OpenCL as an option, remove the OpenCL as a compulsary dependency, 
Add a CMAKE option OPENCL_MINE
Please check the main CMakeLists.txt and build script.
Run ./build.sh to check if build can success. And enable OPENCL_GPU_MINE option in constants.xml and run ./build/tests/POW/Test_POW, there should be error throw out say software is not build with OpenCL.
> Feature/gpu mining - Make build with OpenCL as an option

- src/libMessage/CMakeLists.txt
This PR fixes #518 where the higer version of GCC will complain about "unused parameters" in `libMessage`. There's no need to fix the warnings in machine generated code so it's muted in the scope of libMessage in the same way as https://github.com/Zilliqa/Zilliqa/blob/7d1b0f11a24a222c3530049dae74e224b6142315/src/depends/libTrie/CMakeLists.txt#L3
Need to do a build on Ubuntu 18.04. If you don't have the OS version, here's an example of using docker to verify the build
```
docker run --rm -it ubuntu:18.04
```
In the docker, install the dependencies, clone the code on branch `fix/158` and build.
```
apt update && apt install -y git clang-format-5.0 clang-tidy-5.0 clang-5.0 libboost-system-dev \
libboost-filesystem-dev libboost-test-dev libssl-dev libleveldb-dev libjsoncpp-dev \
libsnappy-dev …
```
> libMessage: suppress unused parameters errors

- src/libNetwork/Blacklist.cpp
- src/libNetwork/Blacklist.h
- src/libNetwork/CMakeLists.txt
- src/libNetwork/P2PComm.cpp
With the need of DDoS reputation manager, blacklist is a fundamental feature and should be provided first.
There is always a blacklist existed (singleton) in each process, and P2PComm will internally use blacklist to block all sending/receiving message with the blacklist nodes.
After this PR, the reputation manager can adjust blacklist by other functions: Add/Remove.
> Blacklist support

- tests/Network/CMakeLists.txt
- tests/Network/Test_Blacklist.cpp
After https://github.com/Zilliqa/Zilliqa/pull/520, some unit test should be provided.
> Blacklist unit test

- src/libNetwork/Blacklist.h
- src/libNetwork/Whitelist.h
This PR add missing header guard to `Whitelist.h` and `Blacklist.h`
> Add missing header guard

- src/libUtils/CMakeLists.txt
- src/libUtils/IPConverter.cpp
- src/libUtils/IPConverter.h
- tests/Utils/CMakeLists.txt
- tests/Utils/Test_IPConverter.cpp
This PR add an utility to convert between ascii and numerical representation of IP address.
> Add IP Converter utility

- src/libNode/FinalBlockProcessing.cpp
- src/libNode/Node.cpp
- src/libNode/Node.h
- src/libZilliqa/Zilliqa.cpp
- tests/Node/test_node_simple.sh
- Some changes on test_node_simple.sh for fixing some problem shown in local test 
- Fixed the logic when storing DSIncompleted in vacuous epoch
- Solved the ds->m_consensusID not matching after recovery
> Fix persistence recovery

- src/libLookup/Lookup.cpp
- src/libLookup/Lookup.h
Fix software crash on double free and data race.
Add mutex to protect data in multi thread environment.
https://github.com/Zilliqa/Issues/issues/153#issuecomment-413433600
Check the libLookup/lookup.cpp
Run 200 nodes test to verify the network status.
> Fix potential crash problem

- .github/PULL_REQUEST_TEMPLATE.md
- tests/Node/watch_node_simple.sh
Non-functional fixes. Contributions are welcome.
This PR fixes #553
> Accumulative fixes

- src/libData/DataStructures/MultiIndexContainer.h
- src/libNode/MicroBlockProcessing.cpp
- src/libNode/Node.cpp
- tests/Data/Test_MultiIndex.cpp
Improved the performance of insertion operation for MultiIndexContainer by fixing issue:
https://github.com/Zilliqa/Issues/issues/186
> Improve insertion performance of MultiIndexContainer

- .travis.yml
- constants.xml
- constants_local.xml
- scripts/ci_install_deps.sh
- scripts/ci_xml_checker.sh
Add a XML checker for Travis Linux build to enforce the format and syntax. It uses `xmllint`.
> Add XML checker

- .clang-tidy
- cmake/LLVMExtraTools.cmake
- scripts/ci_build.sh
- scripts/ci_install_deps.sh
- scripts/run-clang-tidy.py
- src/cmd/gentxn.cpp
- src/libConsensus/ConsensusBackup.h
- src/libConsensus/ConsensusLeader.h
- src/libData/AccountData/Account.cpp
- src/libData/AccountData/Account.h
- src/libData/AccountData/AccountStore.cpp
- src/libData/AccountData/AccountStore.h
- src/libData/AccountData/AccountStoreAtomic.tpp
- src/libData/AccountData/AccountStoreBase.h
- src/libData/AccountData/AccountStoreBase.tpp
- src/libData/AccountData/AccountStoreSC.h
- src/libData/AccountData/AccountStoreSC.tpp
- src/libData/AccountData/AccountStoreTemp.cpp
- src/libData/AccountData/AccountStoreTrie.h
- src/libData/AccountData/AccountStoreTrie.tpp
- src/libData/BlockChainData/BlockChain.h
- src/libData/BlockData/BlockHeader/TxBlockHeader.h
- src/libPersistence/BlockStorage.h
- src/libPersistence/ContractStorage.cpp
- src/libPersistence/ContractStorage.h
- src/libUtils/TimeLockedFunction.h
- src/libUtils/TxnRootComputation.cpp
Directly `using namespace` would incur potential namespace pollution and this PR removes all the `using namespace` statements at global scope in header files. Besides, It also brings `clang-tidy` check to enforce this rule.
See the removal in header files and all the corresponding changes in source files.
> Remove 'using namespace' in header files

- docker/Dockerfile
- release.sh
- scripts/ci_install_deps.sh
- scripts/ci_make_image.sh
- src/libData/BlockData/BlockHeader/DSBlockHeader.h
- src/libMediator/Mediator.h
- src/libUtils/CMakeLists.txt
- src/libUtils/SWInfo.cpp
- src/libUtils/SWInfo.h
- src/libUtils/UpgradeManager.cpp
- src/libUtils/UpgradeManager.h
- tests/Utils/CMakeLists.txt
- tests/Utils/Test_UpgradeManager.cpp
Following release helper (https://github.com/Zilliqa/Zilliqa/pull/544), the download procedure should provide following features:
> Download procedure for upgrading protocol

- src/libDirectoryService/DSBlockPostProcessing.cpp
- src/libDirectoryService/DSBlockPreProcessing.cpp
- src/libDirectoryService/DirectoryService.cpp
- src/libDirectoryService/DirectoryService.h
- tests/POW/CMakeLists.txt
- tests/POW/test_POW.cpp
Support two levels of difficulty adjustment
Add a ```CalculateNewDifficultyCore``` function, so the normal difficulty adjustment function ```CalculateNewDSDifficulty``` and DS difficulty adjustment function will both call ```CalculateNewDifficultyCore```.
Check the ```DirectoryService::CalculateNewDSDifficulty```, ```DirectoryService::CalculateNewDifficultyCore``` and ```DirectoryService::CalculateNewDifficultyCore``` functions.
Build the project, run the test case ```./build/test/POW/Test_POW``` make sure auto test case can pass.
On local machine, run small network first, then run ```./tests/Node/test_node_late.sh``` to join new nodes, the difficulty will adjust.
> Dual difficulty adjustment

- src/libMessage/Messenger.cpp
- src/libMessage/Messenger.h
- src/libMessage/ZilliqaMessage.proto
This PR adds the proto messages and `Messenger` functions for Lookup.
These functions aren't in use yet, pending coordinated work to add Protobuf into the javascript API.
> [Refactor] Add protobuf messages for Lookup

- .clang-tidy
- src/cmd/sendcmd.cpp
- src/libData/AccountData/AccountStore.cpp
- src/libDirectoryService/DSBlockMessage.h
- src/libDirectoryService/DSBlockPreProcessing.cpp
- src/libDirectoryService/DirectoryService.cpp
- src/libDirectoryService/ViewChangePostProcessing.cpp
- src/libDirectoryService/ViewChangePreProcessing.cpp
- src/libLookup/Lookup.cpp
- src/libNetwork/PeerStore.cpp
- src/libNode/FinalBlockProcessing.cpp
- src/libNode/MicroBlockProcessing.cpp
- src/libNode/Node.cpp
- tests/Persistence/Test_DSPersistence.cpp
- tests/Persistence/Test_TxPersistence.cpp
This PR adds another clang-tidy check `modernize-loop-convert`. Now clang-tidy on Travis will suggest improvements on all the places that can use range-based for-loop.
See the refactoring brought by clang-tidy.
> [clang-tidy] Use range-based for-loop preferably

- src/depends/common/Miner.h
- src/libDirectoryService/DirectoryService.h
- src/libDirectoryService/ViewChangePostProcessing.cpp
- src/libDirectoryService/ViewChangePreProcessing.cpp
- src/libMediator/Mediator.h
- src/libNode/Node.h
- src/libPersistence/Retriever.cpp
- src/libUtils/GetTxnFromFile.h
- src/libUtils/HashUtils.h
- src/libZilliqa/Zilliqa.h
Fix the issues that were not covered in #567.
> Remove 'using namespace std' in Miner.h

- .clang-tidy
- src/common/Constants.cpp
- src/libConsensus/ConsensusBackup.cpp
- src/libConsensus/ConsensusCommon.cpp
- src/libConsensus/ConsensusLeader.cpp
- src/libConsensus/ConsensusUser.cpp
- src/libCrypto/MultiSig.cpp
- src/libData/AccountData/Transaction.cpp
- src/libData/BlockData/BlockHeader/VCBlockHeader.cpp
- src/libDirectoryService/DSBlockPostProcessing.cpp
- src/libDirectoryService/DSBlockPreProcessing.cpp
- src/libDirectoryService/DirectoryService.cpp
- src/libDirectoryService/MicroBlockProcessing.cpp
- src/libDirectoryService/PoWProcessing.cpp
- src/libDirectoryService/ViewChangePostProcessing.cpp
- src/libLookup/Lookup.cpp
- src/libNetwork/PeerManager.cpp
- src/libNode/DSBlockProcessing.cpp
- src/libNode/FinalBlockProcessing.cpp
- src/libNode/MicroBlockProcessing.cpp
- src/libNode/Node.cpp
- src/libNode/ViewChangeBlockProcessing.cpp
- src/libPOW/pow.cpp
- src/libUtils/DetachedFunction.h
- src/libZilliqa/Zilliqa.cpp
Use clang-tidy option `readability-simplify-boolean-expr`
> [clang-tidy] Simplify boolean expression

- src/libNode/DSBlockProcessing.cpp
> Fix issue of new ds leader crashing

- src/common/Messages.h
- src/libMessage/Messenger.cpp
- src/libMessage/Messenger.h
- src/libMessage/ZilliqaMessage.proto
Added new messages `GETSHARDSFROMSEED` and `SETSHARDSFROMSEED` and the `Messenger` functions to serialize these.
Functions are unused at this time.
> Added lookup messages to get sharding structure

- src/libDirectoryService/MicroBlockProcessing.cpp
> Deserialization error fix due to wrong offset.

- src/libLookup/Lookup.cpp
- src/libLookup/Lookup.h
- src/libMessage/Messenger.cpp
- src/libMessage/Messenger.h
- src/libMessage/ZilliqaMessage.proto
- src/libNode/Node.cpp
- src/libNode/Node.h
This PR converts the `NODE::FORWARDTXNBLOCK` message to Protobuf
One extra minor update: Changed bool members in Protobuf message for `CoSignatures` to packed, for efficiency improvement.
> Make protobuf message for ForwardTxnPacket

- src/libData/BlockData/BlockHeader/BlockHeaderBase.h
- src/libDirectoryService/ViewChangePostProcessing.cpp
- src/libMessage/Messenger.cpp
- src/libMessage/Messenger.h
- src/libMessage/ZilliqaMessage.proto
- src/libNode/ViewChangeBlockProcessing.cpp
This is a similar update to #598 where `DSBlock` was protobuf-ed.
This time, `VCBlock` is protobuf-ed, along with `Node::VCBLOCK` message.
I also removed the `m_prevHash` inside `BlockHeaderBase`, which was being overridden by a similar `m_prevHash` in some of the block types.
Tested by triggering viewchange in local test. Both set and get were ok.
> Make protobuf message for VCBlock

- src/libLookup/Lookup.cpp
- src/libLookup/Lookup.h
> Added some functions for supporting the functioning of Archival Nodes.

- src/libMessage/Messenger.cpp
- src/libMessage/ZilliqaMessage.proto
In this PR, we create a protobuf-equivalent message for MicroBlock.
> Make protobuf message for MicroBlock

- src/libDirectoryService/DirectoryService.cpp
- src/libLookup/Lookup.cpp
- src/libNode/PoWProcessing.cpp
Disallow bootstrap function after blockchain started. Improve security of the blockchain. Malicious user may use this function to attack the network.
Check the block number when call these functions, if larger than 1, then don't process function.
https://github.com/Zilliqa/Issues/issues/176
Check the file changes.
Run local 20 nodes test. After bootstrap, run the below script to send bootstrap message to the nodes again, from the running log, should can find "...is a bootstrap function, it shouldn't be called after blockchain started" in the log files.
> for ds in {1..10}
> do
>     python tests/Zilliqa/test_zilliqa_local.py sendcmd $ds 01000000000000000000000000000100007F00001389
> done
> sleep 10
> 
> for node in {11..20}
> do
>     python tests/Zilliqa/test_zilliqa_local.py startpow …
> Disallow bootstrap function after blockchain started

- constants.xml
- constants_local.xml
- src/common/Constants.cpp
- src/common/Constants.h
- src/depends/common/Miner.h
- src/depends/libethash-cl/CLMiner.cpp
- src/depends/libethash-cl/CLMiner.h
- src/depends/libethash-cuda/CUDAMiner.cpp
- src/depends/libethash-cuda/CUDAMiner.h
- src/libPOW/pow.cpp
- src/libPOW/pow.h
Support using multiple GPUs to do mining together
Update the POW library. Create a new thread for each GPU to do mining.
https://github.com/Zilliqa/Zilliqa/issues/555
Check the libPOW.
Use a PC with more than 1 GPUs, set NUM_DEVICE_TO_USE in constants to 2. If you are using OpenCL GPU, set OPENCL_GPU_MINE to true, if you are using CUDA gpu, set CUDA_GPU_MINE to true, build the software with ./build.sh opencl or ./build.sh cuda command. Then run cd build && ./tests/POW/Test_POW see if the test case can pass.
> Support using multiple GPUs to do mining together

- src/libDirectoryService/Coinbase.cpp
- src/libDirectoryService/DSBlockPostProcessing.cpp
- src/libDirectoryService/DSBlockPreProcessing.cpp
- src/libDirectoryService/FinalBlockPreProcessing.cpp
- src/libDirectoryService/ViewChangePostProcessing.cpp
- src/libDirectoryService/ViewChangePreProcessing.cpp
- src/libNode/MicroBlockProcessing.cpp
This PR consists of the following
Medium scale test does not include view change. View change is tested separately on a local machine test.
> View change hotfix, DS microblock timeout state transition fix and additional debug logs

- src/libConsensus/ConsensusBackup.cpp
- src/libConsensus/ConsensusBackup.h
- src/libConsensus/ConsensusCommon.cpp
- src/libConsensus/ConsensusCommon.h
- src/libConsensus/ConsensusLeader.cpp
- src/libConsensus/ConsensusLeader.h
- src/libConsensus/ConsensusUser.cpp
- src/libDirectoryService/DSBlockPreProcessing.cpp
- src/libDirectoryService/DirectoryService.h
- src/libDirectoryService/FinalBlockPreProcessing.cpp
- src/libDirectoryService/ViewChangePreProcessing.cpp
- src/libMessage/Messenger.cpp
- src/libMessage/Messenger.h
- src/libMessage/ZilliqaMessage.proto
- src/libNode/FallbackPreProcessing.cpp
- src/libNode/MicroBlockPreProcessing.cpp
- src/libNode/Node.h
Put block number in consensus message and validate it
Put block number in consensus message and validate it
The block number is not used in the consensus, which may give the chance for hacker to attack our network.
Check the file changes.
Run local test.
> Put block number in consensus message and validate it

- src/libNode/FinalBlockProcessing.cpp
The check previously will always fail if the local microblock have no txn. This pr is for fixing this.
> Hot fix for checks on unavailable microblock without transaction

- src/libServer/Server.cpp
- src/libServer/Server.h
This PR modifies CreateTransaction and adds GetContractAddressFromTransactionID APIs for ease of knowing the Contract Address.
* ### CreateTransaction
* #### Returns a JSON containing :
1. Error, if there is an error in creating Transaction
2. Info, tells if the Transaction was a contract transaction and if it went to a ds shard.
3. ContractAddress, if the transaction was a contract transaction, contains the contract Address.
* ### GetContractAddressFromTransactionID
* Given Valid Contract Transaction ID, returns the ContractAddress (string)
Should be merged with corresponding changes in Wallet.
Related issue : #574
> Add/Modify Server APIs for feature request.

- CMakeLists.txt
- build.sh
- scripts/ci_xml_checker.sh
- tests/.gitignore
This PR includes a bunch of small fixes in each commit.
See the commit message
> Miscellaneous fixes on build system

- build.sh
The checker is not ready for Mac platform, let's just remove it first. It will still be run on Travis Linux build.
N/A
> Hotfix for ci_xml_checker.sh issue in build.sh

- src/libData/BlockData/Block/DSBlock.cpp
- src/libData/BlockData/Block/DSBlock.h
- src/libData/BlockData/Block/FallbackBlock.cpp
- src/libData/BlockData/Block/FallbackBlock.h
- src/libData/BlockData/Block/TxBlock.cpp
- src/libData/BlockData/Block/TxBlock.h
- src/libData/BlockData/Block/VCBlock.cpp
- src/libData/BlockData/Block/VCBlock.h
- src/libDirectoryService/DSBlockPreProcessing.cpp
- src/libDirectoryService/DirectoryService.h
- src/libDirectoryService/FinalBlockPreProcessing.cpp
- src/libDirectoryService/ViewChangePreProcessing.cpp
- src/libLookup/Synchronizer.cpp
- src/libMessage/Messenger.cpp
- src/libMessage/ZilliqaMessage.proto
- src/libNode/DSBlockProcessing.cpp
- src/libNode/FallbackBlockProcessing.cpp
- src/libNode/FallbackPreProcessing.cpp
- src/libNode/FinalBlockProcessing.cpp
Add BlockHash Field in DS/VC/FB/TX Block.
The reason that to provide a new field rather than directly calculate the hash of header in the program is because: 
if we have any variable didn't validate (e.g. we never validate the timestamp), so a user may modify such 
variables to make the receiver have a different block hash. Thus it's safer to have an extra field for the block hash to provide the validation.
> Add BlockHash Field in DS/VC/FB/TX Block

- src/libDirectoryService/DSBlockPostProcessing.cpp
- src/libDirectoryService/DirectoryService.cpp
- src/libNode/Node.cpp
This PR cover adding additional logging for TreeBased cluster broadcasting to help benchmarking.
> Benchmarking of TreeBased Cluster Broadcasting

- constants.xml
- constants_local.xml
- src/common/Messages.h
- src/libDirectoryService/DirectoryService.cpp
- src/libLookup/Lookup.cpp
- src/libLookup/Lookup.h
- src/libLookup/Synchronizer.cpp
- src/libMessage/Messenger.cpp
- src/libMessage/Messenger.h
- src/libMessage/ZilliqaMessage.proto
- src/libNode/Node.cpp
- tests/Zilliqa/test_zilliqa_lookup.py
Develop verify lookup node and messages to enhance the security of Zilliqa blockchain.
Add lookup public key to the constants.xml, add signature and pubkey in lookup messages, so we can verify the anthentic of the messages.
Check source code modified, the constants.xml and test_zilliqa_lookup.py.
Run a local test.
> Develop verify lookup node and messages

- src/libDB/ExplorerDB.cpp
- src/libDirectoryService/DSBlockPostProcessing.cpp
- src/libDirectoryService/DSBlockPreProcessing.cpp
- src/libDirectoryService/DirectoryService.cpp
- src/libLookup/Lookup.cpp
- src/libNode/DSBlockProcessing.cpp
- src/libNode/FallbackPreProcessing.cpp
- src/libNode/FinalBlockProcessing.cpp
- src/libNode/MicroBlockPostProcessing.cpp
- src/libUtils/DataConversion.cpp
- src/libUtils/DataConversion.h
- src/libUtils/HashUtils.h
- Applied random selection of the leader based on last txBlock Hash for the next consensus round.
- Fixed bug for using wrong function when received missing txn and about to reprocess the message.
- Unified the usage of BlockHash with the one obtained get by using GetBlockHash().
- Reduce the new ds members elected constaints in local test to 2
> Random shard leader selection

- src/libMessage/Messenger.cpp
- src/libNode/PoWProcessing.cpp
The new node cannot join because verify start pow message verification bug and variable not initialize bug.
Fix the bug.
Check file changes, only a few lines changed.
Run a local test, and run ./tests/Node/test_node_late.sh to rejoin 5 nodes.
> Fix new node cannot join problem

- constants.xml
- constants_local.xml
- src/libMediator/Mediator.cpp
- src/libUtils/ShardSizeCalculator.cpp
- tests/Utils/Test_ShardSizeCalculator.cpp
If we define COMM_SIZE > 0, always use this value as shard size.
Only when COMM_SIZE = 0, the shard size would be automatically calculated.
> Spec. change of COMM_SIZE

- src/common/Messages.h
- src/libData/BlockChainData/BlockLinkChain.h
- src/libData/BlockData/Block/CMakeLists.txt
- src/libData/BlockData/Block/FallbackBlockWShardingStructure.cpp
- src/libData/BlockData/Block/FallbackBlockWShardingStructure.h
- src/libDirectoryService/DSBlockPostProcessing.cpp
- src/libDirectoryService/ViewChangePostProcessing.cpp
- src/libLookup/Lookup.cpp
- src/libLookup/Lookup.h
- src/libLookup/Synchronizer.cpp
- src/libMediator/Mediator.h
- src/libMessage/Messenger.cpp
- src/libMessage/Messenger.h
- src/libMessage/ZilliqaMessage.proto
- src/libNode/DSBlockProcessing.cpp
- src/libNode/FallbackBlockProcessing.cpp
- src/libNode/FallbackPostProcessing.cpp
- src/libNode/Node.cpp
- src/libNode/ViewChangeBlockProcessing.cpp
- src/libPersistence/BlockStorage.cpp
- src/libPersistence/BlockStorage.h
Directory blocks viz. DS, VC, Fallback need to be stored and also be linked to the main chain i.e. the DS chain. The proposed idea is a BlockLinkChain which will link these blocks up.
A block link chain looks like : <total index, ds index, type, blockhash>
* Persistence storage for blocklink, VC, FB
* new data structure for storing FallbackBlock with ShardingStructure
* Lookup functions for fetching directory blocks (un tested)
> Directory Blocks Persistance Storage

- src/libData/BlockData/BlockHeader/MicroBlockHeader.cpp
- src/libData/BlockData/BlockHeader/MicroBlockHeader.h
- src/libMessage/Messenger.cpp
- src/libMessage/ZilliqaMessage.proto
- src/libNode/MicroBlockPreProcessing.cpp
Hardcoded DS block hash 0x77 and Tx Block hash 0x11 is used in Micro block, which has potential security issue.
Change the DS block hash and Tx Block hash to latest one.
Check MicroBlockPreProcessing.cpp.
> Fix hardcoded DS block hash in Micro block

- src/libDirectoryService/DSBlockPreProcessing.cpp
- src/libDirectoryService/DirectoryService.h
- src/libDirectoryService/PoWProcessing.cpp
Enable verification of PoW ordering to check the sharding structure from DS leader
Optimize the code, fix verify PoW ordering fail problem.
Check files modified
Run a local test
> Enable verification of PoW ordering to check the sharding structure from DS leader

- constants.xml
- constants_local.xml
- src/common/Constants.cpp
- src/common/Constants.h
- src/libPOW/pow.cpp
- src/libPOW/pow.h
Let user select which GPU use for mine.
Add an GPU_TO_USE variable in constants.xml, let user choose which GPU used for mine.
https://github.com/Zilliqa/Zilliqa/issues/691
Check file changed.
Find a machine with 2 GPUs, then change the constants.xml GPU_TO_USE option, and run ./build/tests/POW/Test_POW
> Support user select use which GPU for mine

- src/libMessage/Messenger.cpp
> Move the check for initialization to correct place

- src/libDirectoryService/DSBlockPreProcessing.cpp
- src/libDirectoryService/ViewChangePreProcessing.cpp
Some logs will print over 500 lines in 1000 nodes test, it will affect us to find out the useful information. These kind of log should only print out when we do a feature debug which set the DEBUG_LEVEL to higher.
Change the print log condition.
> Optimize logs for production run

- src/libDirectoryService/DSBlockPreProcessing.cpp
- src/libDirectoryService/ViewChangePreProcessing.cpp
Some logs will print over 500 lines in 1000 nodes test, it will affect us to find out the useful information. These kind of log should only print out when we do a feature debug which set the DEBUG_LEVEL to higher.
Change the print log condition.
> [testnetv3-dev] Optimize the logs for production run

- src/libMessage/Messenger.cpp
> [testnetv3-dev]Move the check for initialization to correct place

- src/libNetwork/P2PComm.cpp
- src/libZilliqa/Zilliqa.cpp
Fix lookup cpu usage 100% problem
> [testnetv3-dev] Fix lookup cpu usage 100% problem

- src/libLookup/Lookup.cpp
We'll see a message like this in the lookup node's state log:
```
[ 05:34:07:924 ][SHARD 0] Num nodes = 5
[ 05:34:07:924 ][SHARD 1] Num nodes = 5
[ 05:34:07:924 ][SHARDS] Total num nodes = 10
```
> Add state log for number of peers in shards

- src/libServer/JSONConversion.cpp
* Add gasPrice / gasLimit to JSON return by rpc server
* Change Amount to be a string from front-end
> Fix Json Conversion to include gasPrice/Limit

- src/libProtoServer/CMakeLists.txt
> Suppress -Wno-unused-parameter check in libProtoServer

- src/libNode/DSBlockProcessing.cpp
The check for the dsblock commhash should be later than vc being processed, As the m_dscommittee will be updated after vc.
> Adjust the order of check for DSBlock CommHash in ProcessVCDS

- src/libNode/DSBlockProcessing.cpp
(cherry picked from commit a683aa4465d2a22106e0729a9050c19caae7bd89)
> [testnetv3-dev] Adjust the order of VCDS check for DSBlock CommHash

- src/libDirectoryService/DSBlockPreProcessing.cpp
- src/libDirectoryService/DirectoryService.h
- src/libDirectoryService/PoWProcessing.cpp
- src/libMessage/Messenger.cpp
- src/libMessage/Messenger.h
- src/libMessage/ZilliqaMessage.proto
This is the implementation of #750 for branch testnetv3-dev.
Please refer to that PR for the full description.
> [testnetv3-dev] Added PoW solutions to DSBlock announcement

- scripts/download_proto3.sh
* bash script to download and install proto3
* bash script to download and install gRPC
* cmake script for FindgRPC
> Add support to download proto3

- constants.xml
- constants_local.xml
- src/common/Constants.cpp
- src/common/Constants.h
- src/libUtils/UpgradeManager.cpp
To be more flexible, put the upgrading URL location to constant file instead of hard-code inside our source code.
> Put upgrade location to constant file

- src/libNetwork/PeerManager.cpp
- src/libNetwork/RumorManager.cpp
- src/libRumorSpreading/RumorHolder.cpp
Moved from INFO/WARNING to DEBUG for gossip logging in most of cases except the limited ones.
Check logs.
Run the local test to see the minimized logging for gossip.
> [testnetv3-dev] Moved the logging for DEBUG mode only.

- src/libNetwork/PeerManager.cpp
- src/libNetwork/RumorManager.cpp
- src/libRumorSpreading/RumorHolder.cpp
Moved from INFO/WARNING to DEBUG for gossip logging in most of cases except the limited ones.
Check file changed.
Run the local test to see the minimized logging for gossip.
> Moved the logging for DEBUG mode only.

- src/libData/AccountData/Transaction.cpp
- src/libData/BlockData/Block/DSBlock.cpp
- src/libData/BlockData/Block/FallbackBlock.cpp
- src/libData/BlockData/Block/MicroBlock.cpp
- src/libData/BlockData/Block/TxBlock.cpp
- src/libData/BlockData/Block/VCBlock.cpp
- src/libData/BlockData/BlockHeader/BlockHashSet.h
- src/libData/BlockData/BlockHeader/TxBlockHeader.cpp
- src/libData/BlockData/BlockHeader/TxBlockHeader.h
- src/libDirectoryService/DSBlockPreProcessing.cpp
- src/libMessage/Messenger.cpp
- src/libMessage/ZilliqaMessage.proto
Improvement on comparison operator for several Data structure type, including:
- DSBlock, DSBlockHeader
- TxBlock, TxBlockHeader
- FallbackBlock, FallbackBlockHeader
- VCBlock
- Transaction
Also unified the naming for `m_dsBlockHeader` -> `m_dsBlockHash` in TxBlockHeader and MicroBlockHeader
> Improve comparison operator

- src/libData/BlockChainData/BlockLinkChain.h
Add one more check to see if the size of blockchain is 0.
> Fix a bug in blockchain where in the index 0 for not being pushed

- scripts/ci_make_image.sh
- scripts/make_image.sh
This PR changes the target registry that docker build on Travis will push image to.
N/A
> Change docker registry region

- src/libDirectoryService/DSBlockPreProcessing.cpp
- src/libDirectoryService/DirectoryService.cpp
- src/libDirectoryService/DirectoryService.h
- src/libMediator/Mediator.cpp
- src/libMessage/Messenger.cpp
- src/libMessage/Messenger.h
- src/libMessage/ZilliqaMessage.proto
- src/libPOW/pow.cpp
- src/libPOW/pow.h
DS backup verify the PoW winners that go into DS committee, to prevent malicious DS leader put invalid nodes into DS committee.
Add VerifyPoWWinner function.
It is a follow up PR after https://github.com/Zilliqa/Zilliqa/pull/750
Check function VerifyPoWWinner.
Run a local test.
> DS backup verify the PoW winners

- src/libMessage/Messenger.cpp
Refactor the std::equal to use the version with internal size check.
Refactor the std::equal to use the version with internal size check.
https://github.com/Zilliqa/Zilliqa/issues/648
> Use std::equal with internal size check

- README.md
> Update savant ide url in readme file

- src/libNode/Node.cpp
Fix the mutex block the microblock consensus jam and software crash
Don't use mutex guard the transaction verification. After verified, use mutex to guard them put into m_createdTxns.
https://github.com/Zilliqa/Issues/issues/274
> Fix micro block consensus blocked by mutex

- src/libLookup/Lookup.cpp
- src/libPersistence/Retriever.cpp
> [testnetv4-dev]Fixed incorrect check of AccountStore::DeserializeDelta result

- release.sh
- src/libUtils/UpgradeManager.cpp
- src/libUtils/UpgradeManager.h
constant file should be released to GitHub, and upgrading mechanism should contain this respectively.
> Upgrading mechanism with constant file

- release.sh
- src/libUtils/UpgradeManager.cpp
- src/libUtils/UpgradeManager.h
constant file should be released to GitHub, and upgrading mechanism should contain this respectively.
> [testnetv4-dev] Upgrading mechanism with constant file

- src/libNode/DSBlockProcessing.cpp
- src/libNode/Node.cpp
- src/libNode/Node.h
- src/libNode/ViewChangeBlockProcessing.cpp
- src/libPersistence/BlockStorage.cpp
- src/libPersistence/BlockStorage.h
- src/libPersistence/Retriever.cpp
- src/libPersistence/Retriever.h
- src/libValidator/Validator.cpp
Instead of retrieving just DS Blocks all VC/FB/DS should be retrieved
> Get Directory Blocks From Persistence

- tests/Message/CMakeLists.txt
- tests/Message/Test_Messenger_Consensus.cpp
- tests/libTestUtils/TestUtils.h
So far this PR covers commit and challenge phases.
Other consensus messages will be added in the next PRs.
> [testnetv4-dev] Added tests in Messenger for consensus

- src/libData/BlockChainData/BlockLinkChain.h
- src/libLookup/Lookup.cpp
- src/libNode/MicroBlockPreProcessing.cpp
- src/libNode/Node.cpp
Fix retrieve history failed but genesis account not added to blockchain problem
If StartRetrieveHistory return false, don't directly return the Install function, continue add genesis account. 
https://github.com/Zilliqa/Issues/issues/282
> Fix retrieve history failed but genesis account not added to blockchain problem

- src/libMessage/Messenger.cpp
Fix node crashed when calculate extra micro block info hash.
When the  extra micro info is empty, process without it.
> Fix node crashed when calculate extra micro block info hash

- src/libData/BlockChainData/BlockLinkChain.h
- src/libLookup/Lookup.cpp
- src/libNode/MicroBlockPreProcessing.cpp
- src/libNode/Node.cpp
Fix retrieve history failed but genesis account not added to blockchain problem
If StartRetrieveHistory return false, don't directly return the Install function, continue add genesis account.
Zilliqa/Issues#282
> [testnetv4-dev] Fix retrieve history failed but genesis account not added to blockchain problem

- src/libData/AccountData/AccountStore.cpp
- src/libMessage/Messenger.cpp
- src/libMessage/Messenger.h
> [testnetv4-dev] Fix state delta protobuf issue

- src/libData/AccountData/AccountStore.cpp
- src/libMessage/Messenger.cpp
- src/libMessage/Messenger.h
> Fix state delta protobuf issue

- src/libConsensus/ConsensusLeader.cpp
Previous behavior before the consensus subsets were implemented was to proceed with challenge phase when we receive the minimum 2/3 commits.
After subsets was implemented, we now have a time window to receive as many commits as we want, even above the minimum 2/3.
This PR brings back the old behavior (just receive minimum commits, no timer) when we set `NUM_CONSENSUS_SUBSETS` to 1 in the constants file.
> Avoid commit window when NUM_CONSENSUS_SUBSETS=1

- constants.xml
- constants_local.xml
- src/common/Constants.cpp
- src/common/Constants.h
- src/libData/AccountData/AccountStoreSC.h
- src/libData/AccountData/AccountStoreSC.tpp
Add scilla checker during the processing of transaction that trying to deploy a contract
> Call scilla checker during contract deployment

- src/libData/AccountData/AccountStoreSC.tpp
> Fix scilla runner output parsing issue

- src/libData/AccountData/AccountStoreSC.tpp
> [testnetv4-dev] Fix scilla runner output parsing issue

- src/libDirectoryService/DSBlockPreProcessing.cpp
* Fix issue https://github.com/Zilliqa/Zilliqa/issues/765
> fix node distribution among shards

- src/cmd/sendcmd.cpp
Removal of unsafe function `strcmp` from the utility `sendcmd`
> Remove unsafe function from sendcmd

- src/libMessage/Messenger.cpp
> Fix contract state delta serialization issue

- src/libDirectoryService/DirectoryService.h
> Fix lucky draw logic

- src/libCrypto/Schnorr.cpp
Similar to #834.  The fix was missed in one other place.
> Fix potential out-of-bounds in resizing code

- src/libMessage/Messenger.cpp
- src/libNetwork/P2PComm.cpp
- tests/Crypto/Test_Sha2.cpp
- tests/Data/Test_Block.cpp
- tests/Message/Test_Message.cpp
> Replace unsafe std::equal with the one with size check

- src/cmd/CMakeLists.txt
- src/libMessage/Messenger.cpp
- src/libMessage/Messenger.h
- src/libMessage/ZilliqaMessage.proto
- src/libNetwork/CMakeLists.txt
- src/libNetwork/Peer.cpp
- src/libNetwork/Peer.h
> protobuf peer serialize/deserialize

- src/libDirectoryService/DirectoryService.cpp
- src/libLookup/Lookup.cpp
1. Reject  Tx block of prev DS epoch
2. Fetch DS info for rejoinAsDS()
3. Fix leader consensus id after rejoin as ds
> DS rejoin fix.

- src/libData/AccountData/AccountStoreSC.tpp
This PR check whether Account object is a null ptr before proceeding with the rest of the operation.
> Check for nullptr in AccountStoreSC

- src/libData/AccountData/AccountStore.cpp
Fix core dump when GetAccountStates
> Init AccountStore when run Deserialize

- src/libDirectoryService/FinalBlockPostProcessing.cpp
- src/libNetwork/P2PComm.cpp
Added / Modified logging for bench-marking against different message sizes.
Please check the file changed.
> Add logging for benchmarking

- src/libLookup/Lookup.cpp
- src/libNode/DSBlockProcessing.cpp
- src/libNode/Node.cpp
- src/libNode/Node.h
- src/libNode/PoWProcessing.cpp
Node rejoins the network after it looses PoW. 
Node is able to rejoin if COMM_SIZE = now_of_nodes_doing_pow - 1. and check if it does PoW in the next epoch.
> Fix normal node failing PoW and getting stuck.

- src/libCrypto/Schnorr.cpp
In `Schnorr.cpp`, when memory allocation failures happen, in certain cases, it will proceeds to execute normally. Such behavior can be unpredictable. This PR properly address these cases.
> Fix schnorr memory allocation handling

- src/libData/BlockData/BlockHeader/DSBlockHeader.h
- src/libData/BlockData/BlockHeader/FallbackBlockHeader.cpp
- src/libData/BlockData/BlockHeader/FallbackBlockHeader.h
- src/libData/BlockData/BlockHeader/VCBlockHeader.cpp
- src/libData/BlockData/BlockHeader/VCBlockHeader.h
- src/libDirectoryService/DSBlockPreProcessing.cpp
- src/libDirectoryService/ViewChangePreProcessing.cpp
- src/libMessage/Messenger.cpp
- src/libMessage/ZilliqaMessage.proto
- src/libNode/FallbackPreProcessing.cpp
- tests/libTestUtils/TestUtils.cpp
* Add a prevHash field in VC/FB block which refer to the previous DS/VC/FB block.
* Verify previous hash.
> Add prev blockHash to DS/VC/FB blocks

- src/libLookup/Lookup.cpp
Use reference instead of value to improve efficiency
> Use reference instead of value to improve efficiency

- daemon/CMakeLists.txt
- daemon/ZilliqaDaemon_AWS.cpp
- tests/Zilliqa/daemon_restart.py
Daemon should re-launch Zilliqa process un-limited times, however it's not so far. We use this PR to fix this bug.
> Fix daemon cannot re-launch zilliqa process bug

- src/libDirectoryService/MicroBlockProcessing.cpp
- src/libNode/Node.cpp
> Refines for DM1/3 test cases

- src/libData/BlockData/Block/TxBlock.cpp
- src/libData/BlockData/BlockHeader/TxBlockHeader.cpp
- src/libData/BlockData/BlockHeader/TxBlockHeader.h
- src/libDirectoryService/DirectoryService.h
- src/libDirectoryService/FinalBlockPreProcessing.cpp
- src/libLookup/Lookup.cpp
- src/libLookup/Synchronizer.cpp
- src/libMessage/Messenger.cpp
- src/libMessage/ZilliqaMessage.proto
- src/libNode/FinalBlockProcessing.cpp
- src/libServer/JSONConversion.cpp
- tests/Lookup/Test_LookupNodeForTxBlock.cpp
- tests/Message/Test_Messenger_Primitives.cpp
- tests/Persistence/Test_TxPersistence.cpp
- tests/libTestUtils/TestUtils.cpp
Related issue:
https://github.com/Zilliqa/Issues/issues/310
> Remove TxBlockHeader::GetNumMicroBlockHashes

- src/libLookup/Lookup.cpp
- src/libLookup/Lookup.h
Add partial retrieval flag for RetrieveDSBlocks
> [testnetv5-dev] Add partialRetrival flag for RetrieveDSBlocks

- src/libNode/MicroBlockPreProcessing.cpp
- src/libNode/Node.cpp
> [testnetv5-dev] Wrap operation about m_createdTransaction with mutex in some corner case

- src/libNode/PoWProcessing.cpp
> Start thread when the first solution is sent

- src/libLookup/Lookup.cpp
Fix lookup jammed at processing message
Check if the tx blocks going to send out, if it is empty, then don't send.
> [testnetv5-dev] Fix lookup jammed at processing message

- src/libLookup/Lookup.cpp
Fix lookup jammed at processing message
Check the tx blocks going to send out. If it is empty, don't send.
> Fix lookup jammed at processing message

- src/libData/AccountData/AccountStore.cpp
> Fix dead lock in AccountStore::Deserialize

- src/libData/AccountData/AccountStore.cpp
> [testnet v5]  Fix dead lock in AccountStore::Deserialize

- src/libNode/PoWProcessing.cpp
> [testnet v5] Launch thread after first PoW solution

- tests/Data/CMakeLists.txt
- tests/Data/Test_Account.cpp
- tests/Data/Test_CircularArray.cpp
- tests/libTestUtils/TestUtils.cpp
- tests/libTestUtils/TestUtils.h
Extension of libTestUtils, Test_CircularArray and finally TestAccount.
> Extension of libTestUtils, Test_CircularArray and finally TestAccount.

- tests/Utils/CMakeLists.txt
- tests/Utils/Test_SWInfo.cpp
Unit test for libUtils/SWInfo.cpp  - test of copy constructor and getters - I consider this file covered
> SWInfo test of copy constructor and getters

- src/libData/AccountData/Account.cpp
- src/libData/AccountData/Account.h
Move definitions of methods from Account.h to Account.cpp
> Refactor Account class

- src/libPersistence/BlockStorage.cpp
- src/libUtils/Logger.cpp
- src/libUtils/Logger.h
- src/libUtils/ThreadPool.h
Some minor changes to make reading the testnet logs easier:
1. Avoid printing out all the state deltas
2. We don't need to print the word "TID" in every line in the log
3. Remove the newline at the end of the job pool log
> Some log cleanup

- src/cmd/gentxn.cpp
- src/libZilliqa/Zilliqa.cpp
> GenTxn Offset by one and check for NULL

- src/libUtils/GetTxnFromFile.h
> fix filename

- tests/Utils/Test_SWInfo.cpp
- tests/libTestUtils/TestUtils.h
Suppress more warnings from third-party libraries.
N/A
> Suppress build error on macOS Mojave

- src/libLookup/Lookup.cpp
- src/libNode/DSBlockProcessing.cpp
Once the rejoin started because of DSBlock over time, the node should reject the DSBlock.
> Reject DSBlock when just started rejoin

- daemon/ZilliqaDaemon_AWS.cpp
- daemon/run.sh
- src/libLookup/Lookup.cpp
- src/libNode/Node.cpp
- src/libNode/Node.h
- src/libPersistence/Retriever.cpp
Apply node recovery on lookup node
> Node recovery on lookup node

- src/libNode/Node.cpp
- src/libPersistence/Retriever.cpp
- src/libPersistence/Retriever.h
Refactor the function of retriever to improve code style
Refactor the function of retriever to improve code style
Check the Retriever.cpp
> Refactor the function of retriever to improve code style

- src/libNode/PoWProcessing.cpp
Extend the wait time for DS block
Extend the wait time for DS block
https://github.com/Zilliqa/Issues/issues/329
> Extend the wait time for DS block

- src/libLookup/Lookup.cpp
- src/libUtils/GetTxnFromFile.h
> Add more logging

- src/libData/AccountData/AccountStore.cpp
- src/libLookup/Lookup.cpp
Fix following bugs of node recovery:
1. If the recovery node is not lagging behind, stuck happened for always asking for new tx block
2. With blockchain just initialized, recovery would lead to FATAL error
> Node recovery bug fix

- src/libLookup/Lookup.cpp
- src/libNode/Node.cpp
> More logs for logging peer

- src/libPOW/pow.cpp
Don't init full mine context when use GPU to mine, because it will take 1GB RAM but didn't been used.
Check if using GPU to do mining, if yes, then don't initialize full mine context.
Check libPOW.cpp
Run ./build/tests/POW/Test_POW
> Don't init full mine context when use GPU to mine

- src/libData/AccountData/AccountStoreBase.h
- src/libNode/DSBlockProcessing.cpp
- src/libNode/MicroBlockPreProcessing.cpp
- src/libNode/Node.h
> Fix Minor Bug May Causing Smart Contract Deployment Failure 

- src/libNode/DSBlockProcessing.cpp
> Change TBC place

- src/libDirectoryService/DSBlockPreProcessing.cpp
Fix minor log message where the casing is not consistent. This fix is required to reflect what is on our test plan.
> Fix wrong lower case for vc log message

- src/libDirectoryService/DirectoryService.cpp
- src/libNode/Node.cpp
- src/libNode/Node.h
- src/libNode/PoWProcessing.cpp
Fix new node failed to rejoin problem.
1. Fix when boostrap failed to join testnet, and start to rejoin with retrieve history, but no history to retrieve and didn't add genesis block problem.
2. Fix duplicated rejoin procedure when in StartPoW function.
Run a local 20 nodes test, set COMM_SIZE to 8.
> Fix new node failed to rejoin problem

- src/libData/AccountData/Transaction.cpp
- src/libValidator/Validator.cpp
> Fix 0 division in GetShardIndex

- src/libDirectoryService/DSBlockPostProcessing.cpp
- src/libDirectoryService/DirectoryService.cpp
- src/libDirectoryService/FinalBlockPostProcessing.cpp
- src/libDirectoryService/ViewChangePostProcessing.cpp
- src/libLookup/Lookup.cpp
- src/libLookup/Lookup.h
- src/libNode/DSBlockProcessing.cpp
- src/libNode/FallbackPostProcessing.cpp
- src/libNode/FinalBlockProcessing.cpp
- src/libNode/MicroBlockPostProcessing.cpp
- src/libNode/Node.cpp
- src/libNode/PoWProcessing.cpp
- src/libZilliqa/Zilliqa.cpp
Refactor sync type and stop mining if wait for DS block timeout
Refactor sync type and stop mining if wait for DS block timeout
Fix node started rejoin but still mining problem.
> Refactor sync type and stop mining if timeout

- src/libNode/Node.cpp
Upgraded lookup node should not ask offline lookup node.
> Upgrade mechanism bug fix

- src/libLookup/Lookup.cpp
- src/libNode/DSBlockProcessing.cpp
- src/libNode/FinalBlockProcessing.cpp
> Enable sender thread on every lookup

- src/libNode/Node.cpp
For node recovery/upgrading failed and apply rejoin, change message type to WARNING.
> Change message type to WARN for recovery/upgrade failed

- src/libDirectoryService/DirectoryService.h
- src/libDirectoryService/PoWProcessing.cpp
Drop PoW submission if 
- Soln come from a DS member (IP and port check)
- Soln come from a DS pubkey
> Disallow DS to submit PoW

- src/libNetwork/RumorManager.cpp
Fix the potential crash accessing invalid iterator.
Its just that we never reach that condition because we always receive PUSH for what we asked for.
Check the file changed
> Fix potential crash

- src/libUtils/SafeMath.h
- src/libUtils/SafeMath.tpp
- tests/Utils/Test_SafeMath.cpp
According to NCC-2018-001, safemath may has problem on following scenarios:
Subtraction with an unsigned type
Division and multiplication with a signed type
Additions, subtractions and multiplications with a signed type
This PR will fix the bugs and add more unit tests respectively.
> [NCC-2018-001] Fix safemath potential issue

- src/libData/AccountData/TxnPool.h
> If the txn has same nonce and pubkey and gas Price, keep the one with least TranID

- CMakeLists.txt
- build.sh
- src/libDirectoryService/DirectoryService.h
- src/libDirectoryService/FinalBlockPostProcessing.cpp
- src/libDirectoryService/FinalBlockPreProcessing.cpp
- src/libNode/MicroBlockPreProcessing.cpp
SkipDSMicroBlock shouldn't be allowed as a malicious DS leader may try to interrupt the DS MicroBlock even if it's capable of being processed by a good leader.
> Remove SkipDSMicroBlock

- src/libData/BlockChainData/BlockLinkChain.h
- src/libNode/Node.cpp
- src/libPersistence/Retriever.cpp
Refactor the GetBuiltDSComm function
The get function shouldn't modify the property of class. Change to use set function to update it. It will be easier for people to read and debug the code.
> Refactor the GetBuiltDSComm function

- src/libLookup/Lookup.cpp
> Lookup send to leader

- src/libDirectoryService/DirectoryService.cpp
Fix ds difficulty adjustment too frequent
Fix ds difficulty adjustment too frequent, change the max adjust threshold to 49 from 9. So with some number difference of PoW submissions between DS leader and lookup, the DS difficulty verify still can pass.
[INFO   ][ 2792][13:03:44:  9][CalculateNewDSDifficulty      ][Epoch 5] dsDifficulty 5, currentDSNodes 300, dsPowSubmissions 239
[INFO   ][ 2792][13:03:44:  9][CalculateNewDifficulty        ][Epoch 5] currentDifficulty 3, expectedNodes 900, powSubmissions 897
root@ip-172-20-32-189:/run/zilliqa# grep rimm zilliqa-00001-log.txt 
[INFO   ][  146][12:56:11:623][SortPoWSoln                   ] Trimming the solutions sorted list from 924 to 900 to avoid going over COMM_SIZE 300
[INFO   ][  146][12:56:11:705][SortPoWSoln                   ] …
> Fix ds difficulty adjustment too frequent

- src/libNode/PoWProcessing.cpp
> Send PoW to leader

- src/libDirectoryService/DirectoryService.cpp
- src/libLookup/Lookup.cpp
> use hash for random

- README.md
> Update README - Maoshanwang info

- src/libServer/JSONConversion.cpp
> Fix libServer build

- src/libDirectoryService/DirectoryService.cpp
- src/libDirectoryService/PoWProcessing.cpp
- src/libNode/Node.cpp
- src/libNode/PoWProcessing.cpp
Send Pow submission to DS leader.
DS leader accepts the POW submission.
~~Blocker observed is that leader calculation of DS and normal node results in different leader id.~~
> Fix PoW send

- src/libDirectoryService/DSBlockPreProcessing.cpp
Make proof of reputation can work again
Choose the top reputation/priority nodes and verify top reputation/priority nodes before do the PoW trimming.
https://github.com/Zilliqa/Issues/issues/341
> Make proof of reputation can work again

- README.md
The previous one is broken since the wiki was updated.
> Fix CUDA and OpenCL link in README

- docker/Dockerfile
- docker/Dockerfile.cuda
- docker/Makefile
- docker/README.md
Add instructions to build the release version images. A Dockerfile is ported from nvidia to install dependencies needed for nvidia-docker
This PR doesn't include code changes
> Add release image build instructions

- src/libNetwork/Guard.cpp
> inet_ntop instead of inet_ntoa

- src/libConsensus/ConsensusLeader.cpp
This PR does 2 things:
1. It changes a check on the `subsetID`.  Instead of comparing against `NUM_CONSENSUS_SUBSETS`, the comparison should be against the actual size of the subsets container `m_consensusSubsets`, because in some situations we set this container to be size 1 (see `GenerateConsensusSubsets`).
2. It makes sure `m_mutex` is properly acquired in two places:
- In the worker thread launched inside `StartConsensus` before calling `GenerateConsensusSubsets`
- At the start of `ProcessMessageCommitCore`
The reason is that `m_commitMap` and other related instance members may be modified in other threads.
> Fix potential vulnerabilities in ConsensusLeader code

- src/libNode/Node.cpp
- src/libNode/Node.h
When recovery the entire network, the nodes' IP may change because of the re-launch of cluster/testnet. Thus we need to change IP address according to the external ip-mapping table, after re-launching and retrieving database. Here is the file format of ipMapping.xml:
\<mapping\>
\<peer\>\<ip\>1.1.1.1\</ip\>\<port\>1234\</port\>\<pubkey\>0259C63E4A2A016D38DFD342148F1C740481659FC794384BCE1FA97DF84CAADEDE\</pubkey\>\</peer\>
\<peer\>\<ip\>8.8.8.8\</ip\>\<port\>5678\</port\>\<pubkey\>03D0ECA6DB47212955B0A78D11597DA4481D2E28BF136430DE26D7B8AEF2E6AC57\</pubkey\>\</peer\>
\</mapping\>
> Read IP mapping table after retrieving database

- src/libConsensus/ConsensusCommon.cpp
This PR fixes two out-of-bounds access in ConsensusCommon.
> Check the message size in CanProcessMessage and GetConsensusID

- src/libConsensus/ConsensusLeader.cpp
- src/libData/BlockData/BlockHeader/DSBlockHeader.cpp
- src/libData/BlockData/BlockHeader/FallbackBlockHeader.cpp
- src/libData/BlockData/BlockHeader/MicroBlockHeader.cpp
- src/libData/BlockData/BlockHeader/TxBlockHeader.cpp
- src/libData/BlockData/BlockHeader/VCBlockHeader.cpp
- src/libMediator/Mediator.cpp
- src/libRumorSpreading/RumorHolder.cpp
Added some missing member variables to resolve uninitialized variable errors reported by static code analysis tools.
> Initialize all member variables in constructors

- CMakeLists.txt
- constants.xml
- constants_local.xml
- src/cmd/CMakeLists.txt
- src/cmd/grepperf.cpp
- src/common/Constants.cpp
- src/common/Constants.h
- src/common/MessageNames.h
- src/libNetwork/P2PComm.cpp
- src/libNetwork/P2PComm.h
- src/libNode/FinalBlockProcessing.cpp
- src/libZilliqa/Zilliqa.cpp
- src/libZilliqa/Zilliqa.h
- tests/Message/CMakeLists.txt
- tests/Message/Test_MessageName.cpp
Log message name to track the size and process time. And develop grepperf tool to grep message size and processing time from Zilliqa log.
Add FormatMessageName function in Zilliqa class. Add unit test case for FormatMessageName. Add grepperf tool.
Run follow command after run a local test.
./build/bin/grepperf ./build/local_run/node_0001/zilliqa-00001-log.txt ./build/local_run/node_0001/grepperf_result.txt
> Log message name to track the size and process time

- src/libZilliqa/Zilliqa.cpp
> Avoid printing private key information in the log file

- src/libMessage/Messenger.cpp
This PR just makes sure that `AddAccount(address)` was successful before dereferencing the same account.
> Check for null oriAccount before dereferencing

- src/libData/BlockData/BlockHeader/DSBlockHeader.h
- src/libLookup/Lookup.cpp
- src/libLookup/Lookup.h
- src/libMessage/Messenger.cpp
- src/libMessage/Messenger.h
- src/libMessage/ZilliqaMessage.proto
- src/libNode/MicroBlockPreProcessing.cpp
- src/libNode/Node.cpp
- src/libNode/Node.h
Related issue: https://github.com/Zilliqa/Issues/issues/366
> Always buffer txns from lookup and only do gossip during txn distribution

- src/libLookup/Lookup.cpp
> Fix crash of calling IsLookupNode

- src/libDirectoryService/DSBlockPostProcessing.cpp
- src/libDirectoryService/DSBlockPreProcessing.cpp
- src/libDirectoryService/FinalBlockPostProcessing.cpp
- src/libDirectoryService/MicroBlockProcessing.cpp
- src/libNode/DSBlockProcessing.cpp
- src/libNode/FinalBlockProcessing.cpp
- src/libNode/MicroBlockPostProcessing.cpp
- src/libNode/MicroBlockPreProcessing.cpp
- tests/Zilliqa/profile_time.py
Develop the script to profile consensus time from state log
Add tests/Zilliqa/profile_time.py to fetch the pow, DS consensus, MB consens and FB consensus timing from state log.
> Develop the script to profile consensus time from state log

- src/libData/BlockData/BlockHeader/BlockHashSet.h
- src/libData/BlockData/BlockHeader/DSBlockHeader.cpp
- src/libData/BlockData/BlockHeader/DSBlockHeader.h
- src/libDirectoryService/DSBlockPostProcessing.cpp
- src/libDirectoryService/DSBlockPreProcessing.cpp
- src/libDirectoryService/DirectoryService.h
- src/libMessage/Messenger.cpp
- src/libMessage/Messenger.h
- src/libMessage/ZilliqaMessage.proto
- src/libNode/DSBlockProcessing.cpp
- src/libNode/Node.h
- tests/Message/Test_Messenger_Primitives.cpp
> Remove TxSharingAssignment

- src/libDirectoryService/DSBlockPostProcessing.cpp
- src/libLookup/Lookup.cpp
- src/libMediator/Mediator.h
- src/libNetwork/ShardStruct.h
- src/libNode/DSBlockProcessing.cpp
- src/libNode/Node.cpp
- src/libNode/Node.h
- src/libNode/PoWProcessing.cpp
Refactor the get DS leader peer into a function
Add Node::GetDSLeaderPeer function, so it can be reused in multiple places. Easy to maintain.
https://github.com/Zilliqa/Issues/issues/358
> Refactor the get DS leader peer into a function

- tests/Data/CMakeLists.txt
- tests/Data/Test_Transaction.cpp
- tests/libTestUtils/TestUtils.cpp
- tests/libTestUtils/TestUtils.h
Increase coverage of AccountData/Transaction.cpp
Add more functions to libTestUtils
Lines 92% - further progress possible only when mocking is used
Functions 100%
> Increase coverage of AccountData/Transaction.cpp

- src/libMediator/Mediator.cpp
- src/libNode/FinalBlockProcessing.cpp
Node start to rejoin if missed some tx blocks
https://github.com/Zilliqa/Issues/issues/372
> Node start to rejoin if missed some tx blocks

- src/libUtils/ThreadPool.h
Remove unnecessary cv usage from ThreadPool
Please check the file used.
> Remove unnecessary cv usage from ThreadPool

- src/libDirectoryService/DirectoryService.cpp
- src/libNode/Node.cpp
Refactor FinishRejoinAsDS function to use GetDSLeaderPeer
> Refactor FinishRejoinAsDS function to use GetDSLeaderPeer

- tests/Data/Test_CircularArray.cpp
Lines covered: 93.8%
Functions covered: 25%
Not able to cover remaining size() and capacity() - because of oneline definition in header probably.
> Increse coverage of libData/DataStructures/CircularArray.h

- src/libUtils/ThreadPool.h
Change the log of job pool from 10 to 100
> Change the log of job pool from 10 to 100

- src/libDirectoryService/Coinbase.cpp
- src/libMessage/Messenger.cpp
- src/libMessage/Messenger.h
- src/libNode/FinalBlockProcessing.cpp
Add logs to tell if the current node has received some reward
> Add logs for coinbase

- src/libNetwork/P2PComm.cpp
- src/libUtils/SafeMath.h
- src/libUtils/SafeMath.tpp
- tests/Utils/Test_SafeMath.cpp
Make SafeMath more safe, and apply on broadcast message.
> Fix SafeMath potential bug and apply on broadcast message

- src/libMessage/Messenger.cpp
- src/libMessage/Messenger.h
- src/libMessage/ZilliqaMessage.proto
- src/libNetwork/PeerManager.cpp
- tests/Zilliqa/test_zilliqa_NAT.py
- tests/Zilliqa/test_zilliqa_archival.py
- tests/Zilliqa/test_zilliqa_late.py
- tests/Zilliqa/test_zilliqa_local.py
- tests/Zilliqa/test_zilliqa_lookup.py
To mitigate rogue-key attacks, this PR does the following:
1. Protobuf the `PeerManager::HELLO` message
2. Add a signature to the message (the sender signs over its pubkey and listen port)
3. Verify the signature at the receiving end
*Note that the `PeerManager::HELLO` function is no longer in use in either of our local or cloud testnets (we read the initial keys from file in the `PeerManager` constructor), but upon the recommendation of our auditors, we will be making this fix.*
Additionally, this PR fixes the python scripts after the newline was added to the genkeypair utility in #1041
> Add signature validation to PeerManager Hello message

- src/depends/libethash-cuda/CUDAMiner.cpp
- src/libPOW/pow.cpp
Fix select GPU index other than 0 software crash problem
Set the correct gpu going to use before do mining.
https://github.com/Zilliqa/Zilliqa/issues/1015
The community member already help to test the branch on there 6 Nividia cards machine.
> Fix select GPU index other than 0 software crash problem

- src/libServer/spec.json
These are not implemented and no longer needed.
> Removed getTransactionHistory and getCode from JSON spec

- src/libData/AccountData/AccountStoreSC.h
- src/libData/AccountData/AccountStoreSC.tpp
So that we can call ParseCreate/CallContractOutput as an utility function
> Refactor ParseContractOutput

- src/libUtils/Logger.cpp
Just a minor enhancement for performance and log size - just reduce the level shown in the log to the first 4 characters.
Before this PR:
```
[INFO   ][ 3503][18-12-13T09:21:31.399][ProcessMessageCommitCore      ] BEGIN
[WARNING][ 3503][18-12-13T09:21:31.399][CheckState                    ] Action PROCESS_COMMIT not allowed in state CHALLENGE_DONE
```
After this PR:
```
[INFO][ 3503][18-12-13T09:21:31.399][ProcessMessageCommitCore      ] BEGIN
[WARN][ 3503][18-12-13T09:21:31.399][CheckState                    ] Action PROCESS_COMMIT not allowed in state CHALLENGE_DONE
```
> Simplify log level output

- src/libUtils/SafeMath.tpp
Once you have ruled out the problematic cases (the case b == 0; and the case b == -1 and a == MIN_VALUE), no overflow/underflow is actually possible, so the test a == b * c + a % b is unnecessary
> Removed unnecessary check from div_signint

- src/libDirectoryService/Coinbase.cpp
- src/libDirectoryService/DSBlockPostProcessing.cpp
- src/libDirectoryService/FinalBlockPostProcessing.cpp
- src/libDirectoryService/MicroBlockProcessing.cpp
- src/libNode/DSBlockProcessing.cpp
- src/libNode/FinalBlockProcessing.cpp
- src/libNode/MicroBlockPostProcessing.cpp
- src/libNode/MicroBlockPreProcessing.cpp
- src/libNode/Node.cpp
- tests/Zilliqa/profile_time.py
Enhance state log and enhance script to fetch information from it
build zilliqa, run a local test, execute command python ./tests/Zilliqa/profile_time.py ./build/local_run ./profile_result.txt and check the result in ./profile_result.txt
> Enhance state log and enhance script to fetch information from it

- .gitmodules
- CMakeLists.txt
- README.md
- cmake/InstallOpenSSL.cmake
- docker/Dockerfile
- scripts/ci_install_deps.sh
- src/libCrypto/CMakeLists.txt
- tests/Utils/CMakeLists.txt
On Mac, the package `openssl@1.1` installed through brew is keg-only, which won't have the conflict with system‘s OpenSSL. On Ubuntu, we link OpenSSL 1.1.1 statically to avoid link conflict in dynamic linking. This PR is a complement and should be merged into to #1034 first.
> Safely install openssl 1.1.1

- src/libMessage/Messenger.cpp
> Cast uint128_t to int256_t when trying to get negative value

- src/libServer/Server.cpp
Update Json RPC according to https://www.jsonrpc.org/specification#response_object
> Standardise RPC functions.

- constants.xml
- constants_local.xml
- src/common/Constants.cpp
- src/common/Constants.h
- src/libData/AccountData/TxnOrderVerifier.h
- src/libDirectoryService/DSBlockPreProcessing.cpp
- src/libDirectoryService/DirectoryService.cpp
- tests/Data/Test_TxnOrder.cpp
- tests/Zilliqa/profile_time.py
Add tolerance to different ip address in processing sharding structure
https://github.com/Zilliqa/Issues/issues/373
> Add tolerance to different ip address in processing sharding structure

- src/libServer/JSONConversion.cpp
- src/libServer/Server.cpp
- src/libServer/Server.h
This PR covers two bug fixes in RPC server:
1. fix mbinfos temporary variable bug
2. change return type of GetNumTxEpoch
> fix mbInfos and return string in GetNumTxnsTxEpoch

- tests/Persistence/Test_DSPersistence.cpp
Re-enable ds persistence unit test that was disabled previously
Run the unit test
> re-enable ds persistence unit test

- src/libNode/Node.cpp
> UpdateStateTrieAll after adding genesis account

- src/libDirectoryService/ViewChangePreProcessing.cpp
This PR add a mutex to protect `m_mediator.m_DSCommittee` against any concurrency issue in `RunConsensusOnViewChange`
> Fix potential concurrency issue when running view change

- src/libServer/Server.cpp
> Add missing check for NullAddress for normal txn

- src/libLookup/Lookup.cpp
- src/libServer/Server.cpp
the adding of `continue` if GetTxnFromFile::GetFromFile failed as per request from @KaustubhShamshery
> Check gas price when receiving rpc request as lookup

- src/libServer/Server.cpp
> Fix sent ds bug

- src/libLookup/Lookup.cpp
- src/libLookup/Lookup.h
> Remove Rsync used in Lookup

- constants.xml
- constants_local.xml
- src/common/Constants.cpp
- src/common/Constants.h
- src/libDirectoryService/DSBlockPreProcessing.cpp
- src/libDirectoryService/DirectoryService.h
- src/libUtils/ShardSizeCalculator.cpp
- src/libUtils/ShardSizeCalculator.h
- tests/Utils/Test_ShardSizeCalculator.cpp
The current sharding trims all extra PoW submissions beyond multiples of shard size.
This PR introduces a tolerance, where a shard can go below or above shard size as long as it is within the tolerance value.
Here is an example when running the algorithm (see `tests/Utils/Test_ShardSizeCalculator.cpp`).
Here, the shard size is set to 20, and the tolerance is +/- 10.
The node count runs from 0 to 80.
```
[20074][18-12-24T09:59:13.995][GenerateShardCounts           ] BEGIN
[20074][18-12-24T09:59:13.995][GenerateShardCounts           ] Default shard size          = 20
[20074][18-12-24T09:59:13.995][GenerateShardCounts           ] Minimum allowed shard size  = 10
[20074][18-12-24T09:59:13.995][GenerateShardCounts           ] Maximum allowed shard size  = 30 …
```
> Add tolerance to sharding algorithm

- src/libDirectoryService/Coinbase.cpp
- src/libNode/FinalBlockProcessing.cpp
Refine the reward log to easy understand
https://github.com/Zilliqa/Issues/issues/387
> Refine the reward log to easy understand

- src/libData/BlockData/BlockHeader/FallbackBlockHeader.cpp
- src/libData/BlockData/BlockHeader/FallbackBlockHeader.h
- src/libDirectoryService/DSBlockPostProcessing.cpp
- src/libDirectoryService/DirectoryService.h
- src/libDirectoryService/ViewChangePostProcessing.cpp
- src/libDirectoryService/ViewChangePreProcessing.cpp
- src/libMessage/ZilliqaMessage.proto
- src/libNode/FallbackBlockProcessing.cpp
- src/libNode/Node.cpp
- src/libNode/Node.h
> Unify the type for consensusMyID and consensusLeaderID

- src/libData/AccountData/TransactionReceipt.cpp
- src/libData/AccountData/TransactionReceipt.h
- src/libValidator/Validator.cpp
> Add EpochNum in TxnReceipt

- src/libPersistence/BlockStorage.cpp
- src/libPersistence/BlockStorage.h
- tests/Persistence/Test_Diagnostic.cpp
This PR adds a more convenient way to read out the contents of the diagnostic database.
The current way is not so easy to use as you have to iterate thru the db by inputting the block number.
Also, the database count isn't stored in the db, so it is zero when you launch your code (not a major issue right now, and will be addressed later).
With the new function in this PR, we can just dump out all the contents of the diagnostic data database for our monitoring tools to easily use.
> Updated diagnostic data retrieval

- src/libNode/Node.cpp
Avoid gossip message being rumored by rejoining node.
> Init RumorManager with empty peers in Node::CleanVariables

- src/libLookup/Lookup.cpp
Remove superfluous part from Lookup::SetAboveLayer()
> Remove superfluous part from Lookup::SetAboveLayer()

- src/libConsensus/ConsensusLeader.cpp
> Log the consensus response count

- scripts/list_shards.py
- tests/Zilliqa/list_shards.py
Usage: `list_shards.py [Lookup zilliqa log]`
Output:
```
EPOCH 1
,SHARD 0,SHARD 1,SHARD 2,
PEER 0,34.221.112.135,34.217.2.46,52.35.38.137,
PEER 1,54.244.181.197,54.201.204.147,34.218.79.241,
PEER 2,34.210.85.132,54.245.58.76,54.69.42.15,
...
EPOCH 100
,SHARD 0,SHARD 1,SHARD 2,
PEER 0,54.184.30.67,34.221.64.121,34.214.222.177,
PEER 1,34.220.159.239,52.11.115.149,34.219.252.89,
PEER 2,35.163.96.252,18.236.120.105,54.149.150.242,
...
```
> Script for generating csv-style shard table from lookup zilliqa log

- src/libCrypto/Schnorr.h
Remove `<<` and `string()` from PrivKey to prevent any accidental printing of private key.
> Remove << and string() from privkey

- src/libServer/AddressChecksum.h
- tests/Data/CMakeLists.txt
- tests/Data/Test_EIP.cpp
To avoid confusion between addresses of different block chains, functionality for zilliqa's own checksum is added to differentiate.
> EIP checksum

- src/libLookup/Lookup.cpp
- src/libNode/Node.cpp
There may be a case in which same information may be copied into lookup vector and seed vector.
> Exclude lookup already in m_lookupNodes

- src/libDirectoryService/Coinbase.cpp
- src/libDirectoryService/DirectoryService.h
- src/libNetwork/Guard.h
The guard mode nodes, will not be awarded rewards and skipped during coinbase.
> Change coinbase to exclude

- src/libServer/AddressChecksum.h
The current master build has some build problem due to The pr for data conversion merging before the PR for EIP
> Update with master

- src/libData/AccountData/Account.cpp
- src/libData/AccountData/Account.h
- src/libData/AccountData/AccountStoreSC.tpp
- src/libMessage/Messenger.cpp
- src/libMessage/Messenger.h
- src/libMessage/MessengerAccountStoreBase.cpp
- tests/Data/Test_Account.cpp
Regarding to recent change on Scilla: https://github.com/Zilliqa/scilla/pull/357
> Add "_this_address" in init.json

- src/libDirectoryService/DSBlockPreProcessing.cpp
- src/libServer/AddressChecksum.h
Finish TODO task for POW module
"TODO: Verify the PoW submission for this unknown node", implement the part to verify the PoW from DS leader
> Finish TODO task for POW module

- src/libDirectoryService/DirectoryService.cpp
- src/libDirectoryService/DirectoryService.h
- src/libDirectoryService/FinalBlockPreProcessing.cpp
- src/libDirectoryService/MicroBlockProcessing.cpp
- src/libDirectoryService/PoWProcessing.cpp
- src/libMessage/Messenger.cpp
- src/libMessage/Messenger.h
- src/libMessage/ZilliqaMessage.proto
- src/libNode/MicroBlockPostProcessing.cpp
This PR adds signature to DSMicroBlockSubmission, with the following specific changes:
1. Add `pubkey` and `signature` to `DSMicroBlockSubmission` proto message definition
2. Add signature generation to `Messenger::SetDSMicroBlockSubmission`
3. Add signature verification to `Messenger::GetDSMicroBlockSubmission`
4. Rename `CheckDSPowPacketSubmissionFromNonDSCommittee` to `CheckIfDSNode` and reverse the boolean logic
5. Add `CheckIfShardNode`
6. Update the call to `CheckDSPowPacketSubmissionFromNonDSCommittee` in PoWProcessing.cpp
7. Add the calls to `CheckIfDSNode` and `CheckIfShardNode` inside `ProcessMicroblockSubmission` depending on the microblock type received.
> Added signature to DSMicroBlockSubmission

- docker/Dockerfile
- docker/Dockerfile.cuda
- docker/dev/Dockerfile
- docker/dev/Dockerfile.ci
- docker/dev/Dockerfile.k8s
- src/depends/common/Common.cpp
- src/depends/libDatabase/LevelDB.cpp
- src/depends/libDatabase/LevelDB.h
- src/depends/libTrie/Trie.cpp
- src/depends/libTrie/Trie.h
> Change license

- constants_local.xml
- tests/Zilliqa/test_zilliqa_lookup.py
Put the lookup ip in seed for local test.
> Make local test work

- constants.xml
- constants_local.xml
- src/common/Constants.cpp
- src/common/Constants.h
- src/libNode/Node.cpp
- src/libPersistence/BlockStorage.cpp
- src/libServer/Server.cpp
- src/libServer/Server.h
- src/libValidator/Validator.cpp
- src/libZilliqa/Zilliqa.cpp
> Make the seed node port dynamic and functionality for fetching micro block

- src/libServer/JSONConversion.cpp
- src/libServer/Server.cpp
> Implementation of checksum for server

- src/libDirectoryService/DirectoryService.cpp
- src/libLookup/Lookup.cpp
- src/libMessage/Messenger.cpp
- src/libMessage/Messenger.h
- src/libMessage/ZilliqaMessage.proto
- src/libNode/Node.cpp
- src/libNode/Node.h
- src/libNode/PoWProcessing.cpp
Raise PoW message is an empty message. There is no signature check. Any node will be able to trigger a thread in lookup that will sleep for a certain amount of seconds. 
This PR will change the message to be consist of 
1. msg type 
2. block number
3. pubkey
4. signature
The signature will be signed over (msg, type, block number). This is to prevent a replay attack where one can use a signed message of (block number) of other message type and replay it.
> Add checks for raise pow

- daemon/ZilliqaDaemon.cpp
- src/libNode/Node.cpp
Removed unused function. This function also prints out the private key in the log file which is not desired. 
Removed logging of privkey in Zilliqa daemon
> Remove unused function GetOneGoodKeyPair and unneccessary log from Zilliqa daemon

- .gitmodules
- VERSION
- docker/Dockerfile
- docker/Dockerfile.cuda
- docker/dev/Dockerfile
- scripts/ci_make_image.sh
- src/cmd/main.cpp
- src/libProtoServer/ServerMessages.proto
- src/libProtoServer/ServerResponse.proto
The main goal of this PR is to
- pin public scilla version at v0.0.3
- bump up zilliqa version to v3.2.2
It also covers other issues:
- remove the left git submodules since #1170 
- remove the unused proto imports
> Pin the version of Scilla to v0.0.3 and bump up Zilliqa version to v3.2.2

- src/libCrypto/CMakeLists.txt
- src/libCrypto/Schnorr.cpp
With this PR, the code should be able to be built on
- Ubuntu 16.04 (with OpenSSL 1.0.2g)
- Ubuntu 18.04 (with OpenSSL 1.1.0g)
> Add compatibility support for OpenSSL 1.1.0g

- src/libLookup/Lookup.cpp
> Remove check for sharding structure version in ProcessSetDirectoryBlocksFromSeed

- README.md
- build.sh
Revert some of the accidental change introduced in the recent PRs
> Fix README and build.sh

- src/cmd/sendcmd.cpp
- src/libNetwork/PeerManager.cpp
- src/libNetwork/PeerManager.h
https://github.com/Zilliqa/Zilliqa/issues/759
> Remove unused PeerManager commands

- src/libData/AccountData/AccountStoreBase.tpp
- src/libData/AccountData/AccountStoreSC.tpp
subject to https://docs.google.com/spreadsheets/d/1_Ss0mo5f8VSLjeDQ1W623YGZXe1__WVUiiNhcB1rKWM/edit#gid=0
> Fix TODOs in AccountData

- CMakeLists.txt
With `REQUIRED` added, the missing dependency will be detected earlier during the CMake configuration stage.
> Add REQUIRED to find_package Boost

- constants.xml
- constants_local.xml
Add default value to path corresponding to scripts
> Add default value for Verifier Path

- src/libLookup/Lookup.cpp
> Add retrieval of only latest ds epoch

- src/libServer/JSONConversion.cpp
For community devs, make it easier to see why CreateTransaction fails
> Throw exception in RPC

- constants.xml
- constants_local.xml
- src/libLookup/Lookup.cpp
- src/libLookup/Lookup.h
- src/libNetwork/Blacklist.cpp
- src/libNetwork/Blacklist.h
- src/libNetwork/DataSender.cpp
- src/libNetwork/Peer.cpp
- src/libNetwork/Peer.h
- src/libUtils/IPConverter.cpp
- src/libUtils/IPConverter.h
This PR covers following 
- Use DNS hostname to resolve ip for lookup and seed nodes.
- If DNS resolve fails, use the ip configured.
- Avoid blacklisting Lookup-nodes and Seed nodes
.
> Use DNS to resolve ip for lookup and seed nodes

- src/cmd/signmultisig.cpp
- src/libDirectoryService/FinalBlockPostProcessing.cpp
- src/libNode/FallbackPostProcessing.cpp
- src/libNode/FinalBlockProcessing.cpp
- src/libUtils/UpgradeManager.cpp
Current signmulsig has wrong implementation, we should follow the standard procedure of class MultiSig.
> Fix the wrong implementation of signmultisig

- CMakeGraphVizOptions.cmake
- scripts/dep_graph.sh
Add a script to plot the dependency graph between cmake targets.
It requires:
- dot
- graphviz
Run this and check `deps.pdf`
```
./scripts/dep_graph.sh
```
More customization can be done in `CMakeGraphVizOptions.cmake`
> Add scripts/dep_graph.sh

- scripts/profile_time.py
- src/libDirectoryService/PoWProcessing.cpp
- src/libLookup/Lookup.cpp
- src/libUtils/Logger.cpp
- src/libUtils/Logger.h
This PR changes the log message format as follows:
~~1. Date/Time format.  Before = `19-01-16T08:33:19.697`.  Now = `190116 08:33:19.697`.~~
2. Added ~~line number~~ filename and line number after the time
~~3. Added filename after the line number~~
4. Shortened the function name from 30 to 25
5. Shortened BEGIN to BEG
6. For LOGSTATE, added singe space before the epoch num section
7. Reduced `MAX_BYTES_TO_DISPLAY` from 100 to 64
Sample Before:
```
[INFO][ 7520][18-12-24T13:48:35.045][ProcessSetPrimary             ][Epoch 1] My node ID for this PoW consensus is 0
```
Sample Now:
```
[INFO][10770][19-01-16T10:42:31.415][ctoryService.cpp:267][ProcessSetPrimary        ] [Epoch 1] My node ID for this PoW consensus is 0
```
Notes:
1. Overall, each line length has increased by 18 characters.
2. …
> Make log messages easier to read for debugging

- CMakeLists.txt
- src/cmd/CMakeLists.txt
- src/common/CMakeLists.txt
- src/depends/common/CMakeLists.txt
- src/diagnostic/CMakeLists.txt
- src/libConsensus/CMakeLists.txt
- src/libData/BlockChainData/BlockLinkChain.cpp
- src/libData/BlockChainData/BlockLinkChain.h
- src/libData/BlockChainData/CMakeLists.txt
- src/libData/CMakeLists.txt
- src/libLookup/CMakeLists.txt
- src/libMediator/CMakeLists.txt
- src/libMessage/CMakeLists.txt
- src/libPOW/CMakeLists.txt
- src/libPersistence/CMakeLists.txt
- src/libProtoServer/CMakeLists.txt
- src/libRumorSpreading/CMakeLists.txt
- src/libServer/Server.cpp
- src/libUtils/CMakeLists.txt
- src/libValidator/CMakeLists.txt
- src/libValidator/Validator.cpp
- tests/libTestUtils/CMakeLists.txt
Refactor BlockLinkChain class, put implementation into cpp file, prevent the same functions are build in a lot of libraries.
> Refactor BlockLinkChain class, put implementation into cpp file

- src/libLookup/Lookup.cpp
- src/libMessage/Messenger.cpp
- src/libMessage/Messenger.h
- src/libMessage/ZilliqaMessage.proto
Add signature check for LookupSetDirectoryBlocksFromSeed
> Add signature check for LookupSetDirectoryBlocksFromSeed

- src/libData/BlockData/BlockHeader/VCBlockHeader.cpp
- src/libData/BlockData/BlockHeader/VCBlockHeader.h
- src/libDirectoryService/ViewChangePostProcessing.cpp
- src/libDirectoryService/ViewChangePreProcessing.cpp
- src/libMessage/Messenger.cpp
- src/libNode/ViewChangeBlockProcessing.cpp
- src/libValidator/Validator.cpp
This PR adds log message to state log in lookup node, so we can quickly see when view change happens.
```
[ 19-01-17T07:55:25.473 ][VCBLK] DS = 2 Tx = 1
[ 19-01-17T07:55:25.473 ][VCBLK] Leader = <127.0.0.1:5004>
[ 19-01-17T07:55:25.473 ][VCBLK] Faulty = <127.0.0.1:5016>
```
Other minor fix: `GetVieWChangeDSEpochNo` -> `GetViewChangeDSEpochNo` (changed the `W`)
Tested locally by doing `vc3`.
> Log the VC blocks in lookup state log

- daemon/ZilliqaDaemon_AWS.cpp
- tests/Zilliqa/daemon_restart.py
- tests/Zilliqa/daemon_restart_local.py
Fix https://github.com/Zilliqa/Issues/issues/417
> Daemon should follow testnet command option format

- VERSION
- docker/Dockerfile
- docker/Dockerfile.cuda
- docker/dev/Dockerfile
- src/libUtils/SWInfo.h
> Change scilla version to v0.0.4 and bump up Zilliqa version to v3.3.1

- src/libMessage/Messenger.cpp
- src/libMessage/MessengerSWInfo.cpp
- src/libMessage/ZilliqaMessage.proto
> Change required field in protobuf to optional for Persistent data

- scripts/validateBackupDB.sh
- tests/Node/test_node_validateBackupDB.sh
The file `tests/Node/test_node_validateBackupDB.py` was using `.py` file extension wrongly as the content inside is shell script. This also causes the shebang of the file being accidentally rewritten during the license update PR (#1135).
> Fix shebang and file extension

- CMakeLists.txt
- scripts/dep_graph.sh
The utility `gethetworkhistory` was not successfully installed to the destination. This PR fixes it.
> Add getnetworkhistory to install output directory

- src/libMessage/Messenger.cpp
- src/libMessage/ZilliqaMessage.proto
**LookupSetDSBlockFromSeed**
- sig should be sig(lowBlockNum, highBlockNum, dsBlocks) instead of sig (dsBlocks)
**LookupSetTxBlockFromSeed**
- sig should be sig(lowBlockNum, highBlockNum, txblocks) instead of sig(txblocks)
**LookupSetStateDeltaFromSeed**
- sig should be sig(blockNum, stateDelta) instead of sig(stateDelta)
**Refactoring of VCNodeSetDSTxBlockFromSeed**
> Fix protobuf signature signing

- src/libMediator/Mediator.cpp
- src/libUtils/DataConversion.cpp
Fix compile failed for clang-902.0.39.2.
> Fix mac-os compile failed for clang-902.0.39.2

- src/libData/AccountData/AccountStore.cpp
- src/libData/AccountData/AccountStoreTrie.tpp
The serialization of AccountBase(including balance, nonce, codehash and storageroothash) was replaced with Protobuf instead of RLP. Which will be stored in AccountStore Merkle Trie. This PR is for updating the logics on RetrieveFromDisk for the above changes.
> Update AccountStore::RetriveFromDisk for Protobuf

- src/libNode/DSBlockProcessing.cpp
This PR just appends the difficulty to the state log, which will need to be monitored closely in the first few weeks.
```
[ 19-01-21T06:38:26.363 ][DSBLK][127.0.0.1000000][1] RECVD DSBLOCK -> DS Diff = 5 Diff = 3
```
A script will be made later on to periodically grep this new message in the state log, and automatically notify the team.
> Added difficulty level to the state log message

- VERSION
- docker/Dockerfile
- docker/Dockerfile.cuda
- src/libUtils/SWInfo.h
> Change Zilliqa version to v3.4.0

- constants.xml
- constants_local.xml
- src/common/Constants.cpp
- src/common/Constants.h
- src/libDirectoryService/DirectoryService.cpp
Move pow MAX_ADJUST_THREAD to constants.xml
> [release-3.4] Move pow MAX_ADJUST_THREAD to constants.xml

- src/libConsensus/ConsensusLeader.cpp
Return the correct `bool` in `ProcessMessageCommitCore`
> [Release3.4] Fix correct return value for ProcessMessageCommitCore

- constants.xml
- constants_local.xml
- src/common/Constants.cpp
- src/common/Constants.h
- src/libDirectoryService/DirectoryService.cpp
Move pow MAX_ADJUST_THREAD to constants.xml
> Move pow MAX_ADJUST_THREAD to constants.xml

- src/libConsensus/ConsensusLeader.cpp
Return the correct `bool` in `ProcessMessageCommitCore`
> Fix correct return value for ProcessMessageCommitCore

- VERSION
- docker/Dockerfile
- docker/Dockerfile.cuda
- src/libUtils/SWInfo.h
> [release-3.4] Change Zilliqa version to v3.4.1

- VERSION
- docker/Dockerfile
- docker/Dockerfile.cuda
- src/libUtils/SWInfo.h
> Change Zilliqa version to v3.4.1

- scripts/report_lookup.sh
Usage: `./report_lookup.sh <report title> <webhook URL> [do once]`
This script can be deployed in any lookup, and it will read the state log once every hour and send a report via the webhook.
> Added report_lookup script for state log checking

- CMakeLists.txt
- src/cmd/CMakeLists.txt
- src/cmd/verifymultisig.cpp
Rolling-upgrading may use a script to do following:
1. Release package to AWS S3 bucket
2. Download packet to every nodes
3. Verify downloaded packet
4. Put SUSPEND_LAUNCH file to every nodes
5. Kill Zilliqa process
6. Replace downloaded packet
7. Remove SUSPEND_LAUNCH file in every nodes
This PR provided the utility for verifying multisig in step (3).
> Provide verifymultisig for rolling-upgrading script

- src/libDirectoryService/DSBlockPostProcessing.cpp
- src/libNode/DSBlockProcessing.cpp
- src/libPersistence/BlockStorage.cpp
- src/libValidator/Validator.cpp
- src/libZilliqa/Zilliqa.cpp
After DS consensus, the state delta could be clean from persistence, in order to reduce the usage of database.
> After DS consensus, state delta could be removed

- src/libPersistence/ContractStorage.cpp
- src/libPersistence/ContractStorage.h
TODO Fix
As the total number of state variables for all contracts might be huge, thus a check of whether the index newly generated is already existing is necessary.
>  Avoid index collision for contract state storage

- scripts/report_normal.sh
Usage: `./report_normal.sh <report title> <webhook URL> [do once]`
This script can be deployed in any normal DS node, and it will read the state log once every hour and send a report via the webhook.
> Added monitoring script for normal node

- src/libConsensus/ConsensusLeader.cpp
- src/libServer/Server.cpp
> Remove stale FIXMEs

- constants.xml
- constants_local.xml
- tests/Mediator/constants.xml
- tests/Network/Test_P2PComm.cpp
> Change default port to 33333

- constants.xml
- constants_local.xml
- tests/Mediator/constants.xml
- tests/Network/Test_P2PComm.cpp
> [Release 3.4] Change default port to 33333

- src/libMessage/Messenger.cpp
- src/libMessage/Messenger.h
We have 2 `ProtobufByteArrayToSerializable` functions in Messenger.cpp.
Neither of them check the result of calling `Serializable::Deserialize` and `SerializableDataBlock::Deserialize`.
So it's possible for our code to permit wrongly-formatted messages like this and continue reading the rest of the message, and possibly trigger a crash at some point:
```
[INFO][12372][19-01-24T04:41:32.018][ProcessFinalBlock             ] BEGIN
[INFO][12372][19-01-24T04:41:32.018][GetNodeFinalBlock             ] BEGIN
[WARN][12372][19-01-24T04:41:32.018][GetNumber                     ] Unable to get BIGNUM of size 33 from stream with available size 2
[WARN][12372][19-01-24T04:41:32.018][Deserialize                   ] Deserialization failure
[WARN][12372][19-01-24T04:41:32.018][PubKey …
```
> Enforce checking of Deserialize result in Messenger

- constants.xml
- constants_local.xml
- src/libUtils/ShardSizeCalculator.cpp
SHARD_SIZE_TOLERANCE_LO cannot be greater than current shard size, otherwise the shard size would be underflow then generate unknown sharding structure. This PR add some error-checking to avoid this problem.
> SHARD_SIZE_TOLERANCE_LO cannot be greater than current shard size

- src/libNode/MicroBlockPreProcessing.cpp
> Fix for UpdateProcessedTxn

- CMakeLists.txt
- build.sh
- src/libData/AccountData/Account.cpp
- src/libData/AccountData/Account.h
- src/libData/AccountData/AccountStore.cpp
- src/libData/AccountData/AccountStore.h
- src/libDirectoryService/DirectoryService.cpp
- src/libDirectoryService/DirectoryService.h
- src/libDirectoryService/FinalBlockPreProcessing.cpp
- src/libDirectoryService/MicroBlockProcessing.cpp
- src/libMessage/Messenger.cpp
- src/libNode/FinalBlockProcessing.cpp
- src/libNode/Node.cpp
- src/libPersistence/ContractStorage.cpp
- src/libPersistence/ContractStorage.h
- So the root cause is after RemoveDSMicroBlock called during ViewChange, we no longer process the DSMicroBlock because of some flags. So the DS nodes won't know they have transaction to send as the microblock was already erased, and txn will always be forwarded together with microblock.
Now the solution is to clean the flags and re-run the DSMicroBlock from a clean state ( which shall be the same as the end of MicroBlock submission). Now we requires the AccountStoreTemp to be reverted (by calling DeserializeDelta with m_stateDeltaFromShards). And also revert the AccountStore (by fixing and adopting RevertCommitTemp). Then the DS committee can rerun the DSMicroBlock after the view change, which can happen after the missing transaction was fetched.
- Several reversibility functions was …
> Fix No Transaction Forwarded From DS After View Change

- src/libConsensus/ConsensusLeader.cpp
- src/libDirectoryService/DSBlockPostProcessing.cpp
- src/libDirectoryService/DSBlockPreProcessing.cpp
- src/libDirectoryService/DirectoryService.cpp
- src/libDirectoryService/FinalBlockPostProcessing.cpp
- src/libDirectoryService/MicroBlockProcessing.cpp
- src/libDirectoryService/PoWProcessing.cpp
- src/libDirectoryService/ViewChangePostProcessing.cpp
- src/libLookup/Lookup.cpp
- src/libMessage/Messenger.cpp
- src/libMessage/MessengerAccountStoreBase.cpp
- src/libNetwork/Blacklist.cpp
- src/libNetwork/DataSender.cpp
- src/libNetwork/P2PComm.cpp
- src/libNetwork/PeerManager.cpp
- src/libNetwork/RumorManager.cpp
- src/libNode/DSBlockProcessing.cpp
- src/libNode/FallbackPostProcessing.cpp
- src/libNode/MicroBlockPostProcessing.cpp
- src/libNode/Node.cpp
- src/libPersistence/BlockStorage.cpp
- src/libRumorSpreading/RumorStateMachine.cpp
- src/libUtils/Logger.cpp
- src/libUtils/Logger.h
Some log improvements:
1. Reduced usage of `LOG_EPOCH`
2. Shortened some of the more frequent messages, such as for p2p and gossip
3. Reduced payload lengths
4. More consistent display of committee/shard/peer lists
5. Overall, tried to make logs more concise and able to show in single line
6. Also added temp var before calling `LIMIT_RIGHT` in logger, to avoid repeated string creation inside the macro
> Log cleanup

- src/libZilliqa/Zilliqa.cpp
> Clear diagnostic data from previous runs

- scripts/ci_install_deps.sh
- scripts/release.sh
This PR covers new upgrade mechanism: (release.sh)
To use new release mechanism, set following parmaters in addition to existing ones:
```
useNewUpgradeMethod=""
S3UpgradeFileName=""
testnet=""
current_cluster_name="" # eg: dev.k8s.z7a.xyz
dsguards_count=""
#optional for auto upload the persistent data to S3 DB and ask all nodes to download from S3
S3PersistentDBFileName=""
lookup_no="0"
```  
The `download_and_verifier.sh` script will be available via testnet script. PR to follow: https://github.com/Zilliqa/testnet/pull/288
```
**Known issues:**
```
[Fixed] 1. Daemon seems not to start zilliqa process after step 5.d
2. Occasionally see "substr outside of string at /usr/bin/parallel line 2193, <STDIN> line 21." while executing kubectl commands via parallel tool.
3. For node not in the …
> New upgrade mechanism

- CMakeLists.txt
- src/diagnostic/CMakeLists.txt
- src/diagnostic/getnetworkhistory.cpp
- src/diagnostic/getrewardhistory.cpp
- src/libDirectoryService/Coinbase.cpp
- src/libDirectoryService/DirectoryService.h
- src/libMessage/Messenger.cpp
- src/libMessage/Messenger.h
- src/libMessage/ZilliqaMessage.proto
- src/libNode/DSBlockProcessing.cpp
- src/libPersistence/BlockStorage.cpp
- src/libPersistence/BlockStorage.h
- src/libZilliqa/Zilliqa.cpp
- tests/Persistence/Test_Diagnostic.cpp
This PR moves the existing diagnostic DB storage to persistence/diagnosticNodes.
This PR also creates a new diagnostic DB called persistence/diagnosticCoinb.
The purpose of the database is to store the reward history across each DS epoch.
The storage is done inside `DirectoryService::InitCoinbase()` which is invoked during the vacuous epoch.
A unit test has been added to tests/Persistence/Test_Diagnostic.cpp.
A tool called getrewardhistory has also been created to generate a CSV file from the database.
To use the tool:
1. Go to the location where the "persistence" folder is located.
2. `getrewardhistory <output csv> <location>`
> Added diagnostic db for coinbase reward history

- src/libServer/Server.cpp
- src/libServer/Server.h
Some of the fixes and code cleanup/
> Fixes in server.cpp

- src/libDirectoryService/PoWProcessing.cpp
- src/libDirectoryService/ViewChangePostProcessing.cpp
In the event that DS diff somehow goes below diff, then the soln is not currently pushed into the DS PoW soln list.  The check needs to be changed for this scenario.
Also removed duplicate VC done message.
> Add PoW soln to DS PoW list if difficulty is higher

- src/libData/AccountData/TransactionReceipt.h
- src/libData/BlockChainData/BlockLinkChain.cpp
- src/libDirectoryService/DSBlockPostProcessing.cpp
- src/libDirectoryService/DirectoryService.cpp
- src/libLookup/Lookup.cpp
- src/libNetwork/DataSender.cpp
- src/libNode/DSBlockProcessing.cpp
- src/libNode/FinalBlockProcessing.cpp
- src/libNode/MicroBlockPreProcessing.cpp
- src/libNode/Node.cpp
- src/libNode/Node.h
- src/libNode/PoWProcessing.cpp
- src/libPersistence/BlockStorage.cpp
One more round of log cleanup, for the messages that appear in shard node's log
> Cleaned up logs for shard node

- src/libLookup/Lookup.cpp
- src/libLookup/Lookup.h
- src/libValidator/Validator.cpp
> Check prevHash in validator and GetDSBlock

- src/libLookup/Lookup.cpp
- src/libLookup/Lookup.h
- src/libMessage/Messenger.cpp
- src/libMessage/Messenger.h
- src/libMessage/ZilliqaMessage.proto
- src/libServer/JSONConversion.cpp
- src/libServer/Server.cpp
- src/libServer/Server.h
* Add the var priority (by default false)
* Change logic for seed node forwarding if the flag is true
> Add priority in JSONRPC

- src/libDirectoryService/FinalBlockPreProcessing.cpp
- src/libDirectoryService/MicroBlockProcessing.cpp
- src/libNode/MicroBlockPreProcessing.cpp
- src/libNode/Node.cpp
Add epoch number to dm1 to dm8. This is needed for VC test scenarios automation.
> Add epoch number to vc test scenarios logs

- src/libData/AccountData/Account.cpp
- src/libData/AccountData/AccountStoreSC.tpp
- src/libData/AccountData/TransactionReceipt.cpp
- src/libPersistence/ContractStorage.cpp
- src/libUtils/JsonUtils.h
- tests/Data/ScillaTestUtil.cpp
- tests/Data/Test_Contract.cpp
Fix regarding to
https://github.com/Zilliqa/Zilliqa/pull/1302#discussion_r251219682
>  Refactor JSONUtils to improve performance

- src/libNode/Node.cpp
> Fix compile error for dm1

- src/libNode/FinalBlockProcessing.cpp
> Revert reordering of ProcessStateDeltaFromFinalBlock in ProcessFinalBlock

- scripts/release.sh
Use dsguard statefulset to identify dsguard pods
> use dsguard statefulset to identify dsguard pods

- src/libConsensus/ConsensusCommon.cpp
- src/libConsensus/ConsensusCommon.h
- src/libData/BlockChainData/BlockLinkChain.cpp
- src/libDirectoryService/DirectoryService.cpp
- src/libDirectoryService/ViewChangePostProcessing.cpp
- src/libLookup/Lookup.cpp
- src/libNode/Node.cpp
- src/libNode/Node.h
- src/libNode/PoWProcessing.cpp
- src/libNode/ViewChangeBlockProcessing.cpp
Refactor the code to use more readable data type
Using PairOfNode instead of std::pair<PubKey, Peer>
Using DequeOfNode instead of std::deque<std::pair<PubKey, Peer>>
> Refactor some data types

- scripts/release.sh
Fix fetch lookup pod since index label is gone
> Fix fetch lookup pod since index label is gone

- src/libData/AccountData/AccountStoreSC.tpp
- src/libNode/FinalBlockProcessing.cpp
> Address Security Audit regarding to AccountStore

- scripts/release.sh
For upgrading, dsguard and shard nodes should wake up at the same time. Otherwise the finalblock would be sent to shard node which is still under retrieving persistence, and lead to some error.
> dsguard and shard should wake up at the same time

- src/libNode/MicroBlockPreProcessing.cpp
Fix wrong test scenario (DM6) name
> Fix wrong test scenario (DM6) name

- src/libDirectoryService/Coinbase.cpp
Fix the reward distribution to match the percentages. 
1. Lookup may still get lucky draw
2. Guard node dont get any type of coinbase, and the award they are suppose to get remains in the coinbase addr.
> Fix Coinbase

- scripts/release.sh
Prefetch the pod info to avoid delay spend on fetching pod info during command execution
> Prefecth the POD Info

- src/libCrypto/Schnorr.h
- src/libNetwork/Guard.cpp
- src/libNetwork/Guard.h
For efficiency, we can use set instead of vector to improve the searching effeciency
> Change Guard data storage structure  to set

- src/libDirectoryService/PoWProcessing.cpp
> Stop processing PoW solns when DS Block consensus has already started

- scripts/release.sh
- Rearrange dsguard and shard sequence.
- ```shouldUploadPersistentDB="Y"``` : Option to skip uploading the new persistence to DB
> Rearrange shard and dsguard seq. optionally upload db

- src/libData/AccountData/Account.cpp
- src/libData/AccountData/Account.h
Make sure the Code and Address are set after passing the checks
> Refine InitContract

- docker/Dockerfile
- docker/Dockerfile.cuda
- docker/dev/Dockerfile
> Upgrade to scilla v0.1.0

- VERSION
- docker/Dockerfile
- docker/Dockerfile.cuda
- src/libUtils/SWInfo.h
> To tag v3.5.3

- scripts/release.sh
Fix bug when upgrading both zilliqa and scilla.
> Fix bug for upgrading both zilliqa and scilla

- scripts/release.sh
> Increase ulimit

- scripts/report_bastion.py
- scripts/stall_checker.py
This can be run from bastion or any machine with the kubecfg access to the cluster.
`
nohup python ./report_bastion.py <report title> <lookup pods TXT> <DS guard pods TXT> <webhook URL> <poll interval in mins (0 = run once)> &
`
`lookup pods TXT` and `DS guard pods TXT` will contain the pod names (one per line)
`webhook URL` is the slack incoming webhook
> Python script for monitoring mainnet from bastion

- src/libData/AccountData/AccountStoreSC.tpp
- tests/Data/Test_Account.cpp
> Fix receipt cumulative gas when deployment failed

- tests/Data/Test_Account.cpp
> [UnitTest] Fix/Test_Account

- VERSION
- docker/Dockerfile
- docker/Dockerfile.cuda
- src/libUtils/SWInfo.h
> To tag v3.5.4

- docker/Dockerfile
- docker/Dockerfile.cuda
- docker/dev/Dockerfile
- src/libDirectoryService/DSBlockPostProcessing.cpp
- src/libDirectoryService/ViewChangePostProcessing.cpp
- src/libDirectoryService/ViewChangePreProcessing.cpp
> Scilla to v0.1.1

- src/libDirectoryService/DSBlockPostProcessing.cpp
- src/libDirectoryService/DSBlockPreProcessing.cpp
- src/libDirectoryService/DirectoryService.cpp
- src/libNetwork/Guard.cpp
- src/libZilliqa/Zilliqa.cpp
> Cleanup logs

- src/libNode/Node.cpp
The genesis ds block was not added to the verifier during initialization
> Put genesis block in blocklink

- constants.xml
- constants_local.xml
- tests/Network/Test_P2PComm.cpp
> Change port number to 33133

- scripts/release.sh
The utility "Parallel" has some bugs inside, and it seems there is limitation of task number. We separate the tasks before calling parallel to make sure parallel works fine.
> The utility 'parallel' has some bug

- VERSION
- docker/Dockerfile
- docker/Dockerfile.cuda
- src/libUtils/SWInfo.h
> To tag 4.0.0

- VERSION
- docker/Dockerfile
- docker/Dockerfile.cuda
- src/libUtils/SWInfo.h
> To tag v4.0.1

- README.md
Update testnet wallet URL to dev-wallet to be consistent with dev-api/dev-explorer.
> Update README for testnet wallet URL

- src/libNode/MicroBlockPreProcessing.cpp
> Fixed misleading log message for vacuous epoch

- tests/Zilliqa/daemon_restart.py
Daemon should not launch process with --loadconfig
> Daemon should not launch process with --loadconfig

- src/libNode/MicroBlockPreProcessing.cpp
> Revert PR 1392 except for init in constructor

- README.md
Add security bug bounty and explorer 2 link to README
> Add security bug bounty and explorer 2 link 

- VERSION
- docker/Dockerfile
- docker/Dockerfile.cuda
- src/libUtils/SWInfo.h
> To tag v4.0.2

- src/cmd/main.cpp
- src/libUtils/SWInfo.h
Log the zilliqa brand and version in log file, so we can easilty tell people are using the corrrect software version.
Build software, run local test, can find the version is printed at the zilliqa-00001-log.txt
g3log created log at: Mon Feb 11 16:23:04 2019
[INFO][ 1064][19-02-11T08:23:04.635][src/cmd/main.cpp:140][main                ] **Copyright (C) Zilliqa. Version 4.0.2. <https://www.zilliqa.com/>** 
[INFO][ 1064][19-02-11T08:23:04.635][/PeerManager.cpp:109][PeerManager         ] BEG
[INFO][ 1064][19-02-11T08:23:04.635][/PeerManager.cpp:195][SetupLogLevel       ] BEG
[INFO][ 1064][19-02-11T08:23:04.635][/PeerManager.cpp:195][SetupLogLevel       ] END
[INFO][ 1064][19-02-11T08:23:04.635][/PeerManager.cpp:113][PeerManager         ] Loading configuration file
[INFO][ …
> Log the zilliqa brand and version in log file

- src/libDirectoryService/DirectoryService.h
- src/libDirectoryService/FinalBlockPreProcessing.cpp
- src/libDirectoryService/ViewChangePostProcessing.cpp
Fix coinbase when VC happens in vacous epoch
VC tests
```
vc2 test passed
vc4 test passed
vc1vc6 test passed
vc3vc6 test passed
vc7 test passed
vc8 test passed
dm1 test passed
dm2 test passed
dm3 test passed
dm4 test passed
dm5 test passed
dm6 test passed
[coding/ugly code alert] dm7 using a hacky way to get new leader log ../vcv-dm7/logs/vcv-dm7-dsguard-3.txt
dm7 test passed
dm8 result too fuzzy. Please manually review it. dm7 should be sufficient
```
> Do coinbase again when VC happens

- src/libLookup/Lookup.cpp
- src/libLookup/Lookup.h
- src/libLookup/Synchronizer.cpp
- src/libLookup/Synchronizer.h
> Removed unused code in Lookup

- src/cmd/main.cpp
- src/common/Constants.h
- src/libUtils/SWInfo.cpp
- src/libUtils/SWInfo.h
- tests/Utils/Test_SWInfo.cpp
Check if user using latest sw version to join mainnet
> Check if user using latest sw version to join mainnet

- CMakeLists.txt
- build.sh
- scripts/make_image_for_test.sh
- src/libDirectoryService/MicroBlockProcessing.cpp
- src/libNode/Node.cpp
> Add DM9 vc test and minor modification on previous dm tests

- src/libConsensus/ConsensusLeader.cpp
- src/libConsensus/ConsensusLeader.h
- src/libDirectoryService/DSBlockPreProcessing.cpp
- src/libDirectoryService/FinalBlockPreProcessing.cpp
- src/libDirectoryService/ViewChangePreProcessing.cpp
This PR will help identify the DS nodes that are unable to send response after sending commit earlier
Sample output:
```
[INFO][10856][19-02-15T04:32:48.552][eProcessing.cpp:1275][RunConsensusOnDSBloc] [Epoch 1] Initiated DS block view change. 
[INFO][10856][19-02-15T04:32:48.552][sensusLeader.cpp:903][Audit               ] BEG
[INFO][10856][19-02-15T04:32:48.552][sensusLeader.cpp:923][Audit               ] [Subset 0] State = CHALLENGE_DONE
[INFO][10856][19-02-15T04:32:48.552][sensusLeader.cpp:924][Audit               ] Missing responses:
[INFO][10856][19-02-15T04:32:48.552][sensusLeader.cpp:930][Audit               ] <127.0.0.1:5003>
[INFO][10856][19-02-15T04:32:48.552][sensusLeader.cpp:930][Audit               ] <127.0.0.1:5005> …
```
> Display missing responses before view change

- README.md
- VERSION
- docker/Dockerfile
- docker/Dockerfile.cuda
- docker/dev/Dockerfile
- src/libUtils/SWInfo.h
Zilliqa to v4.1.0; Scilla to v0.2.0
> Zilliqa to v4.1.0; Scilla to v0.2.0

- src/libData/AccountData/AccountStoreTrie.tpp
used for debugging for the previous pr, now it's not needed and it's quite abused in the current log
~- [ ] small-scale cloud test~
> Remove expired log

- README.md
Update readme current live version 4.0.2 -> 4.1.0
> Update readme current live version 4.0.2 -> 4.1.0

- src/libZilliqa/Zilliqa.cpp
> [Release-4.1] Delete object before returning

- src/libNetwork/RumorManager.cpp
This PR adds additional checks to ensure gossip foreign message is handled properly
> [Release-4.1] Handle gossip foreign message properly

- src/libData/AccountData/AccountStoreTrie.tpp
- src/libDirectoryService/FinalBlockPostProcessing.cpp
> [Release-4.1] Minor fix on consensus check

- src/libZilliqa/Zilliqa.cpp
> Delete object before returning

- src/libNetwork/RumorManager.cpp
This PR adds additional checks to ensure gossip foreign message is handled properly
> Handle gossip foreign message properly

- src/libDirectoryService/FinalBlockPostProcessing.cpp
> Minor fix on consensus check

- README.md
- VERSION
- docker/Dockerfile
- docker/Dockerfile.cuda
- src/libUtils/SWInfo.h
Update version from `v4.1.0` -> `v4.1.1`
> [release-4.1] Update version to v4.1.1 

- src/libNode/Node.cpp
During recovery, check and set `m_isVacuousEpoch`
> Set vacuous epoch during recovery

- README.md
Update master branch readme current live version `4.1.0` -> `4.1.1`
> Update master branch readme current live version 4.1.0 -> 4.1.1

- src/libDirectoryService/FinalBlockPreProcessing.cpp
- src/libNode/MicroBlockPreProcessing.cpp
> Put Epoch/Difficulty checker for txn processing

- src/libNode/Node.cpp
Refactor epoch incremental process after calling Node::StartRetrieveHistory. (No logic change)
> Refactor epoch incremental process after StartRetrieveHistory

- src/libDirectoryService/PoWProcessing.cpp
Two issues has been fixed in this PR.
1. User Controlled IP:Port Pairs When Processing Individual Proof-of-Work Submissions Allows for
Targeted Denial-of-Service Attacks
2. Check submission count of Pow
> Check the pow submitter address and submitted count

- src/libData/AccountData/Account.cpp
- src/libData/AccountData/AccountStoreBase.tpp
- src/libData/AccountData/AccountStoreSC.tpp
- src/libMessage/Messenger.cpp
- tests/Data/Test_Account.cpp
- tests/Data/Test_AccountStore.cpp
Use SafeMath for `AccountBase::IncreaseNonce` and `AccountBase::IncreaseNonceBy`, and evaluate the result everywhere these two functions are called.
@kaikawaliu might need help to double-check if it is ok for most of the changed functions here that they directly return false if the check for `IncreaseNonce`/`IncreaseNonceBy` fails.
> Check result of IncreaseNonce

- scripts/release.sh
Since now testnet.sh support **upgrade-all** (https://github.com/Zilliqa/testnet/pull/393), the upgrading feature of release script should be disabled.
> Release script for rolling upgrading

- src/libData/AccountData/AccountStoreBase.tpp
- src/libData/AccountData/AccountStoreSC.tpp
- src/libDirectoryService/Coinbase.cpp
> Add Checks for return from IncreaseBalance

- src/cmd/main.cpp
- src/libUtils/SWInfo.cpp
Don't exit software if not latest version
> Don't exit software if not latest version

- src/libData/AccountData/AccountStoreSC.tpp
So that can get more accurate error code if contract calling failed.
> Adjust the order for checking _accepted in scilla output

- src/libLookup/Lookup.cpp
- src/libLookup/Lookup.h
Fix m_syncType may have data race issue
Change m_syncType to atomic
> Fix m_syncType may have data race issue

- tests/POW/test_POW.cpp
Fix sometimes travis auto build fail problem
Decrease the difficulty in auto test case, because the travis build machine maybe very weak.
47/47 Test #32: Test_POW .........................***Failed  172.73 sec
Running 20 test cases...
/zilliqa/tests/POW/test_POW.cpp(287): fatal error in "mining_and_verification": critical check verifyLight failed
OPENCL_GPU_MINE and CUDA_GPU_MINE option are not enabled, skip test case gpu_mining_and_verification_1
OPENCL_GPU_MINE and CUDA_GPU_MINE option are not enabled, skip test case gpu_mining_and_verification_2
*** 1 failure detected in test suite "powtest"
g3log g3FileSink shutdown at: 04:58:43 160272
Log file at: [./zilliqa-00001-log.txt]
98% tests passed, 1 tests failed out of 47
Total Test time (real) = 212.33 sec
The following tests FAILED:
32 - …
> Fix sometimes travis auto build fail problem

- src/libMediator/Mediator.cpp
> Add epoch number to state log

- src/libNode/PoWProcessing.cpp
- src/libPOW/pow.cpp
- src/libPOW/pow.h
- src/libServer/GetWorkServer.cpp
- src/libServer/GetWorkServer.h
- tests/POW/test_POW.cpp
- tests/POW/test_RemoteMine.cpp
Fix DS pow time window not accurate problem
The DS pow time window is total pow time window minus shard pow time
https://github.com/Zilliqa/Zilliqa/issues/1434
> Fix DS pow time window not accurate problem

- src/libCrypto/BIGNUMSerialize.cpp
> Add check for offset overflow in BIGNUMSerialize

- src/libNode/DSBlockProcessing.cpp
Lookup node should store ds leader information into persistence storage. Otherwise the upgrading/recovery has some chance to be failed.
> Lookup node should store ds leader information into persistance

- src/libNetwork/RumorManager.cpp
> Improve gossip

- src/libData/AccountData/TransactionReceipt.cpp
- src/libUtils/JsonUtils.h
`try-catch` now added to `convertStrtoJson`.
So, we also don't need to add `try-catch` wherever `convertStrtoJson` is called.
> Add exception checking inside convertStrtoJson

- src/libMessage/Messenger.cpp
- src/libMessage/Messenger.h
- src/libNode/DSBlockProcessing.cpp
- src/libNode/FallbackBlockProcessing.cpp
- src/libNode/Node.cpp
- src/libNode/ViewChangeBlockProcessing.cpp
> Improve messaging

- src/libServer/Server.cpp
- src/libValidator/Validator.cpp
…or::CheckCreatedTransactionFromLookup
> Add more check MAX_CODE_SIZE_IN_BYTES

- src/libConsensus/ConsensusLeader.cpp
- src/libConsensus/ConsensusLeader.h
Signature check is not enough, because in some situations the IP may change.
By putting the IP check in place, we can uncover mismatching views of the consensus committee much earlier.
Also, updated `Audit` to print out the backup index number.
> Check IP of commit/response message

- src/libDirectoryService/DirectoryService.cpp
Always use multicast for sending out `NEWDSGUARDIDENTITY` message to existing ds-committee.
> Use multicast for UpdateDSGuardIdentity

- src/cmd/main.cpp
- src/common/Constants.h
- src/libLookup/Lookup.cpp
- src/libLookup/Lookup.h
- src/libZilliqa/Zilliqa.cpp
- src/libZilliqa/Zilliqa.h
Otherwise when later making usage of `m_syncType` in `SetLookupNodes` may cause unexpected result.
> Initialize SyncType when constructing Lookup

- src/libDirectoryService/Coinbase.cpp
Current way is inefficient because of repeated pubkey-guard list checking:
```
for each block
for each pubkey in block
check pubkey against guard list
```
This PR keeps track of which pubkeys have already been identified as guards.
> Avoid excessive key searches in coinbase rewarding algorithm

- README.md
> Update README to v4.3.0

- src/libNode/Node.cpp
- src/libNode/Node.h
Remove old upgrading mechanism because it never be used anymore.
> Remove old upgrading mechanism

- src/libLookup/Lookup.cpp
- src/libLookup/Lookup.h
m_receivedRaiseStartPoW may have data race issue
> m_receivedRaiseStartPoW may have data race issue

- src/libDirectoryService/DSBlockPostProcessing.cpp
- src/libDirectoryService/DSBlockPreProcessing.cpp
- src/libDirectoryService/DirectoryService.cpp
- src/libDirectoryService/FinalBlockPostProcessing.cpp
- src/libDirectoryService/FinalBlockPreProcessing.cpp
- src/libDirectoryService/ViewChangePostProcessing.cpp
- src/libDirectoryService/ViewChangePreProcessing.cpp
For rolling-upgrade usage, we should print ds leader ip in state file.
Format: 
`DSConsensusLeaderID = xx`
> Print ds leader ID in state file

- src/libNode/PoWProcessing.cpp
https://github.com/Zilliqa/Zilliqa/issues/1523
> Fix pow window time for node not correct

- README.md
- VERSION
- docker/Dockerfile
- docker/Dockerfile.cuda
- src/libUtils/SWInfo.h
> [release-4.3] To v4.3.1

- README.md
> To v4.3.1 for readme

- src/libDirectoryService/DSBlockPreProcessing.cpp
- src/libDirectoryService/DirectoryService.h
- src/libDirectoryService/PoWProcessing.cpp
Fix DS backup cannot find pow in sorted solutions
When there is a lot of pow submissions, backup also choose the pows from high priority nodes and then do pow sorting and verifying.
https://github.com/Zilliqa/Issues/issues/464
> Fix DS backup cannot find pow in sorted solutions

- src/libDirectoryService/DirectoryService.cpp
- src/libDirectoryService/DirectoryService.h
- src/libDirectoryService/PoWProcessing.cpp
- src/libNode/Node.cpp
Verify pow solution before buffer it
> Verify pow solution before buffer it

- constants.xml
- constants_local.xml
- src/common/Constants.cpp
- src/common/Constants.h
- src/libServer/Server.cpp
Add option to enable/disable smart contract
> Add option to enable/disable smart contract

- daemon/ZilliqaDaemon.cpp
- daemon/ZilliqaDaemon_AWS.cpp
This PR fixes issue - 
https://github.com/Zilliqa/Issues/issues/469
> ZilliqaDaemon exits immediately at startup if no zilliqa process is yet launched

- src/libDirectoryService/DSBlockPreProcessing.cpp
- src/libDirectoryService/FinalBlockPreProcessing.cpp
This change to integration test is to support changes in incremental db.
> Adjust vc7 and vc8 test case 

- src/depends/libDatabase/OverlayDB.cpp
- src/depends/libDatabase/OverlayDB.h
- src/libData/AccountData/AccountStore.cpp
- src/libData/AccountData/AccountStore.h
- src/libDirectoryService/DirectoryService.cpp
- src/libLookup/Lookup.cpp
- src/libNode/Node.cpp
- src/libNode/Node.h
- src/libPersistence/BlockStorage.cpp
- src/libPersistence/BlockStorage.h
- src/libPersistence/ContractStorage.cpp
- src/libPersistence/ContractStorage.h
- src/libPersistence/Retriever.cpp
- src/libZilliqa/Zilliqa.cpp
After Recovery , Support Rejoin for Node not in sharding structure
> After Recovery , Support Rejoin for Node not in sharding structure

- docker/Dockerfile
- docker/Dockerfile.cuda
- docker/dev/Dockerfile.k8s
> Add new dependencies to images

- src/libPersistence/BlockStorage.cpp
- src/libPersistence/BlockStorage.h
Add mutex to avoid race conditions in libPersistence
> Add mutexes in BlockStorage

- src/libLookup/Lookup.cpp
Fix corner case when INCRDB_DSNUMS_WITH_STATEDELTAS is 1
> Fix corner case when INCRDB_DSNUMS_WITH_STATEDELTAS is 1

- docker/Dockerfile
- docker/Dockerfile.cuda
Used `requests` package instead of `request`.
> Used requests package instead of request

- docker/Dockerfile
- docker/Dockerfile.cuda
> Added deps futures to docker

- docker/Dockerfile.cuda
> Add missing setuptools in cuda dockerfile

- README.md
> Update README to v4.4.0

- cmake/InstallJsonrpccpp.cmake
- src/libPOW/pow.h
Ignore deprecation warning on gcc in 18,04
> Fix build on 18.04

- src/libNode/DSBlockProcessing.cpp
Revert blacklist mechanism for lookup. Lookup will `Clear()` instead of popping some nodes.
> Revert blacklist clearing for lookup

- README.md
> Update README to v4.4.1

- scripts/release.sh
Because level2lookup may have different constants.xml to lookup/newlookup nodes, we need to release one more constants.xml for rolling-upgrading.
> Support level2lookup for rolling-upgrading release

- src/libPersistence/Retriever.cpp
Update ds committee everytime you encounter a directory block
> Fix a corner case in verification

- src/libLookup/Lookup.cpp
- src/libLookup/Lookup.h
- src/libServer/Server.cpp
This PR fixes the issue : https://github.com/Zilliqa/Issues/issues/478
> Fix the DNS resolve issue

- README.md
- VERSION
- cmake/InstallJsonrpccpp.cmake
- docker/Dockerfile
- docker/Dockerfile.cuda
- src/libNode/DSBlockProcessing.cpp
- src/libNode/Node.cpp
- src/libNode/Node.h
- src/libPOW/pow.h
- src/libPersistence/BlockStorage.cpp
- src/libUtils/SWInfo.h
- src/libZilliqa/Zilliqa.cpp
Merging V4.4.1 into release-4.4 branch
> [release-4.4] Merging V4.4.1 into release-4.4 branch

- src/libDirectoryService/DSBlockPreProcessing.cpp
- src/libDirectoryService/DirectoryService.h
Find solution in pow list before verify pow from leader
When DS backup find some different nodes in priority list with same priority, the verify pow ordering will using different nodes, then it cannot find pow in sorted list, it need to check pow in local pow list first, because it is faster, if from local cannot find it, then check the pow from ds leader.
https://github.com/Zilliqa/Issues/issues/477
> Find solution in pow list before verify pow from leader

- README.md
Remove extra  `libssl-dev` in dependencies installation instruction
> Fix extra libssl-dev in readme

- src/libData/AccountData/AccountStoreBase.tpp
- src/libData/AccountData/AccountStoreSC.tpp
- tests/Data/AccountData/Test_AccountStore.cpp
> Remove Contract Accounts If Creation Failed

- src/libDirectoryService/DirectoryService.cpp
- src/libDirectoryService/DirectoryService.h
- src/libNode/FinalBlockProcessing.cpp
- src/libNode/Node.cpp
- src/libZilliqa/Zilliqa.cpp
This PR fixed following issue w.r.t recovery of dsguard:
- https://github.com/Zilliqa/Issues/issues/485
- https://github.com/Zilliqa/Issues/issues/486
- Handle case of GUARD_DS_SYNC - syncType 7. 
- Handle CleanVariable
> Recovery of dsguard

- src/libDirectoryService/DSBlockPostProcessing.cpp
- src/libDirectoryService/DirectoryService.cpp
- src/libLookup/Lookup.cpp
- src/libNode/DSBlockProcessing.cpp
DS committee exclude ds guard nodes from blacklist
https://github.com/Zilliqa/Issues/issues/483
> DS committee exclude ds guard nodes from blacklist

- src/libData/AccountData/Account.cpp
- src/libData/AccountData/AccountStoreSC.tpp
- src/libNode/FinalBlockProcessing.cpp
- src/libPersistence/ContractStorage.cpp
- src/libUtils/JsonUtils.h
Fixed the issue when the data field in transaction is parsed into a Json stringObject, which caused undefined behavior when modifying the object.
And also remove the non-empty check for Microblock TxnHash during Forwarding Txn and MicroBlock from shard to lookup. Otherwise failed transaction will always remain in the txn pool before vacuous epoch.
Besides some try-catch was added for safety reason.
> Fix Json Conversion For Handling Corner Case Of Contract Txn

- scripts/miner_info.py
- src/libNetwork/Blacklist.cpp
- src/libNetwork/Blacklist.h
- src/libServer/Server.cpp
- src/libServer/Server.h
Add RPC for removal  and addition of nodes from whitelist (blacklist exclusion list)
Example output:
```
python scripts/miner_info.py -p 4301 whitelist_add -pm 142.23.2.2 abcd 278.55.1.12
Parameter: 142.23.2.2	True
Parameter: abcd	{u'message': u'IP Address provided not valid', u'code': -8, u'data': None}
Parameter: 278.55.1.12	{u'message': u'IP Address provided not valid', u'code': -8, u'data': None}
```
use `python scripts/miner_info.py whitelist_add --pm [IP]` to add 
use `python scripts/miner_info.py whitelist_remove --pm [IP]` to remove
> Add RPC for addition to whitelist and removal

- constants.xml
- constants_local.xml
- scripts/miner_info.py
- src/common/Constants.cpp
- src/common/Constants.h
- src/common/MempoolEnum.h
- src/libNode/MicroBlockPreProcessing.cpp
- src/libNode/Node.cpp
- src/libNode/Node.h
- src/libServer/JSONConversion.cpp
- src/libServer/JSONConversion.h
- src/libServer/Server.cpp
- src/libServer/Server.h
1. Add API for normal nodes for querying txn status
2. Add API for lookup nodes for getting information about some of the shard nodes
3. Modify `miner_info` to support
Example output
> Check status of a txn in a normal node's mempool

- src/libDirectoryService/DSBlockPreProcessing.cpp
Log the check failed pow winner ip address
There is one view change because of verify pow winner address, but don't know because of which ip.
> Log the check failed pow winner ip address

- README.md
> Update README to v4.5.0

- src/libLookup/Lookup.cpp
- src/libLookup/Lookup.h
- src/libNode/DSBlockProcessing.cpp
- src/libNode/FinalBlockProcessing.cpp
- src/libZilliqa/Zilliqa.cpp
This PR addresses issue -> https://github.com/Zilliqa/Issues/issues/495
> Auto recovery of seed nodes if lagging due to missing FB and DS blocks

- tests/POW/test_POW.cpp
Fix pow test case failed on travis problem
> Fix pow test case failed on travis problem

- src/libMessage/Messenger.cpp
- src/libNode/Node.cpp
- tests/Data/AccountData/Test_AccountStore.cpp
This PR add size check to various part of the code
Details as below
https://github.com/Zilliqa/Issues/issues/497
> Add size check

- src/libDirectoryService/MicroBlockProcessing.cpp
> Check if microblockstatedeltahash null when state delta is empty

- src/libData/AccountData/AccountStoreSC.tpp
> Minor fixes for AccountStoreSC

- src/libData/AccountData/AccountStoreSC.tpp
> Adjust gas cost for failed contract transaction

- src/libData/AccountData/AccountStoreSC.h
- src/libData/AccountData/AccountStoreSC.tpp
Via this pr, we can buffer all the balance and state changes in the atomic state map and run the chain call with dynamic balance.
> Apply atomic state change among contract chain call

- src/libZilliqa/Zilliqa.cpp
The lookup server was initialized after the invocation of the thread.
> Fix Invocation sequence for seed nodes.

- scripts/release.sh
Add `miner_info.py` into release package, in order to upgrade it for rolling-upgrade.
> Add miner_info.py into release package

- src/libData/AccountData/AccountStoreSC.tpp
- tests/Data/Test_Contract.cpp
Fix check scilla output fail problem
https://github.com/Zilliqa/Issues/issues/502
> Fix check scilla output fail problem

- VERSION
- docker/Dockerfile
- docker/Dockerfile.cuda
- docker/dev/Dockerfile
- src/libUtils/SWInfo.h
> To Zilliqa v4.6.0 and Scilla v0.3.0

- src/libLookup/Lookup.cpp
- src/libLookup/Lookup.h
This PR addressed issue - https://github.com/Zilliqa/Issues/issues/504
> skip set online for newlookup

- CMakeLists.txt
- scripts/validatePersistence.sh
- src/cmd/CMakeLists.txt
- src/cmd/validateDB.cpp
- src/libNode/Node.cpp
- src/libNode/Node.h
For usage in testnet ( in /run/zilliqa ) : `bash /zilliqa/scripts/validatePersistence.sh`
> Persistence Validation Script

- src/libData/AccountData/Transaction.cpp
- src/libData/AccountData/Transaction.h
- src/libLookup/Lookup.cpp
- src/libServer/LookupServer.cpp
- src/libValidator/Validator.cpp
- tests/Lookup/Test_txn_send.cpp
Construct a function for reusing the code for calculating the shard index.
> Consolidate shard calculation

- README.md
> Update README to v4.6.0

- src/libPOW/pow.cpp
- src/libPOW/pow.h
- tests/POW/test_POW.cpp
Fix the typo for the function `POW::CheckDifficulty()`
Reported in https://github.com/Zilliqa/Zilliqa/issues/1635
> Fix typo for POW::CheckDifficulty()

- CMakeLists.txt
- README.md
- VERSION
- docker/Dockerfile
- docker/Dockerfile.cuda
- scripts/validatePersistence.sh
- src/cmd/CMakeLists.txt
- src/cmd/validateDB.cpp
- src/libData/AccountData/AccountStoreSC.tpp
- src/libData/AccountData/Transaction.cpp
- src/libData/AccountData/Transaction.h
- src/libLookup/Lookup.cpp
- src/libLookup/Lookup.h
- src/libNode/Node.cpp
- src/libNode/Node.h
- src/libPOW/pow.cpp
- src/libPOW/pow.h
- src/libProtoServer/Server.cpp
- src/libServer/LookupServer.cpp
- src/libServer/Server.cpp
- src/libServer/Server.h
- src/libUtils/SWInfo.h
- src/libValidator/Validator.cpp
- tests/Lookup/Test_txn_send.cpp
- tests/POW/test_POW.cpp
Update `release-4.6` branch to `V4.6.1`
> [release-4.6] To V4.6.1

- README.md
> Update README to v4.6.1

- README.md
- VERSION
- docker/Dockerfile
- docker/Dockerfile.cuda
- src/libLookup/Lookup.cpp
- src/libLookup/Lookup.h
- src/libNode/DSBlockProcessing.cpp
- src/libNode/FinalBlockProcessing.cpp
- src/libUtils/SWInfo.h
- src/libZilliqa/Zilliqa.cpp
- tests/POW/test_POW.cpp
`release-4.5` branch was not updated previously. This PR updates `release-v4.5` branch from `v.4.5.0` to `v4.5.1`
> [release-4.5] To V4.5.1

- daemon/CMakeLists.txt
- daemon/ZilliqaDaemon_AWS.cpp
- daemon/run.sh
This PR will cover core part of issue: https://github.com/Zilliqa/Issues/issues/501
> Daemon support for community seed

- src/depends/libDatabase/OverlayDB.cpp
- src/depends/libDatabase/OverlayDB.h
- src/libData/AccountData/AccountStore.cpp
- src/libData/AccountData/AccountStore.h
- src/libData/AccountData/AccountStoreSC.tpp
- src/libData/BlockChainData/BlockLinkChain.cpp
- src/libData/BlockChainData/BlockLinkChain.h
- src/libDirectoryService/DSBlockPostProcessing.cpp
- src/libDirectoryService/DSBlockPreProcessing.cpp
- src/libDirectoryService/DirectoryService.cpp
- src/libDirectoryService/DirectoryService.h
- src/libDirectoryService/FinalBlockPostProcessing.cpp
- src/libDirectoryService/MicroBlockProcessing.cpp
- src/libDirectoryService/ViewChangePostProcessing.cpp
- src/libLookup/Lookup.cpp
- src/libLookup/Synchronizer.cpp
- src/libNode/DSBlockProcessing.cpp
- src/libNode/FallbackBlockProcessing.cpp
- src/libNode/FallbackPostProcessing.cpp
- src/libNode/FinalBlockProcessing.cpp
- src/libNode/Node.cpp
- src/libNode/Node.h
- src/libPersistence/Retriever.cpp
- src/libValidator/Validator.cpp
- src/libZilliqa/Zilliqa.cpp
> Properer handling for failures of BlockStorage

- src/common/Constants.cpp
- src/libUtils/SafeMath.h
- src/libUtils/SafeMath.tpp
- tests/Utils/CMakeLists.txt
- tests/Utils/Test_SafeMath_Exhaustive.cpp
Check each and every combination of given type and examine if the underflow and overflow is handled correctly. 
Also, throw exception when power fails 
```
terminate called after throwing an instance of 'std::runtime_error'
what():  [Critical] SafeMath::power failed
```
> Add exhaustive test for SafeMath

- src/libLookup/Lookup.cpp
- tests/Lookup/Test_txn_send.cpp
- tests/libTestUtils/TestUtils.cpp
- tests/libTestUtils/TestUtils.h
- Send the unmatched contract call txn to ds
[After #1628 ]
> Fix remap for contract call txns

- src/libServer/JSONConversion.cpp
Add the blockhash of the tx block to the TX block JSON structure.
```
curl -d '{
>     "id": "1",
>     "jsonrpc": "2.0",
>     "method": "GetLatestTxBlock",
>     "params": [""]
> }' -H "Content-Type: application/json" -X POST "https://psbhc-api.aws.z7a.xyz"
{"id":"1","jsonrpc":"2.0","result":{"body":{"BlockHash":"fd003f06def5ff1e24a0ac67ad063357d49b3aaa1ad228ea83950a8980a14548","HeaderSign":"219DDE8649B7B27DA711A490721BCF22CA77DBB38D1D67C26F3F16A17B91E1BB28C5A781A856DA10BDE4FB5BD1FE1037DA228AF69491974E3AC763D8B697DC37","MicroBlockInfos":[{"MicroBlockHash":"7f793c75f492dcd7516b49a247641abc64a61d0861ed4a1398bace49f1889959","MicroBlockShardId":0,"MicroBlockTxnRootHash":"0000000000000000000000000000000000000000000000000000000000000000"},{"MicroBlockHash":"8a96dc6eda9fd9ede7c2492b3074eaacd031 …
```
> Add blockhash to tx block JSON

- src/libServer/JSONConversion.cpp
> [Release 4.6] Add blockhash to tx block JSON

- VERSION
- docker/Dockerfile
- docker/Dockerfile.cuda
- src/libUtils/SWInfo.h
> [release-4.6] To v4.6.2

- tests/POW/test_POW.cpp
Remove redundant pow test case
Some time this test case will fail on travis.
> Remove redundant pow test case

- src/libServer/LookupServer.cpp
Check the listing apis for default block.
> Check Lookup Server for default block

- src/libServer/LookupServer.cpp
> [Release-4.6] Check Server.cpp for Default block

- VERSION
- docker/Dockerfile
- docker/Dockerfile.cuda
- src/libUtils/SWInfo.h
> [release-4.6] To v4.6.3

- scripts/release.sh
As https://github.com/Zilliqa/Issues/issues/521 described, we should release `daemon_restart.py` for rolling upgrade.
> Release daemon_restart.py

- scripts/txn-sanity-check.py
This script will periodically send payment transaction back and forth between two accounts to check if the testnet is still processing transactions. On failure, an error message is sent to Slack.
This script requires [pyzil](https://github.com/deepgully/pyzil) and a minimum python version of 3.6.
**Usage:**
`nohup stdbuf -oL ./txn-sanity-check.py --srchex <base16 addr> --srczil <bech32 addr> --srckey <privkey> --dsthex <base16 addr> --dstzil <bech32 addr> --dstkey <privkey> --frequency <minutes> --apiurl <API url> --webhook <slack webhook url> > txn-sanity-check.log &`
> txn-sanity-check script

- src/libNode/DSBlockProcessing.cpp
This PR addresses issue - https://github.com/Zilliqa/Issues/issues/523
> clear peer counter

- src/libLookup/Lookup.cpp
- src/libNode/FinalBlockProcessing.cpp
- src/libNode/Node.cpp
- src/libNode/Node.h
This PR cover https://github.com/Zilliqa/Issues/issues/524
> [release-4.6] Buffering MB & Txns during seed syncup

- src/common/Constants.cpp
- src/common/Constants.h
- src/libData/AccountData/AccountStore.cpp
- src/libData/AccountData/AccountStore.h
- src/libData/AccountData/AccountStoreTrie.h
- src/libData/AccountData/AccountStoreTrie.tpp
- src/libData/AccountData/Transaction.h
- src/libDirectoryService/FinalBlockPostProcessing.cpp
- src/libNode/FinalBlockProcessing.cpp
- src/libPersistence/BlockStorage.cpp
- src/libPersistence/BlockStorage.h
- src/libPersistence/Retriever.cpp
- src/libServer/StatusServer.cpp
- src/libServer/StatusServer.h
> [release-4.6] epochfin

- VERSION
- docker/Dockerfile
- docker/Dockerfile.cuda
- src/libUtils/SWInfo.h
> [release-4.6] To v4.6.4

- src/libLookup/Lookup.cpp
This is to address state root hash check failure : https://github.com/Zilliqa/Issues/issues/525
> skip adding statedelta

- src/libLookup/Lookup.cpp
- src/libNode/FinalBlockProcessing.cpp
- src/libNode/Node.cpp
- src/libNode/Node.h
This is to address state root hash check failure : Zilliqa/Issues#525
> skip adding state delta

- src/libLookup/Lookup.cpp
- src/libNode/FinalBlockProcessing.cpp
- src/libNode/Node.cpp
- src/libNode/Node.h
> Buffering MB & Txns during seed syncup

- src/libNode/Node.cpp
> Check RECOVERY_TRIM_INCOMPLETED_BLOCK before CleanExtraTxBodies

- src/libNode/Node.cpp
> [Release4.6] Check RECOVERY_TRIM_INCOMPLETED_BLOCK before CleanExtraTxBodies

- src/libNetwork/P2PComm.cpp
> revert nonblocking connection

- src/libData/AccountData/AccountStoreBase.h
- src/libData/AccountData/AccountStoreBase.tpp
- src/libData/AccountData/AccountStoreSC.tpp
> Check whether account exists when create contract

- src/libUtils/SysCommand.h
> log popen failure

- daemon/ZilliqaDaemon_AWS.cpp
To address issue - https://github.com/Zilliqa/Issues/issues/534
> Add timestamp to daemon logging

- src/libPOW/pow.cpp
Continue check result from proxy until timeout
https://github.com/Zilliqa/Zilliqa/issues/1681
> Continue check result from proxy until timeout

- README.md
> Update README to v4.7.0

- src/libNode/FinalBlockProcessing.cpp
For issue:
https://github.com/Zilliqa/Issues/issues/545
> Remove check for microblock epoch num to match the latest tx block num

- src/libData/AccountData/AccountStore.cpp
- src/libData/AccountData/AccountStoreTrie.tpp
- src/libPersistence/BlockStorage.cpp
- src/libPersistence/BlockStorage.h
Fixing issue: https://github.com/Zilliqa/Issues/issues/539
> Fix potential concurrency issue for AccountStore::m_state access

- src/libLookup/Lookup.cpp
- src/libNode/FinalBlockProcessing.cpp
- src/libNode/Node.h
This PR addresses issue https://github.com/Zilliqa/Issues/issues/546
> Fix handling of unavailable microblocks

- src/libData/AccountData/AccountStoreSC.h
- src/libData/AccountData/AccountStoreSC.tpp
Added the state variables in their initial state after the creation of contract.
It's a breaking change as it may result in consensus failure if only part of the nodes are updated with this pr.
> Add states during contract creation

- scripts/release.sh
Remove hard-coded string from `release.sh`
> Add param for bucket name in release.sh

- daemon/ZilliqaDaemon_AWS.cpp
- src/cmd/main.cpp
- src/libUtils/Logger.cpp
- src/libUtils/Logger.h
- tests/POW/test_POW.cpp
- tests/Utils/Test_Logger1.cpp
- tests/Utils/Test_Logger2.cpp
- tests/Zilliqa/daemon_restart.py
As https://github.com/Zilliqa/Zilliqa/issues/1643 described, we should support the customized log path, in order to support the non-root ziliqa in the future.
> Support customized log path

- scripts/uploadIncrDB.py
https://github.com/Zilliqa/testnet/pull/566
> Pick from temp 

- scripts/release.sh
> Comply with new release structure

- src/libData/AccountData/AccountStore.cpp
For fixing issue: https://github.com/Zilliqa/Issues/issues/551
> Remove redundant mutex

- src/libCrypto/PubKey.cpp
- src/libCrypto/Schnorr.h
- src/libLookup/Lookup.cpp
Optimize DS leader verify fail log
> Optimize DS leader verify fail log

- README.md
> Update README to v4.7.1

- src/libServer/LookupServer.cpp
Add stricter check on lookup level to reject transaction.
> Add more lookup checks when creating txn

- src/libNode/Node.cpp
- src/libNode/Node.h
> Avoid validateDB crashing when checking normal node

- src/libDirectoryService/DSBlockPostProcessing.cpp
- src/libDirectoryService/DirectoryService.h
- src/libLookup/Lookup.cpp
- src/libLookup/Lookup.h
- src/libMessage/Messenger.h
- src/libNetwork/DataSender.cpp
- src/libNetwork/DataSender.h
- src/libNetwork/P2PComm.cpp
- src/libNetwork/P2PComm.h
- src/libNetwork/RumorManager.cpp
- src/libNetwork/RumorManager.h
- src/libNetwork/ShardStruct.h
- src/libNode/DSBlockProcessing.cpp
- src/libNode/MicroBlockPostProcessing.cpp
- src/libNode/Node.cpp
Don't fetch info from blacklisted seed nodes, in case some of the seed nodes are problematic, the node still can sync with other good seed nodes without delay. It will be a better solution if compared with another approach in https://github.com/Zilliqa/Zilliqa/pull/1727.
https://github.com/Zilliqa/Issues/issues/549
> Don't fetch info from blacklisted seed nodes

- VERSION
- docker/Dockerfile
- docker/Dockerfile.cuda
- src/libUtils/SWInfo.h
> To v4.8.0-alpha.0

- daemon/ZilliqaDaemon_AWS.cpp
Daemon should re-launch process with previous synctype
> [release-4.7] Daemon should re-launch process with previous synctype

- VERSION
- docker/Dockerfile
- docker/Dockerfile.cuda
- src/libUtils/SWInfo.h
> [release-4.7] To v4.7.2

- daemon/ZilliqaDaemon_AWS.cpp
Daemon should re-launch process with previous synctype
> Daemon should re-launch process with previous synctype

- scripts/uploadIncrDB.py
This PR addresses - Zilliqa/Issues#540
> Add redundant backup

- src/libLookup/Lookup.cpp
- src/libLookup/Lookup.h
- src/libNode/Node.cpp
- src/libPersistence/Retriever.cpp
This PR addresses issue - https://github.com/Zilliqa/Issues/issues/562
> Fetch missing statedelta from seed

- daemon/ZilliqaDaemon_AWS.cpp
Daemon should re-launch process with previous synctype
> [release-4.8] Daemon should re-launch process with previous synctype

- scripts/uploadIncrDB.py
> [release-4.8] Add redundant backup

- src/libLookup/Lookup.cpp
- src/libLookup/Lookup.h
- src/libNode/Node.cpp
- src/libPersistence/Retriever.cpp
> [release-4.8] Fetch missing statedelta from seed

- docker/Dockerfile
- docker/Dockerfile.cuda
- src/libUtils/SWInfo.h
> To v4.8.0-alpha.1

- scripts/uploadIncrDB.py
Fix start uploadIncrDB.py with error
https://github.com/Zilliqa/Issues/issues/565
> Fix start uploadIncrDB.py with error

- scripts/uploadIncrDB.py
Fix start uploadIncrDB.py with error
https://github.com/Zilliqa/Issues/issues/565
> [release-4.8] Fix start uploadIncrDB.py with error

- docker/Dockerfile
- docker/Dockerfile.cuda
- src/libUtils/SWInfo.h
> To v4.8.0-alpha.2

- scripts/uploadIncrDB.py
> [release-4.8] fix backup

- README.md
> Update README to v4.8.0

- src/libNode/Node.cpp
This PR addresses issue  https://github.com/Zilliqa/Issues/issues/569
> Missing include mbstxns flag

- src/common/Constants.h
- src/libServer/LookupServer.cpp
- src/libServer/LookupServer.h
Add API to get total coin supply
> add GetTotalSupply API

- constants_local.xml
Change default value for small scale test, because the right now the default parameter, the ./bootstrap.py command will have warning about the parameter not appropriate, user need to change every time before run `./testnet.sh up`
> Change default value for small scale test

- src/common/Constants.h
- src/libLookup/Synchronizer.cpp
- src/libLookup/Synchronizer.h
- tests/Message/CMakeLists.txt
- tests/Message/Test_Messenger_Compatibility.cpp
Fix genesis DS block hash not correct problem
> Fix genesis DS block hash not correct problem

- src/libValidator/Validator.cpp
Increase checks inside the validator.
> Check the correctness of hash inside the block

- src/libPersistence/BlockStorage.cpp
> Use exists function in CheckTxBody

- constants.xml
- constants_local.xml
> Fix misleading comments

- src/libLookup/Lookup.cpp
> Fix possible race cond

- src/libServer/JSONConversion.cpp
- src/libServer/JSONConversion.h
- src/libServer/LookupServer.cpp
- src/libServer/LookupServer.h
Cherry-picked commit, based on #1789
> Integrate fetching a substate of a smart contract

- VERSION
- docker/Dockerfile
- docker/Dockerfile.cuda
- src/libUtils/SWInfo.h
> To v5.0.0-alpha.0

- src/libLookup/Lookup.cpp
Fix : It incorrectly check node mode. should not have skipped for lookup nodes.
> fix mode check

- CMakeLists.txt
> Add data_migrate to bin folder

- CMakeLists.txt
> [release-5.0] Add data_migrate to bin folder

- src/libDirectoryService/ViewChangePostProcessing.cpp
> [release-5.0] Fix unnecessary mutex

- docker/Dockerfile
- docker/Dockerfile.cuda
- src/libUtils/SWInfo.h
> To v5.0.0-alpha.1

- src/libDirectoryService/ViewChangePostProcessing.cpp
Fix unnecessary mutex. VC consensus message from slower nodes may hinder the next consensus run.
> Fix unnecessary mutex

- tests/Server/Test_ScillaIPCServer.cpp
Add a test that captures a map having an empty string as its key.
Complete
> Add an IPC unit test for empty string map key

- src/libLookup/Lookup.cpp
> [release-5.0] Fix recover community testnet lookup and it crash

- tests/Server/Test_ScillaIPCServer.cpp
> [release-5.0] Add an IPC unit test for empty string map key

- src/cmd/data_migrate.cpp
- src/libData/AccountData/AccountStore.cpp
- src/libData/AccountData/AccountStore.h
- src/libPersistence/ContractStorage2.cpp
- src/libPersistence/ContractStorage2.h
- src/libPersistence/Retriever.cpp
- src/libPersistence/Retriever.h
1) Add option to ignore scilla checker for migration in case some outdated contract affecting the testnet
2) Remove extra quotes during migration to make states inconsistent
3) Enable empty map key in states json api
> Add option to ignore scilla checker for outdated contract

- src/libLookup/Lookup.cpp
Start listening when lookup finish sync
> [Release-5.0] Start listening when lookup finish sync

- docker/Dockerfile
- docker/Dockerfile.cuda
- src/libUtils/SWInfo.h
> To v5.0.0-alpha.2

- src/libLookup/Lookup.cpp
Start listening when lookup finish sync
> Start listening when lookup finish sync

- src/libLookup/Lookup.cpp
>  [Release 5.0] skip myip while sending to random lookup

- src/libData/AccountData/AccountStore.cpp
- src/libPersistence/ContractStorage2.cpp
> [Release-5.0] Fixing migrated state quoting

- docker/Dockerfile
- docker/Dockerfile.cuda
- docker/dev/Dockerfile
- src/libUtils/SWInfo.h
> To v5.0.0-alpha.3 and scilla v0.4.0-alpha.1

- src/libLookup/Lookup.cpp
Addresses https://github.com/Zilliqa/Issues/issues/577
> skip myip while sending to random lookup

- src/libData/AccountData/AccountStore.cpp
- src/libPersistence/ContractStorage2.cpp
> Fixing migrated state quoting

- src/cmd/data_migrate.cpp
- src/libData/AccountData/AccountStore.cpp
- src/libData/AccountData/AccountStore.h
- src/libDirectoryService/FinalBlockPostProcessing.cpp
- src/libNode/FinalBlockProcessing.cpp
- src/libPersistence/Retriever.cpp
- src/libPersistence/Retriever.h
> [Release-5.0] Don't update contract states every epoch & export contract addresses during migration

- docker/Dockerfile
- docker/Dockerfile.cuda
- src/libUtils/SWInfo.h
> To v5.0.0-alpha.4

- tests/Zilliqa/test_zilliqa_local.py
Patch local test constants.xml for `SCILLA_IPC_SOCKET_PATH` for each running node
as `"/tmp/zilliqa." + str(NODE_LISTEN_PORT + x) + ".sock"`
> patch SCILLA_IPC_SOCKET_PATH for local test

- tests/Zilliqa/test_zilliqa_local.py
> [Release 5.0] patch SCILLA_IPC_SOCKET_PATH for local test

- src/libLookup/Lookup.cpp
Fix recovered lookup start to listening crash
https://github.com/Zilliqa/Issues/issues/578
> [Release-5.0] Fix recovered lookup start to listening crash

- src/libData/AccountData/AccountStore.cpp
- src/libData/AccountData/AccountStoreSC.tpp
- src/libPersistence/ContractStorage2.cpp
- src/libPersistence/ContractStorage2.h
> [Release-5.0] Add mutex for ContractStorage2

- src/libLookup/Lookup.cpp
- src/libZilliqa/Zilliqa.cpp
Addresses https://github.com/Zilliqa/Issues/issues/579
> [Release 5.0] Fix synctype for recovery

- src/libZilliqa/Zilliqa.cpp
Don't start lookup server if lookup still syncing
https://github.com/Zilliqa/Issues/issues/580
> [Release-5.0] Don't start lookup server if lookup still syncing

- src/libLookup/Lookup.cpp
- src/libNode/FinalBlockProcessing.cpp
Don't process next buffered fb if any bufferred fb failed.
> [release 5.0] Avoid multiple RejoinAsNewlookup

- src/libZilliqa/Zilliqa.cpp
> [Release 5.0] Avoid setting NO_SYNC for recovery of normal nodes

- docker/Dockerfile
- docker/Dockerfile.cuda
- docker/dev/Dockerfile
- src/libUtils/SWInfo.h
> To v5.0.0-alpha.5 and scilla v0.4.0

- src/libZilliqa/Zilliqa.cpp
> [release-5.0] Set syncType based on lookup's syncType if RECOVERY_LOOKUP_SYNC

- docker/Dockerfile
- docker/Dockerfile.cuda
- src/libUtils/SWInfo.h
> To v5.0.0-alpha.6

- src/libLookup/Lookup.cpp
Fix recovered lookup start to listening crash
https://github.com/Zilliqa/Issues/issues/578
> Fix recovered lookup start to listening crash

- src/libZilliqa/Zilliqa.cpp
Don't start lookup server if lookup still syncing
> Don't start lookup server if lookup still syncing

- src/cmd/data_migrate.cpp
- src/libData/AccountData/AccountStore.cpp
- src/libData/AccountData/AccountStore.h
- src/libData/AccountData/AccountStoreSC.tpp
- src/libDirectoryService/FinalBlockPostProcessing.cpp
- src/libNode/FinalBlockProcessing.cpp
- src/libPersistence/ContractStorage2.cpp
- src/libPersistence/ContractStorage2.h
- src/libPersistence/Retriever.cpp
- src/libPersistence/Retriever.h
> Don't update contract states every epoch & export contract addresses during migration

- src/libServer/LookupServer.cpp
- src/libZilliqa/Zilliqa.cpp
> [Release-5.0] Fix thread invocation

- src/libLookup/Lookup.cpp
- src/libNode/FinalBlockProcessing.cpp
- src/libZilliqa/Zilliqa.cpp
Combined
https://github.com/Zilliqa/Zilliqa/pull/1857
https://github.com/Zilliqa/Zilliqa/pull/1854
https://github.com/Zilliqa/Zilliqa/pull/1853
https://github.com/Zilliqa/Zilliqa/pull/1850
> multiple fixes for recovery

- src/libServer/LookupServer.cpp
- src/libZilliqa/Zilliqa.cpp
> Fix thread invocation

- src/libServer/JSONConversion.cpp
Earlier:
```
"params": ["9611c53BE6d1b32058b2747bdeCECed7e1216793","records",["\"0x9915d0456b878862e822e2361da37232f626a2e47505c8795134a95d36138ed3\""]]
```
Now
```   
"params": ["9611c53BE6d1b32058b2747bdeCECed7e1216793","records",["0x9915d0456b878862e822e2361da37232f626a2e47505c8795134a95d36138ed3"]]
```
for params of `GetSmartContractSubState`
> Preserve quotes in GetSmartContractSubState

- src/libServer/JSONConversion.cpp
> [Release-5.0] Quote string in GetSmartContractSubState

- CMakeLists.txt
- src/cmd/CMakeLists.txt
> [release-5.0] Remove data_migrate from build

- tests/POW/test_POW.cpp
Fix test pow on travis sometimes fail, reduce the test difficulty so the test can pass on weak building machine.
https://github.com/Zilliqa/Issues/issues/586
> Fix test pow on travis sometimes fail

- scripts/miner_info.py
- src/libLookup/Lookup.cpp
- src/libLookup/Lookup.h
- src/libServer/StatusServer.cpp
- src/libServer/StatusServer.h
This is a temporary measure in the event that shard nodes are unable to deal with the volume of transactions, particularly smart contracts.  Since DS nodes are of higher machine specs, we can re-configure the lookups on-the-fly to redirect contracts to the DS committee.
> Add lookup option for sending contracts to DS committee

- README.md
We have recently migrated to discord. Hence, this PR changes the Gitter link at the readme to Discord link.
> Change readme. Gitter link to Discord link

- src/cmd/main.cpp
- src/libUtils/HardwareSpecification.h
Issue - https://github.com/Zilliqa/Issues/issues/591
> Check on min. cpu and ram for mining machine

- src/libData/AccountData/AccountStoreSC.tpp
- src/libData/AccountData/Address.h
- src/libData/AccountData/Transaction.h
- src/libPersistence/ContractStorage.cpp
- src/libPersistence/ContractStorage2.cpp
- src/libProtoServer/Server.cpp
- src/libServer/LookupServer.cpp
- src/libValidator/Validator.cpp
Using bool operator to check address, the current compare method always need to create a temporary Address object, after compare it will be disposed, which is not efficient.
> Using bool operator to check address

- CODE_OF_CONDUCT.md
Update Code of Conduct contact from Gitter to Discord
> Update CoC contact from Gitter to Discord

- src/libUtils/ShardSizeCalculator.cpp
- tests/Utils/Test_ShardSizeCalculator.cpp
Cleaning up this test to prepare for rework in another PR for https://github.com/Zilliqa/Issues/issues/593.
Here's the output now:
```
[18382][19-09-30T02:32:43.501][zeCalculator.cpp:103][ShardCountTestMain  ] Shard lo,mid,hi=[500,600,600] Nodes=590 Shards=[ 590 ] Unsharded=0
[18382][19-09-30T02:32:43.501][zeCalculator.cpp:103][ShardCountTestMain  ] Shard lo,mid,hi=[500,600,600] Nodes=591 Shards=[ 591 ] Unsharded=0
[18382][19-09-30T02:32:43.501][zeCalculator.cpp:103][ShardCountTestMain  ] Shard lo,mid,hi=[500,600,600] Nodes=592 Shards=[ 592 ] Unsharded=0
```
> Clean up Test_ShardSizeCalculator

- src/libDirectoryService/ViewChangePostProcessing.cpp
- src/libNode/ViewChangeBlockProcessing.cpp
Save consensus leader after view change, fix if recover after view change, the DS leader verifiy fail problem.
https://github.com/Zilliqa/Issues/issues/582
> Save consensus leader after view change

- src/libPersistence/Retriever.cpp
Catch potential stoull exception
> Catch potential stoull exception

- src/libDirectoryService/DSBlockPostProcessing.cpp
- src/libDirectoryService/DSBlockPreProcessing.cpp
- src/libDirectoryService/DirectoryService.cpp
- src/libDirectoryService/DirectoryService.h
- src/libDirectoryService/FinalBlockPostProcessing.cpp
- src/libDirectoryService/FinalBlockPreProcessing.cpp
- src/libLookup/Lookup.cpp
- src/libNode/Node.cpp
- src/libNode/Node.h
- src/libProtoServer/Server.cpp
- src/libServer/LookupServer.cpp
This PR will address https://github.com/Zilliqa/Issues/issues/592
> No PoW received, network should progress with DS shard 

- CMakeLists.txt
- build.sh
- cmake/InstallJsonrpccpp.cmake
- src/cmd/restore.cpp
- src/depends/NAT/nat.cpp
- src/libCrypto/MultiSig.cpp
- src/libCrypto/PrivKey.cpp
- src/libCrypto/Schnorr.cpp
- Remove unused variable 
- Make codebase compilable with `clang`
- Add build support with undefined behavior sanitizer and libfuzzer
- Fix a small typo
May conflict with https://github.com/Zilliqa/Zilliqa/pull/1898
> Add support for clang, libfuzzer and undef behavior sanitizer

- src/libDirectoryService/DirectoryService.cpp
- src/libLookup/Lookup.cpp
- src/libNetwork/Blacklist.cpp
- src/libNetwork/Blacklist.h
- src/libNetwork/DataSender.cpp
- src/libNetwork/Guard.cpp
- src/libNetwork/P2PComm.cpp
- src/libNetwork/P2PComm.h
- src/libNode/Node.cpp
- src/libServer/StatusServer.cpp
Handles issue - https://github.com/Zilliqa/Issues/issues/597
> Blacklist at 2 levels strict or relaxed to allow incoming msg

- src/libData/AccountData/AccountStoreSC.tpp
- src/libPersistence/ContractStorage2.cpp
Fix the logic for handling revertible generation.
> Fix contract state reverting

- VERSION
- docker/Dockerfile
- docker/Dockerfile.cuda
- docker/dev/Dockerfile
- src/libUtils/SWInfo.h
> To v5.1.0-alpha.0

- .gitmodules
- CMakeLists.txt
- cmake/InstallWebsocketpp.cmake
> Import submodule for Websocketpp

- README.md
> Update README to v5.1.0

- src/libDirectoryService/MicroBlockProcessing.cpp
Skip duplicate microblock processing earliest before performing any validation.
Issue: https://github.com/Zilliqa/Issues/issues/600
> Skip duplicate microblock processing earliest before performing any validation

- scripts/miner_info.py
- src/libLookup/Lookup.cpp
- src/libLookup/Lookup.h
- src/libServer/StatusServer.cpp
- src/libServer/StatusServer.h
> [release-5.1] Add lookup option for sending contracts to DS committee

- src/libNetwork/Blacklist.cpp
Revert relaxed blacklist temporarily
> [release-5.1] Revert relaxed blacklist temporarily

- VERSION
- docker/Dockerfile
- docker/Dockerfile.cuda
- src/libUtils/SWInfo.h
> [release-5.1] To v5.1.1

- src/libDirectoryService/MicroBlockProcessing.cpp
Fix the possible race condition with usage of `m_microblocks`.
> Fix possible race condition

- scripts/download_incr_DB.py
Fix the marker url for download incremental.
> [Release-5.1] Fix the marker url for download

- README.md
> Update README to v5.1.1

- scripts/download_incr_DB.py
Fix the marker url for download.
> Fix the marker url for download

- tests/Zilliqa/test_zilliqa_NAT.py
- tests/Zilliqa/test_zilliqa_late.py
- tests/Zilliqa/test_zilliqa_local.py
- tests/Zilliqa/test_zilliqa_lookup.py
Some `python3` differences:
1. `print` is now a function, not a keyword (so it must be used with parentheses)
2. `Popen` result defaults to binary (so `universal_newlines=True` must be added to get string result)
For clarity, added `"r"` to places where `open` is used for reading.
> Add python3 support to local test

- src/libData/AccountData/AccountStore.h
- src/libData/AccountData/AccountStoreSC.h
- src/libData/AccountData/AccountStoreSC.tpp
- src/libNode/MicroBlockPreProcessing.cpp
Instead of hashing whenever a transition being processed. we buffer the address need to be rehashed and doing the heavy lift in the end of transaction processing to avoid duplication. Which should significantly reduce the overhead of processing multiple transactions regarding to single contract with large state.
> State hashing optimization via buffering

- src/libMessage/Messenger.cpp
Compile error introduced after #1921 merged before #1898
> Fix compile error due to old Schnorr usage

- src/libNetwork/RumorManager.cpp
- src/libPersistence/BlockStorage.cpp
Some serialization code was not changed correctly after #1898
> Fix pubkey and signature serialization code

- src/libLookup/Lookup.cpp
Keep Updating coinbase during syncup of DS Node to avoid failure ( `Failed to verify the Byzantine nodes to be removed`) at next DS block consensus.
Issue# - https://github.com/Zilliqa/Issues/issues/601
> [Release-5.1] Keep Updating coinbase during syncup of DS Node

- src/libConsensus/ConsensusLeader.cpp
- src/libNetwork/P2PComm.cpp
- src/libNetwork/P2PComm.h
This is the change needed before we can re-enable the relaxed blacklist currently disabled in #1917
> Allow consensus leader to send to node in relaxed blacklist

- src/libLookup/Lookup.cpp
Minor coding fixes
Improve search efficiency
> Minor coding fixes

- src/libData/AccountData/AccountStoreSC.tpp
> Fix bug for feeding balance when invoking interpreter

- VERSION
- docker/Dockerfile
- docker/Dockerfile.cuda
- src/libUtils/SWInfo.h
> To v5.2.0-alpha.0

- src/libNode/Node.cpp
- src/libZilliqa/Zilliqa.cpp
> [Release-5.2] Avoid sending request for blacklist removal by lookup nodes

- src/libNode/Node.cpp
Send Blacklist removal request for shard guard as well. 
Because shard guards are not part of whilelisted IPs.
> [Release-5.2] Send Blacklist removal request for shard guard as well

- src/libNode/Node.cpp
Send Blacklist removal request for shard guard as well.
Because shard guards are not part of whilelisted IPs.
> Send Blacklist removal request for shard guard as well

- src/libData/AccountData/AccountStoreSC.tpp
> message -> messages for contract output parsing

- src/libData/AccountData/AccountStoreSC.tpp
> [release-5.2] message -> messages for contract output parsing

- docker/Dockerfile
- docker/Dockerfile.cuda
- docker/dev/Dockerfile
- src/libUtils/SWInfo.h
> To Zilliqa v5.2.0-alpha.1 and Scilla v0.5.0-alpha.0

- docker/Dockerfile
- docker/Dockerfile.cuda
- src/libUtils/SWInfo.h
> To v5.2.0-alpha.2

- src/libServer/LookupServer.cpp
- src/libValidator/Validator.cpp
> Add checker for txn gas limit against shard limit

- src/libLookup/Lookup.cpp
Accept sharding structure from upper seed as well
> [release-5.2] Accept sharding structure from upper seed as well

- src/libLookup/Lookup.cpp
Accept sharding structure from upper seed as well
> Accept sharding structure from upper seed 

- VERSION
- docker/Dockerfile
- docker/Dockerfile.cuda
- docker/dev/Dockerfile
- src/libUtils/SWInfo.h
> Update master version to Zilliqa v6.0.0 and Scilla v0.5.0

- daemon/ZilliqaDaemon.cpp
- src/common/Constants.h
- src/libNode/Node.cpp
- src/libZilliqa/Zilliqa.cpp
> Remove code for unused sync type DB_VERIF

- docker/Dockerfile
- docker/Dockerfile.cuda
> Fix Docker Build

- src/libPythonRunner/PythonRunner.cpp
> Fix Py Base Path

- src/libData/BlockChainData/BlockChain.h
Improve get last block efficiency
> Improve get last block efficiency

- scripts/download_incr_DB.py
- scripts/upload_incr_DB.py
This PR covers - https://github.com/Zilliqa/Issues/issues/476
Mitigate the increasing persistence( in future) that could potentially end up in recurring fetching of peristence and statedeltas with current logic.
**upload_incr_db.py**
1) Save the current tx blk num to file `.currTxBlkNum` every time their is update to S3.
2) Save the `diff of persistence` for last N DS Epoch in addition to existing logic of syncing peristence and uploading statedelta diff for every new tx blk.
**download_incr_db.py**
1) Get the current tx blk num from `.currTxBlkNum` before starting download of `persistence` and `statedeltas`.
2) Fetch the tx blk num again from `.currTxBlkNum` and if its newer, then fetch the `peristence diff` and `statedeltas` for those missing blks.
3) Then after copying over all the …
> Syncronization beween upload and download incrdb script 

- scripts/miner_info.py
- src/libLookup/Lookup.cpp
- src/libLookup/Lookup.h
- src/libServer/StatusServer.cpp
- src/libServer/StatusServer.h
This PR revises the existing internal lookup switch for SC sharding.
Instead of sending any SC transaction to DS committee, the switch will only send SC calls now.
> Change SendSCToDS to SendSCCallsToDS

- VERSION
- docker/Dockerfile
- docker/Dockerfile.cuda
- src/libUtils/SWInfo.h
> To v6.1.0-alpha.0

- src/libData/AccountData/AccountStoreSC.tpp
- src/libData/AccountData/TransactionReceipt.cpp
- src/libData/AccountData/TransactionReceipt.h
In order to make internal transitions triggered within a contract transaction, we decided to add a new field in transaction receipt to record those information.
Here is an example of transaction receipt after this feature being implemented, basically a new field `transitions` was added:
```
"receipt":{
"cumulative_gas" : "935",
"event_logs" :
[
{
"_eventname" : "ClaimBackSuccess",
"address" : "0x1dd86574dcae382d037f860735ad2b7f83dfec81",
"params" :
[
{
"type" : "ByStr20",
"value" : "0x1b7700f30f2c8318dd2b85715e75634b708120c3",
"vname" : "caller"
},
{
"type" : "Uint128",
"value" : "100",
"vname" : "amount"
},
{
"type" : "Int32",
"value" : "9",
"vname" : "code"
}
]
}
],
"success" : true,
"transitions" :
[
{
"addr" : "1dd86574dcae382d037f860735ad2b7f83dfec81",
"msg" :
{
"_amount" : "100", …
```
> Add contract transitions in transaction receipt

- src/libData/AccountData/AccountStoreSC.tpp
- src/libData/AccountData/TransactionReceipt.cpp
- src/libData/AccountData/TransactionReceipt.h
> [Release-6.1] Transition in Receipt

- docker/Dockerfile
- docker/Dockerfile.cuda
- src/libUtils/SWInfo.h
> To v6.1.0-alpha.1

- src/libData/AccountData/AccountStoreSC.h
- src/libData/AccountData/AccountStoreSC.tpp
- src/libData/AccountData/TransactionReceipt.cpp
- src/libData/AccountData/TransactionReceipt.h
- tests/Data/AccountData/Test_TransactionReceipt.cpp
> [v6.1.0] Use Buffered address when append and add DEPTH in transition field

- docker/Dockerfile
- docker/Dockerfile.cuda
- docker/dev/Dockerfile
- src/libUtils/SWInfo.h
> To Zilliqa v6.1.0-alpha.2 and Scilla v0.5.2-alpha.0

- src/libData/AccountData/AccountStoreSC.tpp
> [release-6.1] Buffer the ret condition in multi-message loop

- docker/Dockerfile
- docker/Dockerfile.cuda
- docker/dev/Dockerfile
- src/libUtils/SWInfo.h
> To Zilliqa v6.1.0 and Scilla v0.5.2

- src/libData/AccountData/AccountStoreSC.tpp
> [release-6.1] Adding jsonerrors flag in scilla checker command

- src/libData/AccountData/AccountStoreSC.tpp
Fix the issue that `ret` might be modified in other loop.
> Buffer the ret condition in multi-message loop

- README.md
> Update README to v6.1.0

- scripts/download_incr_DB.py
> [release-6.1] Add missing global declarations in download script

- src/libServer/WebsocketServer.cpp
> [r6.1] Fix invalid address processing

- src/libServer/WebsocketServer.cpp
> Fix processing invalid address

- docker/Dockerfile
- docker/Dockerfile.cuda
- docker/dev/Dockerfile
> To Scilla version 0.5.2

- scripts/download_incr_DB.py
> Added missing global declarations in download script

- README.md
> Update readme to v6.1.1

- CMakeLists.txt
- src/libData/AccountData/AccountStoreSC.tpp
- src/libPythonRunner/CMakeLists.txt
Fix Boost Python to work with the local Python library version.
> Dynamically configure py version

- CMakeLists.txt
- src/libData/AccountData/AccountStoreSC.tpp
- src/libPythonRunner/CMakeLists.txt
Cherry-picked commit from #2006
> [release-6.1] Dynamically configure py version

- VERSION
- docker/Dockerfile
- docker/Dockerfile.cuda
- src/libUtils/SWInfo.h
> [release-6.1] To v6.1.2

- src/cmd/main.cpp
As https://github.com/Zilliqa/Issues/issues/518 saying, we need a version option for zilliqa binary.
Usage:
```bash
#zilliqa --version
v6.1.0-alpha.0
```
> Support zilliqa --version

- CODE_OF_CONDUCT.md
Update broken link at code of conduct
> Update link at CoC

- src/libData/AccountData/AccountStoreSC.tpp
- src/libData/AccountData/TransactionReceipt.cpp
- src/libData/AccountData/TransactionReceipt.h
In order to know if a contract sent money to another contract, whether the second contract accepted the money, we have this PR.
**Notice**:
- The `accepted` field not inside transitions are regarding to the first call invoked by the transaction. 
- For a pure payment transition, which means it won't invoke scilla interpreter, there won't be `accepted` field.
**Example**:
```
"receipt": {
"accepted" : false,
"cumulative_gas" : "1118",
"success" : true,
"transitions" : 
[
{
"addr" : "0xff5793e4bde5432d2206f5acfae2d6cdb19a4e38",
"depth" : 0,
"accepted" : false,
"msg" : 
{
"_amount" : "0",
"_recipient" : "0x604e8b191ebdb89b762028d6a5bbfe58e8119428",
"_tag" : "Transfer",
"params" : 
[
{
"type" : "ByStr20",
"value" : "0x9bfec715a6bd658fcb62b0f8cc9bfa2ade71434a",
"vname" : "to"
},
{
"type" : …
```
> Adding accepted field in receipt

- docker/Dockerfile
- docker/Dockerfile.cuda
- docker/dev/Dockerfile
> Update Scilla version to 0.6.0-alpha.0

- daemon/ZilliqaDaemon.cpp
As https://github.com/Zilliqa/Issues/issues/610 saying, there is a potential bug for `cseed` option for ZilliqaDaemon. We should provide it to avoid this error.
> Fix cseed option

- README.md
Update git clone instruction for user who does not have write access to repo.
Update latest version to `v6.1.2`
> Update readme version and instruction

- docker/Dockerfile
- docker/Dockerfile.cuda
- docker/dev/Dockerfile
> Update Scilla version to 0.6.0

- scripts/miner_info.py
Changes made:
1. Fix the print statements
2. Use encode/decode in socket send/recv
3. Sort the options dictionary keys so that help message is consistent
> Updated miner_info script to python3

- src/libServer/LookupServer.cpp
- src/libValidator/Validator.cpp
> Add Version Check

- src/libNode/Node.cpp
After #2001, every DS block will now also include miner info.
This PR updates the validateDB tool to check for existence of miner info in leveldb.
> Add check for minerInfo entries in Node::CheckIntegrity

- CMakeLists.txt
- ISOLATED_SERVER_setup.md
- src/cmd/CMakeLists.txt
- src/cmd/isolated_server.cpp
- src/libServer/CMakeLists.txt
- src/libServer/IsolatedServer.cpp
- src/libServer/IsolatedServer.h
To help run smart contracts locally and in isolation.
Enable these APIs
`CreateTransaction` : Input a transaction json payload 
`IncreaseBlocknum` : Increase the blocknum by a given input
`GetSmartContractSubState` : Get the state of a smart contract
`GetSmartContractCode` : Get code at a given address
`GetMinimumGasPrice` : Get the minimum gas price
`SetMinimumGasPrice`: Set the minimum gas price
`GetBalance`: Get balance and nonce of a account
`GetSmartContracts` : get smart contract for an address
`GetNetworkID` 
`GetSmartContractInit` : get init json for a SC.
`GetTransaction` : Get Transaction info by hash
To run, make the following in constants.xml
`<LOOKUP_NODE_MODE>true</LOOKUP_NODE_MODE>`
`<ENABLE_SC>true</ENABLE_SC>`
`<SCILLA_ROOT>path_to_scilla</SCILLA_ROOT>` …
> Isolated server for running smart contracts

- VERSION
- docker/Dockerfile
- docker/Dockerfile.cuda
- src/libUtils/SWInfo.h
> To v6.2.0-alpha.0

- src/libData/BlockChainData/BlockChain.h
> Fix txblock retrieving when no genesis block preloaded

- docker/Dockerfile
- docker/Dockerfile.cuda
- src/libUtils/SWInfo.h
> To v6.2.0-alpha.1

- src/libUtils/HardwareSpecification.h
This PR reduces the minimum RAM requirement (checked during startup) by around 200MB, in order to accommodate newer-generation AWS T3 medium instances (which, although similar to T2 medium, have around 100+ MB lower RAM).
> Reduce MINIMUM_REQ_RAM by 200MB

- src/libUtils/HardwareSpecification.h
Same as #2035 
Cherry-picked commit 0fdbedce6b7a5a500adacc7872378924cbada04c
> [release-6.2] Reduce MINIMUM_REQ_RAM by 200MB

- src/cmd/gentxn.cpp
- src/libServer/LookupServer.cpp
- src/libValidator/Validator.cpp
> [release-6.2] Add logs & fix gentxn

- src/libData/AccountData/AccountStoreTrie.tpp
- src/libMessage/Messenger.cpp
- src/libNetwork/P2PComm.cpp
- src/libZilliqa/Zilliqa.cpp
> Add missing deletion

- src/libData/AccountData/AccountStoreTrie.tpp
- src/libMessage/Messenger.cpp
- src/libNetwork/P2PComm.cpp
- src/libZilliqa/Zilliqa.cpp
> [release-6.2] Added missing deletion

- src/cmd/gentxn.cpp
- src/libServer/LookupServer.cpp
- src/libValidator/Validator.cpp
Fix the use of `TRANSACTION_VERSION` in gentxn.cpp
> Add logs & fix gentxn

- constants.xml
- constants_local.xml
- src/common/Constants.cpp
- src/common/Constants.h
- src/libServer/LookupServer.cpp
- src/libServer/LookupServer.h
> [release 6.2] Add GetTxnBodiesForTxBlock and GetPendingTxns API

- constants.xml
- constants_local.xml
- src/common/Constants.cpp
- src/common/Constants.h
- src/libServer/LookupServer.cpp
- src/libServer/LookupServer.h
Add two additional APIs
For a particular tx block, Get all the txns in verbose form, as you get from `GetTransaction`.
```json
{
"id": "1",
"result": [
{
"ID": "562432bc45c14c788c43c469756453375cbe80cc9c1bc30fa0dfbe77e4220221",
"amount": "1",
"gasLimit": "1",
"gasPrice": "1000000000",
"nonce": "1",
"receipt": {
"cumulative_gas": "1",
"epoch_num": "2",
"success": true
},
"senderPubKey": "0x03393C256D33127CE18FC3646EC88FCE62DBF661300B4017E2FE57E8023B55BCFE",
"signature": "0xCC12816DCE156FECFA1D6EF129D13FA2A5677E159CDF0CAFADF2CD33FBA0D239EE1284D4083BFBA4B895B97419FE78AB249C99AA7A7B7F314F17D353F44E784D",
"toAddr": "b07065cfde6060ad36af3913c65bfb04211608d1",
"version": "131073"
},
{
"ID": "9ebc07e3e15b08dd82b2f2d57eead1b7dea4d06bef33364bbec5f80fc1d1d130",
"amount": "2", …
```
> Add GetTxnBodiesForTxBlock and GetPendingTxns API

- docker/Dockerfile
- docker/Dockerfile.cuda
- docker/dev/Dockerfile
- src/libUtils/SWInfo.h
> To Zilliqa v6.2.0-alpha.2 and Scilla v0.7.0-alpha.0

- scripts/auto_backup.py
Currently, auto_backup.py script perform the compression of persistence without creating local copy.
Compression turns out to be quite time consuming and its very likely that data gets overwritten in persistence as new blocks are mined.
This is observed on community testnet.
So fix is to create a local copy in `tempbackup` and perform rest of compression and upload operation with no fear of having corrupt data.
Also, additionally compressed file is deleted after uploading to S3.
> auto_backup script improvement

- scripts/auto_backup.py
Same as #2053 
Cherry-picked commit d4153ce4c55af2d3b8ff72cdcdad27f3d6dcd42c
> [release-6.2] copy persistence to local temp bef starting upload

- docker/Dockerfile
- docker/Dockerfile.cuda
- src/libUtils/SWInfo.h
> To v6.2.0-alpha.3

- scripts/auto_backup.py
> [release-6.2] Change auto_backup target block

- scripts/auto_backup.py
Reference: Zilliqa/Issues#618
- Added logging to file auto_backup-log.txt
- Added exception handling to avoid crash and log the exception and continue.
> [release-6.2] Add exception handling and logging to auto_backup.py 

- src/libData/AccountData/AccountStoreSC.tpp
- src/libData/AccountData/TransactionReceipt.cpp
- src/libData/AccountData/TransactionReceipt.h
Refers to:
https://github.com/Zilliqa/Zilliqa/pull/2060
> [Release-6.2] Adding exception message from scilla interpreter to receipt

- docker/Dockerfile
- docker/Dockerfile.cuda
- docker/dev/Dockerfile
- src/libUtils/SWInfo.h
> To Zilliqa v6.2.0-alpha.4 and Scilla v0.7.0

- src/libData/AccountData/AccountStoreSC.tpp
- src/libData/AccountData/TransactionReceipt.cpp
- src/libData/AccountData/TransactionReceipt.h
Example:
For contract 
https://github.com/Zilliqa/scilla/blob/master/tests/contracts/salarybot.scilla
<b>The output from Scilla interpreter: </b>
```
{
"gas_remaining": "19493",
"errors": [
{
"error_message":
"Exception thrown: (Message [(_exception : (String \"Not owner exeption\"))])",
"start_location": {
"file": "scilla_files/input.scilla",
"line": 40,
"column": 5
},
"end_location": { "file": "", "line": 0, "column": 0 }
},
{
"error_message": "Raised from add_funds",
"start_location": {
"file": "scilla_files/input.scilla",
"line": 44,
"column": 12
},
"end_location": { "file": "", "line": 0, "column": 0 }
}
],
"warnings": []
}
```
<b>Which is reflected in the receipt as below:</b>
```
{
"cumulative_gas" : "507",
"errors" : 
{
"0" : [ 7 ]
},
"exceptions" : 
[
{
"line" : 40,
"message" : …
```
> Adding exception message from scilla interpreter to receipt

- docker/Dockerfile
- docker/Dockerfile.cuda
- docker/dev/Dockerfile
> Update master to Scilla v0.7.0

- scripts/auto_backup.py
Reference: https://github.com/Zilliqa/Issues/issues/618
- Added logging to file `auto_backup-log.txt`
- Added exception handling to avoid crash and log the exception and continue.
> Add exception handling and logging to auto_backup.py

- src/libServer/WebsocketServer.cpp
> Clean m_eventLogDataBuffer if no subscriber

- src/libServer/WebsocketServer.cpp
> [release-6.2] Clean eventLogDataBuffer if no subscriber

- README.md
> Update Zilliqa version in README
